import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_projects',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'A1:D2',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_projects',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Implement SSO integration"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_projects',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Mike Chen"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_projects',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "2026-03-14"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_projects',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "In Progress"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
