import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
    '--json',
    '{"item": "Annual Insurance", "period": "2026-02", "debit_account": "Insurance Expense", "credit_account": "Prepaid Asset", "amount": 4000}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
    '--json',
    '{"item": "Software License", "period": "2026-02", "debit_account": "Software Expense", "credit_account": "Prepaid Asset", "amount": 600}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
    '--json',
    '{"item": "Cloud Hosting Prepaid", "period": "2026-02", "debit_account": "Hosting Expense", "credit_account": "Prepaid Asset", "amount": 300}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_prepaids',
    '--sheet-id',
    'ws_prepaid_items',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "$18,000.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_prepaids',
    '--sheet-id',
    'ws_prepaid_items',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "$6,000.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_prepaids',
    '--sheet-id',
    'ws_prepaid_items',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "$1,100.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_prepaids',
    '--sheet-id',
    'ws_prepaid_items',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "$6,100.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_prepaids',
    '--sheet-id',
    'ws_prepaid_items',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "$7,200.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_prepaids',
    '--sheet-id',
    'ws_prepaid_items',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "$300.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_prepaids',
    '--sheet-id',
    'ws_prepaid_items',
    '--range',
    'G6',
    '--cells',
    '[[{"value": "$3,300.00"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Annual Insurance | Debit Insurance Expense | Credit Prepaid Asset | $4,000.00\nSoftware License | Debit Software Expense | Credit Prepaid Asset | $600.00\nCloud Hosting Prepaid | Debit Hosting Expense | Credit Prepaid Asset | $300.00\nTotal amortization: $4,900.00',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
