import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'feedback@company.example.com',
    '--message-ids',
    'msg_3162',
    '--as',
    'user',
  ],
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_feedback',
    '--sheet-id',
    'sheet1',
    '--range',
    'A1:C1',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_feedback',
    '--sheet-id',
    'sheet1',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Tom Brennan"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_feedback',
    '--sheet-id',
    'sheet1',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Hi, I just wanted to say your new reporting feature is fantastic. It\'s saved our team hours every week. Keep up the great work! - Tom Brennan"}]]',
  ],
  [
    'mail',
    '+reply',
    '--mailbox',
    'feedback@company.example.com',
    '--message-id',
    'msg_3162',
    '--body',
    'Thank you for sharing your feedback, Tom. We are glad the reporting feature saves your team time.',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
