import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'contracts@company.example.com',
    '--message-ids',
    'msg_3161',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f883a4577cea',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_45a5c62241ee',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_45a5c62241ee',
    '--json',
    '{"subject": "Contract renewal terms", "description": "Hi, our contract is up for renewal next month. We\'d like to discuss modifying the SLA terms. Can someone from your legal team reach out? Thanks, Patricia Delgado", "group_id": "grp_legal"}',
  ],
  [
    'mail',
    '+reply',
    '--mailbox',
    'contracts@company.example.com',
    '--message-id',
    'msg_3161',
    '--body',
    'We have received your contract inquiry and created a ticket for our legal team.',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
