import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b3eae60a9bac',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b3eae60a9bac',
    '--json',
    '{"ratio": "Current Ratio", "value": "1.5577", "target_status": "Meets", "covenant_status": "Fail", "notes": "Industry norm is 2.0; Current Ratio is below the industry norm."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b3eae60a9bac',
    '--json',
    '{"ratio": "Quick Ratio", "value": "1.2885", "target_status": "Meets", "covenant_status": "Not applicable"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b3eae60a9bac',
    '--json',
    '{"ratio": "Debt-to-Equity", "value": "0.3333", "target_status": "Meets", "covenant_status": "Pass"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b3eae60a9bac',
    '--json',
    '{"ratio": "Net Profit Margin", "value": "18.3824%", "target_status": "Meets", "covenant_status": "Not applicable"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b3eae60a9bac',
    '--json',
    '{"ratio": "DSCR", "value": "", "target_status": "Unknown", "covenant_status": "Insufficient data"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    '由于 embargo，报告暂不分发；请待审计解禁后再安排发布。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
