import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_reports',
    '--sheet-id',
    'sheet1',
    '--range',
    'A1:C1',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reports',
    '--sheet-id',
    'sheet1',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Week of Feb 23"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reports',
    '--sheet-id',
    'sheet1',
    '--range',
    'B2',
    '--cells',
    '[[{"value": 12}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reports',
    '--sheet-id',
    'sheet1',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "340K"}]]',
  ],
  [
    'mail',
    '+send',
    '--to',
    'manager@company.example.com',
    '--subject',
    'weekly report',
    '--body',
    'Week of Feb 23：成交12单，收入340K美元。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
