import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--json',
    '{"email": "bob@newlead.example.com", "firstname": "Bob", "lastname": "Jones"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--json',
    '{"email": "frank@another.example.com", "firstname": "Frank", "lastname": "Lee"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--json',
    '{"email": "bob.jones@differentco.example.com", "firstname": "Bob", "lastname": "Jones"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals',
    '--sheet-id',
    'ws_submissions',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals',
    '--sheet-id',
    'ws_submissions',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals',
    '--sheet-id',
    'ws_submissions',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referrals',
    '--sheet-id',
    'ws_submissions',
    '--range',
    'E8',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'REFP-661-Q1\nAlice Smith，感谢推荐 Bob Jones（bob@newlead.example.com），已完成本次推荐处理。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_14',
    '--text',
    'REFP-661-Q1\nEve Green，感谢推荐 Frank Lee（frank@another.example.com），已完成本次推荐处理。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_18',
    '--text',
    'REFP-RENG-2026\nGreg Hall，感谢推荐 Helen Yu（helen@existing2.example.com），已完成本次推荐处理。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_30',
    '--text',
    'REFP-661-Q1\nNina Clark，感谢推荐 Bob Jones（bob.jones@differentco.example.com），已完成本次推荐处理。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
