import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'support@brightpath.example.com',
    '--message-ids',
    'msg_8001',
    '--as',
    'user',
  ],
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_support',
    '--sheet-id',
    'ws_tickets',
    '--range',
    'A1:E1',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_support',
    '--sheet-id',
    'ws_tickets',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Ingrid Svensson"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_support',
    '--sheet-id',
    'ws_tickets',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "ingrid.svensson@nordicfreight.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_support',
    '--sheet-id',
    'ws_tickets',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Unable to export reports in CSV format"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_support',
    '--sheet-id',
    'ws_tickets',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "2026-02-23"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_support',
    '--sheet-id',
    'ws_tickets',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Medium"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
