import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'sales@company.example.com',
    '--message-ids',
    'msg_3198',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f883a4577cea',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_45a5c62241ee',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_45a5c62241ee',
    '--json',
    '{"subject": "Question about pricing", "description": "Hi, could you explain the difference between your pricing tiers? We\'re a team of 30 and not sure which plan fits best. Thanks, Jamie Park"}',
  ],
  [
    'mail',
    '+reply',
    '--mailbox',
    'sales@company.example.com',
    '--message-id',
    'msg_3198',
    '--body',
    'Our pricing is Basic at $29/month, Pro at $79/month, and Enterprise with custom pricing. To help your team of 30 choose, please share your required features and usage; no plan limits or feature differences were provided here.',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
