import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_digest',
    '--sheet-id',
    'sheet1',
    '--range',
    'A1:B6',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice.fernandez@company.example.com',
    '--subject',
    'Weekly Digest - Feb 23',
    '--body',
    "Alice Fernandez, this week's highlights: no verified business updates were provided for this digest.",
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob.nguyen@company.example.com',
    '--subject',
    'Weekly Digest - Feb 23',
    '--body',
    "Bob Nguyen, this week's highlights: no verified business updates were provided for this digest.",
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'clara.singh@company.example.com',
    '--subject',
    'Weekly Digest - Feb 23',
    '--body',
    "Clara Singh, this week's highlights: no verified business updates were provided for this digest.",
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dan.mueller@company.example.com',
    '--subject',
    'Weekly Digest - Feb 23',
    '--body',
    "Dan Mueller, this week's highlights: no verified business updates were provided for this digest.",
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'eva.kowalski@company.example.com',
    '--subject',
    'Weekly Digest - Feb 23',
    '--body',
    "Eva Kowalski, this week's highlights: no verified business updates were provided for this digest.",
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
