import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_237255d7d526',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
    '--json',
    '{"customer_id": "qc_301", "customer_name": "Helix Systems", "period": "2026-04", "total_amount": 4120, "status": "Issued"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
    '--json',
    '{"customer_id": "qc_302", "customer_name": "Orchid Freight", "period": "2026-04", "total_amount": 5250, "status": "Issued"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
    '--json',
    '{"customer_id": "qc_304", "customer_name": "Crestline Partners", "period": "2026-04", "total_amount": 3300, "status": "Issued"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@helix.example.com',
    '--subject',
    'Helix Systems | 2026-04 | Invoice $4,120 | 来源基础单价 $100',
    '--body',
    'Helix Systems | 2026-04 | Invoice $4,120 | 来源基础单价 $100',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ap@orchid.example.com',
    '--subject',
    'Orchid Freight | 2026-04 | Invoice $5,250 | 来源基础单价 $50',
    '--body',
    'Orchid Freight | 2026-04 | Invoice $5,250 | 来源基础单价 $50',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'accounts@crestline.example.com',
    '--subject',
    'Crestline Partners | 2026-04 | Invoice $3,300 | 来源基础单价 $200',
    '--body',
    'Crestline Partners | 2026-04 | Invoice $3,300 | 来源基础单价 $200',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
