import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "SalesTech Today"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "editor@salestech.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Queued"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "sales technology"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Marketing Weekly"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "content@mktweekly.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Queued"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "marketing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Small Biz Blog"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "submit@smallbiz.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Queued"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "small business"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "CloudOps Review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "editorial@cloudopsreview.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Queued"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "cloud operations"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "B2B Growth Blog"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "content@b2bgrowth.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "Queued"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_outreach',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "b2b marketing"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_34',
    '--text',
    'Weekly Link Building\n5 sites added\nSalesTech Today | 58\nMarketing Weekly | 62\nSmall Biz Blog | 32\nCloudOps Review | 55\nB2B Growth Blog | 45',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
