import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4cf94b94b3aa',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_971ff87f017f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_53fb571ac4c7',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_39a1a3489540',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_971ff87f017f',
    '--json',
    '{"name": "Alicia Fernandez", "email": "alicia.fernandez@company.example.com", "department": "Engineering", "manager": "David Okonkwo", "start_date": "2026-03-24", "location": "Austin", "role": "Frontend Developer"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4cf94b94b3aa',
    '--json',
    '{"name": "Alicia Fernandez", "parent_id": "folder_employees"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_39a1a3489540',
    '--json',
    '{"summary": "Alicia Fernandez", "start_date": "2026-03-24", "department": "Engineering", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_971ff87f017f',
    '--json',
    '{"name": "Tyrone Washington", "email": "tyrone.washington@company.example.com", "department": "Sales", "manager": "Lisa Wang", "start_date": "2026-03-25", "location": "Remote", "role": "Account Executive"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4cf94b94b3aa',
    '--json',
    '{"name": "Tyrone Washington", "parent_id": "folder_employees"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_39a1a3489540',
    '--json',
    '{"summary": "Tyrone Washington", "start_date": "2026-03-25", "department": "Sales", "status": "Not Started"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Alicia Fernandez | Frontend Developer | Engineering | David Okonkwo | 2026-03-24 | Austin | welcome | 报到时间和详细地点待经理确认',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Tyrone Washington | Account Executive | Sales | Lisa Wang | 2026-03-25 | Remote | welcome | 报到时间和详细地点待经理确认',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
