import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['drive', 'files', 'list', '--params', '{}'],
  [
    'drive',
    'files',
    'list',
    '--params',
    '{"folder_token": "folder_employees"}',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_971ff87f017f',
  ],
  ['drive', 'files', 'list', '--params', '{}'],
  [
    'drive',
    'files',
    'list',
    '--params',
    '{"folder_token": "folder_employees"}',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_39a1a3489540',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_971ff87f017f',
    '--json',
    '{"name": "Alicia Fernandez", "email": "alicia.fernandez@company.example.com", "department": "Engineering", "manager": "David Okonkwo", "start_date": "2026-03-24", "location": "Austin", "role": "Frontend Developer"}',
  ],
  [
    'drive',
    'files',
    'create_folder',
    '--data',
    '{"name": "Alicia Fernandez", "folder_token": "folder_employees"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_39a1a3489540',
    '--json',
    '{"summary": "Alicia Fernandez", "start_date": "2026-03-24", "department": "Engineering", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_971ff87f017f',
    '--json',
    '{"name": "Tyrone Washington", "email": "tyrone.washington@company.example.com", "department": "Sales", "manager": "Lisa Wang", "start_date": "2026-03-25", "location": "Remote", "role": "Account Executive"}',
  ],
  [
    'drive',
    'files',
    'create_folder',
    '--data',
    '{"name": "Tyrone Washington", "folder_token": "folder_employees"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_39a1a3489540',
    '--json',
    '{"summary": "Tyrone Washington", "start_date": "2026-03-25", "department": "Sales", "status": "Not Started"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alicia.fernandez@company.example.com',
    '--subject',
    'Alicia Fernandez | Frontend Developer | Engineering | David Okonkwo | 2026-03-24 | Austin | welcome | 报到时间和详细地点待经理确认',
    '--body',
    'Alicia Fernandez | Frontend Developer | Engineering | David Okonkwo | 2026-03-24 | Austin | welcome | 报到时间和详细地点待经理确认',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'tyrone.washington@company.example.com',
    '--subject',
    'Tyrone Washington | Account Executive | Sales | Lisa Wang | 2026-03-25 | Remote | welcome | 报到时间和详细地点待经理确认',
    '--body',
    'Tyrone Washington | Account Executive | Sales | Lisa Wang | 2026-03-25 | Remote | welcome | 报到时间和详细地点待经理确认',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
