import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_opp_tv',
    '--json',
    '{"stage": "Proposal"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tmpl_ent", "template_name": "Enterprise Agreement", "account_id": "001_TV", "opportunity_id": "opp_tv", "recipient_email": "buyer@techventures.example.com", "status": "Draft", "amount": 250000}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "proposal_talking_points", "opportunity_id": "opp_tv", "body": "TechVentures | 250000 | 与primary buyer核验定价和范围；与technical lead核验技术问题；价值与ROI待客户确认，合同Draft未发送。"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "TechVentures proposal prep", "description": "TechVentures | internal prep", "start_time": {"timestamp": "1772010000"}, "end_time": {"timestamp": "1772011800"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Pricing Discussion", "description": "TechVentures | 250000", "start_time": {"timestamp": "1772013600"}, "end_time": {"timestamp": "1772016300"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_2',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "buyer@techventures.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Technical Q&A", "description": "TechVentures | technical lead", "vc_data": {"vc_type": "vc"}, "start_time": {"timestamp": "1772017200"}, "end_time": {"timestamp": "1772019000"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_3',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "tech@techventures.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_TV',
    '--text',
    'TechVentures | Proposal | 250000 | 2026-02-25 prep 09:00，Pricing Discussion 10:00–10:45，Technical Q&A 11:00–11:30 UTC | Enterprise Agreement Draft未发送；talking points已准备。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
