import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_vendors',
    '--range',
    'A1:F2',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_vendors',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "CloudForge Solutions"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_vendors',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Dmitri Volkov"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_vendors',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "dmitri.volkov@cloudforge.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_vendors',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Cloud Infrastructure"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_vendors',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "2026-03-01"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_vendors',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "$48,000"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
