import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_tracker',
    '--sheet-id',
    'ws_submissions',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "45.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_tracker',
    '--sheet-id',
    'ws_submissions',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Travel"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_tracker',
    '--sheet-id',
    'ws_submissions',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "2026-02-03"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_tracker',
    '--sheet-id',
    'ws_submissions',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Uber to airport"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_tracker',
    '--sheet-id',
    'ws_submissions',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "slk_exp_002"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_EXPENSES',
    '--text',
    'slk_exp_001 | $127.50 | Meals | 需补人数，未登记；超出每人 $75 上限但缺少 attendees。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_EXPENSES',
    '--text',
    'slk_exp_002 | $45.00 | Travel | 2026-02-03 | Uber to airport | 已登记',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_EXPENSES',
    '--text',
    'slk_exp_003 | $890.00 | Entertainment | 未登记，需要 VP pre-approval，不能通过标准通道提交。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
