import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_updates'],
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_log',
    '--range',
    'A1:D1',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Kwame Asante"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "kwame.asante@boldventures.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Inquiry about enterprise integration options"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_contacts',
    '--sheet-id',
    'ws_log',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "2026-02-23"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
