import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_activity',
    '--sheet-id',
    'ws_log',
    '--range',
    'A1:F2',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_activity',
    '--sheet-id',
    'ws_log',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "2026-02-23"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_activity',
    '--sheet-id',
    'ws_log',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Discovery Call"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_activity',
    '--sheet-id',
    'ws_log',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Vanessa Brooks"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_activity',
    '--sheet-id',
    'ws_log',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Redwood Analytics"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_activity',
    '--sheet-id',
    'ws_log',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Discussed data pipeline needs; interested in Enterprise plan; follow-up demo scheduled for March 1st."}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_activity',
    '--sheet-id',
    'ws_log',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Positive"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
