import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_leads',
    '--sheet-id',
    'ws_leads',
    '--range',
    'A1:F2',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_leads',
    '--sheet-id',
    'ws_leads',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Carla Mendes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_leads',
    '--sheet-id',
    'ws_leads',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Horizon Biotech"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_leads',
    '--sheet-id',
    'ws_leads',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "carla.mendes@horizonbiotech.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_leads',
    '--sheet-id',
    'ws_leads',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "555-0142"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_leads',
    '--sheet-id',
    'ws_leads',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "LinkedIn"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_leads',
    '--sheet-id',
    'ws_leads',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "New"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
