import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8842e79a0fb7',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8842e79a0fb7',
    '--json',
    '{"req_id": "REQ-2026-042", "title": "Staff Product Designer", "department": "Design", "location": "San Francisco", "employment_type": "Full-time", "salary_range": "$160,000 - $200,000", "description": "Lead design for our core platform experience. You\'ll work across product, engineering, and research teams to ship world-class features.", "requirements": "7+ years product design experience. Proficiency in Figma. Experience with design systems. Strong portfolio.", "hiring_manager": "Maria Santos"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_JOBS',
    '--text',
    'Staff Product Designer 职位开放：San Francisco，Full-time，Design 团队，薪资 $160,000 - $200,000，招聘经理 Maria Santos。',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'careers-list@company.example.com',
    '--subject',
    'Staff Product Designer 职位开放',
    '--body',
    'Staff Product Designer，San Francisco，Full-time，薪资 $160,000 - $200,000。Design 团队，经理 Maria Santos。要求 7+ years product design experience. Proficiency in Figma. Experience with design systems. Strong portfolio.',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
