import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZm9sbG93dXBfaGlzdA,Zml4dHVyZTptc2dfZm9sbG93dXBfc29w,Zml4dHVyZTptc2dfZm9sbG93dXBfdnA,Zml4dHVyZTptc2dfZm9sbG93dXBfdmVuZG9y,Zml4dHVyZTptc2dfZm9sbG93dXBfZGlyZWN0b3I,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNQ',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'beth@startup.example.com',
    '--subject',
    'Conference Follow-up',
    '--body',
    'Conference Follow-up\nBeth Martinez，感谢您代表 StartupCo 现场参会。欢迎继续交流产品应用并预约产品演示。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'eric@enterprise.example.com',
    '--subject',
    'Enterprise Success',
    '--body',
    'Enterprise Success\nEric Johnson，感谢您代表 Enterprise Co 现场参会。我们期待继续讨论 Enterprise Solutions 与企业实施支持。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'fiona@midmarket.example.com',
    '--subject',
    'Conference Follow-up',
    '--body',
    'Conference Follow-up\nFiona Clark，感谢您代表 MidMarket Inc 现场参会。欢迎继续交流产品应用并预约产品演示。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'laura@glendale.example.com',
    '--subject',
    'Conference Follow-up',
    '--body',
    'Conference Follow-up\nLaura Kim，感谢您代表 Glendale Group 现场参会。欢迎继续交流产品应用并预约产品演示。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'charles.w@othermega.example.com',
    '--subject',
    'Conference Follow-up',
    '--body',
    'Conference Follow-up\nCharles Wong，感谢您代表 OtherMega Ltd 现场参会。欢迎继续交流产品应用并预约产品演示。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'omar@industrialtech.example.com',
    '--subject',
    'Enterprise Success',
    '--body',
    'Enterprise Success\nOmar Hassan，感谢您代表 Industrial Tech Ltd 现场参会。我们期待继续讨论 Enterprise Solutions 与企业实施支持。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
