import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tmpl_policy_ack", "employee": "Alice Park", "email": "alice.park@company.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tmpl_policy_ack", "employee": "Dave Kim", "email": "dave.kim@company.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tmpl_policy_ack", "employee": "Eve Liu", "email": "eve.liu@company.example.com", "status": "Sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Alice Park | Policy Acknowledgment Form | 请签署',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Dave Kim | Policy Acknowledgment Form | 请签署',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Eve Liu | Policy Acknowledgment Form | 请签署',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_policy_ack',
    '--sheet-id',
    'ws_status',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_policy_ack',
    '--sheet-id',
    'ws_status',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_policy_ack',
    '--sheet-id',
    'ws_status',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_policy_ack',
    '--sheet-id',
    'ws_status',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Deferred"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
