import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_budget',
    '--sheet-id',
    'ws_expenses',
    '--range',
    'A1:E2',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget',
    '--sheet-id',
    'ws_expenses',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Software"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget',
    '--sheet-id',
    'ws_expenses',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Annual Figma license renewal"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget',
    '--sheet-id',
    'ws_expenses',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "$1,200"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget',
    '--sheet-id',
    'ws_expenses',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "2026-02-23"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_budget',
    '--sheet-id',
    'ws_expenses',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Lisa Tran"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
