import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_webinar',
    '--sheet-id',
    'ws_attendees',
    '--range',
    'A1:E2',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_webinar',
    '--sheet-id',
    'ws_attendees',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Tariq Hassan"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_webinar',
    '--sheet-id',
    'ws_attendees',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "tariq.hassan@vanguardsystems.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_webinar',
    '--sheet-id',
    'ws_attendees',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Vanguard Systems"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_webinar',
    '--sheet-id',
    'ws_attendees',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Scaling with AI"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_webinar',
    '--sheet-id',
    'ws_attendees',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "2026-03-12"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
