import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'pm@company.example.com',
    '--message-ids',
    'msg_3165',
    '--as',
    'user',
  ],
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_projects',
    '--sheet-id',
    'sheet1',
    '--range',
    'A1:C1',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_projects',
    '--sheet-id',
    'sheet1',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Mobile App v2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_projects',
    '--sheet-id',
    'sheet1',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Phase 2 Complete"}]]',
  ],
  [
    'mail',
    '+reply',
    '--mailbox',
    'pm@company.example.com',
    '--message-id',
    'msg_3165',
    '--body',
    'Acknowledged: Mobile App v2 Phase 2 Complete has been logged. The next step is Phase 3, which your February 21 email says is ready to begin the following week (February 23–March 1).',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
