import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_content',
    '--sheet-id',
    'ws_calendar',
    '--range',
    'A1:E2',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_content',
    '--sheet-id',
    'ws_calendar',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "10 Ways AI Is Transforming Customer Onboarding"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_content',
    '--sheet-id',
    'ws_calendar',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Olivia Park"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_content',
    '--sheet-id',
    'ws_calendar',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "2026-03-02"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_content',
    '--sheet-id',
    'ws_calendar',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Draft"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_content',
    '--sheet-id',
    'ws_calendar',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "AI & Automation"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
