import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "subscribers", "audience_id": "aud_newsletter", "email": "alice@example.com", "name": "Alice Johnson", "company": "TechCorp", "status": "subscribed", "tags": "[\\"event-2026\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "subscribers", "audience_id": "aud_newsletter", "email": "carol@example.com", "name": "Carol Davis", "company": "CloudSoft", "status": "subscribed", "tags": "[\\"event-2026\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "subscribers", "audience_id": "aud_newsletter", "email": "grace@example.com", "name": "Grace Park", "company": "InnoTech", "status": "subscribed", "tags": "[\\"event-2026\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "subscribers", "audience_id": "aud_newsletter", "email": "rachel.s@widgetfactory.example.com", "name": "Rachel Simmons", "company": "WidgetFactory", "status": "subscribed", "tags": "[\\"event-2026\\"]"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CMKTOPS',
    '--text',
    'Synced | 4 | Alice Johnson | TechCorp | Carol Davis | CloudSoft | Grace Park | InnoTech | Rachel Simmons | WidgetFactory',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
