import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'sheets',
    '+cells-get',
    '--spreadsheet-token',
    'ss_deals',
    '--sheet-id',
    'ws_deals',
    '--range',
    'A1:F2',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_deals',
    '--sheet-id',
    'ws_deals',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Pinnacle Healthcare"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_deals',
    '--sheet-id',
    'ws_deals',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "$185,000"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_deals',
    '--sheet-id',
    'ws_deals',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "2026-02-23"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_deals',
    '--sheet-id',
    'ws_deals',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "Sarah Jones"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_deals',
    '--sheet-id',
    'ws_deals',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "2 years"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_deals',
    '--sheet-id',
    'ws_deals',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "Enterprise"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
