import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdHJpYWdlX3BvbGljeV9vbGQ,Zml4dHVyZTptc2dfdHJpYWdlX3BvbGljeQ,Zml4dHVyZTptc2dfdHJpYWdlX2NyYXNoX3BvbGljeQ,Zml4dHVyZTptc2dfdHJpYWdlX2Rldl9vdmVycmlkZQ,Zml4dHVyZTpyZXZfMQ,Zml4dHVyZTpyZXZfMg,Zml4dHVyZTpyZXZfMw,Zml4dHVyZTpyZXZfNA,Zml4dHVyZTpyZXZfNQ,Zml4dHVyZTpyZXZfNg,Zml4dHVyZTpyZXZfN2E,Zml4dHVyZTpyZXZfNw,Zml4dHVyZTpyZXZfOA,Zml4dHVyZTpyZXZpZXdfYWJ1c2U,Zml4dHVyZTpyZXZpZXdfY29tcA,Zml4dHVyZTptc2dfY29tcF9wYXJ0bmVyX3JlcQ,Zml4dHVyZTpyZXZfYm90,Zml4dHVyZTpyZXZfZW5n,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
    '--json',
    '{"subject": "TRIAGE-308-Q1 Login issues", "reviewer_email": "kevin@example.com", "source_message_id": "rev_2", "content": "Login issues.", "priority": "Normal", "status": "Open"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
    '--json',
    '{"subject": "TRIAGE-308-Q1 [HIGH PRIORITY] Crashes on launch", "reviewer_email": "liam@example.com", "source_message_id": "rev_3", "content": "Crashes on launch every time.", "priority": "High", "status": "Open"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
    '--json',
    '{"subject": "TRIAGE-308-Q1 [HIGH PRIORITY] Crashes on export", "reviewer_email": "marcus.johnson@example.com", "source_message_id": "rev_8", "content": "The app crashes every time I try to export. Lost hours of work. Completely unreliable.", "priority": "High", "status": "Open"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ivy@example.com',
    '--subject',
    'Thank you! 感谢分享反馈：Great product!',
    '--body',
    'Thank you! 感谢分享反馈：Great product!',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'maya@example.com',
    '--subject',
    'Thank you! 感谢分享反馈：Good tool, minor UI bugs.',
    '--body',
    'Thank you! 感谢分享反馈：Good tool, minor UI bugs.',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'olivia@example.com',
    '--subject',
    'Thank you! 感谢分享反馈：Perfect for our team!',
    '--body',
    'Thank you! 感谢分享反馈：Perfect for our team!',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'app-reviews@company.example.com',
    '--subject',
    'TRIAGE-308-Q1',
    '--body',
    'TRIAGE-308-Q1\nTicket | kevin@example.com | Normal\nTicket | liam@example.com | High\nTicket | marcus.johnson@example.com | High\nThank You | ivy@example.com\nThank You | maya@example.com\nThank You | olivia@example.com\nTickets | 3\nThank You Messages | 3',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
